### DISCUSSION TITLE
How is the ephemeral flag supposed to work?

### DISCUSSION THREAD

**Discussion by wilinger** [actions/actions-runner-controller#1024] [Questions] [answered]
I have a RunnerDeployment below and after an action is ran once, Github shows the runner as Idle status and the runner-deployment pod is still running on my cluster. How do I make the runners terminate and only spin up on a new job?
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
spec:
  template:
    spec:
      repository: wilinger/test-self-hosted-runner
      env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
```
