### DISCUSSION TITLE
Does HRA consider idle/active runners or not?

### DISCUSSION THREAD

**Discussion by erplsf** [actions/actions-runner-controller#1114] [Questions] [answered]
We have HRA that looks like this:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ $runnerSetName }}-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: {{ mul 30 60 }} # don't scale down for 30 minutes after scale up
  scaleTargetRef:
    name: {{ $runnerSetName }}
    kind: RunnerSet
  scaleUpTriggers:
    - githubEvent: {}
      amount: 1
      duration: "30m"
  minReplicas: 3
  maxReplicas: 10
```
What we've observed is that when a new workflow is triggered, HRA spins up a new runner even if all of the runners are free (idle in Github). Is it an expected behavior?
