### DISCUSSION TITLE
Is it possible to add and mount secrets on the runner pods?

### DISCUSSION THREAD

**Discussion by Harleyzheng** [actions/actions-runner-controller#1339] [Questions]
Dear community,

I'm setting up CD jobs on the actions runner pods. Due to how our production servers are configured, I plan to create a ssh secret for the actions runner pods, and then add the public key in ~/.ssh/authorized_users on production servers . After looking at the structure of RunnerDeployment yaml files. I'm not sure how to mount a secret to the Runner pods.

 Any help is appreciated, thanks!

**Comment by lucianolacurcia** [comment]
Yes, you can for example use this step:
```
steps:
  - shell: bash
    env:
      SUPER_SECRET: ${{ secrets.SuperSecret }}
    run: |
      echo "$SUPER_SECRET" >> /path/to/mount/location
```

[source](https://docs.github.com/en/actions/security-guides/encrypted-secrets#example-using-bash)
