### DISCUSSION TITLE
Runner stuck on "Completed"

### DISCUSSION THREAD

**Discussion by ostiwe** [actions/actions-runner-controller#1418] [Questions] [answered]
Hi, after the Workflow has passed, the pod completes its work and hangs on the status "Completed" and does not restart
<img width="1271" alt="Screenshot 2022-05-07 at 17 02 18" src="https://user-images.githubusercontent.com/60335090/167257617-e29c9b5c-4a8c-43c6-af78-a2baf71b5aad.png">

Log on controller:
<img width="1275" alt="Screenshot 2022-05-07 at 17 03 19" src="https://user-images.githubusercontent.com/60335090/167257663-597779b1-e6c5-4b89-be6e-9c1503f346b8.png">

Runner config:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  namespace: github-runners
  name: helm-deployment-three
spec:
  labels:
    - helm-deploy
  organization: $orgname$
  ```

Does anyone know why this is happening? Maybe I forgot to specify some parameter somewhere?

**Comment by ostiwe** [comment]
Also, in runner pod log
<img width="602" alt="Screenshot 2022-05-07 at 17 07 27" src="https://user-images.githubusercontent.com/60335090/167257836-3cc3e476-509f-4283-9352-aab278ac531c.png">

**Comment by ostiwe** [comment, marked as answer]
Okay, i set  ``ephemeral: false``, and now all work fine


```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  namespace: github-runners
  name: $runnerName$
spec:
  organization: $org$
  ephemeral: false
  ```
