### DISCUSSION TITLE
Short term solution for "OutOfcpu" issues for runners

### DISCUSSION THREAD

**Discussion by BeyondEvil** [actions/actions-runner-controller#1466] [Show and tell]
We have an issue where runners get `OutOfcpu` even tho their QoS is guaranteed.

This seems to be a known issue and we're waiting on AWS to release a new EKS AMI with the fix.

Here's a (short term) solution to deal with that problem.

https://gist.github.com/BeyondEvil/456ef05f8b31f693e1018abf6b998fd0

**Comment by Diontsoumas** [comment]
@BeyondEvil out of curiosity, you have both requests and limits in your runners?

**Reply by BeyondEvil** [reply]
@Diontsoumas 

Correct. Both for memory and CPU.

```yaml
    resources:
      limits:
        cpu: 1500m
        memory: 4Gi
      requests:
        cpu: 1500m
        memory: 4Gi

qosClass: Guaranteed
```
