### DISCUSSION TITLE
Ephemeral mode and "Runner" resource type

### DISCUSSION THREAD

**Discussion by nlwstein** [actions/actions-runner-controller#1485] [General]
Not sure if it's our particular Kubernetes environment, but using the "Runner" type, which is called out early in the documentation does NOT work properly with the default values set: 

```
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: stm-prd-k8s
  namespace: github-runners
spec:
  organization: MY_ORG_NAME
  labels:
    - prd
```

It seems like the "Runner" bare resource when combined with ephemeral and the dockerd container simply falls into a degraded state (runner container exits with 0, docker left online) and the controller does not clean it up. 

I switched to a "RunnerDeployment", like this: 

```
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: stm-prd-k8s
  namespace: github-runners
spec:
  template:
    spec:
      organization: MY_ORG_NAME
      labels:
        - prd
```

...and it works perfectly! 

This can likely be solved by **[re-writing this section](https://github.com/actions-runner-controller/actions-runner-controller#repository-runners)**, and just instructing new users to use the "RunnerDeployment" type 😄
