### DISCUSSION TITLE
Controller is not launching more pods even though there's a lot of jobs queued

### DISCUSSION THREAD

**Discussion by bmbferreira** [actions/actions-runner-controller#1492] [Questions]
Hi! I'm having a bad time trying to understand why the controller is not launching more pods even though I have an enormous queue of jobs waiting to be executed. 
The situation is, I configured the autoscaling based on the recommended [workflow_job webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_job) and I'm setting a minumum of 1 replica and a max of ten. The configuration is this:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: cypress
  namespace: github-runner
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    name: cypress
  scaleUpTriggers:
  - duration: 5m
    githubEvent: {}
  scheduledOverrides:
  - endTime: "2022-05-16T05:00:00+00:00"
    minReplicas: 0
    recurrenceRule:
      frequency: Weekly
    startTime: "2022-05-13T22:00:00+00:00"
  - endTime: "2022-05-17T05:00:00+00:00"
    minReplicas: 0
    recurrenceRule:
      frequency: Daily
    startTime: "2022-05-16T22:00:00+00:00"
```

What is happening is that we have some jobs that are getting stuck with an external tool and sometimes the pods stay running for like 2 hours before it completes. However, having these long running jobs that are indeed a problem, I never see the number of pods reaching the max number of replicas that I configured (20). I get like 3/4 pods running for a couple of hours and an enormous queue of jobs queued. If I delete manually these long running jobs then the queue starts to recover.

What am I missing? I was expecting to have the max number of replicas being used even if I have other jobs running for a long time. 

Also, the infrastructure is not a problem because the cluster autoscaler is working fine and is launching new nodes when new pods are launched, the problem here seems to be the controller because I don't see new pods starting for the queued jobs.

Thanks in advance for your help!
