### DISCUSSION TITLE
Avoiding x509 TLS errors using daemon.json

### DISCUSSION THREAD

**Discussion by shakerg** [actions/actions-runner-controller#1507] [Show and tell]
I recently had an issue where running Docker Actions would fail authorizations against my private CA with x509 errors. Namely, I was using `docker login` to access my internal Nexus registry. To solve this I injected the `insecure-registries` param into the docker container as a configmap. I figured I'd put this here incase it could help anyone else.

```
      containers:
      - name: docker
        volumeMounts:
        - mountPath: /etc/docker/daemon.json
          name: daemon-json
          subPath: daemon.json
      volumes:
      - name: daemon-json
        configMap:
          name: daemon-json
---
apiVersion: v1
data:
  daemon.json: |-
    {
      "insecure-registries" : ["https://nexus.private.dom"]
    }
kind: ConfigMap
metadata:
  name: daemon-json
```
