### DISCUSSION TITLE
Webhook scaling has no effect

### DISCUSSION THREAD

**Discussion by yves-harms** [actions/actions-runner-controller#1528] [Questions]
Hi, I've deployed the runner controller with helm on kybernetes. Using the suggested webhook scaling config has no effect for me. The number of replicas wont increase, no matter how many workflows I'm manually triggering.
I've checked and the webhook server pod is available, there are no suspicious logs in the other pods to be found either.
My kybernetes scaling config:
[runner-deployment.yml.txt](https://github.com/actions-runner-controller/actions-runner-controller/files/8894327/runner-deployment.yml.txt)

Could anyone offer any advice on how to that running?

**Comment by toast-gear** [comment]
```yaml
  scaleUpTriggers:
  - githubEvent: {}
    duration: "15m"
    amount: 1
```

this is legacy syntax, install the latest chart (and CRDs!!!!!!!) and use the workflow_job syntax unless you have a really compelling reason to use one of the other events

```yaml
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "15m"
```
