### DISCUSSION TITLE
Webhook Autoscaling not correctly detecting HRA

### DISCUSSION THREAD

**Discussion by GoldenMouse** [actions/actions-runner-controller#1567] [Questions] [answered]
This may be related to https://github.com/actions-runner-controller/actions-runner-controller/issues/534 but I can't get a fix.

Here are my runners: 
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sweetspot-runner
spec:
  template:
    spec:
      organization: sweetspot
      #dockerdWithinRunnerContainer: true
      #dockerEnabled: false
      labels:
        - webhook

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: sweetspot-runner
spec:
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 1
  maxReplicas: 100
  scaleTargetRef:
    name: sweetspot-runner
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "5m"
      amount: 1
```

Here are the error logs:
```

2022-06-27T01:54:15Z    DEBUG   controllers.webhookbasedautoscaler      Found 0 HRAs by key     {"key": "sweetspot/helm-harness-poc"}
2022-06-27T01:54:15Z    DEBUG   controllers.webhookbasedautoscaler      Found some runner groups are managed by ARC     {"event": "workflow_job", "hookID": "365510676", "delivery": "0c09fa40-f5bc-11ec-81a4-bebf038f7531", "workflowJob.status": "queued", "workflowJob.labels": ["webhook"], "repository.name": "helm-harness-poc", "repository.owner.login": "sweetspot", "repository.owner.type": "Organization", "enterprise.slug": "dexcom-inc", "action": "queued", "groups": "RunnerGroup{Scope:Organization, Kind:Default, Name:}"}
2022-06-27T01:54:15Z    DEBUG   controllers.webhookbasedautoscaler      groups  {"event": "workflow_job", "hookID": "365510676", "delivery": "0c09fa40-f5bc-11ec-81a4-bebf038f7531", "workflowJob.status": "queued", "workflowJob.labels": ["webhook"], "repository.name": "helm-harness-poc", "repository.owner.login": "sweetspot", "repository.owner.type": "Organization", "enterprise.slug": "dexcom-inc", "action": "queued", "groups": "RunnerGroup{Scope:Organization, Kind:Default, Name:}"}
2022-06-27T01:54:15Z    ERROR   controllers.webhookbasedautoscaler      finding runner group    {"event": "workflow_job", "hookID": "365510676", "delivery": "0c09fa40-f5bc-11ec-81a4-bebf038f7531", "workflowJob.status": "queued", "workflowJob.labels": ["webhook"], "repository.name": "helm-harness-poc", "repository.owner.login": "sweetspot", "repository.owner.type": "Organization", "enterprise.slug": "dexcom-inc", "action": "queued", "enterprise": "dexcom-inc", "organization": "sweetspot", "repository": "helm-harness-poc", "key": "sweetspot", "error": "cache contained <nil>, which is not an Object"}
github.com/actions-runner-controller/actions-runner-controller/simulator.(*VisibleRunnerGroups).Traverse
        /workspace/simulator/runnergroups.go:183
github.com/actions-runner-controller/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).getScaleUpTargetWithFunction
        /workspace/controllers/horizontal_runner_autoscaler_webhook.go:547
github.com/actions-runner-controller/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).getJobScaleUpTargetForRepoOrOrg
        /workspace/controllers/horizontal_runner_autoscaler_webhook.go:461
github.com/actions-runner-controller/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle
        /workspace/controllers/horizontal_runner_autoscaler_webhook.go:236
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
        /usr/local/go/src/net/http/server.go:2462
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2916
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1966
2022-06-27T01:54:15Z    DEBUG   controllers.webhookbasedautoscaler      Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event      {"event": "workflow_job", "hookID": "365510676", "delivery": "0c09fa40-f5bc-11ec-81a4-bebf038f7531", "workflowJob.status": "queued", "workflowJob.labels": ["webhook"], "repository.name": "helm-harness-poc", "repository.owner.login": "sweetspot", "repository.owner.type": "Organization", "enterprise.slug": "dexcom-inc", "action": "queued"}
```
