### DISCUSSION TITLE
why my custom image commands are not seen by the runner

### DISCUSSION THREAD

**Discussion by fafg** [actions/actions-runner-controller#1666] [Questions]
![image](https://user-images.githubusercontent.com/9274235/180333925-a4fe3ac3-3ff3-46a6-9407-a3108170b653.png)

makefile rule
.PHONY: build-common
build-common: ## - execute build common tasks clean and mod tidy
	@ go version

but within my runner I have access to my tools:
![image](https://user-images.githubusercontent.com/9274235/180334341-b327ff94-376b-4e77-8b63-eb2ed13e814f.png)

docker commands are running properly, btw.

**Comment by fafg** [comment]
my runner setup:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: brahma-org-runner
  namespace: buildagents
spec:
  replicas: 5
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      organization: Brahma
      dockerEnabled: true
      dockerdWithinRunnerContainer: false
      serviceAccountName: eks-buildagents-sa
      image: ***.dkr.ecr.us-east-2.amazonaws.com/build-agent:v1.0
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      dockerVolumeMounts:
        - mountPath: /var/lib/docker
          name: docker-graph-storage
          subPathExpr: $(POD_NAME)-docker
        - mountPath: /runner/_work/$(POD_NAME)
          name: build-file-system
          subPathExpr: $(POD_NAME)-work
      volumeMounts:
        - mountPath: /runner/_work/$(POD_NAME)
          name: build-file-system
          subPathExpr: $(POD_NAME)-work
      dockerEnv:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 512Mi
      volumes:
        - name: docker-graph-storage
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: docker-agent-volume
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "gp2"
                resources:
                  requests:
                    storage: 20Gi
        - name: build-file-system
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: build-agent-volume
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "gp2"
                resources:
                  requests:
                    storage: 20Gi
```
