### DISCUSSION TITLE
`containerMode: kubernetes` not taken into account on GitHub Enterprise 3.5.2

### DISCUSSION THREAD

**Discussion by bquenin** [actions/actions-runner-controller#1774] [Questions] [answered]
Hi there!

We have deployed the latest version of ARC (0.25.2 as of the time of writing) and have registered our runner to our GitHub Enterprise instance version 3.5.2. We are facing the following issue:

![image](https://user-images.githubusercontent.com/11057786/187803858-59d75fc4-1914-4e00-af6a-aeb1d873d5b3.png)

The runner is configured as follow:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: bquenin-repository-runner
  namespace: actions-runner-system
spec:
  repository: bquenin/kind-actions
  containerMode: kubernetes
  serviceAccountName: runner-service-account
  workVolumeClaimTemplate:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  env: [ ]
  labels:
  - k8s-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-role
  namespace: actions-runner-system
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "create", "delete" ]
- apiGroups: [ "" ]
  resources: [ "pods/exec" ]
  verbs: [ "get", "create" ]
- apiGroups: [ "" ]
  resources: [ "pods/log" ]
  verbs: [ "get", "list", "watch", ]
- apiGroups: [ "batch" ]
  resources: [ "jobs" ]
  verbs: [ "get", "list", "create", "delete" ]
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "create", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-role-binding
  namespace: actions-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-role
subjects:
- kind: ServiceAccount
  name: runner-service-account
  namespace: actions-runner-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-service-account
  namespace: actions-runner-system
```

We have tried the exact same deployment and register our runner directly to Github instead of our Github Enterprise instance and everything started to work like a charm.

As our Github Enterprise instance version is 3.5.2, can you please confirm that upgrading to version 3.6.0 or above (stated as a prerequisite in the documentation https://github.com/actions-runner-controller/actions-runner-controller#github-enterprise-support) will solve this issue?
