### DISCUSSION TITLE
`containerMode: kubernetes` is it possible to configure the "job" pod and more specifically its "runner" container?

### DISCUSSION THREAD

**Discussion by bquenin** [actions/actions-runner-controller#1798] [Questions]
Hi everyone!

We're using the kubernetes runner and I was wondering if it's possible to configure the "job" pod specifications:

![Screen Shot 2022-09-12 at 12 53 10 PM](https://user-images.githubusercontent.com/11057786/189761806-e81f7508-30f8-43ea-8b3b-2c14a0bfe103.png)

According to the [documentation here](https://github.com/actions-runner-controller/actions-runner-controller#additional-tweaks), it is possible to configure the `runner` container of the runner pod:

```yaml
      containers:
      - name: runner
        # Usually, the runner container's privileged field is derived from dockerdWithinRunnerContainer.
        # But in the case where you need to run privileged job steps even if you don't use docker/don't need dockerd within the runner container,
        # just specified `privileged: true` like this.
        # See https://github.com/actions-runner-controller/actions-runner-controller/issues/1282
        # Do note that specifying `privileged: false` while using dind is very likely to fail, even if you use some vm-based container runtimes
        # like firecracker and kata. Basically they run containers within dedicated micro vms and so
        # it's more like you can use `privileged: true` safer with those runtimes.
        #
        # privileged: true
```

However, it seems to only affect the runner container of the runner pod. This configuration is not taken into account by "job" pod or its runner container.

Also, the configuration of the runner container itself seems pretty minimal (only the privileged flag).

Is there a way to configure the "job" pod runner container?

Thanks!
