### DISCUSSION TITLE
events to subscribe for enterprise runners

### DISCUSSION THREAD

**Discussion by swathida-byte** [actions/actions-runner-controller#1801] [Questions] [answered]
this is what I currently have in my scaler.yaml 
```
apiVersion: actions.summerwind.dev/v1alpha1
metadata:
  name: re-centos7-scaler
kind: HorizontalRunnerAutoscaler
spec:
  scaleTargetRef:
    name: re-centos7-deployment
  minReplicas: 1
  maxReplicas: 25
  scaleUpTriggers:
    - githubEvent:
        pullRequest:
          types: ["reopened","opened","edited","synchronize"]
      amount: 1
      duration: "120s"
```
what do I replace with pull-request event because at enterprise level there is no event type pull-request

**Comment by toast-gear** [comment, marked as answer]
we have deprecated all webhook events other than `workflowJob`, support for the other events will be removed in future versions of ARC as the Workflow Job event is the only event type you need, it was purpose built for runner scaling solutions like ARC. You need to migrate your webhooks and HRAs to the `Workflow Job` event.

**Comment by swathida-byte** [comment]
I'm getting 
`error: error validating "single.yaml": error validating data: ValidationError(HorizontalRunnerAutoscaler.spec.scaleUpTriggers[0].githubEvent): unknown field "workflowJob" in dev.summerwind.actions.v1alpha1.HorizontalRunnerAutoscaler.spec.scaleUpTriggers.githubEvent; if you choose to ignore these errors, turn validation off with --validate=false`

I'm using v.22.0

**Reply by toast-gear** [reply]
Your CRDs are out of date, I assume you manage ARC via Helm https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/docs/UPGRADING.md

**Comment by swathida-byte** [comment]
I have changed my yaml file to 
```
apiVersion: actions.summerwind.dev/v1alpha1
metadata:
  name: re-centos7-scaler
kind: HorizontalRunnerAutoscaler
spec:
  scaleTargetRef:
    name: re-centos7-deployment
  minReplicas: 1
  maxReplicas: 25
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "120s"
```
I'm still getting  unknown field "workflowJob"
