### DISCUSSION TITLE
containerMode: kubernetes - initialize containers fails with error: connect ECONNREFUSED 127.0.0.1:8080

### DISCUSSION THREAD

**Discussion by PaniczM** [actions/actions-runner-controller#1819] [Questions]
Hi, could you help me to find out why I'm getting this error (connect ECONNREFUSED 127.0.0.1:8080) when trying to use containerMode runner?

Here is my RunnerDeployment:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: container-mode-runner
  namespace: self-hosted-runners
spec:
  template:
    spec:
      repository: paniczm/runners-test
      containerMode: kubernetes
      labels:
        - container-mode
      serviceAccountName: container-mode-runner-sa
      workVolumeClaimTemplate:
        storageClassName: "default"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      env:
        - name: ACTIONS_RUNNER_KUBERNETES_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: runner-namespace
              key: actions_runner_kubernetes_namespace
```

Here is my wokflow:
```
name: Hello World
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, container-mode]
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
```

Here is worklow output:
![workflow_job](https://user-images.githubusercontent.com/48347922/191245517-b7366a14-74c4-4ad8-84da-5afe8cc27b6c.png)
