### DISCUSSION TITLE
Stuck building image with rke2 and containerd

### DISCUSSION THREAD

**Discussion by arrowcircle** [actions/actions-runner-controller#1863] [Questions]
Hey! I was trying to build docker image in my rke2 cluster, but struggle with strange errors. Here are my config and logs:

<details><summary>runner.yaml</summary>
<p>

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deploy
  namespace: github
spec:
  replicas: 1
  template:
    spec:
      repository: repo/repo

```

</p>
</details>

<details><summary>github-action.yml</summary>
<p>

```yaml
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          allow: "network.host,security.insecure"
          network: host
          push: true
          tags: repo/repo:${{github.sha}}

```
</p>
</details>

<details><summary>Dockerfile</summary>
<p>

```Dockerfile
FROM --platform=linux/amd64 ruby:3.1.2-slim-bullseye AS base

# Common dependencies
RUN apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    --no-install-recommends \
    build-essential \
    gnupg2 \
    curl \
    less \
    git \
    vim \
    ssh \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log
...
```
</p>
</details>

<details><summary>Log from CI</summary>
<p>

```log
#4 [ 2/13] RUN apt-get update -qq   && DEBIAN_FRONTEND=noninteractive apt-get install -yq     --no-install-recommends     build-essential     gnupg2     curl     less     git     vim     ssh   && apt-get clean   && rm -rf /var/cache/apt/archives/*   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*   && truncate -s 0 /var/log/*log
#4 90.67 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Connection timed out [IP: 199.232.138.132 80]
#4 90.67 W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Connection timed out [IP: 199.232.138.132 80]
#4 90.67 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Connection timed out [IP: 151.101.246.132 80]
#4 90.67 W: Some index files failed to download. They have been ignored, or old ones used instead.
```

</p>
</details>

I was trying to debug this, trying to run these commands in the container of the runner itself, everything is fine here.
How to further debug this or is there are any good examples of how to build docker images flexibly with the ability to install libs via apt?

**Comment by nporta-nep** [comment]
Hi! I have the exact same problem. Did you ever get to fix it?

**Reply by arrowcircle** [reply]
No, I had no success with that.

**Reply by ghost** [reply]
I am also struggling with the same issue. Did you guys made it work?

**Reply by nporta-nep** [reply]
Hi. I was able to make it work by setting to use the host networks in the actions workflow like this:
```
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1
        with:
          version: latest
          endpoint: builders
          driver: docker
          driver-opts: network=host

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          allow: network.host
          network: host
          file: packages/backend/Dockerfile
```
