### DISCUSSION TITLE
How to request resources for `runner` container? (via k8s or GitHub Actions workflow file)

### DISCUSSION THREAD

**Discussion by JLHasson** [actions/actions-runner-controller#1945] [Questions]
We are using ARC to run our own self hosted runners on EKS. So far everything is working great, however some jobs are getting killed by the cluster due to not requesting enough resources for the container:
```
33s         Warning   Evicted                    pod/eks-action-runner-pvdwp-ztdct                  The node was low on resource: ephemeral-storage. Container runner was using 6238024Ki, which exceeds its request of 0. Container docker was using 80Ki, which exceeds its request of 0.
```

I've tried a couple ways to configure this without success. Is it possible to specify in the Workflow file or elsewhere the resources required for the job? Here's what I've tried:

Setting the resources in the deployment for the runner, i.e.
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
...
  template:
    ...
      resources:
        requests:
          ephemeral-storage: "1Gi"
        limits:
          ephemeral-storage: "1Gi"
```
This results in the pod requesting these resources (i.e. the number of running pods will equal `node_resources / ephemeral-storage-requests`), but I still see that the `runner` container requests 0.

Setting the resources in the Github Workflow file, i.e.
```
jobs:
  myjob:
    name: myjob
    runs-on: eks-runner
    container:
      image: ubuntu:latest
      options: --cpus 1 --memory 1000m  # no option for ephemeral storage AFAIK?
```
however as far as I know there isn't a Docker CLI option for storage? https://docs.docker.com/config/containers/resource_constraints/

Would love a pointer on how to resolve this, preferably at the job level since not all of our jobs need the same resources, and would be great not to lose parallelism due to unused resources being locked up.
