### DISCUSSION TITLE
Trying to use dockerRegistryMirror due to Docker Rate Limiting

### DISCUSSION THREAD

**Discussion by JamesAskew** [actions/actions-runner-controller#2025] [Questions]
My runners are scaling in and out really nicely, but as a result, I am now getting hit with some Docker rate limiting. To get around this I want to use Amazon's public ecr gallery. I've set the value of dockerRegistryMirror in my values-override.yaml file and deployed a new revision. But images are still being pulled from docker.io.

Has anyone managed to get a registry mirror working that could give me some tips?

I've read all of the discussion and issues which seem relevant, but nothing has helped me. 

Here are my helm overrides:
```
dockerRegistryMirror: "https://public.ecr.aws"
image:
  repository: "summerwind/actions-runner-controller"
  actionsRunnerRepositoryAndTag: "summerwind/actions-runner:latest"
  dindSidecarRepositoryAndTag: "docker:dind"
  pullPolicy: Always
  # The default image-pull secrets name for self-hosted runner container.
  # It's added to spec.ImagePullSecrets of self-hosted runner pods.
  actionsRunnerImagePullSecrets: []
```

Inside the controller pod, I can see the following arguments:
```

--metrics-addr=127.0.0.1:8080 --enable-leader-election --port=9443 --sync-period=1m --default-scale-down-delay=10m --docker-image=docker:dind --runner-image=summerwind/actions-runner@sha256:af356cd14f621b98194da116b33d331af45191dc0ab07d708769290793494581 --docker-registry-mirror=https://public.ecr.aws
```

But regardless the image is always from docker.io

Any helps or tips would be greatly appreciated.

**Comment by toast-gear** [comment]
Any of docker configuration options that are at a container file system level require you use the dind runner image

**Reply by JamesAskew** [reply]
Thanks for the response toast-gear. Really appreciate it!

I've found this documentation, which I think is what you are referring to: https://github.com/actions-runner-controller/actions-runner-controller/blob/master/docs/detailed-docs.md#runner-with-dind

Our deployment strategy is Helm, so that's where I have made the change:

```
dockerRegistryMirror: "https://public.ecr.aws"
image:
  repository: "summerwind/actions-runner-controller"
  actionsRunnerRepositoryAndTag: "summerwind/actions-runner-dind:latest"
  #dindSidecarRepositoryAndTag: "docker:dind"
  pullPolicy: Always
  # The default image-pull secrets name for self-hosted runner container.
  # It's added to spec.ImagePullSecrets of self-hosted runner pods.
  actionsRunnerImagePullSecrets: []
```

I can see now that the runner image is: `summerwind/actions-runner-dind:latest` but 

- the pod still has two containers `runner` and `docker`
- the full path of the image is still docker.io/summerwind/actions-runner-dind

Is everything correct so far, can you advise on anything I am missing?

Thanks

James
