### DISCUSSION TITLE
Job container authentication to a private Google Container Registry

### DISCUSSION THREAD

**Discussion by jorob16** [actions/actions-runner-controller#2038] [Questions] [answered]
I'm trying to give my runner access to a private Docker registry implemented using Google Container Registry. I need to be able to pull images that are on this Registry server in order to use them for job containers used in my workflows. I'm running the actions runner controller on Google Kubernetes Engine and it's all working fine. IAM is assigned through Workload Identity.

The problem: job containers that need images from private Docker registries only accept usernames and passwords (See: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container). For Google Container Registry it's best practice to install the gcloud sdk and run the gcloud credential helper using `gcloud auth configure-docker` in order to retrieve short lived access tokens for Docker authentication (See: https://cloud.google.com/container-registry/docs/advanced-authentication).

I've set up a `RunnerDeployment` called `oos-basic` which uses a modified actions-runner image that has the gcloud sdk included. And I'm trying to run the following workflow:
```
name: Create new release version
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release version, leave empty for default
        default: ''
        type: string
jobs:
  update-version:
    name: Update release version
    runs-on: [self-hosted, oos-basic]
    container: eu.gcr.io/*<redacted>*/cicd-bumpversion:1
    steps:
    ...
```

Has anyone worked on a problem similar to this? Ideally I would run `gcloud auth configure-docker` on the runner before the actual job starts. Right now I'm obviously getting an authentication error:
![afbeelding](https://user-images.githubusercontent.com/91264722/203639674-d3ede2f4-45f4-4306-8311-be2d786346c4.png)

I've already tried adding a postStart lifecycle hook to the runner pod spec that runs a bash script that simply runs the command, but that kills my runner right after startup with the following error: `unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory`

So I figured that I would have to wait for Docker to have retrieved its' certs, so I added a simple loop in the script that waits for `ca.pem` to be available: 
```
timeout=60
passed=0
echo "Waiting for docker daemon to be fully started"
until [ -f "${DOCKER_CERT_PATH}/ca.pem" ] || [ ${timeout} -lt ${passed} ]; do
    echo -n "."
    passed=`expr $passed + 1`
    sleep 1
done
echo "Adding docker credentials for Google Container Registry"
gcloud auth configure-docker
```
Sadly that still gives the same error.

Would love to hear if anyone has some suggestions for how to best tackle this problem or whether it's at all possible to solve!

**Comment by roulettedares** [comment]
i created an internal composite action for this
```
name: Build and Push Container Image
description: 'Build and Push Container Image'
inputs:
  artifact:
    description: name of a github artifact to download
    required: false
  tags:
    description: docker image tags to push
    required: true
outputs:
  image:
    description: "The docker image"
    value: ${{ steps.container-build.outputs.imageid }}
runs:
  using: "composite"
  steps:
  - name: Set up Docker Context for Buildx
    shell: bash
    run: docker context create arc
  - uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2.4.1
    with:
      endpoint: arc
  - name: Download artifact
    if: ${{ inputs.artifact != '' }}
    uses: actions/download-artifact@v3
    with:
      name: ${{ inputs.artifact }}
  - name: gcr-auth
    shell: bash
    id: gcr-auth
    run: |-
      access_token="$(curl -s --retry 5 \
        "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" \
        -H "Metadata-Flavor: Google" \
        | jq -r .access_token)"
      echo "access_token=$access_token" >> $GITHUB_OUTPUT
      echo "::add-mask::$access_token"
  - name: Login to GCR
    uses: docker/login-action@v2
    with:
      registry: gcr.io
      username: oauth2accesstoken
      password: ${{ steps.gcr-auth.outputs.access_token }}
  - name: Build and push Docker images
    id: container-build
    uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 #v4.0.0
    with:
      push: true
      context: .
      tags: |
        ${{ inputs.tags }}%
```
