### DISCUSSION TITLE
RunnerSet results in: ERROR --- RUNNER_NAME must be set

### DISCUSSION THREAD

**Discussion by IngoS11** [actions/actions-runner-controller#2071] [Questions]
Hi everyone,

I have a Controller and a RunnerDeployment running just fine. Today I wanted to give RunnerSet a try but it results in the POD saying that RUNNER_NAME must be set. I feel like I am missing a very obvious thing but I am not seeing it. Can somebody maybe have a look and point me in the right direction?

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: org-runnerset
spec:
  replicas: 1
  organization: lab
  ephemeral: true
  group: eks-runner-set
  labels:
    - eks-runner-set
  dockerEnabled: false
  selector:
    matchLabels:
      app: org-runnerset
  serviceName: org-runnerset
  template:
    metadata:
      labels:
        app: org-runnerset
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: runner
          image: 'our-internal-company-docker-registry/docker.io/summerwind/actions-runner:v2.299.1-ubuntu-20.04'
          resources:
            limits:
              cpu: '4.0'
              memory: '8Gi'
            requests:
              cpu: '2.0'
              memory: '4Gi'

```
LOG on runner
```
2022-12-05 23:23:44.800  NOTICE --- Runner init started with pid 7
2022-12-05 23:23:44.803  DEBUG --- Github endpoint URL <our_github_enterprise_server>
2022-12-05 23:23:44.805  ERROR --- RUNNER_NAME must be set
2022-12-05 23:23:44.806  NOTICE --- Runner init exited. Exiting this process with code 0 so that the container and the pod is GC'ed Kubernetes soon.
```

**Comment by mumoshu** [comment]
@IngoS11 Hey, I remember ARC injected the RUNNER_NAME envvar via ARC's mutating webhook. Have you uninstalled or not installed ARC's admission webhook server? If so, please install it. It's required.

**Reply by jianliang00** [reply]
Are there any documents about how to configure the webhook server? I'm facing the same problem and I just deployed a minimum worked controller, without configuring the webhook server

**Comment by IngoS11** [comment]
@mumoshu . Thank you so much for the super fast response. I have the `mutatingwebhook` and the `validatingwebhook` installed. I can list them via `kubectl` and see them in `ArgoCD`. I also have a `RunnerDeployment` connected to the same `Controller` and it is running just fine.

**Comment by antonkad** [comment]
Same issue for me, working well with runnerDeployment

When I enable mutatingwebhook, the runnerset doesn't want to deploy any pods anymore.

**Reply by antonkad** [reply]
"DEBUG    actions-runner-controller.runnerset    Skipped reconcilation because owner is not synced yet"

**Reply by antonkad** [reply]
Discovered, there's also a statefulset being created:

```
Internal error occurred: failed calling webhook "mutate-runner-pod.webhook.actions.summerwind.dev": failed to call webhook: Post "https://actions-runner-controller-webhook.actions-runner-system.svc:443/mutate-runner-set-pod?timeout=10s": EOF  
```

**Reply by antonkad** [reply]
wath I don't understand I why the wekhook svc point to 9443:

```
 ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
```

and redirect the request not to the github-webhook-server container but to the actions-runner-controller
