### DISCUSSION TITLE
extra runner labels

### DISCUSSION THREAD

**Discussion by acapogna-pf** [actions/actions-runner-controller#2109] [Questions] [answered]
Hi all! First i wanna say this is a fantastic tool!
I'm having a bit of trouble understanding how to add extra labels to my runners. They all spin up with "self-hosted" "Linux" and "X64" labels as you can see here:
![Screenshot from 2022-12-28 10-58-18](https://user-images.githubusercontent.com/113926469/209794195-5f366a72-1400-4494-895f-458527510d45.png)
but i would need to add some extra. How can i do that?

**Comment by toast-gear** [comment, marked as answer]
https://github.com/actions/actions-runner-controller/blob/master/docs/detailed-docs.md#runner-labels

**Reply by maeghan-porter** [reply]
I'm looking to answer this same question but this link results in a 404 now :( Did the doc get moved?

**Reply by acapogna-pf** [reply]
Hi! Confirm the page is 404, but anyway this is the basic construct i've used:

In the github action you specified which labels you want your runner to have:
```
jobs:
  Production:
    name: Production deployment
    runs-on: [self-hosted, k8s]
    steps:
    ...
```


Then in the definition of the runner you also specify the "k8s" label:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: name-of-the-runner
spec:
  replicas: 1
  template:
    spec:
      repository: github_user/repository
      labels:
        - k8s
```
