### DISCUSSION TITLE
How to stop scaling runners if already some free runners are available

### DISCUSSION THREAD

**Discussion by roshvin** [actions/actions-runner-controller#2190] [Questions]
we are using below HRA conf. even if we have free runners , some time it scale up to 50 and lots of free runners will be available .

how we can check and stop scaling if there is already free runners available. 

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
   name: ent-runner-auto-scaller
spec:
  scaleDownDelaySecondsAfterScaleOut: 5
  scaleTargetRef:
    name: dot-free-runner
    kind: RunnerSet
  minReplicas: 1
  maxReplicas: 50
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"

```
