### DISCUSSION TITLE
Actions Metrics Server on GHES  - no metrics

### DISCUSSION THREAD

**Discussion by stelligent-joao** [actions/actions-runner-controller#2226] [Questions]
I am having issues getting any sort of data from the new actions metrics server on GHES 3.7.4.
Upon deploying the new actions metrics server using the config bl
```
githubEnterpriseServerURL: https://github.akgj.com/api/v3
authSecret:
  github_app_id: <hidden>
  github_app_installation_id: <hidden>
  github_app_private_key: <hidden>
certManagerEnabled: true
scope:
  singleNamespace: false
githubWebhookServer:
  secret:
    enabled: true
    name: "github-webhook-server"
  enabled: true
  service:
    type: LoadBalancer
    ports:
      - port: 443
        targetPort: http
        protocol: TCP
        name: http
        nodePort: 31017
actionsMetricsServer:
  imagePullSecrets: []
  logLevel: "-4"
  enabled: true
  labels: {}
  replicaCount: 1
  secret:
    enabled: true
    create: false
    name: "github-webhook-server"
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
actionsMetrics:
  serviceMonitor: true
  port: 8009
  proxy:
    enabled: false
  serviceMonitorLabels: {release: prometheus-stack}
metrics:
  serviceMonitor: true
  port: 8002
  serviceMonitorLabels: {release: prometheus-stack}
  proxy:
    enabled: false
```

The metrics server logs don't ever log any activity upon start
```
kubectl logs -n actions-runner-system actions-runner-controller-actions-metrics-server-fdcc6ffd-5w4tv -f
2023-01-27T19:39:36Z	INFO	Using the value from GITHUB_WEBHOOK_SECRET_TOKEN for -github-webhook-secret-token
```

curling the actions-runner-controller-metrics-service exposes many metrics but non of the new "actions metrics server" even after running workflows in github that trigger scale up actions and those events can be seen in the github webhook server logs.

Has anyone managed to get this working on GHES hosted?
