### DISCUSSION TITLE
Running w/ Karpenter - recommended resource requests?

### DISCUSSION THREAD

**Discussion by ghost** [actions/actions-runner-controller#2317] [Questions]
Hi there!  

I've combed through all the issues related to runners simply "canceling" mid-build and can't yet find a solution for what we're experiencing (a number of our actions just "cancel" randomly) - seemingly since we switched from using cluster-autoscaler in our build cluster to karpenter.  I'm curious if it's because there are seemingly no resource requests defined in the runner deployments, so karpenter is behaving strangely... if so, are there recommended resource requests?  I found these:
```
  resources:
        limits:
          cpu: "4.0"
          memory: "8Gi"
        requests:
          cpu: "2.0"
          memory: "4Gi"
``` 
at this link - https://github.com/actions/actions-runner-controller/issues/new/choose 
... but these seem fairly high for a single pod/runner..? 

Just wondering if anyone has insight on successfully running ARC with karpenter, _without_ builds randomly canceling... (seems to happen more when there are multiple builds / actions running simultaneously)... thanks!
