### DISCUSSION TITLE
Scheduled Overrides for HRA

### DISCUSSION THREAD

**Discussion by semihural-tomtom** [actions/actions-runner-controller#2319] [Questions]
I would like to configure scheduled overrides for HRA for our time zone which is CET(Amsterdam) and time off.
What I wanna achieve is, to have `minReplica:50` during the day between 08:00 am - 22:00(10:00 pm), and the rest of the time it should be `minReplica:10`.

But seems I made something wrong, cause the Schedule, shows `min=10 time=2023-02-24 21:00:00 +0000 UTC`. Is that correct, or is my configuration looks good?

Meanwhile, I would like to exclude weekends, where `minReplica:1`. How can I achieve this ?

```
$ kubectl get hra --all-namespaces
NAMESPACE             NAME                                 MIN   MAX   DESIRED   SCHEDULE
staging-8c-32gb       gha-staging-8c-32gb-autoscaler       10    150   65        min=10 time=2023-02-24 21:00:00 +0000 UTC
```

```
  maxReplicas: 150
  minReplicas: 10
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: gha-staging-8c-32gb
  scaleUpTriggers:
  - duration: 12h
    githubEvent:
      workflowJob: {}
  scheduledOverrides:
  - endTime: "2023-02-24T22:00:00+01:00"
    minReplicas: 50
    recurrenceRule:
      frequency: Daily
    startTime: "2023-02-24T09:00:00+01:00"
```

**Comment by totogtr** [comment]
hi @semihural-tomtom , were you able to achieve this ?

**Reply by semihural-tomtom** [reply]
Yes, hope it helps.

```
  scheduledOverrides:
  - endTime: "2023-02-27T00:00:00+01:00"
    minReplicas: 1
    recurrenceRule:
      frequency: Weekly
    startTime: "2023-02-25T00:00:00+01:00"
  - endTime: "2023-02-24T18:00:00+01:00"
    minReplicas: 50
    recurrenceRule:
      frequency: Daily
    startTime: "2023-02-24T06:00:00+01:00"
```
