### DISCUSSION TITLE
DinD how to run container as daemon?

### DISCUSSION THREAD

**Discussion by usernamessh** [actions/actions-runner-controller#2364] [Questions] [answered]
Hello community,
I have a special Docker container, which has installed complex build environment. So I like to run this container in the runner-container and just use it on demand. It shall sit idle and wait for commands from the GH workflow-script, which is received by the runner.

In general the setup is able to start, but naturally the special build-container terminates, because it is not run with
```yaml
docker run -it <name> -d
```
Question: How can I tell ARC to run the container with the arguments "-it" and "-d"?
Or any better idea?

```yaml
#runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actionsrunner-win2022
  namespace: actions-runner-system 
spec:
  replicas: 10
  template:
    spec:
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      organization: my-org
      image: ghcr.io/my-org/runner-win2022:latest
      imagePullSecrets:
      - name: runnersecret   
      imagePullPolicy: "Always"
      dockerdWithinRunnerContainer: true
      containers:
        - name: runner-build-server
          image: ghcr.io/my-org/builder-win2022:latest
      nodeSelector:
        kubernetes.io/os: windows      
      labels: 
        - ARC
        - windows
```
