### DISCUSSION TITLE
How to access the sidecar Docker container from within workflow script?

### DISCUSSION THREAD

**Discussion by usernamessh** [actions/actions-runner-controller#2372] [Questions]
Hello community,
In our sidecar container we have a complex build environment. During execution of GH workflow, I need to copy stuff into the sidecar container, start the build inside and at the end I need to copy the build-results from the sidecar container.

In runnerdeployment, `dockerdWithinRunnerContainer: true` is active.
To check if Docker is accesible, I tried using e. g. `docker ps -a` but it ended up in the Docker error message that the named pipe isn't accesible:

How can I access the sidecar container from within the GH worflowscript?

```yaml
error during connect: this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/auth": open //./pipe/docker_engine: The system cannot find the file specified.
```

```yaml
#runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actionsrunner-win2022
  namespace: actions-runner-system 
spec:
  replicas: 10
  template:
    spec:
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      organization: my-org
      image: ghcr.io/my-org/runner-win2022:latest
      imagePullSecrets:
      - name: runnersecret   
      imagePullPolicy: "Always"
      dockerdWithinRunnerContainer: true
      containers:
        - name: runner-build-server
          image: ghcr.io/my-org/builder-win2022:latest
      nodeSelector:
        kubernetes.io/os: windows      
      labels: 
        - ARC
        - windows
```

**Comment by usernamessh** [comment]
@mumoshu Sorry to ask but maybe you can add your valuable comments about it? Question is, how to access the sidecar Docker container (e.g. docker cp, docker exec, docker start, ...) from within a Github workflow script? Please notice, we are on Windows here so there is no real DinD support unfortunately. But since there is a sidecar container running, it should be able to access it somehow? Thanks in advance!

**Reply by MohanSaiTeki** [reply]
Assuming you are running two containers in one Kubernetes pod, one is a runner container, and the second is a docker container.

> how to access the sidecar Docker container

Please check DOCKER_HOST environment variable is accessible or not from the runner container. If not please add that by pointing to the sidecar docker container.

Please refer [this](https://stackoverflow.com/a/39350770/8142010) StackOverflow answer

**Reply by usernamessh** [reply]
Hi MohanSaiTeki!
thanks a lot for your comment. I followed your suggestion and also tried to follow the StackOverflow answer.
The StackOverflow answer suggests using Docker-Toolbox / Docker-Machine that uses VirtualBox. I wasn't able to gain helpful information out of this. (I insalled it all but then ended up in some other strange errors).

Please notice that I have to use Windows-Containers with a own Windows-Runner-Image. And Docker-in-Docker (DinD) still is not really supported by Microsoft / Windows.

How to make DOCKER_HOST point to the sidecar docker container? How to get it's IP? Only know the parents POD IP address.

**Reply by MohanSaiTeki** [reply]
> How to make DOCKER_HOST point to the sidecar docker container?

Assuming the below point is correct.
> Assuming you are running two containers in one Kubernetes pod, one is a runner container, and the second is a docker container

By default containers in the same pod can communicate through localhost. Identify on which port docker is running by default it will run on **2376** and set the environment variable to runner container as below

  ```
containers:
    - name: runner
      image: ghcr.io/my-org/runner-win2022:latest
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2376
```
