### DISCUSSION TITLE
Is there a way to customize the securityContext in `containerMode: kubernetes`?

### DISCUSSION THREAD

**Discussion by Pigueiras** [actions/actions-runner-controller#2404] [Questions]
I have the following running `RunnerDeployment`:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: yyyy
  namespace: default
spec:
  replicas: 3
  template:
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
      containers:
      - name: runner
        env: []
        securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
      repository: xxxx
      containerMode: kubernetes
      serviceAccountName: my-service-account
      workVolumeClaimTemplate:
        storageClassName: local-path
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```

Is it possible to pass `securityContext` rules to the generated pod that will run the job in the Github Actions? I am experimenting with PSS, that's why I want to see if it's possible to generate (at this moment, the `securityContext` of the workflow pod is empty, and therefore the job in GitHub Actions simply fails, because the security standards are preventing the pod from being created).
