### DISCUSSION TITLE
Failed to get new registration token. x509: certificate signed by unknown authority

### DISCUSSION THREAD

**Discussion by Edarjak** [actions/actions-runner-controller#2455] [Questions] [answered]
Hi community,

Is there any option on how to add the root CA of the GitHub Enterprise Server to the actions-runner-controller?

I get this error:

```
ERROR	runner	Failed to get new registration token	{"runner": "github-actions-runner-001-rw88q-nhmhq", "error": "failed to create registration token: Post \"https://my-github.example.org/api/v3/orgs/myorg/actions/runners/registration-token\": could not refresh installation id 5's token: could not get access_tokens from GitHub API for installation ID 5: x509: certificate signed by unknown authority"}
```

The certificate of GHES is self-signed.

Thanks in advance,

**Comment by Edarjak** [comment]
@mumoshu sorry for pinging you, but maybe you have some ideas or guides. I was thinking to use a Dockerfile, but not quite sure how to add root CA to the controller that is written in go (with the runner image everything is understandable)

Should I do something like this?:

```
FROM summerwind/actions-runner-controller

ADD ./My_Root_CA.pem /usr/local/share/my-root-ca.pem
```

P.S. The controller pod is running in K3S cluster

**Comment by Edarjak** [comment, marked as answer]
Solved. Had to add a root CA as a configMap, then in the ARC deployment had to edit the "volumes" section and "volumeMounts":

```
        volumeMounts:
        - name: my-pem
          mountPath: /etc/ssl/certs/my-cert.pem
          subPath: my-cert.pem
          readOnly: false
      volumes:
      - name: my-pem
        configMap:
          name: my-pem
```
