### DISCUSSION TITLE
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?

### DISCUSSION THREAD

**Discussion by Edarjak** [actions/actions-runner-controller#2479] [Questions] [answered]
Hi community,

I have successfully installed ARC on my K3S cluster and created a RunnerDeployment:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-actions-runner
  namespace: github-actions-runner
spec:
  replicas: 1
  template:
    spec:
      organization: myorg
      env:
        - name: GIT_SSL_CAINFO
          value: /etc/ssl/certs/my-root-ca.pem
      labels:
        - arc
        - kubernetes
        - small
      group: Default
      volumes:
        - name: ca-cert
          configMap:
            name: ca-cert
      volumeMounts:
        - name: ca-cert
          mountPath: /etc/ssl/certs/my-root-ca.pem
          subPath: my-root-ca.pem
          readOnly: true
```

However, I found these messages in the runner logs:

```

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration




√ Runner successfully added
√ Runner connection is good

# Runner settings


√ Settings Saved.

2023-04-04 17:03:39.692  DEBUG --- Runner successfully configured.
{
  "isHostedServer": false,
  "agentId": 45,
  "agentName": "github-actions-runner-8hv8f-zjmqw",
  "poolId": 1,
  "poolName": "Default",
  "ephemeral": true,
  "serverUrl": "https://my-github.example.com/_services/pipelines/0Hu2wef48448wefwe8r429349we4foK",
  "gitHubUrl": "https://my-github.example.com/myorg",
  "workFolder": "/runner/_work"
2023-04-04 17:03:39.704  DEBUG --- Docker enabled runner detected and Docker daemon wait is enabled
2023-04-04 17:03:39.706  DEBUG --- Waiting until Docker is available or the timeout of 120 seconds is reached
unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory
unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory
unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?

```

What is the reason for these messages? 

Thanks in advance,

P.S. K3S uses containerd
