### DISCUSSION TITLE
How to get metrics for an HRA with Webhook scaling?

### DISCUSSION THREAD

**Discussion by alexklibisz** [actions/actions-runner-controller#2482] [Questions]
Hi, thanks for the awesome project!

We have been using pull-driven scaling on some HRAs for a few months and collecting the horizontalrunnerautoscaler_runners, horizontalrunnerautoscaler_runners_busy, horizontalrunnerautoscaler_spec_max_replicas, etc. metrics. These metrics seem to be [defined here](https://github.com/actions/actions-runner-controller/blob/56754094ea943ade0ce487c5cb9dfd5211496500/controllers/actions.summerwind.net/metrics/horizontalrunnerautoscaler.go#L20-L33), although I'm not 100% certain about that.

Here's the full list of metrics we currently ingest:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/8015228/229939026-e77abb65-f23c-4e08-a6c0-87e94ad54702.png">

We recently added an HRA with webhook-based scaling. The autoscaling seems to work well. However, we cannot seem to find the corresponding metrics for this new HRA.

The old actions-runner-controller pod that handles pull-driven scaling does not expose any metrics for this HRA. It still exposes metrics for the pull-driven HRA. 

The new webhook-server pod also does not expose any metrics for this HRA or any of the others.

We haven't tried the new actions-metrics pod.

Can someone help me figure out how to expose these metrics for the new webhook-based HRA?

**Comment by alexklibisz** [comment]
After reading the code a bit, I managed to get the controller pod to emit the metrics by adding this to the HRA spec:

```yaml
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
  metrics:
  # This is a bit of a hack. The typical usecase for adding a metrics entry is to use the
  # metric for auto-scaling. However, we just want to see the metric values, even though
  # we are using the scaleUpTriggers or scaling. Adding this metric with all settings set
  # to 1 seems to be the only way to convince the runner-controller to still emit the metrics.
  - type: PercentageRunnersBusy
    scaleUpThreshold: ''
    scaleDownThreshold: ''
    scaleUpAdjustment: 0
    scaleDownAdjustment: 0
```

As noted in the comment, this seems a bit hacky. I appreciate any input :)
