### DISCUSSION TITLE
How does one create labels for runner pods?

### DISCUSSION THREAD

**Discussion by shankarRaman** [actions/actions-runner-controller#2525] [Questions] [answered]
I see that there's field for adding labels to the runners which get translated as runner tags. What I am looking for is adding labels to the actual pod through the `RunnerDeployment` object.

**Comment by devops-sailboat** [comment]
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: POD NAME
  namespace: devops
spec:
  replicas: 1
  template:
    spec:
      repository: xyz/zyx
      labels:
        - auto-runner
        
        
        
        
     I hope this helps you !

**Comment by shankarRaman** [comment, marked as answer]
Thanks @devops-sailboat 
I figured what I needed, 
```yaml
kind: RunnerDeployment
metadata:
  name: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        foo: bar
    spec:
      imagePullSecrets:
```
