### DISCUSSION TITLE
Trying to setup summerwind/actions-runner image with kaniko

### DISCUSSION THREAD

**Discussion by muhamedkapoevolt** [actions/actions-runner-controller#2532] [Questions]
### What would you like added?

Hello everyone, I'm trying to figure out how to use "summerwind/actions-runner" or "summerwind/actions-runner-dind" image as base to install kaniko on it (I know that second image is for DinD). 

I added following part in Dockerfile

```
COPY --from=kaniko --chown=runner /kaniko/executor /kaniko/executor
COPY --from=kaniko --chown=runner /kaniko/docker-credential-gcr /kaniko/docker-credential-gcr
COPY --from=kaniko --chown=runner /kaniko/docker-credential-ecr-login /kaniko/docker-credential-ecr-login
COPY --from=kaniko --chown=runner /kaniko/docker-credential-acr-env /kaniko/docker-credential-acr-env
COPY --from=kaniko --chown=runner /etc/nsswitch.conf /etc/nsswitch.conf
COPY --from=kaniko --chown=runner /kaniko/ssl/certs/ /kaniko/ssl/certs/
COPY --from=kaniko --chown=runner /kaniko/.docker /kaniko/.docker

RUN chown -R runner /kaniko

ENV PATH $PATH:/usr/local/bin:/kaniko
ENV SSL_CERT_DIR=/kaniko/ssl/certs
ENV DOCKER_CONFIG /kaniko/.docker/
ENV DOCKER_CREDENTIAL_GCR_CONFIG /kaniko/.config/gcloud/docker_credential_gcr_config.json
```

After i run job, I got this error (from picture below).

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/102165774/233984500-0b6f9a83-90dc-43a7-a93c-aa38c8c5de01.png">

So, I tried to add couple of different definitions in RunnerDeployment

```
containers:
  - name: runner
    securityContext:
      capabilities:
        drop: [ALL]
        add: [CHOWN, FOWNER, SETUID, SETGID, DAC_OVERRIDE]
      privileged: false
      allowPrivilegeEscalation: false
```

As well i tried to set `privileged: true` and `allowPrivilegeEscalation: true` without setting capabilities. Does anyone have an idea what to do, how to create runners with kaniko?

I would like to get an example in repo for kaniko.

Btw, I'm using AWS as cloud provider.

### Why is this needed?

Because it will be helpful to have an example for kaniko or even buildah/podman.
