### DISCUSSION TITLE
Adding a container sidecar to actions-runner-controller

### DISCUSSION THREAD

**Discussion by NLadib-PartnerAuchan** [actions/actions-runner-controller#2533] [Questions]
Hi there,

I am using actions-runner-controller to deploy self-hosted runners in my Kubernetes cluster. I have a requirement to add a container sidecar to the existing 'runner' and 'docker' containers, and I was wondering if this is possible with actions-runner-controller.

I noticed that the current RunnerSet manifest allows for adding additional containers using the containers field. Would it be possible to add a container sidecar in addition to the existing 'runner' and 'docker' containers using this field? Here's an example of what I have in mind:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: runner
  namespace: actions-runners
spec:
  template:
    spec:
      group: runners
      labels:
        - docker
        - Linux
        - X64
        - self-hosted
      image: my.registry.com/github-internal-runner:latest
      organization: orga-np
      containers:
        - name: runner-sidecar
          image: my.registry.com/runner-sidecar:latest
          args:
            - arg1
            - arg2
          env:
            - name: MY_ENV_VAR
              value: "my-value"
          ports:
            - containerPort: 8080
              protocol: TCP

```

Is this something that could be supported in actions-runner-controller? I would greatly appreciate any guidance or suggestions on how to achieve this.

Thank you!
