### DISCUSSION TITLE
HorizontalRunnerAutoscaler with matrix not scaling

### DISCUSSION THREAD

**Discussion by igutierrezn** [actions/actions-runner-controller#2534] [Questions]
Hello!

I am running self-hosted runners in a GCP GKE cluster. With the following runner_deployment configuration:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: realnaut-runnerdeploy
  namespace: actions-runner-system
spec:
  template:
    spec:
      organization: realnautops # FOR ORG REPOSITORY
      image: $IMAGE #IMAGE is the docker image uploaded in the container registry from the realnaut-gke project in gcloud, the uploaded image is in runner-docker-image folder.
      labels:
        - realnaut

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: realnaut-runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleDownDelaySecondsAfterScaleOut: 60
  scaleTargetRef:
    kind: RunnerDeployment
    name: realnaut-runnerdeploy ## SAME NAME OF THE RUNNERDEPLOYMENT ABOVE
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - onboarding-realnauters ## ONLY THE RESPOSITORY NAME
        - governance-tool-frontend
        - governance-tool-api
        - aws-iam-identity-center

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: rudder-backend-runnerdeploy
spec:
  replicas: 1
  template:
    spec:
      repository: realnautops/governance-tool-backend
      image: $IMAGE #IMAGE is the docker image uploaded in the container registry from the realnaut-gke project in gcloud, the uploaded image is in runner-docker-image folder.
      labels:
        - realnaut-rudder-backend
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: rudder-backend-realnaut-runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    kind: RunnerDeployment
    name: rudder-backend-runnerdeploy
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"

```

The first deployment, **realnaut-runnerdeploy** works fine, but when I execute a workflow with a matrix for the second deployment **rudder-backend-runnerdeploy** the HorizontalRunnerAutoscaler is stuck at desired 1:

```
NAME                                                   MIN   MAX   DESIRED   SCHEDULE
realnaut-runner-deployment-autoscaler                  1     4     1
rudder-backend-realnaut-runner-deployment-autoscaler   1     6     1
```
