### DISCUSSION TITLE
One RD scaling too high and the other seems to not scale at all

### DISCUSSION THREAD

**Discussion by maeghan-porter** [actions/actions-runner-controller#2558] [Questions]
So I have 2 RDs and HRAs to represent production workloads and nonproduction workloads. They are configured fairly similarly with only the scaleUpFactor being different (I will share the configs below). The problem I am seeing is, though the prod runners are used pretty infrequently compared to nonprod, the prod HRA has the RD set to 8 replicas at all times even when no runners are being used, but the nonprod HRA has its RD only set to 1 and though multiple jobs are waiting for a free runner, it is not scaling. Any insight would be very helpful.
Here are my configs:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment-nonprod
  namespace: gha
spec:
  template:
    spec:
      image: summerwind/actions-runner-dind:v2.303.0-ubuntu-22.04
      dockerdWithinRunnerContainer: true
      organization: ***
      labels:
        - ${env} #flux variable substitution going on here
        - ${release}
        - nonprod
      group: ${runner_group}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-autoscaler-nonprod
  namespace: gha
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: runner-deployment-nonprod
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '1'
      scaleDownFactor: '1'
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment-prod
  namespace: gha
spec:
  template:
    spec:
      image: summerwind/actions-runner-dind:v2.303.0-ubuntu-22.04
      dockerdWithinRunnerContainer: true
      organization: ***
      labels:
        - ${env} #flux variable substitution going on here
        - ${release}
        - prod
      group: ${runner_group}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-autoscaler-prod
  namespace: gha
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: runner-deployment-prod
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '2'
      scaleDownFactor: '1'
```

As an example, I saw this in the logs:
```
DEBUG	horizontalrunnerautoscaler	Suggested desired replicas of 1 by PercentageRunnersBusy	{"replicas_desired_before": 1, "replicas_desired": 1, "num_runners": 1, "num_runners_registered": 1, "num_runners_busy": 1, "num_terminating_busy": 0, "namespace": "gha", "kind": "runnerdeployment", "name": "runner-deployment-nonprod", "horizontal_runner_autoscaler": "runner-autoscaler-nonprod", "enterprise": "", "organization": "sonatype", "repository": ""}
```
Which doesn't really make sense to me since if `num_runners_busy` is 1 then shouldn't the `runners_desired` be increased to 2 at this point? Or perhaps I'm misunderstanding the metrics.

Thanks in advance!
