### DISCUSSION TITLE
Checkout repos from runner without action token auth

### DISCUSSION THREAD

**Discussion by bhartm3** [actions/actions-runner-controller#2573] [Questions]
Hello I'm trying to check out a repo "my-custom-action" on GHE on a runner in a runner group with the checkout action. The workflow runs in a different "workflow-repo" where I want to use this action. 

```
44: Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  remote: Repository not found.
  Error: fatal: repository 'https://<redacted>/<redacted>/my-custom-action/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 18 seconds before trying again
```

The runner group has permission to access these two repositories. Can this still be a permission issue since the workflow is started in another repo?

Note, I'm not giving any additional auth to the checkout:
```
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: <redacted>/my-custom-action
```
