### DISCUSSION TITLE
Set Resources for `dind` container in Runner Pod

### DISCUSSION THREAD

**Discussion by funkswing** [actions/actions-runner-controller#2602] [Questions]
How do you set the `resources` for the `dind` container running in the Runner Pod? We have seen issues where the `dind` container is consuming a lot of resources unbounded.

Currently, we set resources for our `RunnerDeployment` like so:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  ...
spec:
  template:
    spec:
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
```

The resulting Runner Pod `containers` look like this:

```
apiVersion: v1
kind: Pod
metadata:
  ...
spec:
  containers:
    - name: runner
       resources:
         limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
    - name: docker
       resources: {}
  initContainers:
    - name: init-docker-hub-auth
       resource: {}
```

![actions-runner-deployment-resources](https://github.com/actions/actions-runner-controller/assets/3672489/98ff40de-0819-4373-a55d-ff2b30de7e12)
