### DISCUSSION TITLE
setup-python action fails with with SSL/TLS error

### DISCUSSION THREAD

**Discussion by nefaye** [actions/actions-runner-controller#2604] [Questions]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.4

### CertManager Version

1.8.2

### Deployment Method

Other

### cert-manager installation

Followed the installation steps in the documentation, using `kubectl`.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: runnerdeploy-fink
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeploy-finktest
  namespace: runnerdeploy-fink
spec:
  replicas: 2
  template:
    spec:
      repository: efayen/fink-broker
      #image: summerwind/actions-runner:ubuntu-22.04
```

### To Reproduce

Run the following workflow

```markdown
name: PEP8

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
```

### Describe the bug

Workflow fails at "Set up Python" step, no matter Python version.

```
 Error: WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
```

### Describe the expected behavior

Setup Python succeeds

### Whole Controller Logs

```shell
https://gist.github.com/efayen/f9f62d6e84a39a524096268d64d75162
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/efayen/dbc56e1abb418ff81514995e01442ca2
```

### Additional Context

ARC is installed in a Minikube cluster.

Switching to ubuntu-22.04 image for the runners didn't help.

Similar issue is raised in https://github.com/actions/setup-python/issues/93. Some solutions are proposed, but they never resulted in a patch of the action apparently. Maybe they could be implemented in the runner image used by ARC to make setup-python work.
