### DISCUSSION TITLE
Runner with docker - allow more docker daemon options

### DISCUSSION THREAD

**Discussion by twildber** [actions/actions-runner-controller#2626] [Ideas]
Hi all, I'm using the actions-runner-dind-rootless and want to share an idea for the docker runners.

### Background
The current implementation allows to specify MTU, Default-Address-Pools and registry mirrors to be defined for the start of the daemon.
The entrypoint-dind (-rootless) creates an empty daemon.json file and adds the above options to it if defined.

In my current situation I need to add the IP address of the DNS nameserver to the `daemon.json` in order to resolve the corporate proxy I have to use. During docker build or run I noticed that the resolution of my corporate proxy domain wasn't possible. This might be due to the usage of docker rootless. The nameserver is correctly defined in the runner pod but docker does not use it.

My solution was to define a `ConfigMap ` with the content of the `daemon.json` and mount it to the defined location in the entrypoint: `home/runner/bin/dockerd-rootless.sh --config-file /home/runner/.config/docker/daemon.json`

That worked, but this changed the permission of the .config directory to root. With the permission change of the .config directory it wasn't writable anymore and some of my actions didn't worked (helm writes it's config to .config per default).

#### The custom solution
RunnerDeployment
```
spec:
  template:
    spec:
      volumeMounts:
        - mountPath: /home/runner/.config/docker
          name: {{ template "runner.name" . }}-config-vol
          readOnly: true
      volumes:
        - name: {{ template "runner.name" . }}-config-vol
          configMap:
            name: {{ template "runner.name" . }}-config
            items:
              - key: daemon.json
                path: daemon.json
      securityContext:
        fsGroup: 1001
```

ConfigMap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "runner.name" . }}-config
data:
  daemon.json: |
    {
      "dns": ["x.x.x.x"]
    }
```

### Idea
I would like to have a similar solution to define the daemon options that are wanted / needed.
In addition it would be good to change the location of the daemon.json or create the directory structure in advance to not have permission issues.

Allowing more options would also solve a question like https://github.com/actions/actions-runner-controller/discussions/2318

Thanks!
