### DISCUSSION TITLE
Can PodDisruptionBudget be used with RunnerDeployment

### DISCUSSION THREAD

**Discussion by jdechicchis** [actions/actions-runner-controller#2627] [Questions]
I'm curious if PodDisruptionBudget can be used with RunnerDeployment. Looking at [this thread](https://github.com/actions/actions-runner-controller/issues/1581#issuecomment-1181618360) it looks like some others have configured a PodDisruptionBudget for their RunnerDeployment. However, when I try to do so I get an error:
```
Warning  CalculateExpectedPodCountFailed  17m (x22 over 20h)  controllermanager  Failed to calculate the number of expected pods: runners.actions.summerwind.dev does not implement the scale subresource 
```

I would expect to see this error given that PodDisruptionBudget [may be matching pods that are not replicated](https://github.com/kubernetes/kubernetes/issues/78427#issuecomment-499052581) (not belonging to StstfulSet, ReplicSet etc). I want to confirm that PodDisruptionBudget not working for RunnerDeployment is expected.

My configs for reference:
RunnerDeployment
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: drydock-runner-deployment
  namespace: github-runners
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      image: OMITTED (custom image that uses summerwind/actions-runner:v2.303.0-ubuntu-22.04-3417c5a as it's base)
      imagePullPolicy: Always
      repository: OMITTED
      env: []
      labels:
      - self-hosted
      ephemeral: true
      resources:
        limits:
          cpu: "1"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "4Gi"
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: github-runners

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - github-runners
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: drydock-runner-autoscaler
  namespace: github-runners
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: drydock-runner-deployment
  minReplicas: 1
  maxReplicas: 10
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    amount: 1
    duration: "5m"
```

PodDisruptionBudget
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: github-runner-disruption-policy
  namespace: github-runners
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      runner-deployment-name: drydock-runner-deployment
```
