### DISCUSSION TITLE
Ruby Install

### DISCUSSION THREAD

**Discussion by AzarOPS** [actions/actions-runner-controller#2636] [Questions]
Hi, How do we install Ruby with a particular version ? 

I tried rvm and rbenv. Can you please give some suggestion !

**Comment by altivi** [comment]
Hello @AzarOPS!
Everything you need is to add the `.ruby-version` file to the root of your repository folder specifying your desired Ruby version like that:
```
3.2.2
```

Or if for some reason it doesn't work for you, you could set up your `ci.yml` in the following way - https://docs.github.com/en/github-ae@latest/actions/automating-builds-and-tests/building-and-testing-ruby#specifying-the-ruby-version

P.S. Please mark as the answer if it's helpful :)

**Reply by AzarOPS** [reply]
Hi @Altivi Thank you for the response. I tried the suggestion which you had provided it in the workflow file. Yet I get the same error. PFA.


The version i am trying to install is '3.1.2'
<img width="1311" alt="Screenshot 2023-06-15 at 5 43 20 PM" src="https://github.com/actions/actions-runner-controller/assets/115992262/2478d815-0027-49fe-bab9-fc9e2044ef89">

**Reply by altivi** [reply]
@AzarOPS it looks like the runner image you're using isn't GitHub-hosted, I would suggest using `runs-on: ubuntu-20.04` setting instead.
Also if it doesn't work, please share your full GitHub actions settings`.yml` in text format so that I could provide more help.

**Reply by altivi** [reply]
Btw, here is the example of the set up which works:
```
name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: myapp
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bin/rspec
```
