### DISCUSSION TITLE
RUNNER_LABELS not being passed to current runner

### DISCUSSION THREAD

**Discussion by isantospardo** [actions/actions-runner-controller#2710] [Questions] [answered]
v0.23.3

I am currently deploying the `actions-runner-controller` via helm, and trying to set up the `RUNNER_LABELS` env in the controller, when setting this up, I see the following in the controller deployment pod:

```
spec:
  containers:
    - args:
        ......
      command:
        - /manager
      env:
          ....
        - name: RUNNER_LABELS
          value: 'self-hosted,dev'
```

But, in the `github-action-runner` I see the env var is not set as it should:

```
spec:
  containers:
    - env:
        ......
        - name: RUNNER_LABELS
        - name: RUNNER_GROUP
        ......
```

I am setting this up in helm with:
```
  source:
    chart: actions-runner-controller
    repoURL: 'https://actions-runner-controller.github.io/actions-runner-controller'
    targetRevision: 0.23.3
    helm:
      values: |-
        env:
          - name: RUNNER_LABELS
            value: self-hosted,dev
         ........
```
And of course, I dont see the label in the github runner `dev`
![image](https://github.com/actions/actions-runner-controller/assets/23554395/3a26c80a-6fd8-4ead-9190-0fba979369f5)

and I would like to see something like:
![image](https://github.com/actions/actions-runner-controller/assets/23554395/7bbd02ba-7df8-4a98-bf1a-4affb72d4d25)

Am I doing anything wrong? or is this an actual bug?
