### DISCUSSION TITLE
Using Secrets with RunnerDeployment

### DISCUSSION THREAD

**Discussion by brconnell4** [actions/actions-runner-controller#2735] [Questions]
I was reviewing https://github.com/actions/actions-runner-controller/issues/245 and the suggestions made there, but I cannot seem to get this working with my runner deployment. 

I have the following runnerdeployment configuration setup in my cluster with a webhook server and controller. All components are working except my workflow is unable to use the variables from the secrets file. 

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: ****
      envFrom:
        - secretRef:
            name: actions-runner-secrets

---

apiVersion: v1
kind: Secret
metadata:
  name: actions-runner-secrets
  namespace: actions-runner-system
data:
  TEST_SECRET: "dGVzdHZhbA=="
```

Looking at the runner, it does grab the env variables, it just doesn't appear to make them available to the workflow running in the runner and I feel like I am missing something

```
│     Environment Variables from:                                                                                                                                                                                                                                           │
│       actions-runner-secrets  Secret  Optional: false
```

Here is my workflow as well

```
name: PR Testing
on:
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  PR-Test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo secret
        run: echo ${{ env.TEST_SECRET }}
        
```


To add, I also exec into the runner pod and the env var is there,

```
runner@actions-runner-2wdzl-4ptjk:/$ echo $TEST_SECRET
testval
```
I just cannot seem to use it in my workflow and I am unsure what step I am missing.
