### DISCUSSION TITLE
How do I keep a minimum idle number of workers to make jobs queue fast?

### DISCUSSION THREAD

**Discussion by cep21** [actions/actions-runner-controller#2793] [General]
My jobs are slow often waiting for the pod to fully spin up and accept the work.  How do I keep a minimum number of idle workers inside my cluster so that runner jobs are instantly available, while also auto scaling up to meet increased demand?

I currently  have:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
spec:
  maxReplicas: 200
  minReplicas: 1
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleUpTriggers:
  - duration: 30m
    githubEvent:
      workflowJob: {}
```

I like scaling up on webhooks, but want to maintain a minimum number of idle workers ready for work at the same time
