### DISCUSSION TITLE
imagePullSecrets with gha-runner-scale-set

### DISCUSSION THREAD

**Discussion by brconnell4** [actions/actions-runner-controller#2818] [Questions]
I see that the gha-runner-scale-set-controller supports `imagePullSecrets`  and I have this working properly, even though it isn't where I need it. 

I just migrated from the old Runner Sets to move away to add no-default-labels and for the autoscaling functionality without the webhook configuration. 

I have some variables or secrets that I want to make available to my pipeline outside of using or managing those values in my Org Secrets. 

Is there anyway to get this functionality back or implement it to make secrets available to the runners?

Thanks in advance!

**Comment by brconnell4** [comment]
I digress, if anyone has the issue, the values are available just not in values and work properly.

```
    template:
        spec:
            containers:
                - name: runner
                  image: my-image
                  imagePullPolicy: IfNotPresent
                  command:
                    - /home/runner/run.sh
                  envFrom:
                    - secretRef:
                        name: actions-runner-secrets
            imagePullSecrets:
              - name: actions-runner-secrets
```
