### DISCUSSION TITLE
How to pick the 22.04 ubuntu image in ARC?

### DISCUSSION THREAD

**Discussion by mrdeshapiro** [actions/actions-runner-controller#2827] [Questions]
Morning,

I have a simple yaml file and was wondering how to tell it to use the 22.04 ubuntu image.  I see it is using dind right now.  The yaml I was using to spin up the runners as it stand now:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ghrunner
  namespace: actions-runner-system
  annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  replicas: 1
  template:
    spec:
      group: "self-hosted-k8s"
      labels: 
        - AKS
        - Linux
      organization: my-test-org
      env:
        - name: GITHUB_ACTIONS_RUNNER_TLS_NO_VERIFY # temp
          value: '0' # temp 0|1
        - name: GIT_SSL_NO_VERIFY # temp
          value: 'false' # temp true|false

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ghrunner-runner-autoscalar
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    kind: RunnerDeployment
    name: ghrunner

  scaleDownDelaySecondsAfterScaleOut: 300  

  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkFlowRuns  
```

**Comment by mrdeshapiro** [comment]
An added bonus to info on how to add some packages to whatever docker image it uses since developers would like a few basic things installed so they do not have to do so in their workflows (e.g., specific versions of npm, php, java, etc).

**Reply by uday1kiran** [reply]
No reply from anyone so far, Have you got any solution for the same?

**Comment by tadayoni1** [comment]
You may pick a specific tag for your `image`.
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ghrunner
  namespace: actions-runner-system
  annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  replicas: 1
  template:
    spec:
      image: summerwind/actions-runner:v2.321.0-ubuntu-22.04-8b36ea9
      group: "self-hosted-k8s"
      labels: 
        - AKS
        - Linux
      organization: my-test-org
      env:
        - name: GITHUB_ACTIONS_RUNNER_TLS_NO_VERIFY # temp
          value: '0' # temp 0|1
        - name: GIT_SSL_NO_VERIFY # temp
          value: 'false' # temp true|false

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ghrunner-runner-autoscalar
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    kind: RunnerDeployment
    name: ghrunner

  scaleDownDelaySecondsAfterScaleOut: 300  

  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkFlowRuns 
```
You may find available tags at https://hub.docker.com/r/summerwind/actions-runner/tags. The default image if not specified is `summerwind/actions-runner:latest`
