### DISCUSSION TITLE
gha-runner-scale-set-controller imagePullSecrets w/ custom actions-runners on github.com enterprise work?

### DISCUSSION THREAD

**Discussion by ira-fox-by** [actions/actions-runner-controller#2835] [Questions] [answered]
Folks,

I was wondering if any has gotten the newer GH Actions runner Scale-Set-Controller to pull custom actions-runner from a private container registry (in this case ghcr.io/MyOrg/actions-runner:v2.0 ?

gha-runner-scale-set-controller - v.0.5.0

I've read thru all the newer documentation on Github  Scale Sets:
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#configuring-the-controller-image
However.. I'm still getting infamous "Failed to pull image 401 Unauthorized"  which tells me the imagePullSecrets is not working or I have it setup wrong (following the standard method documented on [K8S site](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line)

My config for the Scale-Set controller looks like this:
```yaml
githubConfigUrl: "https://github.com/MyOrg"
githubConfigSecret: "gha-myorg-secret"
runnerGroup: "infra-runner-grp"
maxRunners: 6
minRunners: 1
imagePullSecrets:
       - name: "arc-regcred"
containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "longhorn"
    resources:
      requests:
        storage: 1Gi
template:
    spec:
      containers:
      - name: runner
        #image: ghcr.io/actions/actions-runner:latest
        image: ghcr.io/myorg/actions-runner:v2.0
        imagePullPolicy: IfNotPresent
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
controllerServiceAccount:
   namespace: arc-systems
   name: arc-serviceaccount
```

 It works perfectly fine if i use image: ghcr.io/actions/actions-runner:latest however there is some additional software and a private CA I add (/usr/local/share/ca-certificates)  I'd like to add so we don't have wait during deployment.

Any suggestion would be most appreciated...

Kind regards,
 - IF
