### DISCUSSION TITLE
ARC always schedules containers on a single node

### DISCUSSION THREAD

**Discussion by nmortezaei** [actions/actions-runner-controller#2848] [Questions]
Hi,
I am trying to achieve auto scaling using following configurations but all containers are always being created on a single node of our kubernetes cluster and rest of the nodes are idle with no containers related to github actions runners. 
kubernetes cluster itself is healthy and is working fine and when you run a simple deployment, all replicas are being properly distributed in all nodes with no problem.
i appreciate if someone can help.

runner and autoscaler configs are as follows:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-test
  namespace: actions
spec:
  template:
    spec:
      repository: a-test-repo
      labels:
        - linux

```
and

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: k8s-autoscaler-test
  namespace: actions
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: k8s-test
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 1
  maxReplicas: 70
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - a-test-repo
```
