### DISCUSSION TITLE
How to change docker:dind image or customize dind container with commands included using helm charts?

### DISCUSSION THREAD

**Discussion by ram1ex** [actions/actions-runner-controller#2867] [Questions] [answered]
Installing gha-runner-scale-set using this way:

`helm upgrade --install "${INSTALLATION_NAME}" --namespace "${NAMESPACE_RUNNER}" --create-namespace --set githubConfigUrl="${GITHUB_CONFIG_URL}" --set githubConfigSecret.github_token="${GH_PAT}" --values values.yaml oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set`

in `values.yaml` i'd specify my custom image with specific docker setup ( mostly needs to customize daemon.json and private registry) like this:

```
containerMode:
  type: "dind"
template:
  spec:
    containers:
     - name: dind
      image: my_own_image_from_docker_hub
```

Also it's not possible to put `command` in values like this:

```
containerMode:
  type: "dind"
template:
  spec:
    containers:
    - name: dind
      image: docker:dind
      command: [ "/bin/sh", "-c", "mkdir -p /etc/docker ; touch /etc/docker/daemon.json"]
```
(btw it works for 'runner' container)
