### DISCUSSION TITLE
Unable to update image tag of action runner deployment with HorizontalRunnerAutoscaler

### DISCUSSION THREAD

**Discussion by prasad-1210** [actions/actions-runner-controller#2906] [Questions]
we are trying to run action runner deployments on the Kubernetes cluster and orchestrate them using HorizontalRunnerAutoscaler. when we apply values yaml it triggers new pods but uses an old tag. 

here are relevant snips of yaml 

runner.yaml

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: myorg-runner-deployment
spec:
  template:
    spec:
      ephemeral: true
      containers:
      - name: runner
        securityContext:
          privileged: true
      # image: CUSTOME IMAGE HERE
      imagePullPolicy: IfNotPresent
      organization: myorg
      group: Nonprod-runners
      labels:
        - K8S-NONPROD
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: myorg-runner-deployment-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: myorg-runner-deployment
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  minReplicas: 5
  maxReplicas: 10
  metrics:
  - type: PercentageRunnersBusy
     scaleUpThreshold: '0.75'   
     scaleDownThreshold: '0.3'down
     scaleUpFactor: '1.4'        
     scaleDownFactor: '0.7'  
```

values.yml

```
image:
  repository: ""
  actionsRunnerRepositoryAndTag: "us.gcr.io/gcp-myorg-img-prod-prj-02/esgh/myorg/actions-runner:customRunner-2219"
  actionsRunnerControllerRepositoryAndTag: "us.gcr.io/gcp-myorg-img-prod-prj-02/esgh/actions-runner-controller:latest"
```

deploy runner 
```
 kubectl apply -f runner.yaml
```
update actionsRunnerRepositoryAndTag to tag 224 then run the above apply command. but, new runner-deployment pods startƒ with the old tag 219 but not 224.

please advise, if I'm missing something here
