### DISCUSSION TITLE
Issue when sharing local docker images with kind cluster and ARC

### DISCUSSION THREAD

**Discussion by jorgepiloto** [actions/actions-runner-controller#2924] [Questions]
Issue when sharing local docker images with kind cluster and ARC

**Background**

I recently discovered this project and it is amazing. So far, I have been
exploring it using the following technologies:

- docker: https://www.docker.com/ 
- kubectl: https://kubernetes.io/docs/tasks/tools/
- kind (k8s): https://kind.sigs.k8s.io/
- helm: https://helm.sh/

Here are the commands I use for creating the cluster and ARC. Note that I have a
local docker image named `ansys/product:latest` that I want to share with the
cluster.

```console
# Declare the inputs
deployment_file=$1

# Create the cluster
kind create cluster

# Load the desired docker images !!
kind load docker-image ansys/product:1.0

# Install cert-manager to digest webhooks
helm repo add jetstack https://charts.jetstack.io
helm repo update

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml

helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.11.0

# Deploy the PAT as a secret to the cluster
kubectl create namespace actions-runner-system
kubectl create secret generic controller-manager \
    -n actions-runner-system \
    --from-literal=github_token=${GITHUB_TOKEN}

# Install the actions runner controller (ARC)
helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
helm upgrade --install --namespace actions-runner-system --create-namespace \
             --wait actions-runner-controller actions-runner-controller/actions-runner-controller

# Apply the runner and the ARC configuration
kubectl apply -f ${deployment_file}

# Show all the pods in the command line
kubectl get pods -w
```

where in previous code, the `deployment_file` variable points to a YML file with
the following content:

```yml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: scalable-runner
spec:
  template:
    spec:
      repository: jorgepiloto/scalable-runners
      containers:
        - name: ansys-product
          image: ansys/product:1.0
          imagePullPolicy: Never
      labels:
        - scalable-runners
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: scalable-runner-autoscaler
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: scalable-runner
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - jorgepiloto/scalable-runners
```

**Problem**

The cluster deploys, connects and scales as expected with GitHub. However, it is
not able to find the local docker image when trying to create a service with it.

Uploading the image to Docker Hub or the GitHub container registry works fine.
However, I am really interested in using local docker images.
