### DISCUSSION TITLE
What are the default resource limits for runners?

### DISCUSSION THREAD

**Discussion by zxti** [actions/actions-runner-controller#2946] [FAQs] [answered]
Simple basic question - what are the default memory and cpu resources (requested and limits) for new runner pods?

**Comment by ealasgarov** [comment, marked as answer]
if they are not specified specifically, then this will be defined by the namespace limits range, but you can specify resources block at the bottom of values.yaml file in gha-runner-scale-set helm deployment, e.g.:

```
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        resources:
            limits:
              cpu: "2000m"
              memory: "8Gi"
            requests:
              cpu: "500m"
              memory: "4Gi"
    tolerations:
    - effect: NoSchedule
      key: kubernetes.azure.com/scalesetpriority
      operator: Equal
      value: spot
    - effect: NoSchedule
      key: os_type
      operator: Equal
      value: linux 

```
