### DISCUSSION TITLE
Runners: how to add annotations to runners and specify resources

### DISCUSSION THREAD

**Discussion by cweiblen** [actions/actions-runner-controller#2958] [Questions]
I want to add annotation `karpenter.sh/do-not-evict: "true"` to my runners, so Karpenter doesn't evict them and kill running jobs, but when I add it to template spec, it doesn't seem to have any effect.  Same with resources.  Is it possible?

```
template:
  ## template.spec will be modified if you change the container mode
  ## with containerMode.type=dind, we will populate the template.spec with following pod spec
  ## template:
  spec:
    metadata:
      annotations:
        karpenter.sh/do-not-evict: "true" 
    resources:
      limits:
        cpu: "4.0"
        memory: "8Gi"
      requests:
        cpu: "2.0"
        memory: "8Gi"
...
```

**Comment by mattpopa** [comment]
are you adding them under `RunnerDeployment` kind?

works for me (using cluster-autoscaler instead of karpenter, but should be similar)

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted-large
  namespace: actions-runner-system
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:

      [other stuff]

      containers:
      - name: runner
        resources:
          requests:
            memory: "10Gi"
            cpu: "3000m"
          limits:
            memory: "10Gi"
            cpu: "3000m"
      labels:
        - large
```
