### DISCUSSION TITLE
ARC not scaling up and respecting the conditions of HRA

### DISCUSSION THREAD

**Discussion by whibbard-genies** [actions/actions-runner-controller#2969] [Questions] [answered]
Problem:

I have an EKS cluster where I have an ARC deployed, and it generally is working.  A couple runnerdeployments are managed under it, and jobs get assigned to the pods without issue.
However, the HRA seems to be completely ineffective.  Every example I can find in the documentation seems to mirror mine almost exactly.  The logs only make it more confusing.
This is the runner deployment and HRA:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: internal-content-runner
  namespace: actions-runner-system
  labels:
    app: internal-content-runner
    env: infra
spec:
  template:
    spec:
      organization: myorg
      labels:
        - internal-content-runner
      nodeSelector:
        Name: runners_content
      group: content-runners
      image: summerwind/actions-runner-dind:ubuntu-20.04
      dockerdWithinRunnerContainer: true
      ephemeral: true
      resources:
        limits:
          memory: "16Gi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-content-autoscaler
  namespace: actions-runner-system
  labels:
    app: internal-content-runner
    env: infra
spec:
  scaleDownDelaySecondsAfterScaleOut: 600
  scaleTargetRef:
    kind: RunnerDeployment
    name: internal-content-runner
  minReplicas: 5
  maxReplicas: 30
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.75"
      scaleDownThreshold: "0.25"
      scaleUpFactor: "1"
      scaleDownFactor: "1"
```

The logs of the ARC are showing that the maximum is seen and all the runners are in fact busy, but it's not scaling up and instead just continuing to just set the desired replicas to the same number it has been.

> 2023-10-08T20:21:40Z    DEBUG    actions-runner-controller.horizontalrunnerautoscaler    Suggested desired replicas of 5 by PercentageRunnersBusy    {"replicas_desired_before": 5, "replicas_desired": 5, "num_runners": 5, "num_runners_registered": 5, "num_runners_busy": 5, "num_terminating_busy": 0, "namespace": "actions-runner-system", "kind": "runnerdeployment", "name": "internal-content-runner", "horizontal_runner_autoscaler": "runner-content-autoscaler", "enterprise": "", "organization": "myorg", "repository": ""}
2023-10-08T20:21:40Z    DEBUG    actions-runner-controller.horizontalrunnerautoscaler    Calculated desired replicas of 5    {"horizontalrunnerautoscaler": "actions-runner-system/runner-content-autoscaler", "suggested": 5, "reserved": 0, "min": 5, "max": 30}

Actions runner controller image: summerwind/actions-runner-controller:v0.26.0

What am I missing here?
