### DISCUSSION TITLE
ARC on an Azure AKS cluster scales up when my runner's node pool has 1 or more nodes, but not when it has 0 nodes

### DISCUSSION THREAD

**Discussion by JohnLBergqvist** [actions/actions-runner-controller#2975] [Questions]
I've deployed ARC on an Azure Kubernetes Cluster using Runner Scale Sets as described here: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller. My template for the scale set is configured to use only nodes whih have an `os` taint of `ubuntu`, which is the case for my node pool I'm autoscaling on:
```
template:
  spec:
    tolerations:
      - key: os
        operator: Equal
        value: ubuntu
        effect: NoSchedule
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.azure.com/mode: user
```

I have a node pool for my runners configured with a Min of 1 node and Max of (e.g.) 20.
If there is at least 1 node on the node pool, and I schedule more than 1 node's worth of jobs, the nodes autoscale up & down as expected. 

However if I set my node pool's auto-scale minumum size (in AKS) to 0 and the node pool eventually autoscales down to 0, it doesn't then auto scale up again with new jobs until I manually ensure thhere's at least 1 node on the pool. What happens is the jobs are sitting in a pending state waiting for nodes to spin up, which they never do.

Can anyone help?
