### DISCUSSION TITLE
How do I specify custom Volume Mounts using gha-runner-scale-set?

### DISCUSSION THREAD

**Discussion by JohnLBergqvist** [actions/actions-runner-controller#2998] [Questions]
I've been trying to follow [this guide](https://github.com/actions/actions-runner-controller/blob/master/docs/using-custom-volumes.md) to setup a custom Volumne Mount using gha-runner-scale-set. 

The below template worked fine before I added the custom volumeMount stuff, but now i've added them, the containers don't even attempt to spin up and the listener or controller logs aren't telling me anything - this is what i've got so far - do I need to specify DockerVolumeMounts at all?

```
template:
  spec:
    initContainers:
      - name: init-dind-externals
        image: myci.azurecr.io/ubuntu-runner:2023-10-17
        command: ["cp","-r","-v","/runner/externals/.","/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /runner/tmpDir
    containers:
      - name: runner
        image: myci.azurecr.io/ubuntu-runner:2023-10-17
        command: ["/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///run/docker/docker.sock
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: work
            mountPath: /runner/_work
            subPathExpr: $(POD_NAME)-work
          - name: dind-sock
            mountPath: /run/docker
            readOnly: true
          - mountPath: /tmp
            name: tmp
            subPathExpr: $(POD_NAME)-tmp
        resources:
          requests:
            memory: 12Gi
            cpu: 6
      - name: dind
        image: docker:dind:latest
        args:
          - dockerd
          - --host=unix:///run/docker/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "999"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /runner/_work
            subPathExpr: $(POD_NAME)-work
          - name: dind-sock
            mountPath: /run/docker
          - name: dind-externals
            mountPath: /runner/externals
          - mountPath: /tmp
            name: tmp
            subPathExpr: $(POD_NAME)-tmp
    volumes:
      - name: work
        hostPath:
          path: /mnt/work
          type: DirectoryOrCreate
      - name: tmp
        hostPath:
          path: /mnt/tmp
          type: DirectoryOrCreate
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
```
What I had before (which worked with docker-in-docker) was:
```
template:
  spec:
    initContainers:
      - name: init-dind-externals
        image: myci.azurecr.io/ubuntu-runner:2023-10-17
        command: ["cp","-r","-v","/runner/externals/.","/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /runner/tmpDir
    containers:
      - name: runner
        image: myci.azurecr.io/ubuntu-runner:2023-10-17
        command: ["/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///run/docker/docker.sock
        volumeMounts:
          - name: work
            mountPath: /runner/_work
          - name: dind-sock
            mountPath: /run/docker
            readOnly: true
        resources:
          requests:
            memory: 12Gi
            cpu: 6
      - name: dind
        image: docker:dind:latest
        args:
          - dockerd
          - --host=unix:///run/docker/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "999"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /runner/_work
          - name: dind-sock
            mountPath: /run/docker
          - name: dind-externals
            mountPath: /runner/externals
    volumes:
      - name: work
        emptyDir: {}
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
```

Each node has a `/mnt` mountpoint, which is where i'd like to store each pod's `_work` directory and the `/tmp` folder, prefixed with the POD_NAME as in the above example.

My cluster is hosted with AKS on Azure.
