### DISCUSSION TITLE
Runner State Sets Service Accounts and Labels

### DISCUSSION THREAD

**Discussion by joshua-reddish** [actions/actions-runner-controller#3023] [Questions] [answered]
Is there currently anyway to provide a `spec.template.spec.serviceAccountName` and `spec.template.metadata.labels` the same way we are able to in the legacy RunnerDeployments?

We use these two features to assign our runners to Fargate profiles, and provide necessary permissions to the pods via RBAC

I am really excited about the new Runner State Sets, but these are blockers in my testing at the moment. If there isnt a way, what is the best way to make a feature request?

Example from legacy i am trying to replicate.
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ***
  namespace: ***
spec:
  template:
    metadata:
      labels:
        label: common-fargate
        eks.amazonaws.com/fargate-profile: "gh-runners-rss"
    spec:
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      organization: ***
      serviceAccountName: ***
      labels:
        - ***
      image: ***
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 2Gi
```

Thanks!

**Comment by joshua-reddish** [comment]
@Link- I watched your youtube video for setup and read through all the docs on this. Any assistance pointing me in the right direction would be appreciated!

**Comment by joshua-reddish** [comment, marked as answer]
Okay so I did figure out how to add the labels. If anyone else is wondering:

```yaml
template:
  metadata:
    labels:
      label: common-fargate
      eks.amazonaws.com/fargate-profile: "gh-runners-rss"
  spec:
    containers:
      - name: runner
        image: ***
        command: ["/home/runner/run.sh"]
 ```

Looks like since im using dind it wont work with fargate since fargate doesnt allow privileged. Looking into that next!
