### DISCUSSION TITLE
Windows: SO CLOSE (I think!)

### DISCUSSION THREAD

**Discussion by ghost** [actions/actions-runner-controller#3037] [Questions]
Hey all!  

I've been through miles of forum posts as well as the official instructions for windows runners in the ARC docs, enabling Windows in my existing linux cluster.. and feel I am super close to getting a runner up.  Only place I'm stuck now is that when the windows runner comes up, I get this in the logs, then it dies..
```
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

No such host is known. (api.github.com:443)
```

kubernetes version: 1.23
runner deployment: 
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-repo-action-runner-deploy-win
  namespace: actions-runners
spec:
  template:
    spec:
      image: public.ecr.aws/e7b3d8i9/windows-2019-arc-runner:latest
      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.io/arch: amd64
      dockerEnabled: false
      tolerations:
        - key: "os"
          operator: "Equal"
          value: "windows"
          effect: "NoSchedule"
      labels:
        - windows
        - X64
      repository: my/my-repo
      resources:
        limits:
          cpu: "8.0"
          memory: "16Gi"
        requests:
          cpu: "8.0"
          memory: "16Gi"
```

note: 
- this runnerdeploy is a bit different than the one specified in the official docs [here](https://github.com/actions/actions-runner-controller/blob/master/docs/configuring-windows-runners.md) - but when I use the one in the official docs, I get the error "windows cannot run in privileged mode"  - i've added the taint to the pod to further try to ensure that a windows pod doesn't try to get scheduled on a linux node (per another windows issue I found in the issues list) - added the appropriate toleration to the karpenter node provisioner also.  
- the docker image i'm referencing was built from the exact dockerfile in the [offical docs](https://github.com/actions/actions-runner-controller/blob/master/docs/configuring-windows-runners.md)
- I followed the "enabling windows" instructions [here](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html)
- my arc version (installed via helm chart) 

```
NAME                            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
actions-runner-controller       actions-runner-system   3               2023-10-20 15:52:31.530551 -0400 EDT    deployed        actions-runner-controller-0.23.5        0.27.5  
```

In short, I've _finally_ got it scheduling (got through the "no Privateipv4address" issue as well), and now it just seems like the docker container can't access the host's internet... maybe?  I mean, the image was pulled.. so the node must have connectivity...? 

If I can provde any additional info, please let me know!  Thank you in advance!  Been working on this on and off for 2 weeks :(

**Comment by adiroiban** [comment]
Thanks for sharing the progress.

Maybe I might be asking a stupid question.

Is your Windows k8s worker node working? Does it have internet access?

Have you tried deploying a single pod, based on `mcr.microsoft.com/windows/servercore:ltsc2019` and then attach to the pod and see if you have internet access there?

Regards

**Reply by ghost** [reply]
Yep you're right. I ran a pod with this based on that image
```
          image: mcr.microsoft.com/windows/servercore:ltsc2019-amd64
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
          command:
            - powershell.exe
            - -command
            - "ping 8.8.8.8"
```

.. and nope! `request timed out`.  Now to see why.... :/ 

the nodegroup was configured by eksctl and my linux nodes in the same cluster are fine, fwiw... will investigate!
