### DISCUSSION TITLE
Ephemeral storage

### DISCUSSION THREAD

**Discussion by Edarjak** [actions/actions-runner-controller#3066] [Questions]
Hi community,

I have a K3S cluster with ARC controller running. Here is my RunnerDeployment:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-actions-runners-micro
  namespace: github-actions-runners-micro
spec:
  replicas: 6
  template:
    spec:
      organization: myorg
      labels:
        - x-micro
        - micro
      group: Default
      resources:
        limits:
          cpu: "0.25"
          memory: "0.5Gi"
          ephemeral-storage: "20Gi"
        requests:
          cpu: "0.125"
          memory: "0.5Gi"
          ephemeral-storage: "20Gi"
      containers:
        - name: docker
          image: my-docker-images.artifactory.myhost.com/repo/docker:dind
        - name: runner
          image: my-docker-images.artifactory.myhost.com/repo/runners:runner
```

By default, for the ephemeral storage it uses hosts /var and /tmp or /var/tmp dirs (sda). The problem is that there are not enough space on the sda drive, so I have added another disk (sdb) and wondering is it possible to instead of early mentioned dirs make it to use /data on the sdb?

```
NAME                       MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                          8:0    0   70G  0 disk
├─sda1                       8:1    0  200M  0 part /boot/efi
├─sda2                       8:2    0    1G  0 part /boot
└─sda3                       8:3    0 68.8G  0 part
  ├─systemvg-rootlv        253:0    0    2G  0 lvm  /
  ├─systemvg-swaplv        253:1    0    4G  0 lvm
  ├─systemvg-usrlv         253:2    0   10G  0 lvm  /usr
  ├─systemvg-homelv        253:3    0    2G  0 lvm  /home
  ├─systemvg-optlv         253:4    0    5G  0 lvm  /opt
  ├─systemvg-tmplv         253:5    0    5G  0 lvm  /var/tmp
  ├─systemvg-kdumplv       253:6    0    2G  0 lvm  /var/crash
  ├─systemvg-varlogauditlv 253:7    0   10G  0 lvm  /var/log/audit
  ├─systemvg-varloglv      253:8    0    5G  0 lvm  /var/log
  └─systemvg-varlv         253:9    0    5G  0 lvm  /var
sdb                          8:16   0  610G  0 disk
└─datavg-datalv1           253:10   0  610G  0 lvm  /data
```

Thanks in advance,
