### DISCUSSION TITLE
Persistent volumes to workflow pods when using containerMode.type = kubernetes

### DISCUSSION THREAD

**Discussion by adiroiban** [actions/actions-runner-controller#3067] [Questions]
Is there a way to attach persistent volumes to the workflow pod that is created to run the container workflow ?

I would like to add an extra volume for a cache like `/opt/hostedtoolcache`

I guess that my question is related to https://github.com/actions/runner-container-hooks/pull/75 , but I can't find the docs , other than the info from PR https://github.com/actions/runner-container-hooks/pull/96

Note that this is not about the "normal" runner pod. That part is solved via `template.containers`

I am running the helm chart with

```yaml
containerMode:
  type: "kubernetes"
```

I can see that it is created with 2 volume... but I can't find the template for it.

```yaml
spec:
  volumes:
    - name: work
      persistentVolumeClaim:
        claimName: arc-docker-nlc5r-runner-t2bnf-work
    - name: kube-api-access-6wwdf
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: job
      image: ghcr.io/chevah/alpine-chevah:3.16
      command:
        - tail
      args:
        - -f
        - /dev/null
      workingDir: /__w/server/server
      resources: {}
      volumeMounts:
        - name: work
          mountPath: /__w
        - name: work
          mountPath: /__e
          subPath: externals
        - name: work
          mountPath: /github/home
          subPath: _temp/_github_home
        - name: work
          mountPath: /github/workflow
          subPath: _temp/_github_workflow
        - name: kube-api-access-6wwdf
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
```

**Comment by adiroiban** [comment]
I think I found the answer. This is similar to https://github.com/actions/actions-runner-controller/issues/2992

The template from there was not working 100%

Here is what I got

```yaml
#
# This defines how the "container" pod created for workflows that are
# executed inside a container.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-templates
  namespace: arc-runners-docker
data:
  default.yaml: |
    ---
    apiVersion: v1
    kind: PodTemplate
    metadata:
      # metadata.name should not be set as this will cause the
      # workflow container pod to fail.
      labels:
        app: runner-pod-template
    spec:
      containers:
        - name: $job
          volumeMounts:
            - name: hostedtoolcache
              mountPath: /opt/hostedtoolcache
      volumes:
        - name: hostedtoolcache
          hostPath:
            # directory location on host
            path: /var/lib/arc
            type: DirectoryOrCreate

```

and values.yaml

```yaml
template:
  spec:
    containers:
      - name: runner
        image: YOUR-IMAGE
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          # This defines the template used to build the workflow containers
          # Update it via:
          # $ kubectl apply -f infrastructure/k8s/arc-docker-pod-templates.yaml
          - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
            value: /home/runner/pod-templates/default.yaml
        volumeMounts:
          - name: hostedtoolcache
            mountPath: /opt/hostedtoolcache
          - name: pod-templates
            mountPath: /home/runner/pod-templates
            readOnly: true
    volumes:
      - name: hostedtoolcache
        hostPath:
          # directory location on host
          path: /var/lib/arc
          type: DirectoryOrCreate
      - name: pod-templates
        configMap:
          name: pod-templates
```
