### DISCUSSION TITLE
Linux runner scale set hosted on Windows machine can't use `service`/`container` features from GH workflow

### DISCUSSION THREAD

**Discussion by FLuzzi-csw** [actions/actions-runner-controller#3101] [Questions]
Hi,

I've deployed a `runner scale set` with the `dind` feature enabled (pretty much vanilla config, only changed the credentials for GH),
but I'm having some trouble using the `service` and `container` features in a workflow.

## Problematic use case

running this workflow results in the error:
`Error: Container feature is not supported when runner is already running inside container.`

```yml
name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runners
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Try
        run: |
          echo "HELLO" >> $GITHUB_STEP_SUMMARY
          sleep 180
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
```

on the same runner the following workflow runs perfectly:

```yml
name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runners
    steps:
      - name: Spawn redis
        run: docker run --name redis -d -p 6379:6379 redis
      - name: Try
        run: |
          echo "HELLO" >> $GITHUB_STEP_SUMMARY
          sleep 180
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
      - name: Stop redis
        run: docker kill redis
```

## Notes

I'm aware of the issue [#406 on action/runner](https://github.com/actions/runner/issues/406) ([related code](https://github.com/actions/runner/blob/v2.306.0/src/Runner.Worker/ContainerOperationProvider.cs#L529-L535)),
but i've seen it in action in this video https://youtu.be/_F5ocPrv6io?si=m1M-fEpdDO0K1vS_

Can someone help me understand what I'm missing? 😄
