### DISCUSSION TITLE
Prometheus metrics for gha-rs-controller/gha-scale-set not showing.

### DISCUSSION THREAD

**Discussion by namhyuck-kim-otsk** [actions/actions-runner-controller#3111] [Questions] [answered]
Hello everyone.

I've installed ARC (Github Official) and enabled metrics.

The PodMonitor manifest is as follows:

```
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gha-rs-controller
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  podMetricsEndpoints:
  - interval: 30s
    targetPort: 8080
    path: /metrics
  namespaceSelector:
    matchNames:
    - arc-systems
  selector:
    matchLabels:
      app.kubernetes.io/part-of: gha-rs-controller
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gha-runner-scale-set
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  podMetricsEndpoints:
  - interval: 30s
    targetPort: 8080
    path: /metrics
  namespaceSelector:
    matchNames:
    - arc-runners
  selector:
    matchLabels:
      app.kubernetes.io/part-of: gha-runner-scale-set
```

I've also installed `kube-prometheus-stack` on the same cluster and imported the dashboard json from [here](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/samples/grafana-dashboard/ARC-Autoscaling-Runner-Set-Monitoring_1692627561838.json)

The metrics seem to be working but many of the widgets are showing `no data` like the screenshot below.

![image](https://github.com/actions/actions-runner-controller/assets/125936281/16ffc994-d45c-4cbf-b0f3-12e133f48bca)

Is this because the json file is out of date?

Anyone experiencing the same thing?

Thanks in advance.
