### DISCUSSION TITLE
Is it possible to dynamically select instance type

### DISCUSSION THREAD

**Discussion by kaykhan** [actions/actions-runner-controller#3192] [Questions]
Hi friends, Is there some way that i can dynamically set the instance type in the ci/cd github actions config file.

```
   runs-on: self-hosted
```
e.g

```
   runs-on: self-hosted, t2.small
```

what is the best way to get this dynamic behaviour and let the dev decide the size of the node that is required to run their ci/cd job.

Is there also a way to dynamically select the base image?

How far can i get in achieving either of these 2 with this repo

---

It seems like if i want to dynamically select the instance type, i would need to create a new runner deployment for each? Using the nodeSelector, it would be able to provision a node for the ci/cd pod?

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-t3-small
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      organization: <>
      image: <>
      nodeSelector:
        aws/node-type: t3.small
 ```
 
 We have multiple organisations and i want to be able to allow the dev to spinup a new node to use for their ci/cd, allowing them to decide the instance type (and possibly base image). Is this possible?
