### DISCUSSION TITLE
Upgrade to newest release with RUNNER_CONTAINER_HOOKS_VERSION=0.5.0

### DISCUSSION THREAD

**Discussion by cgundy** [actions/actions-runner-controller#3246] [FAQs]
I would like to use the newest features contained in `RUNNER_CONTAINER_HOOKS_VERSION=0.5.0`, specifically the `ACTIONS_RUNNER_USE_KUBE_SCHEDULER=true` feature. I have upgraded to the latest version `0.8.1`, but it does not appear that it is using the latest container hooks version. I was able to deduce this because I am still getting the warning message `Warning: Skipping name override: name can't be overwritten`, which was fixed in the same [PR](https://github.com/actions/runner-container-hooks/pull/111). 

I would like to understand:
1) Am I installing the runner correctly? (Everything works as it should, except that it does not include the latest runner container hook changes)
2) How can I see which RUNNER_CONTAINER_HOOKS version is being used?

Here is my configuration:
```
helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.8.1
    namespace: gh-runner-controller
    releaseName: gha-runner-scale-set-controller
    includeCRDs: true
    valuesInline:
      serviceAccount:
        create: true
        name: gh-runner-controller

  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.8.1
    namespace: gh-runner-sandbox
    releaseName: gha-runner-scale-set
    valuesFile: runner-values.yaml
    includeCRDs: true
```
runner-values.yaml:
```
[redacted]
controllerServiceAccount:
  namespace: gh-runner-controller
  name: gh-runner-controller
containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteMany"]
    storageClassName: "rook-cephfs"
    resources:
      requests:
        storage: 300Gi
template:
  spec:
    securityContext:
      fsGroup: 1001
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:2.312.0
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
            value: /home/runner/pod-templates/bazel-runner.yaml
          - name: ACTIONS_RUNNER_USE_KUBE_SCHEDULER
            value: "true"
          - name: ACTIONS_RUNNER_PREPARE_JOB_TIMEOUT_SECONDS
            value: "300" 
        resources:
          requests:
            memory: 1Gi
        volumeMounts:
          - name: pod-templates
            mountPath: /home/runner/pod-templates
            readOnly: true
    volumes:
      - name: pod-templates
        configMap:
          name: pod-templates
```
Checking my runner pod environment variables, I see that `ACTIONS_RUNNER_USE_KUBE_SCHEDULER: true` but it does not actually schedule the `-workflow` pods on separate nodes. 

Thanks!
