### DISCUSSION TITLE
Running actions in a container job with dind-rootless results in OCI runtime exec failed

### DISCUSSION THREAD

**Discussion by zxiiro** [actions/actions-runner-controller#3258] [Questions]
I'm trying to run ARC runners in dind-rootless mode as described [here](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#example-running-dind-rootless). However if I run a workflow job that uses a container and calls an action such as the actions/checkout action. For example:

```
jobs:
  job:
    name: dind-rootless-with-container-image
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
```

I get an OCI runtime failure:

```
OCI runtime exec failed: exec failed: unable to start container process: exec /__e/node16/bin/node: no such file or directory: unknown
```

This does not seem to happen in dind mode, it only happens when I try with dind-rootless. If I remove the container image declaration and run directly on the runner it also works.

Is this expected? is there a resolution for this?
