### DISCUSSION TITLE
How do I depend on the gha-runner-scale-set-controller chart from another chart?

### DISCUSSION THREAD

**Discussion by alexklibisz** [actions/actions-runner-controller#3263] [Questions] [answered]
I want to write my own helm chart that depends on the new runner-scale-set-controller chart. But I don't know what to provide for the `repository`.

```yaml
apiVersion: v2
name: runner-scale-set-controller
description: Helm chart for deploying a runner scale set controller
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: gha-runner-scale-set-controller
    version: "0.8.2"
    repository: https://what_goes_here.com?
```

I don't see anything about this in the docs. It seems related to another open question https://github.com/actions/actions-runner-controller/discussions/3072.

**Comment by alexklibisz** [comment, marked as answer]
This ended up working:

```yaml
apiVersion: v2
name: runner-scale-set-controller
description: Helm chart for deploying a runner scale set controller
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: gha-runner-scale-set-controller
    version: "0.8.2"
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
```

_AND_ I had to make sure I'm on helm version 3.8.0. OCI support is relatively-newly supported: https://helm.sh/docs/topics/registries/
