### DISCUSSION TITLE
issue with actions-runner-dind:v2.313.0-ubuntu-20.04-a68aa00 image on init containers

### DISCUSSION THREAD

**Discussion by matan-legit** [actions/actions-runner-controller#3285] [Questions]
im trying to use the extended image offered by this repository and for some reason im getting errors in my init container som im definitely configuring something wrong. here is the scale-set values im using:
```
gha-runner-scale-set:
  githubConfigUrl: "https://github.com/matan"

  githubConfigSecret: "arc-secret"

  runnerGroup: "k8s-arc-runners"
  runnerScaleSetName: "ubuntu-dind-16g"

  containerMode:
    type: "dind"

  template:
    spec:
      tolerations:
        - key: karpenter-managed-type
          operator: Equal
          value: arc-scalers
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: karpenter-managed-type
                    operator: In
                    values:
                      - arc-scalers
      containers:
        - name: runner
          image: ghcr.io/actions-runner-controller/actions-runner-controller/actions-runner-dind:v2.313.0-ubuntu-22.04
          command: [ "/home/runner/run.sh" ]
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
            limits:
              memory: "16Gi"
              cpu: "4"

```

if im using the default image it works fine. what am i doing wrong here? should i not configure containermode if im using this image?
