### DISCUSSION TITLE
Unable to set toleration to runner pods

### DISCUSSION THREAD

**Discussion by PaulMoney** [actions/actions-runner-controller#3286] [Questions] [answered]
Hello, currently I'm unable to set toleration field to runner pods (i.e. they are not scheduled on desired node). However, adding it to `listener template` or `gha-runner-scale-set-contoroller` worked correctly and scheduled pods on desired nodes. This is how runner pods template looks like in my `runner-scale-set-values.yml` file: 
```yaml
template:
  template:
      spec:
        tolerations:
        - effect: NoSchedule
          key: github
          operator: Equal
          value: runners
        initContainers:
        - name: init-dind-externals
          image: ghcr.io/actions/actions-runner:latest
          command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
          volumeMounts:
            - name: dind-externals
              mountPath: /home/runner/tmpDir
        containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: DOCKER_HOST
              value: unix:///run/docker/docker.sock
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /run/docker
              readOnly: true
        - name: dind
          image: docker:dind
          args:
            - dockerd
            - --host=unix:///run/docker/docker.sock
            - --group=$(DOCKER_GROUP_GID)
          env:
            - name: DOCKER_GROUP_GID
              value: "123"
          securityContext:
            privileged: true
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /run/docker
            - name: dind-externals
              mountPath: /home/runner/externals
        volumes:
        - name: work
          emptyDir: {}
        - name: dind-sock
          emptyDir: {}
        - name: dind-externals
          emptyDir: {}
```
Maybe I'm placing it in the wrong place ?
Thanks for any help in advance !

**Comment by matan-legit** [comment, marked as answer]
it should be under:
```
  template:
    spec:
      tolerations:
        - key: karpenter-managed-type
          operator: Equal
          value: arc-scalers
```
remove one template
