### DISCUSSION TITLE
Can use ubuntu 20.04 ?

### DISCUSSION THREAD

**Discussion by kingbj940429** [actions/actions-runner-controller#3288] [Questions] [answered]
I use gha-runner-scale-set and gha-runner-scale-set-controller 

It uses ubuntu 22.04 by default

how can I use ubuntu 20.04 ?

I can't find image version

this is my image version
```yaml
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
```
