### DISCUSSION TITLE
How to export listener metrics to prometheus ?

### DISCUSSION THREAD

**Discussion by rekha-prakash-maersk** [actions/actions-runner-controller#3293] [Questions] [answered]
Hi , I have exported controller metrics as it had **PodAnnotations** in its chart by simply adding below config- https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/values.yaml#L42

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8080"

I am looking for similar config for listener as well, instead of creating a podmonitor. Any guidance on this please?

I tried this approach but no luck,

scale-set-values.yaml
```
containerMode:
  type: "dind" 
template:
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"
      prometheus.io/scheme: "https"
  spec:
    imagePullSecrets:
      - name: "xxx"
    containers:
      - name: runner
```

**Comment by rekha-prakash-maersk** [comment, marked as answer]
Update: Figured out the placement of metrics annotations for listener,

```
listenerTemplate:
  spec:
    containers:
      - name: listener
        securityContext:
          runAsUser: 1000
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"
```
