### DISCUSSION TITLE
How to properly input tolerations and affinity values?

### DISCUSSION THREAD

**Discussion by OmpahDev** [actions/actions-runner-controller#3301] [Questions]
I'm trying to deploy version 0.7.0 of the gha-runner-scale-set-controller helm chart from ghcr.io/actions/actions-runner-controller-charts and I'm completely stuck trying to input helm parameters in a way that actually runs because my "tolerations" and "affinity" fields keep getting rejected. I can't find any documentation anywhere saying how they're supposed to be specified.

I'm doing this via ArgoCD and passing in the following values:

```
      parameters:
        - name: 'affinity'
          value: '"affinity":
          "nodeAffinity":
            "requiredDuringSchedulingIgnoredDuringExecution":
              "nodeSelectorTerms":
              - "matchExpressions":
                - "key": "pool"
                  "operator": "NotIn"
                  "values":
                  - "gha-runners"
        '
        - name: 'labels.github-actions'
          value: 'true'
        - name: 'tolerations'
          value: '"tolerations":
        - "effect": "NoSchedule"
          "key": "github-actions"
          "operator": "Equal"
          "value": "true"
        '
```

and it keeps failing with this error:
`error validating data: [ValidationError(Deployment.spec.template.spec.affinity): invalid type for io.k8s.api.core.v1.Affinity: got "string", expected "map", ValidationError(Deployment.spec.template.spec.tolerations): invalid type for io.k8s.api.core.v1.PodSpec.tolerations: got "string", expected "array"]`

I've tried all of the following variations of the syntax (example of for tolerations, but I've tried the same format for affinity as well) and they all fail with the same error
```
    - name: 'tolerations'
      value: |
        - effect: "NoSchedule"
          key: "github-actions"
          operator: "Equal"
          value: "true"
```
```
  - name: 'tolerations'
      value:
        - effect: "NoSchedule"
          key: "github-actions"
          operator: "Equal"
          value: "true"
```
```
    - name: 'tolerations'
      value: |
        [
          {
            "effect": "NoSchedule",
            "key": "github-actions",
            "operator": "Equal",
            "value": "true"
          }
        ]
```
```
        - name: 'tolerations'
          value: |-
            - effect: "NoSchedule"
              key: "github-actions"
              operator: "Equal"
              value: "true"
```

how do I correctly format this yaml so the controller deploys?

**Comment by jonwest** [comment]
Youre passing "affinity" as a big string value, and youre passing in "affinity" (the key) as part of the value youre trying to set.  If youre passing in tolerations the same way, thats probably your issue. 

In your second question about YAML formatting, all of your formats are incorrect--the last one is probably the closest, but you need to remove the "| -".

**Comment by OmpahDev** [comment]
> Youre passing "affinity" as a big string value, and youre passing in "affinity" (the key) as part of the value youre trying to set. If youre passing in tolerations the same way, thats probably your issue.

How do I pass in `affinity` then?

**Comment by OmpahDev** [comment]
> In your second question about YAML formatting, all of your formats are incorrect--the last one is probably the closest, but you need to remove the "| -".

I tried this but it's just making the whole argo application fail with

error validating data: ValidationError(Application.spec.source.helm.parameters[9].value): invalid type for io.argoproj.v1alpha1.Application.spec.source.helm.parameters.value: got "array", expected "string"

**Comment by jgreat** [comment]
Not specifically for Argo, but Here's my values file for the gha-runner-scale-set chart that includes nodeSelector,tolerances and resources.  I found that you basically need to specify the entire pod spec template to customize the runners. 

This also includes a downstream runner image with some nice-to-have utilities like git. 

```
runnerScaleSetName: ...
githubConfigUrl: ...
githubConfigSecret: gha-rss
maxRunners: 25
minRunners: 0
runnerGroup: default
metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: "/metrics"

template:
  spec:
    imagePullSecrets:
    - name: docker-credentials
    initContainers:
    - name: init-dind-externals
      image: mobilecoin/gha-runner:latest
      command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
      volumeMounts:
      - name: dind-externals
        mountPath: /home/runner/tmpDir
    containers:
    - name: runner
      # https://github.com/mobilecoinofficial/gha-runner
      image: mobilecoin/gha-runner:latest
      command: ["/usr/local/bin/wait_for_docker_then_run.sh"]
      env:
      - name: DOCKER_HOST
        value: unix:///run/docker/docker.sock
      volumeMounts:
      - name: work
        mountPath: /home/runner/_work
      - name: dind-sock
        mountPath: /run/docker
        readOnly: true
      resources:
        limits:
          cpu: 22
          memory: 92Gi
        requests:
          cpu: 11
          memory: 46Gi
    - name: dind
      image: docker:dind
      args:
      - dockerd
      - --host=unix:///run/docker/docker.sock
      - --group=$(DOCKER_GROUP_GID)
      env:
      - name: DOCKER_GROUP_GID
        value: "123"
      securityContext:
        privileged: true
      volumeMounts:
      - name: work
        mountPath: /home/runner/_work
      - name: dind-sock
        mountPath: /run/docker
      - name: dind-externals
        mountPath: /home/runner/externals
      resources:
        limits:
          cpu: 22
          memory: 92Gi
        requests:
          cpu: 11
          memory: 46Gi
    volumes:
    - name: work
      emptyDir: {}
    - name: dind-sock
      emptyDir: {}
    - name: dind-externals
      emptyDir: {}
    tolerations:
    - effect: NoSchedule
      key: builder
      operator: Exists
    nodeSelector:
      builder-node: 'true'
```
