### DISCUSSION TITLE
How to use metrics for action runner controller

### DISCUSSION THREAD

**Discussion by dhutsj** [actions/actions-runner-controller#3331] [Questions]
Here is the code snippets of my `values.yaml`
```yaml
metrics:
  serviceAnnotations: {}
  serviceMonitor:
    enable: true
    namespace: "git-actions"
    timeout: 30s
    interval: 1m
  serviceMonitorLabels: {}
  port: 8080
  proxy:
    enabled: false
actionsMetrics:
  serviceAnnotations: {}
  serviceMonitor:
    enable: true
    namespace: "git-actions"
    timeout: 30s
    interval: 1m
  serviceMonitorLabels: {}
  port: 8080
  proxy:
    enabled: false
actionsMetricsServer:
  enabled: true
  logFormat: json
  secret:
    enabled: true
    create: false
    name: "github-webhook-token"
    github_webhook_secret_token: ${github_token}
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8080"
```
But I do not see any metrics like `github_workflow_xxx`.

Please help. Thank you in advance!
