### DISCUSSION TITLE
Runner-scale-set with Ubuntu 20.04

### DISCUSSION THREAD

**Discussion by serbantarmure** [actions/actions-runner-controller#3332] [Questions]
Hello!

I want to use a runner based on the Ubuntu 20.04 instead of Ubuntu 22.

I got the base image that is used by the action-runner-set [here](https://github.com/actions/runner/blob/main/images/Dockerfile) and I changed `jammy` with `focal`. I pushed the image to the registry but when I try to deploy the action-runner-set with that image I get

`failed container "runner" in pod "runner-test-set-jftwc-runner-jppkm" is waiting to start: ContainerCreating for gha-runner-scale-set-main-test-0/runner-test-set-jftwc-runner-jppkm (runner) `

This is how my `values.yaml` file looks like:
```
githubConfigUrl: "https://github.com/my-company"

maxRunners: 25

## minRunners is the min number of idle runners. The target number of runners created will be
## calculated as a sum of minRunners and the number of jobs assigned to the scale set.
minRunners: 1

runnerGroup: "runner-set-test"

## name of the runner scale set to create.  Defaults to the helm release name
runnerScaleSetName: "runner-test-set"

template:
  spec:
    containers:
    - name: runner
      image: "ubuntu-20-test:latest" # ghcr.io/actions/actions-runner:latest
      command: ["home/runner/run.sh"]
    resources:
      requests:
        cpu: "0.5m"
        memory: "1.0Gi"
```
P.S. If I use this image `ghcr.io/actions/actions-runner:latest` it's working fine.
Do you know what am I doing wrong?
