### DISCUSSION TITLE
Define general resource limits in kubernetes mode for service container

### DISCUSSION THREAD

**Discussion by David9902** [actions/actions-runner-controller#3338] [Questions]
Hi everyone, 
I am currently trying to run service container but I am failing to set cpu and memory request and limit spec for them in a general way. 

The option to go is in my opinion the [Hook](https://github.com/actions/runner-container-hooks/blob/main/docs/adrs/0096-hook-extensions.md). Though I dont see  a way how to set the memory and cpu limits as easily, as it can be done for the "normal" workflow pods. 
I see how it is done for specific service containers like redis shown [here](https://github.com/actions/runner-container-hooks/blob/main/examples/extension.yaml#L23). Though it is not very practical to add specific implementations for every possible side-car container.
If I am misunderstanding some logic there, please let me know about it :)

**Comment by jonwest** [comment]
From my understanding, that's exactly how it works, and you _are_ expected to add specific implementations for every possible side-car container.  I realize that's not good news, or what you (or I 😅) wanted to hear, but that seems to be the case.

**Reply by David9902** [reply]
Thanks for your comment @jonwest . Since my cluster requires cpu and memspecs on every container. The problem I see is, when offering ARC runners to other users, they can only use side car containers I have specified in the backend of arc.

When having a general cpu and memory setting for all side cars the user could launch any side car.

**Reply by cgiraldo** [reply]
FYI, we modify the k8s runner-container-hook to use an extra container name "$default" defined in the hook-extension configmap. This allows us to merge the container spec with all service containers.

https://github.com/Gradiant/runner-container-hooks/tree/main

example configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hook-extension
  namespace: arc-runners
data:
  content: |
    metadata:
      annotations:
        example: "extension"
    spec:
      containers:
        - name: "$job" # Target the job container
          resources: # set resource request
            requests:
              cpu: "500m"
        - name: "$redis" # Target the redis container
          resources: # set resource limits
            requests:
              cpu: "1000m"
        - name: "$default" # Target  the rest of the service containers
          resources: # set resource limits
            requests:
              cpu: "300m"
```

We have a temporary image `gradiant/actions-runner:2.325.0` with the modified hook for evaluation.
