### DISCUSSION TITLE
HorizontalRunnerAutoscaler - not scale when used in a matrix workflow

### DISCUSSION THREAD

**Discussion by ShaiShalev87** [actions/actions-runner-controller#3404] [Questions]
Hi, i have a problem where using ARC with a github workflow that has matrix.
the matrix jobs running one after the other and not in parallel.
if i run them on ubuntu-latest they run in parallel.

the ARC runners working fine and scale fine with regular workflow that is triggered multiple times.
but they do not scale with one workflow with matrix.
please help me understand if that configuration problem or that how the runners behave.

thanks.
here my HorizontalRunnerAutoscaler:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: gcp-runner
  namespace: actions-runner
spec:
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: gcp-runner
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '2'
      scaleDownFactor: '0.5'
  ```

**Comment by ShaiShalev87** [comment]
ive ended up using
```
  scaleUpTriggers:
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - tier1_shai
```
and after 1 minute another one scaled up and the jobs run in parallel
