### DISCUSSION TITLE
Support `podAnnotations` in gha-runner-scale-set listener Pod

### DISCUSSION THREAD

**Discussion by newdeal123** [actions/actions-runner-controller#3429] [Ideas]
Hi,
We would like to put annotations on controllers and listener pods to collect metrics of gha-runner-scale-set with datadogs.
The gha-runner-scale-set-controller helm chart supports the podAnnotations field to collect metrics with the datadog, but the **gha-runner-scale-set listener pod does not support that field**, so it is not possible to add it.

I expected (in helm values)
```yaml
podAnnotations:
    ad.datadoghq.com/listener.checks: |
      {
        "openmetrics": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8080/metrics",
              "namespace": "arc-systems",
              "metrics": ["gha_*"]
            }
          ]
        }
      }
```

I expected (in listener pod)
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-12T08:02:05Z"
  annotations:
    ad.datadoghq.com/listener.checks: |
      {
        "openmetrics": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8080/metrics",
              "namespace": "arc-systems",
              "metrics": ["gha_*"]
            }
          ]
        }
      }
  labels:
    actions.github.com/organization: ***
    actions.github.com/scale-set-name: self-hosted
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: runner-scale-set-listener
    app.kubernetes.io/part-of: gha-runner-scale-set
    app.kubernetes.io/version: 0.8.3
  name: self-hosted-6cd58d58-listener
  namespace: arc-systems
```

Do you have any plans for assistance? Thanks in advance.

**Comment by nikola-jokic** [comment]
Hey @newdeal123,

I think you are using incorrect field.

The correct way to set annotations on the listener pod would be:

```yaml
listenerTemplate:
  metadata:
    annotations:
      example: "annotation"
```

**Comment by newdeal123** [comment]
@nikola-jokic  I've solved it. thanks :) 

```yaml

listenerTemplate:
  metadata:
    annotations:
      ad.datadoghq.com/listener.checks: |
        {
          "openmetrics": {
            "init_config": {},
            "instances": [
              {
                "openmetrics_endpoint": "http://%%host%%:8080/metrics",
                "namespace": "arc-systems",
                "metrics": ["gha*"]
              }
            ]
          }
        }
  spec:
    containers:
    - name: listener
```
