### DISCUSSION TITLE
Runner pods do not get scheduled if I uncomment the whole dind template section in a scale set's values.yaml

### DISCUSSION THREAD

**Discussion by alexgaganashvili** [actions/actions-runner-controller#3435] [General]
When I have only

 ```
   containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
```
in my template spec in values.yaml, I runner pods created. However, when I uncomment the whole template.spec with initContainers and a dind container and upgrade/install the scale-set chart, runner pods do not get scheduled (or if there's one running with default values.yaml, it gets terminated).

Please advise.
Thanks.
