### DISCUSSION TITLE
Upgrade v0.9.0 Error: permission denied while trying to connect to the Docker daemon socket at unix:///run/docker/docker.sock

### DISCUSSION THREAD

**Discussion by rekha-prakash-maersk** [actions/actions-runner-controller#3461] [Questions]
Hi,

After upgrading to the v0.9.0 version, encountering this permission issue with docker host connection, I have made changes to dind-sock as per this [PR](https://github.com/actions/actions-runner-controller/commit/46cfbb6ec7c91ca573e7e2bff9940d18d88c445d) to the runner dind template. any idea how to resolve this issue ?

![image](https://github.com/actions/actions-runner-controller/assets/140515122/9d569ef8-8e46-4e91-83a8-c0c0cb783c5c)

```

spec:
    initContainers:
      - name: init-dind-externals
        image: "gha-sh-runner:0.0.5"
        command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
    containers:
      - name: runner
        image: "gha-sh-runner:0.0.5"
        imagePullPolicy: Always
        command: ['/home/runner/run.sh']
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
            ephemeral-storage: "12Gi"
          limits:
            memory: "4Gi"
            cpu: "1"
            ephemeral-storage: "12Gi"
        env:
          - name: DOCKER_HOST
            value: unix:///run/docker/docker.sock
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --host=unix:///run/docker/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
          - name: dind-externals
            mountPath: /home/runner/externals
    volumes:
    - name: work
      emptyDir: {}
    - name: dind-sock
      emptyDir: {}
    - name: dind-externals
      emptyDir: {}

```
