### DISCUSSION TITLE
Can't run "regular" actions on ARC am I misunderstanding how this thing works?

### DISCUSSION THREAD

**Discussion by sinkr** [actions/actions-runner-controller#3489] [Questions]
I can run DinD tasks just fine, but something that would `runs-on: ubuntu-latest` fails on a locally-hosted ARC runner, even something as simple as this:
```
name: Lint

on:
  push:
    branches:
      - "**"

jobs:
  enforce_format:
    runs-on: my-local-runner  # was ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: "23.9.1"
  lint:
    runs-on: ubuntu-latest
    needs: enforce_format
    env:
      DJANGO_SETTINGS_MODULE: my-api.settings.common
      WORKER: TRUE
(...)
```

Fails like so:
```Run psf/black@stable
Run # Even when black fails, do not close the shell
Traceback (most recent call last):
  File "/runner/_work/_actions/psf/black/stable/action/main.py", line 117, in <module>
    run([sys.executable, "-m", "venv", str(ENV_PATH)], check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'venv', '/runner/_work/_actions/psf/black/stable/.black-env']' returned non-zero exit status 1.
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/runner/_work/_actions/psf/black/stable/.black-env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

Will these tasks always have to run in GitHub?  Coming from GitLab where I could run everything in house, this feels strange.

Thanks for the insight!
