### DISCUSSION TITLE
Enable EKS IRSA

### DISCUSSION THREAD

**Discussion by maljolani** [actions/actions-runner-controller#3491] [Questions] [answered]
Hi,

I am using AWS EKS, and deploying scale-set runners, I am trying to enable the k8s mode but still failing to pickup the right service account to access the required AWS role.

Could you please guid me or share some docs.

**Comment by KrisJohnstone** [comment]
+1

**Reply by maljolani** [reply, marked as answer]
Answering myself 

```
  containerMode:
    type: "kubernetes"
    kubernetesModeServiceAccount:
      annotations:
        eks.amazonaws.com/role-arn: {AWS_ROLE_ARN}
```
