### DISCUSSION TITLE
Caching the "setup-$language" tools

### DISCUSSION THREAD

**Discussion by danielloader** [actions/actions-runner-controller#3500] [Ideas]
Just wondering if anyone had ideas on the caching of the setup-language actions github offers.

The java one especially takes a long time to download each time a job starts.

I can see the work dir in the runners is expected to be `/home/runner/_work` so I am assuming the tools would go to `/home/runner/_work/_tool`. 

Due to the way the containers are defined with a mount:

```yaml
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
```

I'm assuming because of this I can build a container image extending the actions runner one by populating that directory, and it looks like the environment variable used to set the tool cache is set by github (as expected) so I can't set it to another directory.

Anyone had any success on how to re-use this tools cache? 

It's becoming unfeasible to download a gig or so of setup-node@v20 and setup-java@17 each time the runner starts.
