### DISCUSSION TITLE
Mounting a volume to a container job in `containerMode: kubernetes`

### DISCUSSION THREAD

**Discussion by sofiegonzalez** [actions/actions-runner-controller#3508] [Questions]
Hi! 
I want to mount a volume to a container job from a previous job in the same workflow. Example workflow:
```
jobs:
  job1:
    runs-on: gha-runner-scale-set-dind-mode
    steps:
        - name: Checkout Mono
           uses: actions/checkout@v2
  job2:
    runs-on: gha-runner-scale-set-kubernetes-mode
    container:
      image: <private-container-image>
      volumes:
          - ${{ github.workspace }}:${{ github.workspace }}
    steps:          
      - name: see workspace
         run:  |
             ls ${{ github.workspace }}
```

My private container image is unable to run the Checkout Mono action because it is limited in space, so I tried checking out my repo in a previous job (job1) and mounting the ${{ github.workspace }} as a volume. 
When the job2 runner pod spins it, it spins up the corresponding workflow pod to run the private container image, but the volume does not seem to be mounted properly. There are no contents within the ${{ github.workspace }} of the workflow pod.
Is this possible? Or am i misunderstanding how to share data across jobs?

I know it is possible to have artifacts and outputs for jobs, but my main question is if its possible to mount a volume from a previous job to a job that is running on a `containerMode: kubernetes` runner. I am using Github Actions Runner Scale Sets and am on the latest version of the controller and the runners.
Thanks!
