### DISCUSSION TITLE
RunnerDeployment => no pods are started

### DISCUSSION THREAD

**Discussion by laurijssen** [actions/actions-runner-controller#3585] [Questions]
I'm trying to get a RunnerDeployment on k8s v1.29. 

I've installed helm charts so there is a actions-runner-controller-5c996cd9c7-bvvvs running plus secrets and all that.

But on kubectl apply -f of the following

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeploy
spec:
  replicas: 2
  template:
    spec:
      organization: org
```

The logs of the controller say:

```
ERROR   Reconciler error        {"controller": "runner-controller", "controllerGroup": "actions.summerwind.dev", "controllerKind": "Runner", "Runner": {"name":"runnerdeploy-7z5mk-df28r","namespace":"default"}, "namespace": "default", "name": "runnerdeploy-7z5mk-df28r", "reconcileID": "da159d71-e07a-4acf-8d0d-590b0c146655", "error": "pods \"runnerdeploy-7z5mk-df28r\" is forbidden: violates PodSecurity \"baseline:latest\": privileged (container \"docker\" must not set securityContext.privileged=true)"}
```

and no runner pods are started. I know that lots has changed in the securityContext space but can I change the yaml to get it working again?

The same is working fine on 1.24.
