### DISCUSSION TITLE
Unable to resolve action `actions/<action>`, repository not found.

### DISCUSSION THREAD

**Discussion by Edarjak** [actions/actions-runner-controller#3603] [Questions]
Hi community,

I have encountered an issue when actions suddenly stop working. The problem happens occasionally and identifying the root cause is a bit challenging. Actions runner controller is running in the K3S cluster behind the proxy and is connected to the Enterprise server. The server has an access to the github.com through GitHub Connect.

Error:
<img width="1103" alt="Screenshot 2024-06-18 at 15 20 32" src="https://github.com/actions/actions-runner-controller/assets/129397700/0c4a9dc0-f45e-4a4d-957f-0a72679ba016">

RunnerDeployment:

```

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-actions-runners-test
  namespace: github-actions-runners-test
spec:
  template:
    spec:
      organization: org
      env:
        - name: http_proxy
          value: "http://proxy:80"
        - name: https_proxy
          value: "http://proxy:80"
        - name: no_proxy
          value: ".localhost,127.0.0.1,.host.com,github.host.com,app1.host.com"
        - name: GIT_SSL_CAINFO
          value: /etc/ssl/certs/ca-certificates.crt
      labels:
        - x-test
        - test
      group: Default
      containers:
        - name: docker
          image: <docker-image>
        - name: runner
          image: <base runner image + additional software, like: curl, wget, jq, etc. >
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-actions-runners-test-autoscaler
  namespace: github-actions-runners-test
spec:
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: github-actions-runners-test
  minReplicas: 6
  maxReplicas: 16
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'
```

Maybe someone faced the same issue and could recommend some workarounds?

Hope, someone could help or at least point to the right way :) 

Thanks in advance,
