### DISCUSSION TITLE
CPU and Memory build over time in scaleset listeners

### DISCUSSION THREAD

**Discussion by rekha-prakash-maersk** [actions/actions-runner-controller#3604] [Questions]
Noticing this behaviour with recent 0.9.2 upgrade that the listener resources slowly builds up and gets restarted and the cycle goes on. No error or warning logs either. any idea how to approach this ?

![Screenshot 2024-06-18 at 12 39 21](https://github.com/actions/actions-runner-controller/assets/140515122/e3ecb778-821c-451d-8a8b-dac17dc0759d)

**Comment by nikola-jokic** [comment]
Oh, this is definitely unexpected. I'll try to investigate this behavior and get back to you. Thank you for bringing this up!

**Reply by rekha-prakash-maersk** [reply]
The scaleset is handling ~50 job at any given time so its resource buildsup faster.  The other scaleset with less load having same behaviour but the buildup rate is very slow

**Reply by rekha-prakash-maersk** [reply]
@nikola-jokic Have you had a chance to look at this ? I could not progress much on what causes this build up.

**Reply by rekha-prakash-maersk** [reply]
Hi @nikola-jokic any update on this? this issue started after upgrading from 0.8.* to 0.9.*
in 0.8.* I even had to reduce the allocated resource because of the underconsumption while using 0.8 version, this is the current allocation,

```
listenerTemplate:
  spec:
    containers:
      - name: listener
        securityContext:
          runAsUser: 1000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
```
