### DISCUSSION TITLE
Can not set `privileged` in containers by arc on K3s

### DISCUSSION THREAD

**Discussion by Rory-Z** [actions/actions-runner-controller#3690] [Questions]
Hello, guys, actions-runner-controllers is a great project, I like this.

I'm install arc by helm  in `v1.29.6+k3s2`, all of them looks good, this is my helm value
```
runnerScaleSetName: my-k3s

githubConfigUrl: https://github.com/my-org/my-repo
githubConfigSecret:
  github_token: my-token

containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

template:
  spec:
    securityContext:
      fsGroup: 123 ## This is the GID of the docker group in the container
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:2.317.0
        command: ["/home/runner/run.sh"]
```

Now I want build docker image in arc pod, this is my workflow file:
```
jobs:
  build:
    runs-on: my-k3s
    container:
      image: docker:dind
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
       ...
```

But I got error: `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`, I'm checking the `.spec.containers[].securityContext` of workflow pods, I didn't see `{privileged: true}`

Looking forward the answer
