### DISCUSSION TITLE
Issue with Pushing Docker Images to Self-Hosted Registry via docker/build-push-action@v6 on Self-Hosted GitHub Actions Runner Behind Reverse Proxy

### DISCUSSION THREAD

**Discussion by demissiea** [actions/actions-runner-controller#3717] [Questions]
I'm using a self-hosted GitHub Actions runner setup with Actions Runner Controller (ARC) on Azure AKS, along with a small VM serving as a proxy for the AKS. My self-hosted Docker registry is set up with a Nginx reverse proxy and is configured to only accept requests from the VM proxy server from azure. I'm experiencing issues when trying to push Docker images to the registry using docker/build-push-action@v6 in GitHub Actions. The push works flawlessly when I  build and push the Docker images using regular Docker commands in the pipeline script, but it fails with a 403 Forbidden error response when using the GitHub Action. I suspect this is because the docker/build-push-action@v6 GitHub Action is not utilizing the proxy VM configured for the AKS cluster.

I also tried to include the proxy's on builds-args but its still not working.

What could be causing this discrepancy, and how can I resolve it?

```
name: poc
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: selfhosted-ubuntu-runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to selfhosted-registry.com
        uses: docker/login-action@v3
        with:
          registry: selfhosted-registry.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}  

      - name: Build and Push Docker Image
        id: push-tag
        uses: docker/build-push-action@v6
        with:
          context: .  
          push: true
          tags: "selfhosted-registry.com/testrepo:01"
          build-args: |
            http_proxy=${{ secrets.http_proxy }}
            https_proxy=${{ secrets.https_proxy }}
```
