### DISCUSSION TITLE
Job randomly skips ahead in the middle of execution

### DISCUSSION THREAD

**Discussion by hae-andrew-young** [actions/actions-runner-controller#3773] [Questions]
This isn't about the job skipping entirely. It's about the job, while executing, would skip ahead to the next one with out fully completing. For example:

```yml
- name: Setup Terraform
  uses: hashicorp/setup-terraform@v3
  with:
    terraform_version: 1.8.1
    terraform_wrapper: false
- name: Terraform Apply
  run: terraform apply -auto-approve "deployment.tfplan"
- name: Output inventory
  run: terraform output -json ansible_inventory
```

The `terraform apply` step typically takes about 20 minutes but in some cases, it would run for about 1 minute, then prematurely skip ahead. No logs, no error, nothing. The step is considered "successful". It just fails further down in the steps because the `terraform output` pretty much empty.

ARC logs show nothing unusual either. Has anyone experienced this before?
