### DISCUSSION TITLE
Ephemeral storage limits added from nowhere

### DISCUSSION THREAD

**Discussion by zongsizhang** [actions/actions-runner-controller#3792] [Questions]
Hi I'm hosting an ARC controller + some auto scaling runner set in EKS.
We recently found that, in the runners there are resources requests+limits for ephemeral storage applied
```
image: docker:dind
          name: dind
          resources:
            limits:
              ephemeral-storage: 50Gi
            requests:
              ephemeral-storage: 20Gi
```
While I can't find the specification anywhere in the helm-chart.
Can anyone help me understand where are the limits added and how to tune it?
Thanks!
