### DISCUSSION TITLE
Using Proxy for action-controller

### DISCUSSION THREAD

**Discussion by sandeepraj-chandrakant-bhandari-db** [actions/actions-runner-controller#501] [Questions] [answered]
HI,

We have been successfully able to run the controller in our dev and uat environments, but when we promoted to production, the github url is accessible only via proxy.

Is there a way we can set a proxy to get the token and register the runners?

Currently I am getting below error because GitHub is not reachable

```
  ERROR   controller-runtime.controller   Reconciler error        {"controller": "runner", "request": "default/runnerdeploy-zdjx7-hx7tc", "error": "failed to create registration token: Post \"https://api.github.com/enterprises/deutsche-bank/actions/runners/registration-token\": dial tcp 140.82.121.6:443: i/o timeout"}

```

**Comment by donovanmuller** [comment, marked as answer]
@sandeepraj-chandrakant-bhandari-db you can just add the HTTP proxy environment variables to your `RunnerDeployment` as below:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: demo-runners
spec:
  template:
    spec:
      env:
        - name: http_proxy
          value: "http://proxy.example.com:8080"
        - name: https_proxy
          value: "http://proxy.example.com:8080"
        - name: no_proxy
          value: "172.20.0.1,*.example.com"
...
```

**Reply by mumoshu** [reply]
Thanks for sharing @donovanmuller ☺️

**Reply by sandeepraj-chandrakant-bhandari-db** [reply]
Hey @donovanmuller @mumoshu thanks for the response. I tried this way but the controller doesn't seem to recognize proxy.
 I get the same timeout error. 

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeploy
spec:
  replicas: 2
  template:
    spec:
      env:
        - name: http_proxy
          value: "http://serverproxy.intranet.db.com:8080"
        - name: https_proxy
          value: "http://serverproxy.intranet.db.com:8080"
      enterprise: deutsche-bank
      labels:
        - dind
      image: gcr.io/db-ctl-0504-runners/summerwind/actions-runner-dind:latest
      dockerdWithinRunnerContainer: true
      resources:
        limits:
          cpu: "4000m"
          memory: "2Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
 ......
```

**Reply by donovanmuller** [reply]
Ah ok, my suggestion would add support for the actual runners, not the controller. However, it's the same thing for controller proxy support. I'm not sure what install option you're using but you have to add the same environment variables to the controller Deployment.

Using the Helm chart, you can use `env.https_proxy=http://serverproxy.intranet.db.com:8080` etc. as a chart value for example.

**Reply by sandeepraj-chandrakant-bhandari-db** [reply]
I am using the kubectl method to install. I have also already added the proxy variables in controller.

```
 env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: github_token
              name: controller-manager
              optional: true
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              key: github_app_id
              name: controller-manager
              optional: true
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              key: github_app_installation_id
              name: controller-manager
              optional: true
        - name: GITHUB_APP_PRIVATE_KEY
          value: /etc/actions-runner-controller/github_app_private_key
        - name: http_proxy
          value: "http://serverproxy.intranet.db.com:8080"
        - name: https_proxy
          value: "http://server-proxy.intranet.db.com:8080"
        image: summerwind/actions-runner-controller:v0.17.0
        name: manager
```
