### DISCUSSION TITLE
Possibility to set pod labels & annotations

### DISCUSSION THREAD

**Discussion by ekarlso** [actions/actions-runner-controller#576] [Questions] [answered]
Is there a way to set extra labels & annotations on the Runner pod's ?

**Comment by toast-gear** [comment, marked as answer]
https://github.com/actions-runner-controller/actions-runner-controller/pull/583 there is now!

**Reply by braedongough** [reply]
If I'm reading this correctly, this is just for the controller pod and this would not apply to the runner pods, correct? I'm very interested in being able to add labels to the runners if that's possible!

**Reply by toast-gear** [reply]
labels can be added to runners like this:

```yaml
# RunnerDeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner-deployment
spec:
  template:
    metadata:
      labels:
        key: value
        keyTwo: valueTwo
```

I highly recommend using this plugin https://github.com/rewanthtammana/kubectl-fields to explore the CRDs in a human readable way. You can then search for what attributes are in the various kinds and see what the path is
