### DISCUSSION TITLE
Multiple Controllers on same EKS cluster

### DISCUSSION THREAD

**Discussion by spencer-steed** [actions/actions-runner-controller#692] [Questions] [answered]
We have multiple orgs that I am attempting to make runners for, and am having trouble with making multiple controllers in the same cluster (I think its required since each org has a seperate install ID). Is there a certain way I should be making the 2nd controller?

**Comment by toast-gear** [comment, marked as answer]
Nothing specific beyond you will need a unique namespace for each set of runners, each controller configured to only watch their namespace like below, and a unique github app secret configured for each controller

```yaml
scope:
  singleNamespace: true
  watchNamespace: actions-1
```

```yaml
scope:
  singleNamespace: true
  watchNamespace: actions-2
```

etc etc
