### DISCUSSION TITLE
How to pull private actions docker from private registry

### DISCUSSION THREAD

**Discussion by peimanja** [actions/actions-runner-controller#698] [Questions] [answered]
I want to use private actions in form of docker from a private docker registry (we use Artifactory), something like:
```yaml
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: docker://<my-private-registry>:<image>:<tag>
```

Github does not support passing the credentials yet (although it supports [job containers](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer)) and since pulling images happens before any steps you cannot really authenticate with Artifactory.

Is there any chance we can support that in the runner [startup script](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/startup.sh)?
