### DISCUSSION TITLE
Using your runner's IRSA IAM role within a workflow job container

### DISCUSSION THREAD

**Discussion by toast-gear** [actions/actions-runner-controller#798] [Show and tell]
A correctly configured IRSA setup will bootstrap your runners IAM role onto the runner automatically, at this point your runner will have the permissions of the associated IAM role. You may want to bring those permissions into a conatiner defined in a workflow, for example:

```yaml
name: My Awesome Workflow

on:
  workflow_dispatch:

jobs:
  checks:
    runs-on: self-hosted
    container:
      image: amazon/aws-cli:latest
    steps:
        - run: aws sts get-caller-identity
```

With this pipeline, our defined container `amazon/aws-cli` won't have any AWS rights as the bootstrapped token is on the runner, not in the `amazon/aws-cli:latest` container. As a result of this our `aws sts` call would fail. In order to bring our runner's bootstrapped IAM role into our container we must manually port the environment variables IRSA creates as well as mount of web identity token into our container:

```yaml
name: My Awesome Workflow

on:
  workflow_dispatch:

jobs:
  checks:
    runs-on: self-hosted
    container:
      image: amazon/aws-cli:latest
      env:
        AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        # This should be the same role that is being bootstrapped onto our runner 
        AWS_ROLE_ARN: arn:aws:iam::xxxx:role/runner-irsa-role
      volumes:
        - /var/run/secrets/eks.amazonaws.com/serviceaccount/token:/var/run/secrets/eks.amazonaws.com/serviceaccount/token
    steps:
        - run: aws sts get-caller-identity
```
