### DISCUSSION TITLE
[QUESTION] $HOME variable and .m2 cache (runner - not manager)

### DISCUSSION THREAD

**Discussion by jbkc85** [actions/actions-runner-controller#868] [General]
To whom it may concern,

I recently downloaded this project and got it running - kudos to all btw...this is pretty freakin spectacular.

That being said, I am running into a wall trying to figure out why my `~/.m2` cache seems to be populating two different directories while using the `actions/cache@v2` action.

What happens:

1. mvn clean install
 - populates /runner/.m2
 - populates /home/runner/.m2
2. 'check in cache'
3. reference cache
 - cache downloads to /runner/.m2
 - cache does not download to ~/.m2

I want to say something is going on here with the WORKSPACE/HOME variables, but I really have no idea and wanted to see if anyone else was running into this situation.  I do apologize if its been mentioned, I have not been able to find it!

Is there something I have to do to have `~/.m2` always go to `/home/runner` instead of the `/runner/` directory?

**Comment by jbkc85** [comment]
```
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
```
