### DISCUSSION TITLE
private-ca: How to pass the certificates to the controller

### DISCUSSION THREAD

**Discussion by pharndt** [actions/actions-runner-controller#945] [Questions]
When using this for an internal GitHub Enterprise installation, it might be necessary to pass self-signed certificates to the controller in order to get it to work with an internal hostname.

Currently, I see two options on how to achieve this:
1) Adding the certificates as a volume mount (e.g., to the mountPath `/etc/ssl/certs`)
This comes with the drawback, that is currently necessary to change the helm chart, which will cause effort on each update.

2) Adding the certificates by re-bundle the controller image
In this case, the certificates can be copied to the image and the Helm chart stays untouched. On the other hand, it comes with the drawback that you will need to re-bundle each new version of the controller.

Do I miss an option? Would you accept a PR for the Helm chart, that adds an optional value for self-signed certificates that will get mounted to `/etc/ssl/certs`?

**Comment by gazab** [comment]
Edit: But now I realise you wanted to do this for the controller, not the Runners... I'll leave my reply below anyway

You are missing an option! I currently solve this by using initContainers in my RunnerSet spec. Something like this (ignore that it is an normal Deployment. The principle works with RunnerDeployment and RunnerSet as well):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
        # This init container builds a cert bundle including self signed cert and stores it in the shared volume (/tmp)
        - name: ca-certs
          image: mcr.microsoft.com/dotnet/core/runtime-deps:3.0.3-buster-slim
          imagePullPolicy: Always
          command: [ 'sh', '-c', 'update-ca-certificates && cp /etc/ssl/certs/* /tmp/' ]
          volumeMounts:
          - name: enterprise-ca
            mountPath: /usr/local/share/ca-certificates/enterprise-ca.crt
            subPath: enterprise-ca.crt
          - mountPath: /tmp/
            name: ca-bundle
      containers:
      - name: app
        image: webapp:latest
        ports:
        - containerPort: 80
        # Mounts ca-bundle, which is now filled with both normal certs and custom certs, to /etc/ssl/certs in the main container
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-bundle
      restartPolicy: Always
      volumes:
      # Load custom cert from secret
      - name: enterprise-ca
        secret:
          secretName: enterprise-ca
      # Shared volume between init container and main container
      - name: ca-bundle
        emptyDir: {}
```

So the init container collects all certs, included a custom cert populated from a secret, to a shared volume. This volume is then mounted to `/etc/ssl/certs` in the main container.
