### ISSUE TITLE
Better behavior with Cluster Autoscaler

### ISSUE THREAD

**Issue by GoldenMouse** [actions/actions-runner-controller#1581]
**Is your feature request related to a problem? Please describe.**
I'm testing ARC with cluster autoscaler (on GKE).  I add the annotation `safe-to-evict:true` for the runners.
Occasionally cluster autoscaler reschedules the pod that is running a workflow so the workflow remains in limbo til it fails. 
This happens very rarely but enough to warrant not using it. 

**Describe the solution you'd like**
I wonder if we can toggle the `safe-to-evict:true` annotation when the runner is processing a job. Set it to false when it's busy, and true when it's not. 

**Describe alternatives you've considered**
I consider not setting `safe-to-evict:true` annotation at all. This will not reschedule the pods but it's less than accurate node autoscaling.

**Comment by mumoshu** [comment]
@GoldenMouse Thanks for raising this up!

> Occasionally cluster autoscaler reschedules the pod that is running a workflow

This is the most interesting part to me. With today's ARC, a runner pod and its `runner` container should terminate gracefully as long as there's enough time to do so.
How long was your GitHub Actions workflow job got stuck due to this issue running? 1min, 20min, or hours?

**Comment by ttruong-dexcom** [comment]
It waited for 15m and times out (jobs usualy takes 2mins). 
![image](https://user-images.githubusercontent.com/88852650/177413165-f6c97692-b506-4293-8703-0678091c3f84.png)

**Comment by ttruong-dexcom** [comment]
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sweetspot-runner
spec:
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      organization: sweetspot
      # repository: sweetspot/helm-harness-poc
      #dockerdWithinRunnerContainer: true
      #dockerEnabled: false
      group: Default
      labels:
        - arc
        - sweetspot
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
          # ephemeral-storage: 10Gi
---

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: sweetspot-runner-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 1
  maxReplicas: 100
  scaleTargetRef:
    name: sweetspot-runner
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "5m"
      amount: 2
```

**Comment by genisd** [comment]
I'm running with a 0 pdb to avoid unnecessary evitcs.
i.e.:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: runner-16-ramdisk
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      runner-deployment-name: runner-16-ramdisk
```

The runners surely wait to finish handling the job, but they will be given only so much time.
That however is configurable in kubernetes (`terminationGracePeriodSeconds`), one can configure how much time the pod gets to terminate by itself before kubernetes will force kill it.

I've ran workloads with `terminationGracePeriodSeconds` up to half an hour, with no issues.
So if that was configurable (maybe it already is?) it would be a good extension to help OPs issue.

Only concern I'd have is if moving pods around doesn't introduce possible new race condition (scenarios). That would be the risk :)
