### ISSUE TITLE
pods in offline state and webhook scaling is not happening

### ISSUE THREAD

**Issue by swathida-byte** [actions/actions-runner-controller#1806]
<img width="1336" alt="Screenshot 2022-09-15 at 3 42 25 PM" src="https://user-images.githubusercontent.com/97519234/190378404-3af7bef4-449e-4d73-90a8-bcdd5e66d15e.png">

**Comment by swathida-byte** [comment]
scaler yaml file 
```
apiVersion: actions.summerwind.dev/v1alpha1
metadata:
  name: re-centos7-scaler
kind: HorizontalRunnerAutoscaler
spec:
  scaleTargetRef:
    name: re-centos7-deployment
  minReplicas: 1
  maxReplicas: 25
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "120s"
```

**Comment by swathida-byte** [comment]
deployment yaml file 
```
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: re-centos7-deployment
spec:
  replicas: 1
  template:
    spec:
      enterprise: 
      image: "docker-sandbox.infra.cloudera.com/releng/centos07-runner:v3"
      labels:
        - re-centos7
      env: []
      group: RELENG-RUNNERS
      ```
