### ISSUE TITLE
Deployment strategy for the CRD self-runners deployment

### ISSUE THREAD

**Issue by mattpopa** [actions/actions-runner-controller#1932]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to upgrade the runner image because I cannot edit deployment strategy (`maxUnavailable` and `maxSurge`). I don't have resources to create all new runners upfront (maxSurge 100% like it seems to be default behavior now) and I end up editing the old replicaSet to progress.

**Describe the solution you'd like**
I would like the `kind: RunnerDeployment` to use the same deployment strategy as a regular k8s deployment:
```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 25%
```

This is useful when using container limits.

**Describe alternatives you've considered**

**Additional context**
