### ISSUE TITLE
Scaling runners based on webhook is sometimes stuck

### ISSUE THREAD

**Issue by damyan90** [actions/actions-runner-controller#2073]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

0.21.1

### CertManager Version

v1.10.1

### Deployment Method

Helm

### cert-manager installation

source: https://charts.jetstack.io
Values:
```
installCRDs: true
podDnsPolicy: 'None'
podDnsConfig:
  nameservers:
    - '1.1.1.1'
    - '8.8.8.8'
```

Standard `helm upgrade --install`

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: small-gha-runner
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: "fourvcpueph"
      image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
      imagePullPolicy: {{ .Values.image.imagePullPolicy }}
      group: {{ .Values.github.runnersGroup }}
      organization: {{ .Values.github.organization }}
      labels:
        - small-gha-runner
        - ubuntu-latest-small
      resources:
        limits:
          memory: 5Gi
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: small-gha-runner-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: 30
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    kind: RunnerDeployment
    name: small-gha-runner
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: '10m'
```

### To Reproduce

```markdown
1. Define several github workflows with trigger set on Pull Requests
2. Ask developers to start working
3. Observe the situation when many workflows are triggered, new commits pushed. We also have:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

set in workflows, but that doesn't seem to happen only when such cancel takes place for a particular branch.
```

### Describe the bug

Scaling is sometimes stuck for no visible reason. 
Editiing the horizontalrunnerautoscalers.actions.summerwind.dev and forcing `minReplicas` to be higher than current value also doesn't take place during that period.

No errors in any ACR component.

Jobs are pending in `Queued` state for up to 1hour during the day.

### Describe the expected behavior

Runners are scaled up/down based on the number of queued jobs in Github workflow.

### Whole Controller Logs

```shell
https://gist.github.com/damyan90/7ffacb6f48ae10f13fd5cf168da142ac
```

### Whole Runner Pod Logs

```shell
Not relevant really, but here's an example one:
https://gist.github.com/damyan90/567979a84cbbd1210ad1ac423e7bac38
```

### Additional Context

![2022-12-06_10-20](https://user-images.githubusercontent.com/24733538/205880129-62ae3dbf-fc34-46ac-bce4-3edc342c53d2.png)
![2022-12-06_10-40](https://user-images.githubusercontent.com/24733538/205879649-fc508263-4a38-4288-9dc1-458885e99dc4.png)
![2022-12-06_10-40_1](https://user-images.githubusercontent.com/24733538/205879678-bae239de-216e-47f5-a413-0d3e897594f5.png)
![2022-12-06_10-40_2](https://user-images.githubusercontent.com/24733538/205879712-b45d5036-edef-44fa-abb7-b76fa690287f.png)

Webhook delivery:
https://user-images.githubusercontent.com/24733538/205882331-086724a1-48b7-4e3f-ae77-23d35f959d02.png - 100% successful.

Runner's definition:
```
FROM summerwind/actions-runner:latest

RUN lsb_release -ra

ENV DIR=opt
COPY apt.sh /$DIR/
RUN sudo chmod +x /$DIR/apt.sh && sudo sh /$DIR/apt.sh 

COPY azure.sh /$DIR/
RUN sudo chmod +x /$DIR/azure.sh && sudo sh /$DIR/azure.sh

COPY software.sh software.json /$DIR/
RUN cd $DIR && sudo chmod +x /$DIR/software.sh && sudo sh /$DIR/software.sh

COPY cleanup.sh /$DIR/
RUN sudo chmod +x /$DIR/cleanup.sh && sudo sh /$DIR/cleanup.sh

RUN sudo apt-get update && sudo apt-get dist-upgrade -y

```

**Comment by mumoshu** [comment]
> I would have to cancel it first and then re-run?

Exactly.

**Comment by cristicalin** [comment]
I'm experiencing a very similar issue. In my case I have `minReplicas: 0` trying to scale up from 0 since these particular runners we need are quite large and don't want to keep idle ones running.

**Comment by damyan90** [comment]
> > I would have to cancel it first and then re-run?
> 
> Exactly. It should have worked if you had done so.

Well, even if. Can you imagine reaction of developers who are supposed to do that for their CI pipelines whenever that thing is stuck? I would be frustrated ;)

**Comment by mumoshu** [comment]
Of course, I can 😄 However my conclusion was that, as a "developer" who uses ARC,  I'd never want another system like Memcached, Redis, MySQL, etc., just to solve that problem. It isn't only about a code-only enhancement.

**Comment by damyan90** [comment]
Just did! That's awesome! ;)

**Comment by davidsielert** [comment]
i have the same problem, what I'm seeing though, is for matrix jobs its not dispatching an event for each matrix item. Which would be more related to a github platform issue.

**Comment by ns-ggeorgiev** [comment]
I have the same issue. And ARC in webhook mode is impossible to use with matrix builds at all. I am considering of backing the webhook with a second pull controller, so I can get the best of the two worlds. I wonther if anyone have tried that.

**Comment by omer2500** [comment]
@mumoshu @damyan90 
we are experiencing  the same issue, did you solve it? seems like a existing bug
we do see webhook (also 100% success) event for every matrix item and no errors to be found
but when i expect for 20 runner to spawn up i see only 3-4 that were created the rest stays in queued for a long time.

UPDATE:
Well we had 2 replicas for the webhook server
after reduced it to 1 everything is working as it should

might be a racing issue? what do you think?

**Comment by damyan90** [comment]
Not sure. I have 2 replicas for the webhook as well as for the controller and it works fine for now. I don't see too many issues, but I'm also not downscaling to 0. So might be that I'm just hiding the issue a bit.
Waiting for a new versions though. There's been some development together with Github on the autoscaling matter, for now available only to some beta testers. I suppose these issues were addressed there too.

**Comment by omer2500** [comment]
Thanks for the info @damyan90 
actually after more testing even 1 webhook server pod didnt solve the issue

imagine that we have matrix job with 20 tasks
but only 10 of them are scaling up 
the other 10 just hangs or some of them might be able to run, its a little bit random
in my case down scaling to zero is a must because im using expensive machines 
hope that they will solve it soon.

**Comment by shirkevich** [comment]
scaling with webhook from 0 or 1 replica is not working for us either

controller version: 0.27.0

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner56-deployment-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: 600
  scaleTargetRef:
    name: runner56-deployment
  minReplicas: 0
  maxReplicas: 3
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
```

Deliveries on GitHub are green. How can we debug it further?
