### ISSUE TITLE
/github/home/bin/docker: No such file or directory

### ISSUE THREAD

**Issue by softcane** [actions/actions-runner-controller#2097]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.20.2

### Deployment Method

Kustomize

### cert-manager installation

cert-manager is installed correctly. 

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner
  labels:
spec:
  template:
    spec:
      organization: organization-name
      group: organization-runners
      dockerEnabled: false
      dockerdWithinRunnerContainer: true
      image: summerwind/actions-runner-dind-rootless
```

### To Reproduce

```markdown
None
```

### Describe the bug

We are running `dind-rootless` image. While executing the workflow, we are noticing the following error.
```
/github/home/bin/docker: No such file or directory
```
We noticed the rootless docker is installed in the HOME. However, $HOME is overwritten to `/github/home` by GitHub context which we can't change.

DOCKER is picked up from the home.
https://github.com/actions/actions-runner-controller/blob/master/runner/docker-shim.sh#L7

Any recommendation? Probably update the docker-shim.sh with
```
DOCKER=/usr/bin/docker
if [ ! -e $DOCKER ]; then
  DOCKER=/home/runner/bin/docker
fi
```

### Describe the expected behavior

Probably update the docker-shim.sh with
```
DOCKER=/usr/bin/docker
if [ ! -e $DOCKER ]; then
  DOCKER=/home/runner/bin/docker
fi
```

### Whole Controller Logs

```shell
none
```

### Whole Runner Pod Logs

```shell
none
```
