### ISSUE TITLE
Containers created inside runner pods can't communicate with outside networks (i.e. internet/private rds instances)

### ISSUE THREAD

**Issue by gaspo53** [actions/actions-runner-controller#2101]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

0.21.1

### CertManager Version

1.10.1

### Deployment Method

Helm

### cert-manager installation

- Yes
- Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: songfinch-runnerdeploy
spec:
  template:
    spec:
      organization: songfinch
      env:
        - name: ARC_DOCKER_MTU_PROPAGATION
          value: "true"      
---

apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: songfinch-runnerdeploy-hpa
spec:
  scaleTargetRef:
    name: songfinch-runnerdeploy
  minReplicas: 1
  maxReplicas: 5
  scaleDownDelaySecondsAfterScaleOut: 400
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.3'
      scaleUpFactor: '1.4'
      scaleDownFactor: '0.7'
```

### To Reproduce

```markdown
1. Deploy controller and CRD
2. Trigger a GH Action having a step doing sleep 10000000, using a container that has telnet installed, or install manually
3. Exec into the runner pod and then exec into the container
4. Do a telnet against any service outside the pod
```

### Describe the bug

The containers created in the runner pod are not being configured with hostNetwork

### Describe the expected behavior

A container reaches outter networks

### Whole Controller Logs

```shell
none
```

### Whole Runner Pod Logs

```shell
none
```

### Additional Context

This is running on an EKS 1.24 Cluster
