### ISSUE TITLE
RunnerSet has dynamic name

### ISSUE THREAD

**Issue by navi86** [actions/actions-runner-controller#2103]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

latest

### Helm Chart Version

0.21.0

### CertManager Version

1.8

### Deployment Method

Helm

### cert-manager installation

yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: default-runner
spec:
  ephemeral: true
  organization: Test
  replicas: 1
    spec:
      containers:
        - env:
            - name: STARTUP_DELAY_IN_SECONDS
              value: '2'
            - name: DISABLE_WAIT_FOR_DOCKER
              value: 'false'
            - name: DISABLE_RUNNER_UPDATE
              value: 'true'
          name: runner
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          name: docker
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker
              subPathExpr: $(POD_NAME)
        volumes:
        - hostPath:
            path: /mnt/cache/docker
            type: DirectoryOrCreate
          name: docker
```

### To Reproduce

```markdown
create RunnerSet resource
```

### Describe the bug

stateful set created with dynamic string in the name
"default-runner-**kgd9h**-0"

### Describe the expected behavior

statefullset doesn't have dynamic string in the name:
"default-runner-0"

### Whole Controller Logs

```shell
none
```

### Whole Runner Pod Logs

```shell
none
```
