### ISSUE TITLE
Add enterprise to CRD

### ISSUE THREAD

**Issue by Sam-Lin-MillersLab** [actions/actions-runner-controller#2117]
### What would you like added?

currently there are organization and repository under spec>template>spec

It would be nice to have enterprise as well
```yml
                        organization:
                          pattern: ^[^/]+$
                          type: string
                        repository:
                          pattern: ^[^/]+/[^/]+$
                          type: string
```

Otherwise we can't set enterprise and got error message like "no repository/organizational/enterprise runner found" from the webhook

*A clear and concise description of what you want to happen.*

To make webhook autoscaler to find enterprise runners

*A clear and concise description of any alternative solutions or features you've considered.*

To make webhook autoscaler to find enterprise runners
