### ISSUE TITLE
Github sends a workflow_job completed webhook event for check runs attached to the Actions job which causes the webhook server to erroneously scale down by 2

### ISSUE THREAD

**Issue by nathanklick** [actions/actions-runner-controller#2118]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

0.21.1

### CertManager Version

1.10.1

### Deployment Method

ArgoCD

### cert-manager installation

- Yes, guide was followed.
- Yes, cert-manager was installed via the official helm chart.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  labels:
    argocd.argoproj.io/instance: swirlds-platform-linux-large
  name: swirlds-platform-linux-large
  namespace: swirlds-platform-linux-large
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    spec:
      ephemeral: true
      image: 'summerwind/actions-runner:ubuntu-20.04'
      imagePullPolicy: IfNotPresent
      labels:
        - self-hosted
        - Linux
        - large
        - ephemeral
      nodeSelector:
        arc-scheduling.io/os: linux
        arc-scheduling.io/size: xlarge
      repository: swirlds/swirlds-platform
      resources:
        limits:
          cpu: '8'
          memory: 32Gi
        requests:
          cpu: '4'
          memory: 16Gi
      tolerations:
        - effect: NoSchedule
          key: arc-scheduling.io/runners
          operator: Exists
        - effect: NoSchedule
          key: arc-scheduling.io/os
          operator: Equal
          value: linux
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  labels:
    argocd.argoproj.io/instance: swirlds-platform-linux-large
  name: swirlds-platform-linux-large-autoscaler
  namespace: swirlds-platform-linux-large
spec:
  maxReplicas: 50
  minReplicas: 0
  scaleTargetRef:
    kind: RunnerDeployment
    name: swirlds-platform-linux-large
  scaleUpTriggers:
    - duration: 30m
      githubEvent:
        workflowJob: {}
```

### To Reproduce

```markdown
1. Setup the webhook server.
2. Configure the repository to send a webhook for `workflow_job` events.
3. Create an actions workflow using a step like `EnricoMi/publish-unit-test-result-action@v2` which creates a check run attached to the Action workflow job.
4. Observe that Github sends the webhook server a `workflow_job` event with a status of completed when the check run is created. Note that the `runner_id`, `runner_name`, `runner_group_id`, and `runner_group_name` fields are all `null` json values.
5. Observe that Github sends a second `workflow_job` event when the Actions job completes. This time the `runner_*` fields are populated with non-null values.
6. Observe that the webhook server erroneously decremented the HRA `capacityReservations` by 2 instead of the correct value of 1.
```

### Describe the bug

When an Action step like `EnricoMi/publish-unit-test-result-action@v2` attaches a check run to the Workflow Job, Github sends a `workflow_job` webhook event with the status set to completed for the custom check run. This extra event has the `runner_id`, `runner_name`, `runner_group_id`, and `runner_group_name` fields set to a `null` json value. Additionally, the `steps` array is omitted from the payload. 

This causes the webhook server to erroneously update the HRA `capacityReservations` with a single decrement. Subsequently when the workflow job actually completes, Github sends another `workflow_job` event with a status of completed and the `steps`, `runner_id`, `runner_name`, `runner_group_id`, and `runner_group_name` fields are populated with non-null and non-empty values. The webhook server subsequently scales down the `capacityReservations` again by one.

This causes the webhook server to incorrectly scale the `capacityReservations` and thereby causes additional `workflow_job` events with the status of `queued` to not properly trigger the controller to spin up additional runner pods.

### Describe the expected behavior

The webhook server should ignore `workflow_job` events with a status of completed and where the `runner_id` is set to a `null` json value.

### Whole Controller Logs

```shell
- Controller Logs: https://gist.github.com/nathanklick/bff1b8b8b515427614d336ffdae70d95
- Webhook Server Logs: https://gist.github.com/nathanklick/9ba28dabe915c577aa92b2ec4d9a7e9f
```

### Whole Runner Pod Logs

```shell
Not applicable

- Webhook Payload Triggered by the Check Run:
   - https://gist.github.com/nathanklick/268fea6496a4d7b14cecb2999747ef84
-  Webhook Payload Triggered by the Actual Job Completion:
   - https://gist.github.com/nathanklick/837aa3c64b3520135b86a9e177a090fb 
```
