### ISSUE TITLE
TotalNumberOfQueuedAndInProgressWorkflowRuns not working

### ISSUE THREAD

**Issue by shichengripple001** [actions/actions-runner-controller#2122]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.21.1

### Helm Chart Version

0.21.1

### Deployment Method

Helm

### cert-manager installation

yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  annotations:
    meta.helm.sh/release-name: runnerset
    meta.helm.sh/release-namespace: repo-shichengripple001-xxx
  labels:
    app.kubernetes.io/managed-by: Helm
  name: xxx-runner-dind
  namespace: repo-shichengripple001-xxx
spec:
  replicas: 0
  selector: null
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: xxx-runner-dind
    spec:
      dockerEnabled: false
      dockerdContainerResources: {}
      dockerdWithinRunnerContainer: true
      ephemeral: true
      image: summerwind/actions-runner-dind
      imagePullSecrets:
      - name: docker
      labels:
      - self-hosted
      - xxx-runner-dind
      nodeSelector:
        x-heavy-runner: "true"
      repository: shichengripple001/xxx
      resources:
        limits:
          cpu: "15"
          memory: 59Gi
        requests:
          cpu: "15"
          memory: 59Gi
      securityContext:
        fsGroup: 20566
      tolerations:
      - key: x-heavy-runner
        operator: Exists
      volumeMounts:
      - mountPath: /runner
        name: work
      volumes:
      - emptyDir: {}
        name: work
      workDir: /runner

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  annotations:
    meta.helm.sh/release-name: runnerset
    meta.helm.sh/release-namespace: repo-shichengripple001-xxx
  labels:
    app.kubernetes.io/managed-by: Helm
  name: metrics-based-autoscaler
  namespace: repo-shichengripple001-xxx
spec:
  maxReplicas: 20
  metrics:
  - repositoryNames:
    - shichengripple001/xxx
    type: TotalNumberOfQueuedAndInProgressWorkflowRuns
  minReplicas: 0
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: xxxxx-runner-dind
```

### To Reproduce

```markdown
1. deploy the helm chart
2. create the runnerDeployment
3. trigger concurrent jobs in the repo
```

### Describe the bug

it is always show 0, I have job waiting to be picked up, but the controller logs says:
Suggested desired replicas of 0 by TotalNumberOfQueuedAndInProgressWorkflowRuns	{"workflow_runs_completed": 0, "workflow_runs_in_progress": 0, "workflow_runs_queued": 0, "workflow_runs_unknown": 0, "namespace": "repo-shichengripple001-xxx", "kind": "runnerdeployment", "name": "xxx-runner-dind", "horizontal_runner_autoscaler": "metrics-based-autoscaler"}

this is a fresh repo. I can confirm there is no earlier stuck job

### Describe the expected behavior

it should scale from 0

### Whole Controller Logs

```shell
2023-01-06T17:01:47Z	DEBUG	actions-runner-controller.horizontalrunnerautoscaler	Suggested desired replicas of 0 by TotalNumberOfQueuedAndInProgressWorkflowRuns	{"workflow_runs_completed": 0, "workflow_runs_in_progress": 0, "workflow_runs_queued": 0, "workflow_runs_unknown": 0, "namespace": "repo-shichengripple001-xxx", "kind": "runnerdeployment", "name": "xxx-runner-dind", "horizontal_runner_autoscaler": "metrics-based-autoscaler"}
2023-01-06T17:01:47Z	DEBUG	actions-runner-controll
```

### Whole Runner Pod Logs

```shell
N.A
```
