### ISSUE TITLE
Add ability to specify annotations in helm chart CRDs manifests

### ISSUE THREAD

**Issue by minhthong582000** [actions/actions-runner-controller#2125]
### What would you like added?

Currently in the actions-runner helm chart, we don't have any way to specify a custom annotations inside CRDs manifests. So I would like to add this feature by template it and move all of the CRDs manifests to `templates` folder.

For example:

```yaml
# ./templates/crds/actions.summerwind.dev_horizontalrunnerautoscalers.yaml
{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
    {{- if .Values.crds.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.crds.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: horizontalrunnerautoscalers.actions.summerwind.dev
...
{{- end }}
```

```yaml
# ./values.yaml
# Custom resource configuration
crds:
  # Install and upgrade CRDs
  install: true
  # Keep CRDs on chart uninstall
  keep: true
  # Annotations to be added to all CRDs
  annotations: {}
```

### Why is this needed?

I'm facing an issue with annotations size limitation (metadata.annotations: Too long: must have at most 262144 characters) when deploying the actions-runner-controller helm chart using ArgoCD. One way to fix this is using [server side apply](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply). And I know that I can specify this annotation in the ArgoCD Aplication. But I think it would be cleaner to specify `argocd.argoproj.io/sync-options: ServerSideApply=true` in the CRDs annotation.
