### ISSUE TITLE
Root Docker container exiting immediately on SIGTERM

### ISSUE THREAD

**Issue by dan0dbfe** [actions/actions-runner-controller#2151]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

0.21.1

### CertManager Version

1.10.1

### Deployment Method

Helm

### cert-manager installation

```bash
helm upgrade cert-manager jetstack/cert-manager \
--install \
--wait \
--create-namespace \
--namespace cert-manager \
--version "v1.10.1" \
--set installCRDs=true \
--set global.leaderElection.namespace=cert-manager
```

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dataworks-runner-deployment
  namespace: self-hosted-runners
spec:
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      ephemeral: false
      repository: ""
      resources:
        requests:
          cpu: 15
          memory: "56Gi"
          ephemeral-storage: "100Gi"
        limits:
          memory: "56Gi"
          ephemeral-storage: "100Gi"
      nodeSelector:
        pool: "worker-pool"
      terminationGracePeriodSeconds: 1830
      env:
        - name: RUNNER_GRACEFUL_STOP_TIMEOUT
          value: "1800"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
  namespace: self-hosted-runners
spec:
  scaleTargetRef:
    name: ""
  minReplicas: 4
  maxReplicas: 20
  scaleDownDelaySecondsAfterScaleOut: 1800
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - ""
```

### To Reproduce

```markdown
Wait for runners to scale down
```

### Describe the bug

Job terminates unexpectedly with error code `137` even though RAM usage is far from pod memory limit.

From the logs it seems that the docker sidecar is receiving `SIGTERM` and terminates immediately. This caused the job to terminate.

The runner container could not find a running docker sidecar when processing `SIGTERM` and logged a configuration error, however I don't know what other configuration I should have done.

docker container log shows:
```
time="2023-01-13T00:35:04.282194874Z" level=info msg="Processing signal 'terminated'"
```

Runner container log shows:
```
2023-01-13 00:35:04.283 NOTICE --- Executing actions-runner-controller's SIGTERM handler.
2023-01-13 00:35:04.283 WARNING --- Detected configuration error: dockerd should be running but is already nowhere. This is wrong. Ensure that your init system to NOT pass SIGTERM directly to dockerd!
```

### Describe the expected behavior

Job container to not terminate while it is still running, up to grace period of `1800` seconds as configured.

### Whole Controller Logs

```shell
https://gist.github.com/dan0dbfe/63b62a8090e7d1a8a46694e7c86a2f71
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/dan0dbfe/d3423c2de3766262499a61ccdd84f469
```
