### ISSUE TITLE
Ssh-keygen not presented

### ISSUE THREAD

**Issue by sspakush** [actions/actions-runner-controller#2152]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

2.300.2

### Helm Chart Version

v0.21.0

### CertManager Version

1.9.1

### Deployment Method

Helm

### cert-manager installation

yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
spec:
  organization: org
  dockerEnabled: true
  dockerMTU: 1300
#  dockerdWithinRunnerContainer: true
  labels:
    - docker-runner
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: runners
  serviceName: runners
  template:
    metadata:
      labels:
        app: runners
```

### To Reproduce

```markdown
add action with ssh keys
```

### Describe the bug

We use an actions with ssh-keygen.
After migration to runners v2.300.2  we face a problem: "Error: Unable to locate executable file: ssh-keygen. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable."

### Describe the expected behavior

I believe that need to add ssh-keygen package

### Whole Controller Logs

```shell
Logs in controller are of no interest
```

### Whole Runner Pod Logs

```shell
Logs in controller are of no interest
```

### Additional Context

Github action log:
Error: Error: Unable to locate executable file: ssh-keygen. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
