### ISSUE TITLE
How to stop scaling runners if already some free runners are available <Please write what didn't work for you here>

### ISSUE THREAD

**Issue by roshvin** [actions/actions-runner-controller#2191]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.0

### Helm Chart Version

0.22.0

### CertManager Version

latest

### Deployment Method

Helm

### cert-manager installation

yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
   name: ent-runner-auto-scaller
spec:
  scaleDownDelaySecondsAfterScaleOut: 5
  scaleTargetRef:
    name: dot-free-runner
    kind: RunnerSet
  minReplicas: 10
  maxReplicas: 50
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
``
```

### To Reproduce

```markdown
even we have free runners , ARC will scale runners till 50 

how we can check and stop scaling if there is already free runners available.
```

### Describe the bug

even we have free runners , ARC will scale runners till 50 

how we can check and stop scaling if there is already free runners available. 

### Describe the expected behavior

ARC should not be adding more runners if already free runners are available. 

### Whole Controller Logs

```shell
ARC should not be adding more runners if already free runners are available.
```

### Whole Runner Pod Logs

```shell
ARC should not be adding more runners if already free runners are available.
```
