### ISSUE TITLE
mount volume inside container

### ISSUE THREAD

**Issue by navi86** [actions/actions-runner-controller#2246]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

default from chart

### Helm Chart Version

0.22.0

### Deployment Method

Helm

### cert-manager installation

-

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: default-runner
spec:
  ephemeral: true
  labels:
    - default
  replicas: 1
  selector:
    matchLabels:
      app: gha-runnerset
  serviceName: gha-runnerset
  template:
    metadata:
      labels:
        app: gha-runnerset
    spec:
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STARTUP_DELAY_IN_SECONDS
              value: '2'
            - name: DISABLE_WAIT_FOR_DOCKER
              value: 'false'
            - name: DISABLE_RUNNER_UPDATE
              value: 'true'
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  key: VAULT_ROLE_ID
                  name: github-actions-runner-runner
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  key: VAULT_SECRET_ID
                  name: github-actions-runner-runner
          name: runner
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
          volumeMounts:
            - mountPath: /runner/_work/bundle
              name: cache-bundle
      securityContext:
        fsGroup: 1000
      volumes:
        - hostPath:
            path: /mnt/ci-cache/bundle
            type: DirectoryOrCreate
          name: cache-bundle
```

### To Reproduce

```markdown
deploy runnerset, create a pod and check permissions of mounted folder. permissions are:
drwxr-xr-x 3 runner docker 4096 Jan 17 16:20 bundle
```

### Describe the bug

volume should be mounted as runner:runner, so this allows to mount it to nested pod.

### Describe the expected behavior

-

### Whole Controller Logs

```shell
-
```

### Whole Runner Pod Logs

```shell
-
```
