### ISSUE TITLE
RunnerSet pods are not coming up 

### ISSUE THREAD

**Issue by Navnitkumarbarnwal** [actions/actions-runner-controller#2331]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

v0.26.0

### Helm Chart Version

3.x

### Deployment Method

Helm

### cert-manager installation

https://josh-ops.com/posts/actions-runner-controller-without-cert-manager/

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: persistent-runner
  namespace: actions-runner-system
spec:
  organization: myorg
  replicas: 2
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: persistent-runner
  serviceName: persistent-runner
  template:
    metadata:
      labels:
        app: persistent-runner
    spec:
      containers:
        - name: docker
          volumeMounts:
            - mountPath: /var/lib/docker
              name: persistent-runner-data
  volumeClaimTemplates:
    - metadata:
        name: persistent-runner-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
```

### To Reproduce

```markdown
please deploy using above yaml
```

### Describe the bug

I am not able to see new pods coming while using the runner set 
though if i use runnerdeployment kind i am able to use and new pods are coming up 
below i am attaching the image for the same

<img width="1279" alt="Screenshot 2023-02-27 at 5 19 24 PM" src="https://user-images.githubusercontent.com/113497931/221557271-288d86a6-b779-4aaf-8bab-0e4a06bb07a5.png">

### Describe the expected behavior

I expect a new set of pods

### Whole Controller Logs

```shell
controller.runnerpersistentvolumeclaim	Retrying sync until statefulset gets removed	{"pvc": "actions-runner-system/persistent-runner-data-persistent-runner-p65qq-0", "requeueAfter": "10s"}
2023-02-27T11:55:08Z	DEBUG	actions-runner-controller.runnerpersistentvolumeclaim	Retrying sync until statefulset gets removed	{"pvc": "actions-runner-system/persistent-runner-data-persistent-runner-knmxs-0", "requeueAfter": "10s"}
2023-02-27T11:55:18Z	DEBUG	actions-runner-controller.runnerpersistentvolumeclaim	Retrying sync until statefulset gets removed	{"pvc": "actions-runner-system/persistent-runner-data-persistent-runner-p65qq-0", "requeueAfter": "10s"}
2023-02-27T11:55:18Z	DEBUG	actions-runner-controller.runnerpersistentvolumeclaim	Retrying sync until statefulset gets removed	{"pvc": "actions-runner-system/persistent-runner-data-persistent-runner-knmxs-0", "requeueAfter": "10s"}
```

### Whole Runner Pod Logs

```shell
No pods
```
