### ISSUE TITLE
Random Operation `Cancelled` or `Stuck` or Failed

### ISSUE THREAD

**Issue by Zheer09** [actions/actions-runner-controller#2376]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.0

### Helm Chart Version

0.22.0

### CertManager Version

v1.5.3

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  # if you rename this, don't forget to rename in topologySpreadConstraints as well
  name: runner
  namespace: github-actions
spec:
  replicas: 10
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              runner-deployment-name: runner
      dockerdWithinRunnerContainer: true
      organization: org-name
      group: Default
      labels:
        - k8s-runner
      serviceAccountName: github-actions-runner
      resources:
        limits:
          cpu: 15
          memory: 32Gi
        requests:
          cpu: 128m
          memory: 256Mi
      volumes:
        - name: cert
          secret:
            secretName: cert
      volumeMounts:
        - mountPath: "/usr/local/share/ca-certificates"
          name: cert
          readOnly: true
```

### To Reproduce

```markdown
Run our repository workflow
```

### Describe the bug

On the smaller workflow , or workflow that doesn't take so much time there is no issue but with others workflow either the runner will canceled randomly or failed or stuck until it timeout.

### Describe the expected behavior

Expected to run the jobs without canceling or stuck or failed , i expect to run the job in slower because of the limit for CPU but not failing. 

### Whole Controller Logs

```shell
https://gist.github.com/Zheer09/106cce713e985d59ee37ec2ec6e7b190
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/Zheer09/6c0cea25bf01deb32cec66ddcd32b1cc
```
