### ISSUE TITLE
apt does not have a stable cli interface / can't locate package during github action run

### ISSUE THREAD

**Issue by ghost** [actions/actions-runner-controller#2415]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27

### Helm Chart Version

0.22

### CertManager Version

1.5.3

### Deployment Method

Helm

### cert-manager installation

cert-manger was already installed on default namespace

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
spec:
  template:
    spec:
      image: ghcr.io/actions-runner-controller/actions-runner-controller/actions-runner:v2.303.0-ubuntu-22.04-3417c5a 
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      repository: my-org/my-repo
      labels:
        - linux
        - X64
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: runner-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - my-org/my-repo
```

### To Reproduce

```markdown
Run the action with the actions-runner:v2.303.0-ubuntu-22.04-3417c5a image
```

### Describe the bug

All controller and runner pods are running fine. I am also able to see the runners under my github-repo / actions / runners. Github-action is giving me following error : 

![Bildschirm­foto 2023-03-16 um 11 47 59](https://user-images.githubusercontent.com/121792205/225596520-a0b3e3ac-9878-4bfa-9d3c-01bbcb5183ad.png)

i have tried using different runner images in my custom resource definition. I would be really happy if someone could point me in the right direction how to solve this issue. 

### Describe the expected behavior

run the action properly

### Whole Controller Logs

```shell
no errors
```

### Whole Runner Pod Logs

```shell
no errors
```
