### ISSUE TITLE
Add support for Affinity and Tolerations on runner scale set

### ISSUE THREAD

**Issue by leadelngalame1611** [actions/actions-runner-controller#2434]
### What would you like added?

Configure the actions runner helm chart to allow runner scale set inherits its affinity and tolerations from the runner scale set controller

### Why is this needed?

We do have dedicated kubernetes node groups for our action runner and use tolerations and affinity to allow runners to run on the correct group of nodes. Currenty only the runner scale set controller runs on a dedicated node because we can set affinity and toleration in the values.yaml file. 

The runner scale set on the other hand do not have  affinity and toleration settings causing them to be deployed on non dedicated nodes.

**Comment by christianherweg0807** [comment]
Agree, we run 2 different types of the runner: "x64" & "arm64". Without affinity we are not able to route a arm runner to the correct k8s node.

**Comment by jschwanz** [comment]
I'm running 0.4.0 and was hitting the same issue. On a whim I added my desired entries for `template.spec.nodeSelector` and `template.spec.tolerations` to my Runner Scale Set values.yaml, and it worked. I can't find any documentation on this, so YMMV.

**Comment by nikola-jokic** [comment]
That is the correct approach @jschwanz :relaxed: 
The idea of the template field is to be able to customize runners anyway you see fit. However, I don't think the autoscaling runner set should inherit the spec from the controller. The controller is meant to run many autoscaling runner sets, so the configuration should be defined per autoscaling runner set, not per controller.

Also, you might have issues customizing the listener pod until [this PR](https://github.com/actions/actions-runner-controller/pull/2758) is merged and released

**Comment by mthemis-provenir** [comment]
For anyone finding this on Google, it appears this is still not resolved when trying to use a separate namespace for your controller than your runners when using ArgoCD. Tried all of the solutions in this thread and more but no luck, so sticking with OpenTofu and the Helm provider.

**Comment by asinitson** [comment]
Hello good people coming here from search engines! Since documents for this are very sparse, I am leaving here the `values.yaml` for version 0.9.3 which worked for me (we don't use selector, but instead taint all node pools and apply toleration on every deployment, but you can use selectors instead in a similar fashion):

* For controller
```yaml
# https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/values.yaml
tolerations: 
  - key: "CriticalAddonsOnly" # <------------ Use non-scalable node pool here (we use `system` pool in AKS for that)
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

```
* For runners
```yaml
# https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
githubConfigSecret:
  github_token: ${github_token}

githubConfigUrl: "https://github.com/organization" # Organization level runners (instead of repo-level)

containerMode:
  type: "dind" # Docker support

template:
  spec:
    tolerations: 
      - key: "purpose"
        operator: "Equal"
        value: "runners" # <----------- Use scalable pool here to scale down/up aggressively without affecting controller or listener
        effect: "NoSchedule"

listenerTemplate:
  spec:
    containers: # <------------- Without these two lines Helm will refuse applying your values
      - name: listener # <------ and will consider spec invalid.
    tolerations:
      - key: "CriticalAddonsOnly": # <------------ Use non-scalable node pool here (we use `system` pool in AKS for that)
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

```
Hopefully this will help someone.
