### ISSUE TITLE
Containers are missing in AutoscalingRunnerSet specs

### ISSUE THREAD

**Issue by bangnh1** [actions/actions-runner-controller#2440]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

gha-runner-scale-set-controller:0.3.0

### Helm Chart Version

controller chart version 0.3.0

### CertManager Version

1.11.0

### Deployment Method

Helm

### cert-manager installation

Helm install used

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
gha-runner-scale-set value.yaml as below:

githubConfigUrl: https://github.com/actions/actions-runner-controller
githubConfigSecret:
  github_token: test

template:
  spec:
    containers:
    - name: runner
      image: runner-image:latest
      env:
      - name: SOME_ENV
        value: SOME_VALUE
      - name: MY_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      volumeMounts:
      - name: work
        mountPath: /work
      - name: others
        mountPath: /others
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
    - name: other
      image: other-image:latest
      volumeMounts:
      - name: work
        mountPath: /work
      - name: others
        mountPath: /others
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
    volumes:
    - name: work
      hostPath:
        path: /data
        type: Directory
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - 192.0.2.1
containerMode:
  type: none
```

### To Reproduce

```markdown
NAMESPACE="arc-systems"

  helm install --timeout 5m --wait arc \
      --namespace "${NAMESPACE}" \
      --create-namespace \
      ./deployments/helm/platforms/arc-systems/gha-runner-scale-set-controller-0.3.0.tgz \
      --values ./deployments/helm/platforms/arc-systems/values.yaml

  helm upgrade --install --timeout 5m --wait 8-32-runner-set \
      ./deployments/helm/platforms/arc-systems/gha-runner-scale-set-0.3.0.tgz \
      --values ./deployments/helm/platforms/arc-systems/8-32-runner-set/values.yaml
```

### Describe the bug

Some containers are missing in AutoscalingRunnerSet specs, for example: container 'runner' disappeared as below manifest.
k get AutoscalingRunnerSet 8-32-runner-set -o yaml

spec:
  githubConfigSecret: test
  githubConfigUrl: https://github.com/actions/actions-runner-controller
  maxRunners: 5
  minRunners: 0
  runnerScaleSetName: 8-32-runner-set
  template:
    spec:
      containers:
      - env:
        - name: SOME_ENV
          value: SOME_VALUE
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: other-image:latest
        name: other
        resources:
          limits:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
        - mountPath: /work
          name: work
        - mountPath: /others
          name: others
      dnsConfig:
        nameservers:
        - 192.0.2.1
      dnsPolicy: None
      serviceAccountName: 8-32-runner-set-gha-runner-scale-set-no-permission-service-account
      volumes:
      - hostPath:
          path: /data
          type: Directory
        name: work

### Describe the expected behavior

AutoscalingRunnerSet specs have enough containers.

### Whole Controller Logs

```shell
null
```

### Whole Runner Pod Logs

```shell
null
```
