### ISSUE TITLE
Can not connect to docker daemon when running rootless dind sidecar

### ISSUE THREAD

**Issue by erypolovina** [actions/actions-runner-controller#2446]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

actions-runner-controller-0.21.0

### Deployment Method

Helm

### cert-manager installation

Manually created a custom cert and mounted it as a secret

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: github-actions-runnerset-dependabot
  namespace: github-actions-runner
  labels:
    app: github-actions-runnerset-dependabot
    component: dependabot
    managed-by: terraform
    repository: github-enterprise
spec:
  replicas: 1
  enterprise: <GHES enterprise name>
  #organization: test-github
  labels:
    - dependabot
  serviceName: github-actions-runnerset-dependabot
  ephemeral: true
  # dockerdWithinRunnerContainer: true
  selector:
    matchLabels:
      app: github-actions-runnerset-dependabot
  template:
    metadata:
      labels:
        app: github-actions-runnerset-dependabot
        component: dependabot
        managed-by: terraform
        repository: github-enterprise
    spec:
      containers:
        - name: runner
          env:
            - name: RUNNER_FEATURE_FLAG_EPHEMERAL
              value: "true"
            - name: RUNNER_EPHEMERAL
              value: "true"
          volumeMounts:
            - name: artifactory-credentials
              mountPath: /home/runner/.docker/
            # - name: github-actions-var-lib-docker
            #   mountPath: /home/runner/.local/share/docker/
            # - name: var-lib-docker
            #   mountPath: /var/lib/docker
        - name: docker
          volumeMounts:
            - name: github-actions-var-lib-docker
              mountPath: /var/lib/docker
      volumes:
        - name: artifactory-credentials
          secret:
            secretName: artifactory-credentials
            items:
              - key: .dockerconfigjson
                path: config.json
      nodeSelector:
        dedicated: cicd
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: cicd
  volumeClaimTemplates:
    - metadata:
        name: github-actions-var-lib-docker
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: github-actions-runner-pd-ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: github-actions-runner-pd-ssd
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

### To Reproduce

```markdown
1. Change `actionsRunnerRepositoryAndTag` in values.yml to `actionsRunnerRepositoryAndTag: "hub.docker.com/summerwind/actions-runner-dind-rootless:latest"`
1. Apply the changes
1. Apply the RunnerSet described above

At this point, docker runs in the container and I can connect to it when sshing into the runner, but when my actions tries to run a dependabot job, it will throw


Some required dependencies were not installed, please ensure the following issues are resolved and try again:
Error: Cannot connect to docker. Make sure docker is running and accessible by the actions runner.
Error: Process completed with exit code 1.
```

### Describe the bug

When using rootless runners with a docker sidecar container, docker runs inside the container and sshing into the runner shows docker is running, but when running a job (dependabot job in my case) the actions run errors out when running a check to see if docker is reachable and pulling any images results in an error.

This behaviour does not occur when running the job using a rootful container. 

Docker seems to work with rootless containers if `dockerdWithinRunnerContainer: true` but slow when pulling images as the storage driver is VFS and on rootful containers its overlay2.

### Describe the expected behavior

If docker is installed and running in the runner pod, the job should be able to access the docker agent and successfully run.

### Whole Controller Logs

```shell
https://gist.github.com/erypolovina/3d0dccea3e6984f0d7f42925defefdf8
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/erypolovina/3d0dccea3e6984f0d7f42925defefdf8
```

### Additional Context

Not sure if this can be addressed here, but is it expected that using docker within the runner container uses VFS storage driver over overlay2?
