### ISSUE TITLE
Multitenancy attempts to parse app/install IDs even with a token present

### ISSUE THREAD

**Issue by sthomson-wyn** [actions/actions-runner-controller#2462]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.1

### Helm Chart Version

0.23.0

### CertManager Version

1.5.4

### Deployment Method

Helm

### cert-manager installation

Confirmed

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: my-runner
  namespace: actions-runner-system
spec:
  githubAPICredentialsFrom:
    secretRef:
      name: controller-manager
  maxReplicas: 20
  metrics:
    - scaleDownFactor: "0.7"
      scaleDownThreshold: "0.3"
      scaleUpFactor: "1.1"
      scaleUpThreshold: "0.75"
      type: PercentageRunnersBusy
  minReplicas: 1
  scaleTargetRef:
    name: my-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - github-actions
              weight: 100
      enterprise: wynshop
      ephemeral: true
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      labels:
        - my-linux-stg
---
apiVersion: v1
kind: Secret
metadata:
    name: controller-manager
    namespace: actions-runner-system
stringData:
    github_token: <redacted>
type: Opaque
```

### To Reproduce

```markdown
Install the CRDs above
```

### Describe the bug

HorizontalRunnerAutoscaler encounters an error

### Describe the expected behavior

{
    "name": "wynshop-runner",
    "controllerKind": "HorizontalRunnerAutoscaler",
    "HorizontalRunnerAutoscaler": {
      "name": "my-runner",
      "namespace": "actions-runner-system"
    },
    "ts": "2023-03-31T15:58:37Z",
    "controller": "horizontalrunnerautoscaler-controller",
    "message": "Reconciler error",
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235",
    "controllerGroup": "actions.summerwind.dev",
    "error": "strconv.ParseInt: parsing \"\": invalid syntax",
    "reconcileID": "8f24ff87-4ebf-4e9c-8378-e073c4c4d400",
    "namespace": "actions-runner-system"
  }

### Whole Controller Logs

```shell
{
    "name": "wynshop-runner",
    "controllerKind": "HorizontalRunnerAutoscaler",
    "HorizontalRunnerAutoscaler": {
      "name": "my-runner",
      "namespace": "actions-runner-system"
    },
    "ts": "2023-03-31T15:58:37Z",
    "controller": "horizontalrunnerautoscaler-controller",
    "message": "Reconciler error",
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235",
    "controllerGroup": "actions.summerwind.dev",
    "error": "strconv.ParseInt: parsing \"\": invalid syntax",
    "reconcileID": "8f24ff87-4ebf-4e9c-8378-e073c4c4d400",
    "namespace": "actions-runner-system"
  }
```

### Whole Runner Pod Logs

```shell
n/a, pod did not scale
```

### Additional Context
This is because the controller attempts to parseInt github_app_id and github_app_installation_id even if github_token is present

This can be currently resolved by setting

          github_app_id: "0"
          github_app_installation_id: "0"

in your secret

PR incoming
