### ISSUE TITLE
Bump helm chart version for ARC 0.27.2

### ISSUE THREAD

**Issue by elocke** [actions/actions-runner-controller#2469]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.2

### Helm Chart Version

0.23.0

### Deployment Method

Helm

### cert-manager installation

Yes.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: v2
name: actions-runner-controller
description: A Kubernetes controller that operates self-hosted runners for GitHub Actions on your Kubernetes cluster.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.23.0

# Used as the default manager tag value when no tag property is provided in the values.yaml
appVersion: 0.27.1

home: https://github.com/actions/actions-runner-controller

sources:
  - https://github.com/actions/actions-runner-controller

maintainers:
  - name: actions-runner-controller
    url: https://github.com/actions-runner-controller
```

### To Reproduce

```markdown
N/A
```

### Describe the bug

Chart and App should be upgraded for 0.27.2

### Describe the expected behavior

Helm chart can be installed for ARC 0.27.2

### Whole Controller Logs

```shell
N/A
```

### Whole Runner Pod Logs

```shell
N/A
```
