### ISSUE TITLE
Workflow stuck running for 5 days with failed cancellation and error message

### ISSUE THREAD

**Issue by NLadib-PartnerAuchan** [actions/actions-runner-controller#2471]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.21.1

### Helm Chart Version

0.26.0

### CertManager Version

v1.10.0

### Deployment Method

Helm

### cert-manager installation

Yes, I follow the https://github.com/actions/actions-runner-controller/blob/master/docs/installing-arc.md

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: orga-runner
  namespace: actions-runners
spec:
  template:
    spec:
      labels:
        - Linux
        - X64
        - self-hosted
      organization: orga
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: orga
  namespace: actions-runners
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    name: orga-runner
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'    # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
    scaleDownThreshold: '0.3'   # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
    scaleUpAdjustment: 2        # The scale up runner count added to desired count
    scaleDownAdjustment: 1      # The scale down runner count subtracted from the desired count
```

### To Reproduce

```markdown
We are facing an issue with our GitHub Actions workflow, where it appears to be running indefinitely without adding the status of completion to the workflow.

Our runners are functioning correctly, but the workflow stays running in the void without showing any progress. We have verified that there are no failed or running steps in the workflow.

We have tried to cancel the workflow, but we receive an error message stating "Failed to cancel the workflow." Additionally, we have checked for any errors in the logs, but we did not find any.

We suspect that this issue may be related to the GitHub platform, as we have not made any recent changes to our workflow configuration.

We would appreciate your help in resolving this issue as it is causing delays in our development process. Please let us know if there is any additional information needed from our end to diagnose and fix this issue.

Thank you for your assistance.
```

### Describe the bug

We are experiencing an issue with our GitHub Actions workflow, which has been stuck running for 5 days. 
![image](https://user-images.githubusercontent.com/107919589/229708227-bce72713-5e7d-4a3e-8f77-98b5e0dc9fe7.png)

The workflow has no failed or running steps, and we cannot cancel it as we receive the message "Failed to cancel the workflow."
![image](https://user-images.githubusercontent.com/107919589/229709154-d77b209b-9b0b-4f69-a050-c74ca752d632.png)

We have attached a screenshot of the workflow showing the long-running duration and another screenshot showing the absence of any failed or running steps. Additionally, there is an error message under our workflow, which appears after the long-running duration.
![image](https://user-images.githubusercontent.com/107919589/229709387-09075c32-be99-4b13-b22c-7da8057414aa.png)

We suspect that this issue may be related to the recent GitHub incident (https://www.githubstatus.com/incidents/z3c6q056q332), which occurred around the same time.

We would appreciate any support or guidance on how to resolve this issue and prevent similar incidents from occurring in the future.

Thank you for your help.

### Describe the expected behavior

The GitHub Actions workflow should complete with either a success or failure status, which should be reflected in the workflow run page. The logs should be available for debugging purposes, providing information on the root cause of any failure.

### Whole Controller Logs

```shell
We do have logs on the actions controller regarding this execution where the logs on the actions controller do not show any failures.
```

### Whole Runner Pod Logs

```shell
We have checked the Kubernetes cluster logs and confirmed that the pod responsible for running the workflow was terminated abruptly, and we suspect that this may have caused the absence of logs in the actions controller.

As a result, we are unable to determine the root cause of the failure or identify any issues that may have occurred during the workflow execution.
```
