### ISSUE TITLE
Warm cache on runner init / runner idle

### ISSUE THREAD

**Issue by malt3** [actions/actions-runner-controller#2484]
### What would you like added?

I want to use stateful runners with autoscaling.
I want to specify custom commands that are run in the pod (with access to the pods mounts / volumes) before the runner registers with github or from time to time when it's idling that are used to warm up caches for build actions. (Bazel in my case but this probably applies to other build systems / actions as well).

### Why is this needed?

I want to have a small amount of runners always available. However, those runners should not only be available but also have a warm cache. The same applies while scaling up: if a fresh runner becomes available, I want it to have a baseline of pre-caching.
If runners are not used for some time, their caches will be stale so I would either like to re-run the cache warming or replace runners if they are idle for some amount of time.

### Additional context

n/a

**Comment by mumoshu** [comment]
Hey @malt3! Thanks for reporting.

I believe this is where our RunnerSet becomes useful.

RunnerSet is based in K8s StatefulSet and hence has the ability to reuse PVs. Instead of pre-warming, which can be complex to implement, every stateful runner pod which RunnerSet brings up always tries to remount the previously used/cache-populated PV. This doesn't require you to fork our runner image or introduce another ARC subsystem for caching.

To be clear, I believe pre-warming doesn't provide any meaningful benefit in this case. In terms of the first job run, you'll either need the pre-wraming process you mentioned to do a full cache population, or RunnerSet-managed pod starts running the job immediately and that results in the cache being populated on the PV for reuse. So... the time required to complete the first job is same.

For second job runs, the pre-warming enables you to move the time required for updating the cache to the pre-job-run. If the job is run on a RunnerSet-managed, the cache update would take the same time as the pre-warming, and the only difference would be that the cache update is done as a part of the Bazel run.

If you really need to ensure that  the cache is fully up-to-date 99% of time it runs a new job, I would just create a workflow definition that periodically runs bazel builds on many runners (I would use a matrix job for that)] along with RunnerSet. This will update the cache and recreates idle runners, because runners managed by ARC are one-off by default.

**Comment by alec-drw** [comment]
@mumoshu regarding the PV cache - where should it be mounted for the runner to use it between jobs?

**Comment by malt3** [comment]
> where should it be mounted for the runner to use it between jobs?

<strike>I'm still trying this and did not find a configuration that caches things correctly</strike> but I believe for a default bazel configuration, `/home/runner/.cache/bazel` would be the directory to cache.
If you also specify `--disk_cache` or `--repository_cache` in your bazelrc, those paths should also be cached.

My `.bazelrc` includes this:

```
build --disk_cache=~/.cache/shared_bazel_action_cache
build --repository_cache=~/.cache/shared_bazel_repository_cache
```

And I simply mount `/home/runner/.cache`.

EDIT: I managed to get this working! Here is my `RunnerSet` definition:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: test-runner
  namespace: test-runner
spec:
  ephemeral: true
  image: ghcr.io/malt3/actions-runner-bazel:v6.1.2-0
  replicas: 5
  repository: malt3/arc-test
  selector:
    matchLabels:
      app: test-runner
  serviceName: test-runner
  template:
    metadata:
      labels:
        app: test-runner
    spec:
      containers:
      - name: runner
        volumeMounts:
        - mountPath: /home/runner/.cache
          name: bazel-cache
  volumeClaimTemplates:
  - metadata:
      name: bazel-cache
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: bazel-cache
```

And here is the storage class (local-path is maybe not what you want in production):

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: bazel-cache
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```
