### ISSUE TITLE
Interrupted system call when setting up a job

### ISSUE THREAD

**Issue by shankarRaman** [actions/actions-runner-controller#2494]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.25.2

### Helm Chart Version

0.20.2

### Deployment Method

Helm

### cert-manager installation

We use an existing cert-manager for managing certs

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdep
spec:
  template:
    spec:
      imagePullSecrets:
        - name: imagePullSecret
      image: summerwind/actions-runner-dind:v2.303.0-ubuntu-20.04
      imagePullPolicy: Always
      organization: test
      labels:
        - runner
      group: Runner
      dockerdWithinRunnerContainer: true
      resources:
        limits:
          memory: 8Gi
        requests:
          cpu: "0.25"
          memory: 1Gi
      env:
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
```

### To Reproduce

```markdown
Any normal code check in. The workflow is triggered and picked up the runner.
```

### Describe the bug

We get this error when setting up the job after an action has been downloaded and tried to copy the action the `/runner/_work/_actions/` folder
Error: Interrupted system call
##[debug]System.IO.IOException: Interrupted system call
##[debug]   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
##[debug]   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo, String destDirectory)
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
##[debug]   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
##[debug]Finishing: Set up job

### Describe the expected behavior

The action is downloaded and copied to the necessary folder and proceeds to the next step in the job. 
FYI - on subsequent attempt, the step passes. However this UX is very frustrating. 

### Whole Controller Logs

```shell
https://gist.github.com/shankarRaman/896f960266505bbeecf3925002902305#file-arc-log
```

### Whole Runner Pod Logs

```shell
Not available since the pod got terminated
```
