### ISSUE TITLE
Workflow job run duration metric shows wrong value if the job was canceled before it was started

### ISSUE THREAD

**Issue by serhij-matvejev** [actions/actions-runner-controller#2506]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.2

### Helm Chart Version

0.23.1

### CertManager Version

1.9.1

### Deployment Method

Helm

### cert-manager installation

Cert manager was installed using the official helm chart from the jetstack repository.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: ga-runner-deployment-default-test-poc
  namespace: system-actions-runner
spec:
  labels:
  - test-poc
  selector:
    matchLabels:
      type: test-poc
  dockerdWithinRunnerContainer: true
  organization: #######
  serviceName: test-poc
  template:
    metadata:
      labels:
        type: test-poc
    spec:
      containers:
      - name: runner
        image: summerwind/actions-runner-dind:v2.303.0-ubuntu-20.04-3417c5a
        resources:
          limits:
            cpu: 2
            memory: 7Gi
          requests:
            cpu: 2
            memory: 7Gi
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: github_actions
      nodeSelector:
        apps: github-actions-runners
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  namespace: system-actions-runner
  name: ga-runner-deploy-autoscaler-default-test-poc
spec:
  scaleTargetRef:
    kind: RunnerSet
    name: ga-runner-deployment-default-test-poc
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    amount: 1
    duration: "5m"
  minReplicas: 1
  maxReplicas: 1
```

### To Reproduce

```markdown
1. Scale down your runners to 1;
2. Run two simple workflow runs (workflow jobs) that runs sleep 60 in a step;
3. Wait until one of workflows will be started on the runner;
4. Cancel second job which was not manage to start on the runner (waited in a queue);
5. Check the github_workflow_job_run_duration_seconds_sum metric value of your job - you will find it by job_conclusion="cancelled".
6. Check the actions-metrics-server /metrics endpoint. You will see giant value of your job run duration. Something like 9.223372036854776e+09 after the first try.
```

### Describe the bug

It seems we have a bug in a `actions-metrics-server` component.

It generates wrong value of the `github_workflow_job_run_duration_seconds_sum` metric if the job was queued but canceled before it started on some of runners.

It could happen if you have all of your runners are busy by other workflow jobs and one of queued jobs cancelled by user. So the job never started, but the metrics server increases the value of `github_workflow_job_run_duration_seconds_sum` belong for the cancelled workflow_job by some giant value.
In my case this is 9.223372036854776e+09. The job could be found by `job_conclusion="cancelled"` label.

![image](https://user-images.githubusercontent.com/52668029/231487711-ef46a1a5-0606-44a3-b0d5-e46a26836b6f.png)

Events of queued but not started (cancelled) job that goes from the GitHub to the metrics-server:

- workflow_run `requested`;
- workflow_job `queued`;
- workflow_run `in_progress`. It has `workflow_run.status: in_progress` and `workflow_run.conclusion: cancelled`;
- workflow_job `completed`.  It has `workflow_job.status: in_progress` and `workflow_job.conclusion: cancelled`.

It is easy to reproduce.
Scale down runners to 1 and start two separate workflow runs (workflow job). These workflows should have a `sleep 60` or something like that to let second job wait for the runner. Once you start these two jobs, just cancel one of them from the UI.

So your first workflow_job goes through the event `workflow_job.in_progress` with "status": "in_progress"`, and `"conclusion": null,`. But second workflow_job event will not have `in_progress` in action, but `completed` - never started on a runner. 

I am not sure where the problem is, it might be [here](https://github.com/actions/actions-runner-controller/blob/v0.27.2/pkg/actionsmetrics/event_reader.go#L156-L157) or [there](https://github.com/actions/actions-runner-controller/blob/v0.27.2/pkg/actionsmetrics/event_reader.go#L270) and [there](https://github.com/actions/actions-runner-controller/blob/v0.27.2/pkg/actionsmetrics/event_reader.go#L283) or somewhere else. I expect there is no start time in logs so may be some kind of conditions needs to be added.

### Describe the expected behavior

I would expect that `github_workflow_job_run_duration_seconds_sum` metric will not be increased if the workflow job did not manage to run - when the metrics server never receive `workflow_job` event with `in_progress` status. Or if the job logs are blank or have no start time.

### Whole Controller Logs

```shell
https://gist.github.com/serhij-matvejev/1c56de86ddf9d00ccc0a4474ac6f9f41
```

### Whole Runner Pod Logs

```shell
Metrics server topic. The job never started on a runner. So there are no runner logs available.
```
