### ISSUE TITLE
github workflows with  schedule triggering cause HorizontalRunnerAutoscaler to set desired replica much higher then needed

### ISSUE THREAD

**Issue by Tal-E** [actions/actions-runner-controller#2526]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.2

### Helm Chart Version

0.23.2

### CertManager Version

1.6.0

### Deployment Method

Helm

### cert-manager installation

Yes to all questions related to cert manager

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-ci-runner-2xlarge
  namespace: actions
spec:
  template:
    spec:
      nodeSelector:
        node-type: jobs
      repository: test/test
      labels:
        - eks-github-ci-runner-2xlarge
      resources:
        requests:
          cpu: "5"
          memory: "15Gi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: k8s-ci-runner-2xlarge-autoscaler
  namespace: actions
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: k8s-ci-runner-2xlarge
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 0
  maxReplicas: 20
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - test/test
```

### To Reproduce

```markdown
To reproduce the issue create a github actions in your repo with schedule

'''
name: 'test'

on:
    schedule:
        - cron: '30 1 * * *'
jobs:
    stale:
        runs-on: eks-github-ci-runner-2xlarge
        steps:
            -   name: test
                run: echo "test"
```

### Describe the bug

With this configuration, the runner is expected to have been in 0 replicas and when the time for the workflow comes to be executed it should scale to 1. 

### Describe the expected behavior

The actual behavior is that the runner is starting at 1 and not scaling down. if I will create more Github actions with the schedule with will bring up more replicas and not scale down even if the GitHub actions not running them yet.

So the problem is I can have 3 GitHub actions running on one time in a day and have 3 runners all time up because it will not scale down

### Whole Controller Logs

```shell
DEBUG	horizontalrunnerautoscaler	Suggested desired replicas of 0 by PercentageRunnersBusy	{"replicas_desired_before": 1, "replicas_desired": 0, "num_runners": 1, "num_runners_registered": 1, "num_runners_busy": 0, "num_terminating_busy": 0, "namespace": "actions", "kind": "runnerset", "name": "k8s-testimio-ci-runner-2xlarge", "horizontal_runner_autoscaler": "k8s-testimio-ci-runner-2xlarge-autoscaler", "enterprise": "", "organization": "", "repository": "testimio/testimio"}
```

### Whole Runner Pod Logs

```shell
2023-04-22 10:43:43.275  DEBUG --- Docker enabled runner detected and Docker daemon wait is enabled
2023-04-22 10:43:43.276  DEBUG --- Waiting until Docker is available or the timeout of 120 seconds is reached
}CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
2023-04-22 10:43:43.299  NOTICE --- WARNING LATEST TAG HAS BEEN DEPRECATED. SEE GITHUB ISSUE FOR DETAILS:
2023-04-22 10:43:43.301  NOTICE --- https://github.com/actions/actions-runner-controller/issues/2056

√ Connected to GitHub

Current runner version: '2.303.0'
2023-04-22 10:43:45Z: Listening for Jobs
```
