### ISSUE TITLE
actions-runner-dind-rootless no longer work in version v0.27.2 and v0.27.3

### ISSUE THREAD

**Issue by m-barczyk** [actions/actions-runner-controller#2539]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.3

### Helm Chart Version

0.23.2

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1                      
kind: RunnerDeployment                                           
metadata:                                                        
  name: runner-<hidden>-actions-runners-test                     
  namespace: actions-runners-dev                                 
spec:                                                            
  replicas: 1                                                    
  template:                                                      
    metadata:                                                    
      labels:                                                    
        app: "actions-runner-controller-dev-runner"              
    spec:                                                        
      ephemeral: true                                            
      dockerdWithinRunnerContainer: true                         
      repository: <myorg>/<myrepository>                         
      image: summerwind/actions-runner-dind-rootless:ubuntu-22.04
      labels:                                                    
        - <mylabel>                                              
      terminationGracePeriodSeconds: 900                         
      env:                                                       
        - name: RUNNER_GRACEFUL_STOP_TIMEOUT                     
          value: "870"                                           
      containers:                                                
        - name: runner                                           
          resources:                                             
            requests:                                            
              cpu: "0.5"                                         
              memory: "4Gi"                                      
            limits:                                              
              memory: "4Gi"                                      
      dockerVolumeMounts:                                        
        - mountPath: /var/lib/docker                             
          name: docker                                           
      volumeMounts:                                              
        - mountPath: /runner                                     
          name: runner                                           
        - mountPath: /runner/_work                               
          name: work                                             
      volumes:                                                   
        - name: docker                                           
          emptyDir:                                              
            sizeLimit: 20Gi                                      
        - name: work                                             
          emptyDir:                                              
            sizeLimit: 20Gi                                      
        - name: runner                                           
          emptyDir:                                              
            sizeLimit: 5Gi
```

### To Reproduce

```markdown
1. Install fresh ARC in the latest version: 0.23.2
2. Deploy runner based on summerwind/actions-runner-dind-rootless:ubuntu-22.04
3. Simple setup, no autoscaling, runner attached to a single repository.
4. Single replica of controller.
```

### Describe the bug

I've installed ARC in version 0.23.2. controller started up fine without any problem. After trying to add first `RunnerDeployment` based on `actions-runner-dind-rootless:ubuntu-22.04` controller crashes with the following error:
```
{"severity":"info","ts":"2023-04-26T11:47:19Z","message":"Starting workers","controller":"runnerpod-controller","controllerGroup":"","controllerKind":"Pod","worker count":1}
{"severity":"info","ts":"2023-04-26T11:47:19Z","message":"Starting workers","controller":"runner-controller","controllerGroup":"actions.summerwind.dev","controllerKind":"Runner","worker count":1}
{"severity":"info","ts":"2023-04-26T11:47:19Z","message":"Starting workers","controller":"runnerdeployment-controller","controllerGroup":"actions.summerwind.dev","controllerKind":"RunnerDeployment","worker count":1}
        runtime/panic.go:884 +0x212
github.com/actions/actions-runner-controller/controllers/actions%2esummerwind%2enet.(*RunnerReconciler).newPod(_, {{{0x15d92f5, 0x6}, {0xc0006aa1c0, 0x1f}}, {{0xc000e72440, 0x31}, {0xc001344480, 0x2c}, {0xc0006a1620, ...}, ...}, ...})
        github.com/actions/actions-runner-controller/controllers/actions.summerwind.net/runner_controller.go:613 +0x1865
github.com/actions/actions-runner-controller/controllers/actions%2esummerwind%2enet.(*RunnerReconciler).processRunnerCreation(_, {_, _}, {{{0x15d92f5, 0x6}, {0xc0006aa1c0, 0x1f}}, {{0xc000e72440, 0x31}, {0xc001344480, ...}, ...}, ...}, ...)
        github.com/actions/actions-runner-controller/controllers/actions.summerwind.net/runner_controller.go:298 +0x14d
github.com/actions/actions-runner-controller/controllers/actions%2esummerwind%2enet.(*RunnerReconciler).Reconcile(0xc0001b1380, {0x1c04098, 0xc0006967e0}, {{{0xc000b92120, 0x13}, {0xc001308180, 0x31}}})
        github.com/actions/actions-runner-controller/controllers/actions.summerwind.net/runner_controller.go:147 +0x7f2
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1c04098?, {0x1c04098?, 0xc0006967e0?}, {{{0xc000b92120?, 0x16b38e0?}, {0xc001308180?, 0x0?}}})
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000001040, {0x1c03ff0, 0xc000454540}, {0x17af880?, 0xc0006d2ae0?})
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323 +0x38f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000001040, {0x1c03ff0, 0xc000454540})
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:231 +0x333
```

What it is interesting is the fact that it works correctly with default runner: `summerwind/actions-runner:ubuntu-22.04` (when runner pod consists of two containers `runner`, `docker`).

I've also installed previous versions of ARC and this problem started in version: chart 0.23.1, app version 0.27.3
```
 chart 0.23.0, app version 0.27.2 - works
 chart 0.23.1, app version 0.27.3 - does not work - I think problem was introduced in app version 0.27.3
 chart 0.23.2, app version 0.27.3 - does not work
```

### Describe the expected behavior

I would like to be able to use `actions-runner-dind-rootless` with the latest version of ARC.

### Whole Controller Logs

```shell
https://gist.githubusercontent.com/m-barczyk/ec7bc96b5cea2e43191aee01c5a4550a/raw/f45d8907bbdc741212af75c76a5089babdd66a0c/arc-controller-logs.txt
```

### Whole Runner Pod Logs

```shell
N/A
```

### Additional Context

N/A

**Comment by m-barczyk** [comment]
After I've removed:
```
   volumeMounts:
        - mountPath: /runner/_work                               
          name: work   
    volumes:                                  
      - name: work                                             
        emptyDir:                                              
          sizeLimit: 20Gi 
```
controller no longer crashes. It is good for me. I'm closing the issue.
