### ISSUE TITLE
Build `docker buildx` into runners

### ISSUE THREAD

**Issue by jwhitaker-swiftnav** [actions/actions-runner-controller#2571]
### What would you like added?

Add the `docker buildx` plugin to the default runners

### Why is this needed?

I'm aware of and sympathetic to the desire to keep the runners slimmer than the github hosted runners, but could a special case be made for `docker buildx`?

 - it's a plugin for docker with heavy use that is present in hosted runners
 - a similar plugin, `compose`, is installed into the runners
 - building containers is a hugely important use-case for ARC runners, and the `buildx` action sometimes breaks/behaves differently to hosted runners already, so having this built-in + tested in CI would be highly appreciated.
 - `buildx` is installed by default in almost all distributions of docker, having it missing is likely to cause more issues in the future, esp as docker moves towards using it by default.

I wouldn't ask this for any other tool, promise!

Happy to contribute a PR if this is acceptable but wanted to check your amenability first. Thanks for maintaining this system!

**Comment by pof-jhansilva** [comment]
Any updates on this one? I wouldn't like this to go stale if that's possible, this would be great to have as we could steps like this for our builds; which really makes things easier.

````
  - name: Build and push Docker image # Can't use this step because we need buildx.
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          file: Dockerfile  # Your Dockerfile name
          push: true
          ````

**Comment by Vladyslav-Miletskyi** [comment]
Hello @pof-jhansilva You can try running workflow like [this](https://github.com/docker/setup-buildx-action):

```yaml
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        file: Dockerfile  # Your Dockerfile name
        push: true
```
