### ISSUE TITLE
Make dockerd configuration more generic

### ISSUE THREAD

**Issue by twildber** [actions/actions-runner-controller#2588]
### What would you like added?

In the entrypoint of the runners are **MTU**, **Default-Address-Pools** and **Registry-Mirrors** defined.
I would like to have more configuration options available to add to the start of dockerd.

### Why is this needed?

Dockerd provides more options that could be needed to configure for some use-cases.
In my case I need to add a DNS entry to the daemon. I found out that during "docker build / run" my corporate proxy couldn't be resolved because the "pod" dns nameserver was not used. Maybe due to docker-rootless.

### Additional context

- I'm using the docker-rootless runner
- Idea:
  - Mouting a configmap to the daemon.json

**Comment by twildber** [comment]
I found a way to configure my settings without need to implement my proposed request.
My solution is to mount the daemon.json from a configmap.

RunnerDeployment
```
spec:
  template:
    spec:
      volumeMounts:
        - mountPath: /home/runner/.config/docker
          name: {{ template "runner.name" . }}-config-vol
          readOnly: true
      volumes:
        - name: {{ template "runner.name" . }}-config-vol
          configMap:
            name: {{ template "runner.name" . }}-config
            items:
              - key: daemon.json
                path: daemon.json
```

Configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "runner.name" . }}-config
data:
  daemon.json: |
    {
      "dns": ["x.x.x.x"]
    }
```

**Comment by joshtharakan** [comment]
@twildber I tried the above and didnt work. Could you please confirm if we have to mount it to `/home/runner/.config/docker` or `/home/runner/.docker`? Also even when I mounted it to `/home/runner/.docker` it failed as `.docker` is then mounted with the permission of `root:root` and then other steps in my workflow like ecr login fails to update the config with permission denied error.

**Comment by twildber** [comment]
Hi @joshtharakan, I opened a PR to address that feature: https://github.com/actions/actions-runner-controller/pull/2701/files

You have to mount the daemon.json file to /home/runner/.config/docker/daemon.json. It should look like below. But without that change in the mentioned PR it won't work as the `.config` directory is mounted with the permissions of `root:root`.

```
spec:
  template:
    spec:
      dockerdWithinRunnerContainer: true
      image: summerwind/actions-runner-dind(-rootless)
      volumeMounts:
        - mountPath: /home/runner/.config/docker/daemon.json
          name: daemon-config-volume
          subPath: daemon.json
      volumes:
        - name: daemon-config-volume
          configMap:
            name: daemon-cm
            items:
              - key: daemon.json
                path: daemon.json
      securityContext:
        fsGroup: 1001 # runner user id
```
