### ISSUE TITLE
Add OpenAPI metadata for kustomize patches

### ISSUE THREAD

**Issue by fheinecke** [actions/actions-runner-controller#2620]
### What would you like added?

Support for kustomize strategic merge patches. This can be done by adding specific `x-kubernetes-patch-*` metadata keys to the CRD OpenAPI schema.

### Why is this needed?

Currently when applying a strategic merge patch to resources like RunnerDeployments or RunnerSets, lists/arrays of objects always get clobbered by the patch instead of merged. It would be nice to be able to apply a patch that contains baseline/required values for the resources, and have those values appended instead of replaced.

Here is an example of the issue and my specific use case:

runner.yaml:
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-runner
spec:
  replicas: 1
  template:
    spec:
      ephemeral: true
      repository: my-repo
      labels:
        - runner-label
      tolerations:
        - key: firstTaint
          operator: Equal
          value: firstTaintValue
          effect: NoSchedule
```

patch.yaml:
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: This field is required by kustomize but ignored
spec:
  template:
    spec:
      labels:
        - required-label
      tolerations:
        - key: secondTaint
          operator: Equal
          value: secondTaintValue
          effect: NoSchedule
```

kustomization.yaml:
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner-controller
resources:
  - runner.yaml
# There are additional runners here that are omitted for brevity's sake
patches:
  - path: ./patch.yaml
    target:
      kind: RunnerDeployment

```

Output:
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-runner
spec:
  replicas: 1
  template:
    spec:
      ephemeral: true
      repository: my-repo
      labels:
        - runner-label
        - required-label
      tolerations:
        - key: secondTaint
          operator: Equal
          value: secondTaintValue
          effect: NoSchedule
```

This would be the ideal output:
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-runner
spec:
  replicas: 1
  template:
    spec:
      ephemeral: true
      repository: my-repo
      labels:
        - runner-label
        - required-label
      tolerations:
        - key: firstTaint
          operator: Equal
          value: firstTaintValue
          effect: NoSchedule
        - key: secondTaint
          operator: Equal
          value: secondTaintValue
          effect: NoSchedule
```

### Additional context

Here's details on the feature and how it can be added:
* Kustomize docs: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/customOpenAPIschema.md
* KEP for the feature: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2206-openapi-features-in-kustomize
* Reference page for the feature: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/
* How Argo Rollouts implemented the feature: https://github.com/argoproj/argo-rollouts/pull/1371
