### ISSUE TITLE
Github Actions that run many containers using dockerd sidecar run out of space on `/run` volume mount

### ISSUE THREAD

**Issue by opdude** [actions/actions-runner-controller#2621]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.4

### Helm Chart Version

0.23.3

### CertManager Version

1.11.0

### Deployment Method

Helm

### cert-manager installation

Cert manager is deployed separately with the jetstack.io helm chart and shouldn't affect the bug.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-runner
spec:
  template:
    spec:
      organization: my-org
      group: Default
      dockerMTU: 1460
      terminationGracePeriodSeconds: 4200
      containers:
        - name: runner
          env:
            # Allow for an hour to finish the build
            - name: RUNNER_GRACEFUL_STOP_TIMEOUT
              value: "3600"
        - name: docker
      initContainers:
        # Copy secrets from a read-only location to a read-write location so that the docker
        # config can be modified if the user wishes to
        - name: copy-docker-secrets
          image: "busybox:stable"
          command: ['sh', '-c', "cp /home/runner/.secrets/docker/config.json /home/runner/.docker/config.json"]
          volumeMounts:
            - name: docker-emptydir
              mountPath: "/home/runner/.docker"
            - name: docker-secret
              mountPath: "/home/runner/.secrets/docker"
              readOnly: true

      volumeMounts:
        - name: docker-emptydir
          mountPath: "/home/runner/.docker"
        - name: docker-emptydir
          mountPath: "/github/home/.docker"
      dockerVolumeMounts:
        - name: docker-emptydir
          mountPath: "/home/runner/.docker"
        - name: docker-emptydir
          mountPath: "/github/home/.docker"
      volumes:
        - name: docker-secret
          secret:
            secretName: docker-config
        - name: docker-emptydir
          emptyDir: {}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.gke.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              runner-deployment-name: my-runner
      tolerations:
        - effect: NoSchedule
          key: sandbox.gke.io/runtime
          operator: Exists
      resources:
        requests:
          cpu: '2'
          memory: 8Gi
        limits:
          cpu: '2'
          memory: 8Gi
```

### To Reproduce

```markdown
1. Run an action which launches a large number of containers (see the below docker-compose example)
2. The included runner pod error will occur as the `/run` volume mount runs out of space
```

```
# Docker-compose file
version: '3.8'

services:
  nginx:
    deploy:
      replicas: 100
    image: nginx
```

```
# Workflow example
name: Test Many Containers

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-many-containers:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
```

### Describe the bug

When a large number of containers are launched via docker-compose, this adds multiple files under the `/run` volume mount which will eventually run out of space meaning that no further containers can be launched and failing the workflow.

### Describe the expected behavior

A user can change the size of the `/run` volume mount from the 1M default to any value and launch more containers without issues.

### Whole Controller Logs

```shell
The controller doesn't contain anything relevant as the problem lies within the `dockerd` container.
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/opdude/66320853f749ef7206567be9cc5103b1
```

### Additional Context

I'll look into writing a patch to allow for working around this issue shortly.
