### ISSUE TITLE
Scaleset listener fails: could not patch ephemeral runner set 

### ISSUE THREAD

**Issue by robertsa1-els** [actions/actions-runner-controller#2633]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.4.0

### Helm Chart Version

0.4.0

### CertManager Version

NA

### Deployment Method

Helm

### cert-manager installation

NA

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
Using ScaleSets
```

### To Reproduce

```markdown
1. Helm install the scaleset controller `helm install -n gha-controller gha-runner-scale-set-controller oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller`

2. Install a scale set in another namespace

helm install "${INSTALLATION_NAME}" \
    --namespace "${NAMESPACE}" \
    --set githubConfigUrl="${GITHUB_CONFIG_URL}" \
    --set githubConfigSecret.github_token="${GITHUB_PAT}" \
    --set minRunners=1 \
    --set runnerGroup="${INSTALLATION_NAME}" \
    --set containerMode.type="dind" \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
```
3. The Listener goes into an Error loop with the error message
```
2023-05-30T15:07:22Z	ERROR	Run error	{"error": "failed to start message queue listener: could not get and process message. fail to process initial message. could not scale ephemeral runner set (gha-runners/test-scaleset-44xvv). could not patch ephemeral runner set , patch JSON: {\"spec\":{\"replicas\":1}}, error: ephemeralrunnersets.actions.github.com \"test-scaleset-44xvv\" is forbidden: User \"system:serviceaccount:gha-controller:test-scaleset-67fdb58c-listener\" cannot patch resource \"ephemeralrunnersets\" in API group \"actions.github.com\" in the namespace \"gha-runners\""}
```

### Describe the bug

It looks like the listener only has a namespaced scoped role to the namespace where the controller lives.
This role doesn't appear to have any permissions over `ephemeralrunnersets` even if it was a cluster role

```
❯ k get -o yaml roles gha-runner-scale-set-controller-manager-listener-role -n gha-controller
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: gha-runner-scale-set-controller
    meta.helm.sh/release-namespace: gha-controller
  creationTimestamp: "2023-05-30T14:44:13Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gha-runner-scale-set-controller-manager-listener-role
  namespace: gha-controller
  resourceVersion: "74506"
  uid: 7154a61f-fc71-4539-9733-9b26e9650ff1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - patch
  - update
 ```

### Describe the expected behavior

According to the docs here https://github.com/actions/actions-runner-controller/tree/master/docs/preview/gha-runner-scale-set-controller
This approach should work and controller and listener can manage runner in another NS

### Whole Controller Logs

```shell
Cannot give this as working for a company. There are no errors in this logs.
```

### Whole Runner Pod Logs

```shell
There is no runner log as cannot get listener to spin them up
```

**Comment by robertsa1-els** [comment]
Attaching the Controller ClusterRole (which does have permissions over `ephemeralrunnersets`) to the listener allows this to work. So it is certainly a permissions bug.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {SNIP}
  creationTimestamp: "2023-05-30T16:23:22Z"
  name: test-listener-binding
  resourceVersion: "128950"
  uid: 01763f80-d907-490a-805e-3fd19c82b40d
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gha-runner-scale-set-controller-manager-cluster-role
subjects:
- kind: ServiceAccount
  name: test-scaleset-67fdb58c-listener
  namespace: gha-controller
```

**Comment by robertsa1-els** [comment]
Have re-created the listener role as a cluster role and needed to add some further scopes to allow editing of `ephemeralscalesets` and this also worked.  
However just adding the `ephemeralscalesets` scopes to the namespaced listener role did NOT work as it could not patch in a different namespace.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gha-runner-scale-set-listener-cluster-role
rules:
  - apiGroups:
      - actions.github.com
    resources:
      - ephemeralrunnersets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - actions.github.com
    resources:
      - ephemeralrunners/finalizers
    verbs:
      - patch
      - update
  - apiGroups:
      - actions.github.com
    resources:
      - ephemeralrunners/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - patch
      - update
```
