### ISSUE TITLE
containerMode: kubernetes error "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by rpenziol** [actions/actions-runner-controller#2641]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.4

### Helm Chart Version

0.23.3

### CertManager Version

1.10.0

### Deployment Method

Helm

### cert-manager installation

Yes, yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: test-runner
  namespace: actions-runners
spec:
  repository: org/repo
  containerMode: kubernetes
  serviceAccountName: runner-set-service-account
  workVolumeClaimTemplate:
    storageClassName: custom-storage-class
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  selector:
    matchLabels:
      app: test-runner
  serviceName: test-runner
  labels:
    - test-runner
  template:
    metadata:
      labels:
        app: test-runner
    spec:
      containers:
      - name: runner
        image: summerwind/actions-runner-dind:latest
        env: []
        resources:
          limits:
            cpu: "1.0"
            memory: "1Gi"
          requests:
            cpu: "1.0"
            memory: "1Gi"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-set-role
  namespace: actions-runners
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch",]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-set-service-account
  namespace: actions-runners

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-set-rolebinding
  namespace: actions-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-set-role
subjects:
- namespace: actions-runners
  kind: ServiceAccount
  name: runner-set-service-account
```

### To Reproduce

```markdown
1. Create a RunnerSet with the above configuration
2. Run a basic pipeline with the `runs-on` field set to the RunnerSet name

name: hello
on: push

jobs:
  hello-world:
    runs-on: test-runner
    container:
      image: docker.io/library/node:14.16
    steps:
      - name: Hello step
        run: |
          echo "Hello world"
```

### Describe the bug

I'm trying to create a RunnerSet using the `containerMode: kubernetes` feature (feature PR: https://github.com/actions/actions-runner-controller/pull/1546)

However, on every job execution the runner prints the error

```bash
##[group]Checking docker version
##[error]Object reference not set to an instance of an object.
```

I'm quite confident the error originates from the `AssertCompatibleOS` function
https://github.com/actions/runner/blob/04761e535339bbcb94fae5efe264b8d9a704967a/src/Runner.Worker/ContainerOperationProvider.cs#L562: 
```
[2023-06-01 15:47:31Z ERR  StepsRunner] Caught exception from step: System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.Runner.Worker.ContainerOperationProvider.AssertCompatibleOS(IExecutionContext executionContext)
   at GitHub.Runner.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
   at GitHub.Runner.Worker.JobExtensionRunner.RunAsync()
   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

### Describe the expected behavior

The `containerMode: kubernetes` feature creates job pods and executes workflows/jobs without errors

### Whole Controller Logs

```shell
https://gist.github.com/rpenziol/8001a63808a0dac7f79667dad04d11eb
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/rpenziol/8001a63808a0dac7f79667dad04d11eb
```

### Versions
actions-runner-controller Helm chart: 0.23.3
actions-runner-controller image: summerwind/actions-runner-controller:v0.27.4
runner image: summerwind/actions-runner-dind:v2.304.0-ubuntu-20.04-e571df5 (via summerwind/actions-runner-dind:latest)

### My findings from the runner code
- `StartContainersAsync` is called https://github.com/actions/runner/blob/04761e535339bbcb94fae5efe264b8d9a704967a/src/Runner.Worker/ContainerOperationProvider.cs#L46
- `StartContainersAsync` hits this `if` statement, https://github.com/actions/runner/blob/04761e535339bbcb94fae5efe264b8d9a704967a/src/Runner.Worker/ContainerOperationProvider.cs#L64
- `IsContainerHooksEnabled` is called https://github.com/actions/runner/blob/04761e535339bbcb94fae5efe264b8d9a704967a/src/Runner.Worker/FeatureManager.cs#L8
- `IsContainerHooksEnabled` returns false (more on this later) https://github.com/actions/runner/blob/04761e535339bbcb94fae5efe264b8d9a704967a/src/Runner.Worker/FeatureManager.cs#L12
- Because `IsContainerHooksEnabled` returned false, the `if` block in `StartContainersAsync` with the return statement is skipped https://github.com/actions/runner/blob/04761e535339bbcb94fae5efe264b8d9a704967a/src/Runner.Worker/ContainerOperationProvider.cs#L70
- `AssertCompatibleOS` is called https://github.com/actions/runner/blob/04761e535339bbcb94fae5efe264b8d9a704967a/src/Runner.Worker/ContainerOperationProvider.cs#L72
- `AssertCompatibleOS` logs `Checking docker version`, presumably the next line is where the `Object reference not set to an instance of an object.` error happens https://github.com/actions/runner/blob/04761e535339bbcb94fae5efe264b8d9a704967a/src/Runner.Worker/ContainerOperationProvider.cs#L562

### Further analysis
`IsContainerHooksEnabled` checks for two variables. Both must be true for it to return `true`.
- `isContainerHookFeatureFlagSet` comes from the feature flag `"DistributedTask.AllowRunnerContainerHooks"` https://github.com/actions/runner/blob/eeb0cf6f1e52149a890a48bdaf660d8efd86fa34/src/Runner.Common/Constants.cs#L159
- `isContainerHooksPathSet` comes from the environment variable `ACTIONS_RUNNER_CONTAINER_HOOKS` https://github.com/actions/runner/blob/eeb0cf6f1e52149a890a48bdaf660d8efd86fa34/src/Runner.Common/Constants.cs#L209

I can confirm `ACTIONS_RUNNER_CONTAINER_HOOKS` is set on my runner pod and that the file exists
```bash
kubectl exec -it test-runner-8btkv-0 -- printenv | grep ACTIONS_RUNNER_CONTAINER_HOOKS
ACTIONS_RUNNER_CONTAINER_HOOKS=/runner/k8s/index.js
kubectl exec -it test-runner-8btkv-0 -- ls /runner/k8s/index.js
/runner/k8s/index.js
```

However, I haven't found any reference to `"DistributedTask.AllowRunnerContainerHooks"`. I've downloaded the runner-diagnostic-logs from GitHub and don't see it set under the `variables` section. Presumably this is the root cause of the issue.
