### ISSUE TITLE
Pods are not GC'd at the end of a job

### ISSUE THREAD

**Issue by WoodyWoodsta** [actions/actions-runner-controller#2662]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.4

### Helm Chart Version

0.23.3

### CertManager Version

1.12.1

### Deployment Method

Helm

### cert-manager installation

- Yes
- Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner
spec:
  replicas: 6
  template:
    spec:
      image: <redacted>
      organization: <redacted>
      volumeMounts:
        - name: yarn-cache
          mountPath: /home/runner/.yarn/berry
      volumes:
        - name: yarn-cache
          hostPath:
            path: /var/cache/arc/runner/.yarn/berry
            type: DirectoryOrCreate
```

### To Reproduce

```markdown
I've not been able to "reproduce" so much as it's currently an issue in my cluster.
```

### Describe the bug

After a job has finished, the `runner` container exits with code 0, but the pod remains alive indefinitely (until I delete it). The `docker` container also remains alive.

I've done nothing with the arc installation between now and when it was working correctly.

### Describe the expected behavior

Pods should terminate once the runner has finished its job.

### Whole Controller Logs

```shell
https://gist.github.com/WoodyWoodsta/cb8339388352f7b95d1c912f4e9ba733
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/WoodyWoodsta/2e870e8a5c70735242c43a59b79bf422
```

### Additional Context

I've noticed that even though the logs show `Removed finalizer	{"runner": "github-arc/actions-runner-g2d7z-qvgss"}`, I can still see an entry in the `finalizers` field in the pod yaml:

```yaml
  finalizers:
    - actions.summerwind.dev/runner-pod
```

I don't seem to be able to remove that.
