### ISSUE TITLE
On demand runner action based on user provided docker image

### ISSUE THREAD

**Issue by abhilashissac-myntra** [actions/actions-runner-controller#2684]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.23.3

### CertManager Version

1.10

### Deployment Method

Helm

### cert-manager installation

We followed the ARC installation steps. Also we installed cert-manager from the official documentation.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runners
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      organization: myntra-PoC
      labels:
        - vanilla
        - azure
        - java
        - go
        - nodejs
        - python  
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-deployment-autoscaler
  namespace: default
spec:
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: github-runners
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'
```

### To Reproduce

```markdown
kubectl apply -f actions.yml
```

### Describe the bug

We are able to create on demand action runners, but then we are not able to ensure that the runners are created based on the user provided docker image. For example, a Java based repo should be able to create on demand runners with the JAVA image that is provided by the user for running the actions.

### Describe the expected behavior

We would like to ensure that an on demand runner action is created based on user provided docker image

### Whole Controller Logs

```shell
Will update the logs shortly
```

### Whole Runner Pod Logs

```shell
Will provide the logs shortly
```
