### ISSUE TITLE
Runner Pods randomly receiving a sigterm and killing jobs

### ISSUE THREAD

**Issue by maeghan-porter** [actions/actions-runner-controller#2695]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.3

### Helm Chart Version

0.23.2

### CertManager Version

1.10.0

### Deployment Method

Helm

### cert-manager installation

I am installing it via helm as outlined here: https://cert-manager.io/docs/installation/helm/
With the `installCRDs=true` option set.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment-nonprod
  namespace: gha
spec:
  template:
    spec:
      image: docker-all.repo.sonatype.com/summerwind/actions-runner-dind:v2.303.0-ubuntu-22.04
      imagePullSecrets:
        - name: repo.sonatype.com
      dockerdWithinRunnerContainer: true
      organization: sonatype
      labels:
        - stable
        - 0-8-0
        - nonprod
      group: my-runner-group
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-autoscaler-nonprod
  namespace: gha
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: runner-deployment-nonprod
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '2'
      scaleDownFactor: '1'
```

### To Reproduce

```markdown
I can't really reproduce it on demand, it happens randomly.
```

### Describe the bug

It is described in this question from March: https://github.com/actions/actions-runner-controller/discussions/2417
But no one has said anything on it and since multiple people are experiencing it I am filing it as an issue/bug.

The TL;DR is that runner pods are randomly getting a shutdown signal for no reason that anyone can gather from the logs or from the metrics of the instances at the time of the shutdown signal and it cancels whatever job it is running at the moment.

I am running 8vCore 32GB memory instances and there were no significant resource use increases at the time of the sigterm. 

### Describe the expected behavior

I expect that jobs shouldn't be cancelled randomly for no obvious reason.

### Whole Controller Logs

```shell
https://gist.github.com/maeghan-porter/aceb7352951cd0a834dc133051772f9f
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/maeghan-porter/88973c0dbd24ab55d4162a5cc037ffff
```
