### ISSUE TITLE
Panic if `RunnerDeployment` contains `volumeMounts`

### ISSUE THREAD

**Issue by fatmcgav** [actions/actions-runner-controller#2719]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.4

### Helm Chart Version

0.23.3

### CertManager Version

1.21.1

### Deployment Method

Helm

### cert-manager installation

Yes, `cert-managed` install via Helm.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: infra-general-runner
  namespace: actions-runner-agents
spec:
  minReplicas: 0
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: infra-general-runner
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "15m"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: infra-general-runner
  namespace: actions-runner-agents
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      repository: <owner>/<repo>
      image: europe-west2-docker.pkg.dev/****/containers/github-runner:816ae67
      labels:
        - infrastructure
      dockerEnabled: false
      env:
        - name: DISABLE_WAIT_FOR_DOCKER
          value: "true"
        - name: LOG_DEBUG_DISABLED
          value: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_pool
                    operator: In
                    values:
                      - ci-agents
      tolerations:
        - key: "ci-agents"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: infra-terraform-runner
  namespace: actions-runner-agents
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: infra-terraform-runner
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "90m"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: infra-terraform-runner
  namespace: actions-runner-agents
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      repository: <owner>/<repo>
      image: europe-west2-docker.pkg.dev/***/containers/github-runner:816ae67
      labels:
        - infrastructure
        - terraform
      dockerEnabled: false
      ephemeral: true # Ensure that workspace gets cleaned up
      env:
        - name: DISABLE_WAIT_FOR_DOCKER
          value: "true"
        - name: LOG_DEBUG_DISABLED
          value: "true"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      resources:
        requests:
          cpu: "1"
          memory: "512Mi"
          ephemeral-storage: "5Gi"
      serviceAccountName: terraform-runner-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_pool
                    operator: In
                    values:
                      - ci-agents
      tolerations:
        - key: "ci-agents"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      volumeMounts:
        - mountPath: /runner/_work
          name: work
        - mountPath: /tmp
          name: tmp
      volumes:
        - name: work
          emptyDir: {}
        - name: tmp
          emptyDir: {}
```

### To Reproduce

```markdown
TBC
```

### Describe the bug

Whilst performing a routine node-pool rotation on the underlying GKE cluster, the `actions-runner-controller` pod entered a `CrashLoopBackoff` status.

Upon investigating the logs, there is a `panic: runtime error: slice bounds out of range [:-1] [recovered]` error.

### Describe the expected behavior

Pod should restart cleanly.

### Whole Controller Logs

```shell
https://gist.github.com/fatmcgav/1cd12307c644c687f04e602ad651fcd3#file-arc-log
```

### Whole Runner Pod Logs

```shell
N/A
```

### Additional Context

None
