### ISSUE TITLE
Support stringData field and annotations in githubsecret.yaml

### ISSUE THREAD

**Issue by tim-yiu-mox** [actions/actions-runner-controller#2729]
### What would you like added?

- add annotations to [githubsecret.yaml](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/githubsecret.yaml)
- support stringData field in  [githubsecret.yaml](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/githubsecret.yaml)

### Why is this needed?

We would like to inject secrets from HC vault to Secret Yaml via [ArgoCD Vault Plugin](https://argocd-vault-plugin.readthedocs.io/en/stable/howitworks/) 

### Additional context

The secret template should be rendered like this

```
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "path/to/secret"
  finalizers:
    - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: example
    actions.github.com/scale-set-namespace: example
    app.kubernetes.io/instance: example
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gha-runner-scale-set
    app.kubernetes.io/part-of: gha-runner-scale-set
    app.kubernetes.io/version: 0.4.0
    helm.sh/chart: gha-runner-scale-set-0.4.0
type: Opaque
stringData:
  password: <password-vault-key>
```
