### ISSUE TITLE
RUNNER_LABELS not being passed to current runner

### ISSUE THREAD

**Issue by isantospardo** [actions/actions-runner-controller#2730]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.23.3

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
spec:
  containers:
    - args:
        ......
      command:
        - /manager
      env:
          ....
        - name: RUNNER_LABELS
          value: 'self-hosted,dev'
```

### To Reproduce

```markdown
1. I am currently deploying the actions-runner-controller via helm, and trying to set up the RUNNER_LABELS env in the controller, when setting this up, I see the controller deployment pod from above.
2. But, in the github-action-runner I see the env var is not set as it should be, see the code below
```

### Describe the bug

```yaml
spec:
  containers:
    - env:
        ......
        - name: RUNNER_LABELS
        - name: RUNNER_GROUP
        ......
```

### Describe the expected behavior

There should be a label in the GitHub runner, called `dev`

### Whole Controller Logs

```shell
No error logs
```

### Whole Runner Pod Logs

```shell
No error logs
```

### Additional Context

I opened a question here, but no answer after a while https://github.com/actions/actions-runner-controller/discussions/2710
