### ISSUE TITLE
Ability to share service account from runner pod to job pod in Kubernetes mode

### ISSUE THREAD

**Issue by veronicatjan** [actions/actions-runner-controller#2754]
### What would you like added?
We're installing ARC on EKS cluster, then set up IRSA to grant permission to a service account. 
We need a way to let job pod use the same service account as the runner pod, so that they have the same permission. 

I saw this solution https://github.com/actions/actions-runner-controller/discussions/798 , but it is no longer working due to `Error: Volume mounts outside of the work folder are not supported` 

### Why is this needed?
The runner will be used to build image then push to our private ECR registry. We were able to configure the runner pod to use the right service account with ECR push permission, but the workflow job pod that runs the actual job is using `default` service account that doesn't have ECR push permission. 

### Additional context
Manifests:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: kubernetes-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-runner-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch",]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-runner-role
subjects:
- kind: ServiceAccount
  name: kubernetes-runner
  namespace: default
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: nonprivileged-runners
spec:
  template:
    spec:
       securityContext:
         # For Ubuntu 20.04 runner
         fsGroup: 1000
      containerMode: kubernetes
      serviceAccountName: kubernetes-runner
      workVolumeClaimTemplate:
        storageClassName: "gp2"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      labels:
        - eks
        - teamsvcs
        - kaniko
      repository: infra/runner-test
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: nonprivileged-runners-autoscaler
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: nonprivileged-runners
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - infra/runner-test
```
