### ISSUE TITLE
helm uninstall leaves the autoscalingrunnerset and other resources behind(missing rbac?)

### ISSUE THREAD

**Issue by wherka-ama** [actions/actions-runner-controller#2781]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.23.3

### Helm Chart Version

0.4.0

### Deployment Method

Helm

### cert-manager installation

This is for ARC v2, so cert-manager may not be relevant here.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
Arc v2 - these are not relevant here.

<values.yaml>
githubConfigSecret: runners-secret

## maxRunners is the max number of runners the auto scaling runner set will scale up to.
maxRunners: 10

## minRunners is the min number of runners the auto scaling runner set will scale down to.
minRunners: 0

runnerGroup: "runner_group"

## template is the PodSpec for each runner Pod
template:
  spec:
    containers:
    - name: runner
      image: <internal_repo>/runner-image-infra:x.x.x
      command: ["./entrypoint-dind-rootless.sh"]
      securityContext:
        privileged: true
        runAsUser: 1001
        runAsGroup: 0
      env:
        - name: DOCKER_CLIENT_ADDRESS
          value: unix:///run/user/1001/docker.sock
        - name: ENTRYPOINT_SCRIPT
          value: /home/runner/run.sh
        - name: DISABLE_RUNNER_UPDATE
          value: "false"
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 1
          memory: 4Gi
    volumes:
    - name: work
      emptyDir: {}

## Optional controller service account that needs to have required Role and RoleBinding
## to operate this gha-runner-scale-set installation.
## The helm chart will try to find the controller deployment and its service account at installation time.
## In case the helm chart can't find the right service account, you can explicitly pass in the following value
## to help it finish RoleBinding with the right service account.
## Note: if your controller is installed to only watch a single namespace, you have to pass these values explicitly.
controllerServiceAccount:
  namespace: actions-runner-controller
  name: actions-runner-controller
```

### To Reproduce

```markdown
1. install chart release
helm upgrade --install --namespace actions-runner-controller --skip-crds --debug --values=values.yaml infra oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
2. uninstall the release
helm uninstall infra
3. list resources (autoscalingrunnerset, role, rolebinding)
```

### Describe the bug

Helm uninstall does not seem to work in a consistent way. Sometimes it leaves autoscalingrunnerset, roles, rolebindings. However, it's not super consistent.
Sometimes these objects prevent a subsequent re-installations on the the release name as well.

### Describe the expected behavior

Helm uninstall should enforce the clean up of all the resources managed by a specific release. 

### Whole Controller Logs

```shell
N/A
```

### Whole Runner Pod Logs

```shell
N/A
```

### Additional Context

The situation seems to be improved when the following patch is applied(it's not covering 100% of the cases though):

```
diff --git a/charts/gha-runner-scale-set/templates/manager_role.yaml b/charts/gha-runner-scale-set/templates/manager_role.yaml
index f6a1e49..df7a335 100644
--- a/charts/gha-runner-scale-set/templates/manager_role.yaml
+++ b/charts/gha-runner-scale-set/templates/manager_role.yaml
@@ -23,6 +23,15 @@ rules:
   - pods/status
   verbs:
   - get
+- apiGroups:
+  - ""
+  resources:
+  - pods/finalizers
+  verbs:
+  - create
+  - delete
+  - get
+  - list
 - apiGroups:
   - ""
   resources:
   ```
