### ISSUE TITLE
RunnerSet Pods Using Volumes Don't Get Injected With Expected Envs

### ISSUE THREAD

**Issue by gaspo53** [actions/actions-runner-controller#2794]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.4

### Helm Chart Version

0.23.3

### Deployment Method

Helm

### cert-manager installation

I've followed all instructions described in the docs

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: xxx-runnerset-us-east-2
  namespace: github
spec:
  organization: xxx
  ephemeral: true
  dockerEnabled: true
  replicas: 1
  dockerdWithinRunnerContainer: true
  labels:
    - xxx-runnerset-us-east-2
  serviceName: xxx-runnerset-us-east-2
  selector:
    matchLabels:
      app: xxx-runnerset-us-east-2
  template:
    metadata:
      labels:
        app: xxx-runnerset-us-east-2
    spec:
      containers:
      - name: docker
        image: summerwind/actions-runner-dind
        volumeMounts:
          - name: var-lib-docker
            mountPath: /var/lib/docker
      - name: runner
        image: summerwind/actions-runner-dind
        volumeMounts:
          - name: var-lib-docker
            mountPath: /var/lib/docker

      tolerations:
        - effect: NoSchedule
          key: xxx-application
          value: github-runner

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: xxx-application
                operator: In
                values:
                  - github-runner
  volumeClaimTemplates:
  - metadata:
      name: var-lib-docker
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
      storageClassName: gp2
---

apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: xxx-runnerset-us-east-2-hpa
  namespace: github
spec:
  scaleTargetRef:
    name: xxx-runnerset-us-east-2
  minReplicas: 2
  maxReplicas: 10
  scaleDownDelaySecondsAfterScaleOut: 400
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.3'
      scaleUpFactor: '1.4'
      scaleDownFactor: '0.7'
```

### To Reproduce

```markdown
1. Ensure the EKS cluster has EBS controller deployed and configured with right IAM permissions
2. Deploy ARC through Helm
3. Deploy the runnerset with kubectl apply -n github
```

### Describe the bug

After the pod starts, Docker container dies with this:
2023-08-02 19:36:28.605  DEBUG --- dockerd is running
2023-08-02 19:36:28.607  DEBUG --- Working with public GitHub
2023-08-02 19:36:28.608  ERROR --- RUNNER_NAME must be set
2023-08-02 19:36:28.609  NOTICE --- Runner init exited. Exiting this process with code 0 so that the container and the pod is GC'ed Kubernetes soon.

Since the documentation states that for having volumeMounts, that should be defined on each container spec, the default environment variables from the chart should be injected.

### Describe the expected behavior

The pod starts and docker container has all required environment variables set. 
Even I've harcoded those envs, and then an error like this happened: "/runner must be an emptyDir"

I've been searching across the entire issues/doc, and found nothing. It's very likely I'm missing something, but don't know what. For the record, I have self-hosted runners working using RunnerDeployment, but need to switch to RunnerSet in order to use a PVC for caching purposes.

### Whole Controller Logs

```shell
https://gist.github.com/gaspo53/b3e51622a02e5fcf40616e688c4cd574
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/gaspo53/77de9f6d5ae436d51a96aac08868f350
```

**Comment by stefanandres** [comment]
We've ran into the same issue.
This one took us a few hours to debug. For us this is caused by this:

The webhook actually selects on a label called `name` instead of the actual name itself. 
https://github.com/actions/actions-runner-controller/commit/1f8a23c12961fdfa46bd32f572bee4b0a9c7740b#diff-f223f13177d34575a050c4333a9110e4494d40f9910f34024ec2c9b1baa11635R16
```
 namespaceSelector:
    matchLabels:
      name: {{ default .Release.Namespace .Values.scope.watchNamespace }}
```

This should use matchExpressions instead, I'll create a PR. Workaround: Set the label name=$namespace in your namespace.
This is why the mutatingwebhook never was called, hence it was not updating the RUNNER_NAME and RUNNER_TOKEN. I think the runnedeployments actually don't use the webhook for this.

Tested:
```
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - $mynamespace
  objectSelector:
    matchLabels:
      actions-runner-controller/inject-registration-token: "true"
[...]
```
