### ISSUE TITLE
AutoscalingRunnerSet should be named after the runnerScaleSetName - not Helm release name

### ISSUE THREAD

**Issue by hawkesn** [actions/actions-runner-controller#2802]
### What would you like added?

The AutoScalingRunnerSet's name should be named after the runnerScaleSetName - not the Helm release name.
This field: [https://github.com/actions/actions-runner-controller/blob/6a75bc088003fa24d1a9307a982f7b1c4115efff/charts/gha-runner-scale-set/templates/autoscalingrunnerset.yaml#L10](https://github.com/actions/actions-runner-controller/blob/6a75bc088003fa24d1a9307a982f7b1c4115efff/charts/gha-runner-scale-set/templates/autoscalingrunnerset.yaml#L10)

### Why is this needed?
We want to deploy multiple runner-scale-sets to our Kubernetes Cluster and therefore need to install multiple helm charts.
A very easy way to organize this is to have a parent helm chart and subsequent child charts:

Example in parent `Chart.yaml`
```
apiVersion: v2
name: actions-runner-scale-set-group
description: A multi-chart for actions-runner-scale-set

dependencies:
- name: gha-runner-scale-set-controller
  version: 0.4.0
  repository: oci://ghcr.io/actions/actions-runner-controller-charts
- name: gha-runner-scale-set
  version: 0.4.0
  repository: oci://ghcr.io/actions/actions-runner-controller-charts
  alias: ci-small
- name: gha-runner-scale-set
  version: 0.4.0
  repository: oci://ghcr.io/actions/actions-runner-controller-charts
  alias: ci-medium
```

NOTE: The alias above is an easy way to reference the different runner-scale-sets and [this approach is supported and recommended by Helm](https://helm.sh/docs/topics/charts/#alias-field-in-dependencies).

Example in `values.yaml`
```
gha-runner-scale-set-controller:
  replicaCount: 3
  ...
ci-small:
   githubConfigUrl: <my org>
   githubConfigSecret: <my secret>
   runnerScaleSetName: ci-small
   ...
ci-medium:
   githubConfigUrl: <my org>
   githubConfigSecret: <my secret>
   runnerScaleSetName: ci-medium
   ...
```

However, deploying it this way means that all our runners are named after the parent Chart's name: `actions-runner-scale-set-group` since it is based on `release.name`

### Additional context

We want to go with this approach since grouping them into a single Chart makes it easier for us to reference it as a single ArgoCD `Application`
