### ISSUE TITLE
Failed to get new registration token for GitHub Self hosted runners.

### ISSUE THREAD

**Issue by RafiqAleem78** [actions/actions-runner-controller#2807]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.25.1

### Helm Chart Version

0.20.1

### CertManager Version

1.6.1

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-actions-runners-deployment
  namespace: github-actions-runners
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      ephemeral: true
      organization: org-my
      group: shared-service
      labels:
        - shared-service
      serviceAccountName: github-actions-runners
      securityContext:
        fsGroup: 1000
      resources:
        requests:
          cpu: "1000m"
          memory: "4500000Ki"
        limits:
          cpu: "1900m"
          memory: "6000000Ki"
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10

---

apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-actions-runners-hpa
  namespace: github-actions-runners
spec:
  scaleDownDelaySecondsAfterScaleOut: 180
  scaleTargetRef:
    name: github-actions-runners-deployment
  minReplicas: 1
  maxReplicas: 15
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.3'
    scaleUpFactor: '1.4'
    scaleDownFactor: '0.7'
```

### To Reproduce

```markdown
I haven't tried it. but recreating runner deplyment causing this error again in the controller logs.
```

### Describe the bug

Recently our Github id where all tokens were residing got deleted. but still after reinitiating his ID we are failed to regenerate a token and run our self hosted runners.

### Describe the expected behavior

Runner status should be running stage, currently it is none. also runner are created but their pods are not.

### Whole Controller Logs

```shell
2023-08-10T10:11:58Z    ERROR   Reconciler error        {"controller": "horizontalrunnerautoscaler-controller", "controllerGroup": "actions.summerwind.dev", "controllerKind": "HorizontalRunnerAutoscaler", "horizontalRunnerAutoscaler": {"name":"github-actions-runners-hpa","namespace":"github-actions-runners"}, "namespace": "github-actions-runners", "name": "github-actions-runners-hpa", "reconcileID": "6044ff3d-2df2-4bdc-bbdc-57945543c48f", "error": "failed to list runners: GET https://api.github.com/orgs/org-my/actions/runners?per_page=100: 401 Bad credentials []"}
2023-08-10T10:13:28Z    ERROR   actions-runner-controller.runner        Failed to get new registration token    {"runner": "github-actions-runners-deployment-7vmhv-5xrt5", "error": "failed to create registration token: POST https://api.github.com/orgs/org-my/actions/runners/registration-token: 401 Bad credentials []"}
```

### Whole Runner Pod Logs

```shell
failed to create registration token.
```
