### ISSUE TITLE
Jobs intermittently fail to initialize when using containerMode kubernetes

### ISSUE THREAD

**Issue by tkflexys** [actions/actions-runner-controller#2895]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

N/A

### Helm Chart Version

0.5.0

### Deployment Method

Helm

### cert-manager installation

N/A

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
maxRunners: 24

template:
  spec:
    securityContext:
      fsGroup: 1000 
    containers:
    - name: runner
      image: "ghcr.io/actions/actions-runner:latest"
      imagePullPolicy: Always
      command: ["/home/runner/run.sh"]
      resources:
        requests:
          cpu: 500m
    tolerations:
    - key: "gh-runner-worker"
      operator: "Exists"
      effect: "NoSchedule"
    nodeSelector:
      workerType: gh
containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "fast"
    resources:
      requests:
        storage: 8Gi
```

### To Reproduce

```markdown
1) Launch a GitHub workflow that uses this runner
2) Get workflow error in `Initialize containers` step


Run '/home/runner/k8s/index.js'
Error: Error: Pod failed to come online with error: Error: Pod runner-scale-set-9wbg5-runner-spmjr-workflow is unhealthy with phase status Failed
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

### Describe the bug

We use dynamic scaling for our runner node pool so when an action is triggered there is a bit of a delay before a node is ready, this seems to be causing a lot of our jobs to fail with the above error message

### Describe the expected behavior

The runners should support some kind of retry mechanism when the initialization step fails

### Whole Controller Logs

```shell
N/A
```

### Whole Runner Pod Logs

```shell
N/A
```

### Additional Context
![Screenshot from 2023-09-14 13-49-53](https://github.com/actions/actions-runner-controller/assets/108266117/a1f54d66-859e-4a0b-a12a-3dd2135b4829)
#2031 
_No response_

**Comment by tkflexys** [comment]
Some more context here, it seems like kubelet fails to put the workflow pod on the right node because of resource constraints and then deletes it causing the failure, I wonder if this could be fixed by tweaking the workflow pod requests so that a more appropriate CPU request value would ensure proper scheduling.


```
I0915 08:08:30.902436    1997 kubelet.go:2075] "SyncLoop ADD" source="api" pods=[default/runner-scale-set-9wbg5-runner-jv4bj-workflow]

I0915 08:08:30.903328    1997 predicate.go:133] "Predicate failed on Pod" pod="default/runner-scale-set-9wbg5-runner-jv4bj-workflow" err="Node didn't have enough resource: cpu, requested: 100, used: 3903, capacity: 3920"

[background-id:b0bd5db7bedb2dfe] Syncing pod "default/runner-scale-set-9wbg5-runner-jv4bj-workflow"

[background-id:b0bd5db7bedb2dfe] Pod "default/runner-scale-set-9wbg5-runner-jv4bj-workflow" not found after refresh

I0915 08:08:30.939389    1997 kubelet.go:2091] "SyncLoop DELETE" source="api" pods=[default/runner-scale-set-9wbg5-runner-jv4bj-workflow]

audit_log, method: "io.k8s.core.v1.pods.delete", principal_email: "system:serviceaccount:default:runner-scale-set-gha-rs-kube-mode"

I0915 08:08:30.942423    1997 kubelet.go:2085] "SyncLoop REMOVE" source="api" pods=[default/runner-scale-set-9wbg5-runner-jv4bj-workflow]

[WORKER 2023-09-15 08:08:31Z INFO ExecutionContext]     "Error: Pod failed to come online with error: Error: Pod runner-scale-set-9wbg5-runner-jv4bj-workflow is unhealthy with phase status Failed",

[background-id:fd2e8b6cb7941751] Syncing pod "default/runner-scale-set-9wbg5-runner-jv4bj-workflow"

[background-id:fd2e8b6cb7941751] Pod "default/runner-scale-set-9wbg5-runner-jv4bj-workflow" not found
```

**Comment by tkflexys** [comment]
The biggest confusion is around specifying the runner specs as found here https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#updating-the-pod-specification-for-the-runner-pod

I would expect that those resource limits would apply to the pod that runs the action itself but it doesn't, in Kubernetes mode a second pod with the `-workflow` suffix is spawned which runs the action and doesn't inherit any of the specs we have set.

**Comment by tkflexys** [comment]
It seems like this problem has been reported here already https://github.com/actions/runner-container-hooks/issues/100

**Comment by guillaumevillemont** [comment]
Hi @tkflexys, I'm failing to see how this [container hooks resolution](https://github.com/actions/runner-container-hooks/issues/100) (`fixed with 0.4.0 release`) fixed your issue.

I'm having the same issue and I'm already using hook v0.4.0 as part as the latest actions-runner image. I'm providing a PodTemplate to specify resources : 

<details>
  <summary>PodTemplate ConfigMap</summary>
  
  ```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-templates
  namespace: gh-arc
data:
  default.yaml: |
    ---
    apiVersion: v1
    kind: PodTemplate
    metadata:
      name: runner-pod-template
      namespace: gh-arc
      labels:
        app: runner-pod-template
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 123
      containers:
      - name: $job
        resources:
          requests:
            cpu: 1000m
            memory: 8Gi
          limits:
            memory: 8Gi

  ```
  
</details>

but since it appears the `-workflow` pod get created on the same node as the runner, it's not getting a proper scheduling and get created on busy node without enough available resources. Hence it's getting OOM or OOCPU killed.

How did you solve your issue ?

**Comment by tkflexys** [comment]
> Hi @tkflexys, I'm failing to see how this [container hooks resolution](https://github.com/actions/runner-container-hooks/issues/100) (`fixed with 0.4.0 release`) fixed your issue.
> 
> I'm having the same issue and I'm already using hook v0.4.0 as part as the latest actions-runner image. I'm providing a PodTemplate to specify resources :
> PodTemplate ConfigMap
> 
> but since it appears the `-workflow` pod get created on the same node as the runner, it's not getting a proper scheduling and get created on busy node without enough available resources. Hence it's getting OOM or OOCPU killed.
> 
> How did you solve your issue ?

From what I can remember we created some dedicated nodes for the workers as the `-workflow` pods get scheduled alongside runners, we can essentially apply the resource requests to the runner to ensure it's spread out evenly

Here 500m cpu requests guarantees even scheduling for runners/workflow pods and the tolerations ensure that they go to the dedicated node
```
template:
  spec:
    containers:
    - name: runner
      image: "ghcr.io/actions/actions-runner:2.309.0"
      imagePullPolicy: IfNotPresent
      command: ["/home/runner/run.sh"]
      resources:
        requests:
          cpu: 500m
    tolerations:
    - key: "gh-runner-worker"
      operator: "Exists"
      effect: "NoSchedule"
    nodeSelector:
      workerType: gh
```
