### ISSUE TITLE
gha-runner-scale-set is not usable with ArgoCD

### ISSUE THREAD

**Issue by DAGRSAG** [actions/actions-runner-controller#2949]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.6.1

### Helm Chart Version

0.6.1

### Deployment Method

ArgoCD

### cert-manager installation

-

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
php-runner-set:
  githubConfigUrl: REPO_URL
  githubConfigSecret: gha-github-secret
  runnerScaleSetName: php-runner
  runnerGroup: arc
  maxRunners: 3

  controllerServiceAccount:
    namespace: gha-system
    name: gha-controller-gha-rs-controller

  template:
    metadata:
      labels:
        runner-type: gha
        runner/access-mode: restricted
    spec:
      containers:
        - name: runner
          image: acraksarisman.azurecr.io/php-gha-runner:v1
          command: [/home/runner/run.sh]
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 1Gi
---
apiVersion: v2
name: gha-scale-sets
version: 1.0.0
dependencies:
  - name: gha-runner-scale-set
    version: 0.6.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    alias: php-runner-set

  - name: gha-runner-scale-set
    version: 0.6.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    alias: runner-set1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-scale-sets
  namespace: management
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gha-scale-sets
  project: name
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
    path: charts/gha-scale-sets
    repoURL: {{ .Values.sourceRepo }}
    targetRevision: {{ .Values.branch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
```

### To Reproduce

```markdown
I have created a simple application, which uses the oci chart `gha-runner-scale-set`. Then I've added the application to ArgoCD and it should deploy the app. 

The same happens also, when I completely remove the template configuration from `values.yaml`
```

### Describe the bug

ArgoCD shows the following error:
`AutoscalingRunnerSet.actions.github.com "php-runner" is invalid: [spec.template.spec.containers[0].env: Invalid value: "null": spec.template.spec.containers[0].env in body must be of type array: "null", spec.template.spec.containers[0].volumeMounts: Invalid value: "null": spec.template.spec.containers[0].volumeMounts in body must be of type array: "null"]`

### Describe the expected behavior

The whole application including the runners gets deployed. 

This is only possible, when I add some pseudo values to the spec template

```yaml
  template:
    metadata:
      labels:
        runner-type: gha
        runner/access-mode: restricted
    spec:
      containers:
        - name: runner
          image: acraksarisman.azurecr.io/php-gha-runner:v1
          command: [/home/runner/run.sh]
          env:
            - name: PSEUDO
              value: "1"
          volumeMounts:
            - name: test
              mountPath: /test-only
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 1Gi
      volumes:
        - name: test
          emptyDir: {}
```

This configuration works, but it is ugly to define some env and volumeMounts

### Whole Controller Logs

```shell
see bug description
```

### Whole Runner Pod Logs

```shell
see bug description
```
