### ISSUE TITLE
Allow nodeSelector for gha-runner-scale-set helm deployment

### ISSUE THREAD

**Issue by DPatrickBoyd** [actions/actions-runner-controller#2984]
### What would you like added?

Much like the controller helm chart for GHA, I would like to be able to assign my scale sets to specific nodes.

### Why is this needed?

Two different reasons why this is needed; first, I have each node on a separate subnet, which then has security rules for outbound traffic. Second, different teams have different hardware requirements, which I need to be able to select for using something like nodeSelector or affinity settings.

**Comment by LillyHolden-Tide** [comment]
It's not really well documented but CRD already has nodeSelector:  
 https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/crds/actions.github.com_autoscalingrunnersets.yaml#L7355
which can be passed through the helm chart here: 
https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/crds/actions.github.com_autoscalingrunnersets.yaml#L7355

So your values.yaml it should look something like this:
```
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
    nodeSelector: 
      my-key:my-value
    tolerations:
      - key: "my-key"
        operator: "Equal"
        value: "my-value"
        effect: "NoSchedule"
```
