### ISSUE TITLE
Worker pod will not run workflow in Kubernetes mode

### ISSUE THREAD

**Issue by stephen-tatari** [actions/actions-runner-controller#3002]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Stand up controller and Runner Scale Set with official Helm charts from v0.6.1 on Kubernetes 1.26.
2. define custom ConfigMap for the runner PodTemplate so that it uses a custom service account and specifies the fsGroup to mount the volume (described in the troubleshooting document).
3. Attempt to run an Actions workflow job on the `gha-runner-scale-set` runner group.
```

### Describe the bug

I'm attempting to create a single Runner Scale Set that will create worker pods in "kubernetes" mode. Per documentation and other issues I've found, I've modified the Helm `values.yaml` such that `containerMode.type` is undefined, and this is the value of `template`:

```yaml
template:
  spec:
    securityContext:
      fsGroup: 123
    serviceAccountName: gha-runners
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
            value: /home/runner/pod-templates/default.yaml
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: pod-templates
            mountPath: /home/runner/pod-templates
            readOnly: true
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "gp3"
              resources:
                requests:
                  storage: 1Gi
      - name: pod-templates
        configMap:
          name: pod-templates
```

I've created a separate Config Map for the container hook:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-templates
  namespace: gha-runners
data:
  default.yaml: |
    ---
    apiVersion: v1
    kind: PodTemplate
    metadata:
      name: runner-pod-template
      namespace: gha-runners
      labels:
        app: runner-pod-template
    spec:
      serviceAccountName: gha-runners
      securityContext:
        fsGroup: 123
```

If I attempt to run a workflow job without specifying a container, the job fails when running a step that uses `actions/checkout@v3` with the following error:

```
/home/runner/_work/_temp/08994f33-5f34-4fe7-ad8e-3dd24fa6d1d2.sh: line 1: git: command not found
```

If I specify a value for the container image like this:

```
container:
  image: ghcr.io/actions/actions-runner:latest
```

I get the following error during the "Initializing containers" step (prior to running any steps of the job I defined):

```
   Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  '
  Error: Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'version --format '{{.Server.APIVersion}}''.
```

It appears to me like it's running in `dind` mode even though I've laid out a template that should be compatible with Kubernetes.

### Describe the expected behavior

If I define an Actions workflow job to run on the `gha-runner-scale-set` runner, The runner pod creates a worker pod that runs in native Kubernetes mode and runs my job on that pod.

### Additional Context
Full gha-runner-scale-set values.yaml:

```yaml
githubConfigUrl: "https://github.com/<myorg>"
githubConfigSecret: gha-runners
maxRunners: 2
minRunners: 1
template:
  spec:
    securityContext:
      fsGroup: 123
    serviceAccountName: gha-runners
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
            value: /home/runner/pod-templates/default.yaml
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: pod-templates
            mountPath: /home/runner/pod-templates
            readOnly: true
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "gp3"
              resources:
                requests:
                  storage: 1Gi
      - name: pod-templates
        configMap:
          name: pod-templates
controllerServiceAccount:
  namespace: gha-system
  name: gha-controller
```

### Controller Logs

https://gist.github.com/stephen-tatari/6a7b7c6303e5d43efe738320e8bcb387

### Runner Pod Logs

https://gist.github.com/stephen-tatari/124ebe12d76fb639e3bee69622a6244a

**Comment by nikola-jokic** [comment]
Hey @stephen-tatari,

You missed some environment variables that are instructing the runner to run in k8s mode. If you look at the documented `values.yaml` section for the [containerMode.type=kubernetes](https://github.com/actions/actions-runner-controller/blob/e1edb84abe646d23d210bd57b233da1a2cc4fe3b/charts/gha-runner-scale-set/values.yaml#L160C11-L160C40), you can see that `ACTIONS_RUNNER_CONTAINER_HOOKS` and `ACTIONS_RUNNER_POD_NAME` envs are set.  The first one explains where the hook script is, while the second one allows the script to spin up and associate job pods with the runner.

With the way you specified the values.yaml, runner is not aware that it should invoke the hook instead of docker commands and thus failing and showing that the docker socket is not present.

**Comment by stephen-tatari** [comment]
Thanks for the response. I do have `ACTIONS_RUNNER_POD_NAME` set as in the documented values, but you're right, I'm missing `ACTIONS_RUNNER_CONTAINER_HOOKS`. I think I was confusing it for `ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE`. That said, it would be nice to see some more official documentation around how to properly configure some custom Kubernetes mode runners where you need to define a separate `PodTemplate`.

**Comment by stephen-tatari** [comment]
Looks like it works. At least, I can get a `worker` pod that accepts my tests in bash. One more thing I'm trying to figure out here (and I apologize if I'm missing something in the docs), but what container image should I specify in the Actions workflow job to get a runner that matches (or is as close as possible to) what I'd get if I ran this on a GitHub-hosted runner?

I tried this with `ghcr.io/actions/actions-runner:latest`, but got `git: command not found`:

```yaml
jobs:
  test:
    name: Unit Tests
    runs-on: gha-runner-scale-set
    timeout-minutes: 10
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - uses: actions/checkout@v3
```
