### ISSUE TITLE
Scaleset not created due to RBAC error

### ISSUE THREAD

**Issue by marcusramberg** [actions/actions-runner-controller#3012]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Deployed the following to EKS using helmfile - See values below for the used settings.
```

### Describe the bug

Controller is created correctly, but it fails to create the scaleset because of an RBAC role permissions error (see logs below)

### Describe the expected behavior

Expecting the scaleset to be created. I was able to get it to work by editing the created cluster role and adding `create` permissions to the gha-runner-scaleset-controller-gha-rs-controller cluster-role for rolebindings and roles:

```
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - list
  - watch
  - patch
  - create
```

### Additional Context

```yaml
- chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    version: 0.6.1
    name: gha-runner-scaleset-controller
    namespace: runners
    installed: true
    values:
      - flags:
          logFormat: json
  - chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    version: 0.6.1
    name: cs-linux-gha-runner-scaleset
    installed: true
    namespace: runners
    values:
      - githubConfigUrl: https://github.com/our-org
        githubConfigSecret:
          github_token: <token secret>
        controllerServiceAccount:
          name: gha-runner-scaleset-controller-gha-runner-scale-set-controller
          namespace: runners
        runnerGroup: scaleset
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
                resources:
                  requests:
                    cpu: "2.0"
                    memory: "4Gi"
```
```


### Controller Logs

```shell
gha-runner-scaleset-controller-gha-rs-controller-c68b549bb6phzm manager {"severity":"error","ts":"2023-10-23T10:43:33Z","logger":"AutoscalingListener","message":"Unable to create listener role","autoscalinglistener":"runners/cs-linux-gha-runner-scaleset-7d446b46-listener","namespace":"runners","name":"cs-linux-gha-runner-scaleset-7d446b46-listener","rules":[{"verbs":["patch"],"apiGroups":["actions.github.com"],"resources":["ephemeralrunnersets"],"resourceNames":["cs-linux-gha-runner-scaleset-8m8tt"]},{"verbs":["patch"],"apiGroups":["actions.github.com"],"resources":["ephemeralrunners","ephemeralrunners/status"]}],"error":"roles.rbac.authorization.k8s.io is forbidden: User \"system:serviceaccount:runners:gha-runner-scaleset-controller-gha-rs-controller\" cannot create resource \"roles\" in API group \"rbac.authorization.k8s.io\" in the namespace \"runners\"","stacktrace":"github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*AutoscalingListenerReconciler).createRoleForListener\n\tgithub.com/actions/actions-runner-controller/controllers/actions.github.com/autoscalinglisten
```
```


### Runner Pod Logs

```shell
Not relevant as the runner isn't created due to the permissions error.
```
