### ISSUE TITLE
ephemeralrunners.actions.github.com out of sync with running pods

### ISSUE THREAD

**Issue by adiroiban** [actions/actions-runner-controller#3014]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
I have a cluster for which the nodes can go offline before a drain.

To reproduce, turn of a node in a cluster, without a draing.
```

### Describe the bug

I have a runner set that is configured to have a minium of 4 runners.

I can see the 4 CRD objects.

```
$ kubectl get -n arc-runners ephemeralrunners.actions.github.com
NAME                                GITHUB CONFIG URL                  RUNNERID   STATUS    JOBREPOSITORY   JOBWORKFLOWREF                                                                 WORKFLOWRUNID   JOBDISPLAYNAME                        MESSAGE                                     AGE
arc-runner-set-s7hwz-runner-bknms   https://github.com/chevah/server   692        Failed    chevah/server   chevah/server/.github/workflows/installer.yaml@refs/pull/6419/merge            6597771588      Ubuntu 22.04 x64 Installer            Pod has failed to start more than 5 times   2d2h
arc-runner-set-s7hwz-runner-ngvvt   https://github.com/chevah/server   783        Running                                                                                                                                                                                                    4h14m
arc-runner-set-s7hwz-runner-pv92p   https://github.com/chevah/server   690        Failed    chevah/server   chevah/server/.github/workflows/release.yaml@refs/heads/6279-arc-linux-arm64   6597771472      Distributable Py3 Generic Linux X64   Pod has failed to start more than 5 times   2d2h
arc-runner-set-s7hwz-runner-wfk4z   https://github.com/chevah/server   695        Failed    chevah/server   chevah/server/.github/workflows/release.yaml@refs/heads/6279-arc-linux-arm64   6597771472      download and docs - development       Pod has failed to start more than 5 times   2d2h
```

But I only have 1 pod

```
$ kubectl get -n arc-runners pods
NAME                                READY   STATUS    RESTARTS   AGE
arc-runner-set-s7hwz-runner-ngvvt   1/1     Running   0          4h15m
```

and on GitHub only one runner is registered (I also have separate set)

![image](https://github.com/actions/actions-runner-controller/assets/204609/684d93cb-9b95-405e-ba82-99c20b06a601)

### Describe the expected behavior

I was expecting to see a total of 4 pods in that namespace and 4 GitHub runners registered on GitHub.com

### Additional Context

```yaml
## We install it only on the repo.
githubConfigUrl: "https://github.com/chevah/server"

## githubConfigSecret is the k8s secrets to use when auth with GitHub API.
## We use a PAT stored in a separate secret
githubConfigSecret: pre-defined-secret


## proxy can be used to define proxy settings that will be used by the
## controller, the listener and the runner of this scale set.
#
# proxy:
#   http:
#     url: http://proxy.com:1234
#     credentialSecretRef: proxy-auth # a secret with `username` and `password` keys
#   https:
#     url: http://proxy.com:1234
#     credentialSecretRef: proxy-auth # a secret with `username` and `password` keys
#   noProxy:
#     - example.com
#     - example.org

## maxRunners is the max number of runners the autoscaling runner set will scale up to.
maxRunners: 27

## minRunners is the min number of runners the autoscaling runner set will scale down to.
minRunners: 3

# runnerGroup: "default"

## name of the runner scale set to create.  Defaults to the helm release name
# runnerScaleSetName: ""

## A self-signed CA certificate for communication with the GitHub server can be
## provided using a config map key selector. If `runnerMountPath` is set, for
## each runner pod ARC will:
## - create a `github-server-tls-cert` volume containing the certificate
##   specified in `certificateFrom`
## - mount that volume on path `runnerMountPath`/{certificate name}
## - set NODE_EXTRA_CA_CERTS environment variable to that same path
## - set RUNNER_UPDATE_CA_CERTS environment variable to "1" (as of version
##   2.303.0 this will instruct the runner to reload certificates on the host)
##
## If any of the above had already been set by the user in the runner pod
## template, ARC will observe those and not overwrite them.
## Example configuration:
#
# githubServerTLS:
#   certificateFrom:
#     configMapKeyRef:
#       name: config-map-name
#       key: ca.crt
#   runnerMountPath: /usr/local/share/ca-certificates/

## Container mode is an object that provides out-of-box configuration
## for dind and kubernetes mode. Template will be modified as documented under the
## template object.
##
## If any customization is required for dind or kubernetes mode, containerMode should remain
## empty, and configuration should be applied to the template.
containerMode:
  type: "kubernets"  ## type can be set to dind or kubernetes
  ## the following is required when containerMode.type=kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    # For local testing, use https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md to provide dynamic provision volume with storageClassName: openebs-hostpath
    storageClassName: "dynamic-blob-storage"
    resources:
      requests:
        storage: 1Gi

## template is the PodSpec for each listener Pod
## For reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
# listenerTemplate:
#   spec:
#     containers:
#     # Use this section to append additional configuration to the listener container.
#     # If you change the name of the container, the configuration will not be applied to the listener,
#     # and it will be treated as a side-car container.
#     - name: listener
#       securityContext:
#         runAsUser: 1000
#     # Use this section to add the configuration of a side-car container.
#     # Comment it out or remove it if you don't need it.
#     # Spec for this container will be applied as is without any modifications.
#     - name: side-car
#       image: example-sidecar

## template is the PodSpec for each runner Pod
## For reference:
## https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
template:
  spec:
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      # fsGroup is ignored by hostPath
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"
    containers:
      - name: runner
        # Default image was ghcr.io/actions/actions-runner:latest
        image: ghcr.io/chevah/arc-runner:2.310.2.ci.8-x64
        command: ["/home/runner/run.sh"]
        env:
          - name: CHEVAH_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CHEVAH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: hostedtoolcache
            mountPath: /opt/hostedtoolcache
    volumes:
      - name: hostedtoolcache
        hostPath:
          # directory location on host
          path: /tmp/arc
          type: DirectoryOrCreate

```

### Controller Logs

https://gist.github.com/adiroiban/5973c0c5a78395440db91faa3d9edb43

### Runner Pod Logs

```shell
There is no pod.
THe pod that is active, works ok.
```
