### ISSUE TITLE
Container Hooks creating a new step pod to be created causing the action to fail

### ISSUE THREAD

**Issue by nathanwong91** [actions/actions-runner-controller#3025]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Use `super-linter` with a self hosted kubernetes runner.
```

### Describe the bug

The action causing a new step pod to be created is `super linter`.

```
jobs:
  superlinter:
    runs-on: selfhosted-runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: master
          DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
```

You see the usual logs for actions such as 
```
Run actions/checkout@v3
Run github/super-linter/slim@v5
```
However after `Run github/super-linter/slim@v5` I see `Run '/home/runner/k8s/index.js'` in that step. This is spawning a new step pod `selfhoster-runner-f4zm4-runner-d69s2-step-8e232917znx2t` from the original pod `selfhoster-runner-f4zm4-runner-d69s2` which I believe is missing the same configs that the original runner pod has as it fails with the following error
```
time [INFO]   Successfully found:[GITHUB_EVENT_PATH], value:[/github/workflow/event.json]
/action/lib/linter.sh: line 537: /github/workflow/event.json: No such file or directory
/action/lib/linter.sh: line 545: /github/workflow/event.json: No such file or directory
2023-10-26 04:45:24 [ERROR]   Failed to get [GITHUB_ORG]!
2023-10-26 04:45:24 [FATAL]   []
Error: Error: job selfhosted-runner-f4zm4-runner-d69s2-step-8e232917 has failed
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

### Describe the expected behavior

This only seems to happen with the new Scale Set runners. We've been using Community ARC for over a year now and this has not happened.

Why is this hook activating now and here? We have not encountered this hook running anywhere else during our testing.

### Additional Context

```yaml
Current config

githubConfigUrl: 'https://github.com/ourorg'
githubConfigSecret: github-token

minRunners: 2
runnerGroup: 'selfhosted-runner'
runnerScaleSetName: 'selfhosted-runner'

containerMode:
  type: 'kubernetes'

template:
  spec:
    ## this is required for non-root to access the pvc
    securityContext:
      fsGroup: 123
    containers:
      - name: runner
        command: ['/home/runner/run.sh']
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: 'false'
        image: selfhostedrunnerimage:1
        volumeMounts:
          - mountPath: /home/runner/_work
            name: work
    serviceAccountName: runner-role
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: ['ReadWriteOnce']
              storageClassName: gp3
              resources:
                requests:
                  storage: 1Gi

controllerServiceAccount:
  namespace: github-actions-runners
  name: gha-runner-set-controller
```
```


### Controller Logs

```shell
Nothing of note to assist in this
```

### Runner Pod Logs

```shell
Nothing of note to assist in this
```

**Comment by nikola-jokic** [comment]
Hey @nathanwong91,

Can you please try applying the following yaml and let us know if it solves the issue?

```yaml
githubConfigUrl: 'https://github.com/ourorg'
githubConfigSecret: github-token

minRunners: 2
runnerGroup: 'selfhosted-runner'
runnerScaleSetName: 'selfhosted-runner'

containerMode:
  type: 'kubernetes'
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "gp3"
    resources:
      requests:
        storage: 1Gi

template:
  spec:
    ## this is required for non-root to access the pvc
    securityContext:
      fsGroup: 123
    containers:
      - name: runner
        image: selfhostedrunnerimage:1
        command: ['/home/runner/run.sh']
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: 'false'


controllerServiceAccount:
  namespace: github-actions-runners
  name: gha-runner-set-controller
```
