### ISSUE TITLE
Runner Scale Sets Controller cannot create new Runner pod

### ISSUE THREAD

**Issue by stephen-tatari** [actions/actions-runner-controller#3042]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Create a GitHub App and save the secret values to a secret in a pre-existing namespace with an app running.
2. Deploy the Runner Scale Sets Controller Helm chart to its own namespace
3. Deploy the Runner Scale Set Helm chart to the same namespace as in step 1, specifying the secret created in step 1.
4. Attempt to run an Actions workflow job on the Runner Scale Set.
```

### Describe the bug

When I attempt to run a workflow job on the Runner Scale Set, I see an error from the controller manager stating that it can't find the GitHub config secret:

```
❯ kubectl logs -n gha-system -l app.kubernetes.io/instance=gha-runner-scale-set-controller
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
2023-11-02T21:12:22Z    ERROR   Reconciler error        {"controller": "autoscalingrunnerset", "controllerGroup": "actions.github.com", "controllerKind": "AutoscalingRunnerSet", "AutoscalingRunnerSet": {"name":"test-some-testserver","namespace":"some-testserver"}, "namespace": "some-testserver", "name": "test-some-testserver", "reconcileID": "cae03d98-94b2-40a0-a47c-3e4d384286e2", "error": "failed to find GitHub config secret: secrets \"gha-runners\" is forbidden: User \"system:serviceaccount:gha-system:gha-rss-controller\" cannot get resource \"secrets\" in API group \"\" in the namespace \"some-testserver\""}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
```

From the log, it looks like the controller manager is attempting (via its service account `gha-system:gha-rss-controller`) to access the secret `gha-runners` in the `some-testserver` namespace. That secret does exist, and from the documentation and Helm chart values and templates, it would indicate that it's the Runner Scale Set that needs access to the secret to authenticate against GitHub, not the controller manager.

### Describe the expected behavior

I'm expecting an ephemeral runner pod to start up and run the workflow job.

### Additional Context

controller values.yaml:
```yaml
labels: {}
replicaCount: 1
image:
  repository: "ghcr.io/actions/gha-runner-scale-set-controller"
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: "gha-rss-controller"
fullnameOverride: "gha-rss-controller"
env: {}
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
priorityClassName: ""
flags:
  logLevel: "debug"
  logFormat: "text"
  updateStrategy: "immediate"
```

runner scale set values.yaml:
```yaml
  runnerScaleSetName: "test-some-testserver"
  githubConfigUrl: "https://github.com/tatari-tv"
  githubConfigSecret: gha-runners
  nameOverride: "some-testserver-gha"
  minRunners: 1
  maxRunners: 2
  controllerServiceAccount:
    namespace: gha-system
    name: gha-controller
  template:
    metadata:
      labels:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext:
        fsGroup: 123
      serviceAccountName: gha-runners
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOKS
              value: /home/runner/k8s/index.js
            - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
              value: /home/runner/pod-templates/default.yaml
            - name: ACTIONS_RUNNER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "true"
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: pod-templates
              mountPath: /home/runner/pod-templates
              readOnly: true
      volumes:
        - name: work
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                storageClassName: "gha"
                resources:
                  requests:
                    storage: 10Gi
        - name: pod-templates
          configMap:
            name: gha-pod-templates
```

### Controller Logs

```shell
https://gist.github.com/stephen-tatari/1343a10097bd8d5fe47c9f51d3a248fa
```

### Runner Pod Logs

```shell
N/A (runner pod does not start)
```
