### ISSUE TITLE
Starting up listener fails on GitHub enterprise 3.10.2

### ISSUE THREAD

**Issue by ArthurSchiavom** [actions/actions-runner-controller#3048]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

Using:
ARC version: 0.6.1
Deployment method: helm
GitHub version: GitHub Enterprise Server 3.10.2

1. Set the controller (gha-runner-scale-set-controller) values.yaml to:

```yaml
labels: {}

replicaCount: 1

image:
  # Note: image pushed to <private_repo> with these commands:
  # docker pull ghcr.io/actions/gha-runner-scale-set-controller:0.6.1
  # docker tag ghcr.io/actions/gha-runner-scale-set-controller:0.6.1 <private_repo>/actions/gha-runner-scale-set-controller:0.6.1
  # docker push <private_repo>/actions/gha-runner-scale-set-controller:0.6.1
  repository: "<private_repo>/actions/gha-runner-scale-set-controller"
  pullPolicy: IfNotPresent
  tag: "0.6.1"

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

env:

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""

flags:
  logLevel: "debug"
  logFormat: "text"

  watchSingleNamespace: "github-runners"

  updateStrategy: "immediate"
```

2. Apply it using `helm install arc-controller --namespace github-runners --set image.tag="0.6.1" --version "0.6.1" . --set=githubURL="https://<github_enterprise_url>/api/v3"`

3. Set the listener (gha-runner-scale-set) values.yaml to:
```yaml
githubConfigUrl: "https://<github_enterprise_url>/<organization>"

githubConfigSecret: github-app

## maxRunners is the max number of runners the autoscaling runner set will scale up to.
maxRunners: 5

## minRunners is the min number of runners the autoscaling runner set will scale down to.
minRunners: 2

runnerGroup: "arc-runner-group"
  spec:
    containers:
      - name: runner
        # Pulled using these commands:
        # docker pull ghcr.io/actions/actions-runner:2.311.0
        # docker tag ghcr.io/actions/actions-runner:2.311.0 <private_repo>/actions/actions-runner:2.311.0
        # docker push <private_repo>/actions/actions-runner:2.311.0
        image: <private_repo>/actions/actions-runner:2.311.0
# also tried with the runner version 2.304.0, which is the version that shows up when I click the "New runner" button in GitHub.
#        image: <private_repo>/actions/actions-runner:2.304.0
        command: ["/home/runner/run.sh"]
    imagePullSecrets:
      - name: regcred
```

4. Apply the listener configuration using `helm install scaleset --namespace github-runners -f values.yaml --version 0.6.1 . --set=githubURL="https://<github_enterprise_url>/api/v3"`

### Describe the bug

The listener restarts infinitely and states that it does not find the input EphemeralRunnerSetNamespace and/or EphemeralRunnerSetName, and prints the values it finds in them: EphemeralRunnerSetNamespace='github-runners', EphemeralRunnerSetName=''.

### Describe the expected behavior

The listener should start up and start runners up.

### Additional Context

* Listener/Scale set logs: https://gist.github.com/ArthurSchiavom/2c854c3e5c94507e66d3bbaf09d1468e#file-listenererrorlogs-log

* Runners are registered in the runner group when scale sets are created and removed when scale sets are removed

### Controller Logs

https://gist.github.com/ArthurSchiavom/8f96761c688da8f0c4ea62e8cefd85f5

### Runner Pod Logs

The runner itself never starts up.

Edit: remove commented lines from yaml files for easier readability + formatting
