### ISSUE TITLE
Failed to clean up container hooks resources: "failed to list runner-linked secrets" 

### ISSUE THREAD

**Issue by joshuabaird** [actions/actions-runner-controller#3054]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
N/A
```

### Describe the bug

I have installed a fresh copy of gha-runner-scale-set-controller and gha-scale-set, and I am observing the following errors in the controller logs:

```
gha-runner-scale-set-controller-gha-rs-controller-6f755869npbkz manager {"severity":"error","ts":"2023-11-08T19:07:00Z","logger":"EphemeralRunner","message":"Failed to clean up container hooks resources","ephemeralrunner":"arc-systems/gha-runner-scale-set-5dfdk-runner-f9qxq","error":"failed to list runner-linked secrets: secrets is forbidden: User \"system:serviceaccount:arc-systems:arc\" cannot list resource \"secrets\" in API group \"\" in the namespace \"arc-systems\"","stacktrace":"github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*EphemeralRunnerReconciler).Reconcile\n\tgithub.com/actions/actions-runner-controller/controllers/actions.github.com/ephemeralrunner_controller.go:115\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235"}

gha-runner-scale-set-controller-gha-rs-controller-6f755869npbkz manager {"severity":"error","ts":"2023-11-08T19:07:00Z","message":"Reconciler error","controller":"ephemeral-runner-controller","controllerGroup":"actions.github.com","controllerKind":"EphemeralRunner","EphemeralRunner":{"name":"gha-runner-scale-set-5dfdk-runner-f9qxq","namespace":"arc-systems"},"namespace":"arc-systems","name":"gha-runner-scale-set-5dfdk-runner-f9qxq","reconcileID":"48541a1d-1944-4d02-a429-178df398964d","error":"failed to list runner-linked secrets: secrets is forbidden: User \"system:serviceaccount:arc-systems:arc\" cannot list resource \"secrets\" in API group \"\" in the namespace \"arc-systems\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235"}
```

Here are the values I am using:

```
helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.6.1
    releaseName: gha-runner-scale-set-controller
    namespace: arc-systems
    valuesInline:
      githubConfigSecret: controller-manager
      flags:
        logLevel: info
        logFormat: json
      serviceAccount: 
        create: false
        name: arc
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.6.1
    releaseName: platform-utility
    namespace: arc-runners
    valuesInline:
      githubConfigUrl: https://github.com/galileo-inc
      githubConfigSecret: controller-manager
      controllerServiceAccount:
        namespace: arc-systems
        name: arc
      minRunners: 1
      maxRunners: 10
```

I am bringing my own _ServiceAccount_ here which may be an issue?

### Describe the expected behavior

No errors.

### Additional Context

```yaml
N/A
```

### Controller Logs

```shell
https://gist.github.com/joshuabaird/00b2eac5dbba57ca888d8d52ec6cc4cd
```

### Runner Pod Logs

```shell
https://gist.github.com/joshuabaird/668629c5eb22f68aac696e28f4559408
```
