### ISSUE TITLE
Installing arc-runner-set with helm doesn't deploy pods in the namespace.

### ISSUE THREAD

**Issue by namhyuck-kim-otsk** [actions/actions-runner-controller#3076]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
I've followed the official guideline to install gha-runner-scale-set-controller / gha-runner-scale-set.

### Install controller


NAMESPACE="arc-systems"
helm install arc \
    --namespace "${NAMESPACE}" \
    --create-namespace \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
```

### Create secret for Github App
```
kubectl create secret generic one-arc-secret \
   --namespace=my_namespace \
   --from-literal=github_app_id=xxxxxx \
   --from-literal=github_app_installation_id=xxxxxx \
   --from-file=github_app_private_key=(path to pem file)
```

### Install Runnerset

```
INSTALLATION_NAME="arc-runner-set"
NAMESPACE="arc-runners"
CONFIG_FILE=[Config File Path (values.yaml)]
helm install "${INSTALLATION_NAME}" \
    --namespace "${NAMESPACE}" \
    --create-namespace \
    -f ${CONFIG_FILE}
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
```

### Describe the bug

Following the installation guide, I expect to see runner-set listener in the `arc-systems` namespace and runner pods (minium pod = 3) in the `arc-runners` namespace. But I don't see any of them. 

The runners do not appear on Github Runner list as well.

### Describe the expected behavior

- Expect Github Runner Pods and Listener in respective namespaces.
- Github Runner appears on GitHub Runner List / Group

### Additional Context

```yaml
value.yaml

## githubConfigUrl is the GitHub url for where you want to configure runners
## ex: https://github.com/myorg/myrepo or https://github.com/myorg
githubConfigUrl: "https://github.com/xxxxxxx"

## githubConfigSecret is the k8s secrets to use when auth with GitHub API.
## You can choose to use GitHub App or a PAT token
githubConfigSecret: xxx-xxx-secret

## maxRunners is the max number of runners the autoscaling runner set will scale up to.
maxRunners: 5

## minRunners is the min number of runners the autoscaling runner set will scale down to.
minRunners: 3

runnerGroup: "ARC-TEST"

## name of the runner scale set to create.  Defaults to the helm release name
# runnerScaleSetName: ""

containerMode:
  type: "dind"  ## type can be set to dind or kubernetes

spec:
  containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]

```

### Controller Logs

```shell
https://gist.github.com/namhyuck-kim-otsk/cf0d4f1edf04c846d3290368bf010d19
```

### Runner Pod Logs

```shell
No Runner Pod Logs since no runner pod is running.
```
