### ISSUE TITLE
Upgrading to 0.7.0 from 0.6.1 broke listeners and couldn't revert back to 0.6.1

### ISSUE THREAD

**Issue by mattpopa** [actions/actions-runner-controller#3082]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. have 0.6.1 controller and scale-set running, auth with gh app
2. update version to 0.7.0 to controller and scale-set
3. listeners do not come up anymore, no errors in the controller
4. rolled back doesn't help, now listeners don't start on 0.6.1

managed to restore by
5. delete cdrs
6. delete/redeploy controller on 0.6.1
7. delete/redeploy sets on 0.6.1
```

### Describe the bug

Did the update to 0.7.0 mainly for the cardinality fix, and 0.7.0 broke the scale-sets, listeners gone, no error logs, not much to investigate/figure out why this is happening. Using github app for auth.

The most annoying part was that restore on 0.6.1 didn't help, and I had to remove the CRDs and reinstall the controller + sets one by one.

### Describe the expected behavior

1. Update to 0.7.0 from 0.6.1
2. Controller starts up successfully
3. Listeners start up and connect to gh using the same gh app config
4. business as usual

### Additional Context

```yaml
This is a dind setup, but the problem is related to CRDs and listeners. Deployment's via helm chart

Using terraform with helm provider to deploy

# controller vars
image:
  repository: "ghcr.io/actions/gha-runner-scale-set-controller"
  pullPolicy: IfNotPresent
  tag: ${arc_version}

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: "/metrics"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8080"
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

nodeSelector:
  pool: ${arc_pool}

priorityClassName: ${arc_priority_class}

flags:
  ## Log level can be set here with one of the following values: "debug", "info", "warn", "error".
  logLevel: "error"
  ## Log format can be set with one of the following values: "text", "json"
  logFormat: "json"
  updateStrategy: "immediate"



# scale-set vars

githubConfigUrl: "https://github.com/my-org"
githubConfigSecret: my-org-arc

maxRunners: 25
minRunners: 0

runnerScaleSetName: "small-set"

listenerTemplate:
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  spec:
    priorityClassName: ${arc_priority_class}
    nodeSelector:
      pool: ${arc_pool}
    containers:
    - name: listener
      securityContext:
        runAsUser: 1000

template:
  metadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  spec:
    serviceAccountName: ${runners_sa}
    priorityClassName: ${arc_priority_class}
    nodeSelector:
      pool: ${runner_pool}
    imagePullSecrets:
      - name: dockerhub-auth
    initContainers:
    - name: init-dind-externals
      image: my-org/ci-custom-runner:runner-${custom_img}
      command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
      volumeMounts:
        - name: dind-externals
          mountPath: /home/runner/tmpDir
    containers:
    - name: runner
      image: my-org/ci-custom-runner:runner-${custom_img}
      command: ["/home/runner/run.sh"]
      env:
        - name: DOCKER_HOST
          value: unix:///run/docker/docker.sock
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /run/docker
          readOnly: true
    - name: dind
      image: my-org/ci-custom-runner:dind-${custom_img}
      args:
        - dockerd
        - --host=unix:///run/docker/docker.sock
        - --group=$(DOCKER_GROUP_GID)
      env:
        - name: DOCKER_GROUP_GID
          value: "123"
      securityContext:
        privileged: true
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /run/docker
        - name: dind-externals
          mountPath: /home/runner/externals
      resources:
        requests:
          memory: "2Gi"
          cpu: "900m"
        limits:
          memory: "2Gi"
          cpu: "900m"
    volumes:
    - name: work
      emptyDir: {}
    - name: dind-sock
      emptyDir: {}
    - name: dind-externals
      emptyDir: {}

ci-custom-runner:runner is  FROM ghcr.io/actions/actions-runner:latest + zip, unzip, jq, wget, aws-iam-authenticator, etc
ci-custom-runner:dind is FROM FROM docker:dind + docker registry cache injected RUN echo "{\"registry-mirrors\": [\"http://${REGISTRY_CACHE_IP}:${REGISTRY_CACHE_PORT}\"]}" > /etc/docker/daemon.json
```

### Controller Logs

```shell
The controller log level was set on ERROR and it was blank -- no errors in the controller
```

### Runner Pod Logs

```shell
This is the main problem, because there are no errors in the controller and the listeners are gone. There are no listeners + no runner pods to get errors from.
```
