### ISSUE TITLE
Listener randomly turns non-responsive after some time

### ISSUE THREAD

**Issue by audunsolemdal** [actions/actions-runner-controller#3100]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Create a runner group, e.g. `my-group`
Create self hosted runner via ARC, link it to `my-group`
In github actions yaml, make your jobs target the runner group


runs-on:
  group: my-group

Run some jobs
wait patiently
This will work fine for some days, then all of a sudden the listener seems to freeze for no obvious reason
```

### Describe the bug

The listener works fine to start with and jobs are assigned as usual. After some time (days) it seems that the listener freezes. It seems random when this occurs. This results in requested jobs not being assigned.

Once the listener pod is deleted/recreated, jobs are instantly assigned as expected. Without restarting the listener pod it seems that the listener pod stops working without any output indicating that it failed. I do not see any blocked network traffic, so I do not believe that to be the issue.

### Describe the expected behavior

Business as usual

### Additional Context

```yaml
The listener does not detect new jobs for some time. Restarting the listener pod solves the issue

YAML for helm chart


securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

labels:
  app: actions-runner-controller

priorityClassName: platform-high

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists



yaml for runnerset:

githubConfigUrl: "https://github.com/myorg"
githubConfigSecret: "pre-defined-secret"

runnerGroup: mygroup

template:
  spec:
    containers:
      - name: runner
        image: mycustomrunnerimage:latest
        command: ["/home/runner/run.sh"]
        resources:
          limits:
            memory: "1Gi"
            cpu: "700m"
          requests:
            cpu: "75m"
            memory: "250Mi"

minRunners: 0

```

### Controller Logs

```shell
Logs are completely empty in the relevant period
```

### Runner Pod Logs

```shell
Listener logs:
--- several previous successful refreshing_client runs on an hourly basis before this
2023-11-22T18:35:24Z   INFO    refreshing_client    message queue token is expired during GetNextMessage, refreshing...
2023-11-22T18:35:24Z    INFO    refreshing token        {"githubConfigUrl": "https://github.com/myorg"}
2023-11-22T18:35:24Z    INFO    getting access token for GitHub App auth        {"accessTokenURL": "https://api.github.com/app/installations/myappid/access_tokens"}
2023-11-23T08:35:29Z    INFO    getting runner registration token       {"registrationTokenURL": "https://api.github.com/orgs/myorg/actions/runners/registration-token"}
2023-11-23T08:35:30Z    INFO    getting Actions tenant URL and JWT      {"registrationURL": "https://api.github.com/actions/runner-registration"}
-- No further output until pod is restarted
```
