### ISSUE TITLE
Configure Worker Resources

### ISSUE THREAD

**Issue by MartiUK** [actions/actions-runner-controller#3108]
### What would you like added?

When running in `kubernetes` mode, a workflow pod is created for each job. Unfortunately, there doesn't seem to be a way to configure the CPU & memory resource requests and limits for these worker pods, despite setting resource requests/limits on the runner containers.

### Why is this needed?

A tool such as yarn will use as much CPU and memory as possible to complete its task. As such, when pods are created without resource limits, they can starve the node and prevent other services or workers from running on it. This also means that clusters with cluster autoscaling cannot scale to handle large spikes of workflow runs.

### Additional context

<img width="800" alt="image" src="https://github.com/actions/actions-runner-controller/assets/1244603/569dd6ac-bed8-48e4-81c3-d814f1155ed9">

**Comment by johnoloughlin** [comment]
Cant it be limited like this? maybe I misunderstand

```apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-runner
spec:
  replicas: 2
  template:
    spec:
      repository: myrepo
      labels:
         - my-runner
      containers:
        - name: runner
          resources:
            limits:
              cpu: "250m"
              hugepages-2Mi: 2Gi
              memory: 100Mi
            requests:
              cpu: "250m"
              memory: 100Mi
              hugepages-2Mi: 2Gi
          volumeMounts:
            - mountPath: /dev/hugepages
              name: hugepage
          env:
            - name: USER
              value: "runner"
      volumes:
        - name: hugepage
          emptyDir:
            medium: HugePages
```

**Comment by MartiUK** [comment]
@johnoloughlin I'm using runner scale sets via the helm chart, there doesn't seem to be a way to set the resources specifically for the worker pod that is created, it's only set on the `runner` pod.

**Comment by MichaelHudgins** [comment]
I was looking for something similar, i don't see a way to pass through resources like GPUs because they need the limit set on the pod actually running the workflow.

**Comment by MichaelHudgins** [comment]
For others here i found this: https://github.com/actions/actions-runner-controller/discussions/3107#discussioncomment-7691417 which looks to allow for what is needed

**Comment by omri-shilton** [comment]
does anyone have an example for the hook extension?

**Comment by MartiUK** [comment]
@omri-shilton

```yaml
---
<snip>
          env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
            value: /etc/config/runner-template.yaml
          volumeMounts:
          - mountPath: /home/runner/_work
            name: work
          - mountPath: /etc/config
            name: hook-template
        volumes:
        - name: hook-template
          configMap:
            name: runner-config
```
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-config
  namespace: actions-runners
data:
  runner-template.yaml: |
    ---
    spec:
      containers:
      - name: $job
        resources:
          limits:
            cpu: 2
            memory: 8Gi
          requests:
            cpu: 2
            memory: 8Gi
```

This still doesn't help us, unfortunately, we need a way to use the standard k8s scheduler and use inter-pod affinity to ensure the runner and the job pods are scheduled on the same node.

Ideally, there should be a shared label between the two pods that we can use to do this without needing to use ReadWriteMany storage providers.

**Comment by tskinner-oppfi** [comment]
>we need a way to use the standard k8s scheduler and use inter-pod affinity to ensure the runner and the job pods are scheduled on the same node

We are in the same boat. How does anyone successfully use this architecture with something like karpenter that is constantly scaling nodes up and down depending on the demand especially when assigning resources and things like pod affinity are difficult or impossible wrangle?

**Comment by zarko-a** [comment]
@tskinner-oppfi  we've manged to work around these issues partially by having a podAntiAffinty to force scheduling only one runner per k8s node and having the taints so that only the associated workflow pod [which has tolerations too] will schedule on the same node. 

Each runner set has it's own Karpenter node pool with instance size fixed to accommodate the total value of requests for runner and workflow pods. 
In our example below we have a runner requesting 500Mb of memory and workflow pod requesting 26Gb, so Karpenter node pool is configured with instances of 32GB of RAM (to leave some room for kubelet and daemonsets). 


here are the code snippets that we are using. it's far from ideal and kinda defeats the purpose of Karpenter packing pods efficiently but it works for the most part. 

I really hope that GH removes the need for shared volume, it's really not a common scenario in K8S. I don't know how GitLab does this, but we never had this issue with their self-hosted runners. 

We also tried with CephFS which supports `ReadWriteMany` volumes, but encountered the same problem that's described [here](https://github.com/actions/runner-container-hooks/issues/145). No solution yet.    


**Scale set values**
```
runnerScaleSetName: "linux-xxl-gha-runner-set"

containerMode:
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    # For local testing, use https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md to provide dynamic provision volume with storageClassName: openebs-hostpath
    resources:
      requests:
        storage: 5Gi

template:
  spec:
    securityContext:
      fsGroup: 123
    nodeSelector:
      example.com/node-pool: gha-runners-xxl
      kubernetes.io/os: linux
      kubernetes.io/arch: amd64
    tolerations:
      - key: "example.com/node-pool"
        operator: "Equal"
        value: "gha-runners-xxl"
        effect: "NoSchedule"
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "true"
          - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
            value: /home/runner/pod-templates/gh-runners-xxl.yaml
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: memory-storage
            mountPath: /mnt/memory/
          - name: pod-templates
            mountPath: /home/runner/pod-templates
            readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 2
            memory: 500Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - runner
          topologyKey: kubernetes.io/hostname
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "ebs-gp3"
              resources:
                requests:
                  storage: 5Gi
      - name: pod-templates
        configMap:
          name: pod-templates
      - name: memory-storage
        emptyDir:
          medium: Memory
          sizeLimit: 20Mi
```

excerpt from pod templates confgMap.

```
....
          gh-runners-xxl.yaml: |
            ---
            apiVersion: v1
            kind: PodTemplate
            metadata:
              name: default-pod-template
              labels:
                app: default-pod-template
              annotations:
                karpenter.sh/do-not-disrupt: "true"
            spec:
              nodeSelector:
                example.com/node-pool: gha-runners-xxl
              tolerations:
                - key: "example.com/node-pool"
                  operator: "Equal"
                  value: "gha-runners-xxl"
                  effect: "NoSchedule"
              securityContext:
                fsGroup: 123  # provides access to /home/runner/_work directory in ephemeral volume
              containers:
                - name: $job
                  volumeMounts:
                    - name: memory-storage
                      mountPath: /mnt/memory/
                  resources:
                    limits:
                      cpu: 16
                      memory: 26Gi
                    requests:
                      cpu: 14
                      memory: 26Gi
              volumes:
                - name: memory-storage
                  emptyDir:
                    medium: Memory
                    sizeLimit: 20Mi
....
```

**Comment by arun291091** [comment]
This Worked for me in kubernetes mode. 

Create a Configmap.yaml

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-runner-hook-template
  namespace: arc-runners
data:
  hook-template.yaml: |
    spec:
      containers:
        - name: $job
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"


```

mount that to gh-runner-scale-sets helm release 

```
values:
    containerMode:
      type: "kubernetes"
    template:
      spec:
        imagePullSecrets:
          - name: test
        securityContext:
          fsGroup: 1001

###
        volumes:
          - name: hook-template                                                 ##  for HOOK 
            configMap:
              name: gha-runner-hook-template
###
          - name: work
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 1Gi
        containers:
          - name: runner
            image: gh-action-runner:latest
            command: ["/home/runner/run.sh"]
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
####
              - name: hook-template                                                                    ##  for HOOK
                mountPath: /home/runner/hook-template.yaml
                subPath: hook-template.yaml
####
            env:
####
              - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE                ##  for HOOK
                value: /home/runner/hook-template.yaml
####
              - name: ACTIONS_RUNNER_CONTAINER_HOOKS
                value: /home/runner/k8s/index.js
              - name: ACTIONS_RUNNER_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "true"
```

Output : 
```
$  k get pod runner-cvzn5-runner-gkcjk-workflow   -o jsonpath="{.spec.containers[*].resources}"
{"limits":{"cpu":"2","memory":"2Gi"},"requests":{"cpu":"1","memory":"1Gi"}}

$  k get pod runner-cvzn5-runner-gkcjk   -o jsonpath="{.spec.containers[*].resources}"
{"limits":{"cpu":"2","memory":"2Gi"},"requests":{"cpu":"1","memory":"2Gi"}}
 
```
