### ISSUE TITLE
PATH for dind GHA is completely different than a normal github-hosted runner

### ISSUE THREAD

**Issue by DPatrickBoyd** [actions/actions-runner-controller#3122]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

install gha-runner-scale-set using argoCD as the installer with helm as the source with dind enabled

run this side by side to see the difference
```
name: Actions Runner Controller Debug
on:
  workflow_dispatch:

jobs:
  debug_ubuntu:
    runs-on: ubuntu-latest  
    steps:
    - name: Run debug
      run: |  
        echo $PATH
  debug_self:
    runs-on: debug-dev  
    steps:
    - name: Run debug
      run: |  
        echo $PATH

```

the output will look something like this:

```
ubuntu:latest
/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

```
ARC:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

This is causing a lot of failures for normal operations where path is required

### Describe the bug

PATH is not as expected for self-hosted runners ARC with dind enabled

### Describe the expected behavior

the PATH should look similar to the github-hosted runners since it is the same image

### Additional Context

example of a values.yaml file:

```yaml
runnerGroup: "debug-dev"

maxRunners: 10
minRunners: 0

containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
    nodeSelector: 
      nodepool: dev_node
controllerServiceAccount:
  namespace: arc-system
  name: arc-system-gha-rs-controller
```

### Controller Logs

```shell
not applicable
```

### Runner Pod Logs

```shell
not applicable
```
