### ISSUE TITLE
Installation of scaleset helm chart gives error 'manifest does not contain minimum number of descriptors (2), descriptors found: 1'

### ISSUE THREAD

**Issue by crazyelectron-io** [actions/actions-runner-controller#3129]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Helm (version 3.13.2)

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Setup a K3s cluster with 3 worker nodes
2. Run `helm install arc --namespace arc-systems --create-namespace oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller`
3. Create private key (.pem)
4. Create secret for GitHub App: `kubectl create secret generic ghapp-secret --namespace=arc-runners --from-literal=github_app_id=xxxx --from-literal=github_app_installation_id=xxxx \
--from-literal=github_app_private_key="$(cat ~/private-key.pem)"`
5. Install controller with Helm (works fine).
6. Run `helm install arc-runner-set --namespace arc-runners -f scaleset1_values.yaml \
oci://ghrc.io/actions/actions-runner-controller-charts/gha-runner-scale-set`
```

### Describe the bug

Installing the ScaleSet with the provided Helm chart gives the error `manifest does not contain minimum number of descriptors (2), descriptors found: 1`.

### Describe the expected behavior

The `helm install` should install the action runners controller.

### Additional Context

```yaml
Values.yaml:

githubConfigUrl: "https://github.com/myorg"
githubConfigSecret: ghapp-secret
runnerScaleSetName: "ubuntu-dind-16g"
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
```

### Controller Logs

```shell
No logs available.
```

### Runner Pod Logs

```shell
No logs available.
```
