### ISSUE TITLE
Access to the path '/proc/<ID>/oom_score_adj' is denied

### ISSUE THREAD

**Issue by romanvogman** [actions/actions-runner-controller#3132]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Trigger a jenkins-action job with a self hosted github runner
```

### Describe the bug

Trying to set up a self hosted runner in a kubernets mode that will replace a self hosted runner which currently runs on a dedicated VM.
When running a github action that runs [a jenkins action](https://github.com/marketplace/actions/jenkins-action) I'm seeing a permissions error on `Access to the path '/proc/<ID>/oom_score_adj' is denied` 

### Describe the expected behavior

Expect it to run as is when running on a self hosted runner in a dedicated VM instead of in a kubernets cluster 

### Additional Context

Followed the following [video](https://www.youtube.com/watch?v=_F5ocPrv6io&ab_channel=glich.stream) to set it up 
```yaml
This is the runner config I'm currently using for the helm chart:

containerMode:
 type: "kubernetes"  ## type can be set to dind or kubernetes
   ## the following is required when containerMode.type=kubernetes
 kubernetesModeWorkVolumeClaim:
   accessModes: ["ReadWriteOnce"]
   storageClassName: "standard-rwo"
   resources:
     requests:
       storage: 1Gi

template:
  spec:
    securityContext:
      fsGroup: 123
      runAsUser: 1001
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
```

### Controller Logs

```
same
```

### Runner Pod Logs

```shell
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper] Starting process:
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   File name: '/home/runner/externals/node16/bin/node'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   Arguments: '/home/runner/k8s/index.js'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   Working directory: '/home/runner/_work/end2end/end2end'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'True'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper] Failed to update oom_score_adj for PID: 57.
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper] System.UnauthorizedAccessException: Access to the path '/proc/57/oom_score_adj' is denied.
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]  ---> System.IO.IOException: Permission denied
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    --- End of inner exception stack trace ---
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    at System.IO.StreamWriter.Dispose(Boolean disposing)
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    at System.IO.File.WriteAllText(String path, String contents)
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper]    at GitHub.Runner.Sdk.ProcessInvoker.WriteProcessOomScoreAdj(Int32 processId, Int32 oomScoreAdj)
[WORKER 2023-12-06 12:45:00Z INFO ProcessInvokerWrapper] Process started with process id 57, waiting for process exit.
```
