### ISSUE TITLE
Buildx Setup Failure

### ISSUE THREAD

**Issue by rarecrumb** [actions/actions-runner-controller#3150]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Use the default helm installation method
```

### Describe the bug

```
Download buildx from GitHub Releases
  Use 0.12.0 version spec cache key for v0.12.0
  Cache Size: ~15 MB (15242173 B)
  /usr/bin/tar -xf /home/runner/_work/_temp/d53d0905-8735-4ad0-be44-a2747e653177/cache.tgz -P -C /home/runner/_work/backend/backend -z
  /usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
  /usr/bin/tar: ../../../../home/runner/.docker/buildx/.bin/0.12.0/linux-arm64: Cannot mkdir: No such file or directory
  /usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
  /usr/bin/tar: ../../../../home/runner/.docker/buildx/.bin/0.12.0/linux-arm64/docker-buildx: Cannot open: No such file or directory
  /usr/bin/tar: Exiting with failure status due to previous errors
  Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
  Downloading https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-arm64
  Received 15242173 of 15242173 (100.0%), 13.3 MBs/sec
  /usr/bin/tar --posix -cf cache.tgz --exclude cache.tgz -P -C /home/runner/_work/backend/backend --files-from manifest.txt -z
  Failed to save: Unable to reserve cache with key buildx-dl-bin-0.12.0-linux-arm64, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/develop, Key: buildx-dl-bin-0.12.0-linux-arm64, Version: 728[95](https://github.com/x/x/actions/runs/7204670473/job/19627608809#step:7:97)c89f46916ebf6753c6c76e20443af733b6516726cbc8801f1aa4838abbb
  Cached to /home/runner/.docker/buildx/.bin/0.12.0/linux-arm64/docker-buildx
```

### Describe the expected behavior

The builds should just work...

### Additional Context

```yaml
Why'd you guys have to break it?
```

### Controller Logs

```shell
...
```

### Runner Pod Logs

```shell
...
```

**Comment by rarecrumb** [comment]
Just trying to use the latest ARC.

Tried upgrading and using the new helm charts.

Builds just won't work with dind, no matter all the different possibilities that I try.

Here is my helm config:

```yaml
# Default values for actions-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
gha-runner-scale-set-controller:
  fullnameOverride: gha-rs-controller
  authSecret:
    name: actions-runner
  logFormat: json
  replicaCount: 2

  updateStrategy: "eventual"

  resources:
    requests:
      cpu: 500m
      memory: 256Mi

  nodeSelector:
    kubernetes.io/arch: arm64
  tolerations:
  - key: kubernetes.io/arch
    operator: Equal
    value: arm64
    effect: NoSchedule

gha-runner-scale-set:
  githubConfigUrl: https://github.com/PrivateRepo
  githubConfigSecret: actions-runner

  controllerServiceAccount:
    namespace: actions-runner
    name: gha-rs-controller

  runnerScaleSetName: self-hosted

  containerMode:
    type: dind

  template:
    spec:
      securityContext:
          fsGroup: 1000
          runAsUser: 1000
      initContainers:
        - name: kube-init
          image: ghcr.io/actions/actions-runner:latest
          command: ["sudo", "chown", "-R", "1000:1000", "/home/runner/_work"]
          volumeMounts:
          - name: work
            mountPath: /home/runner/_work
      nodeSelector:
        karpenter.k8s.aws/instance-family: c7g
        kubernetes.io/arch: arm64
      tolerations:
      - key: kubernetes.io/arch
        operator: Equal
        value: arm64
        effect: NoSchedule
```

Here are the relevant build steps in my workflow:
```yaml
      - name: Build SHA tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Docker builder context
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          endpoint: builders
          version: latest
          platforms: linux/${{ matrix.arch }}

      - name: Bump version and push tag
        uses: PrivateRepo/github-tag-action@1.0.0
        if: github.event_name != 'pull_request'
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: develop
          DEFAULT_BUMP: patch
          MINOR_STRING_TOKEN: feat
          RELEASE_BRANCHES: master
          VERBOSE: false
          WITH_V: true

      - name: "GraphQL: Build and Push"
        uses: docker/build-push-action@v5
        with:
          build-args: |
            SERVICE_NAME=graphql
            VERSION=${{ steps.vars.outputs.sha_short }}
          context: .
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: x.dkr.ecr.us-east-1.amazonaws.com/graphql:${{ github.sha }}-${{ matrix.arch }}
          cache-from: |
            type=gha
          cache-to: |
            type=local,dest=/tmp/.buildx-cache
            type=gha
          no-cache-filters: |
            runner
            splitter
```

**Comment by rarecrumb** [comment]
Also seeing this from the checkout v4 step:
```
Deleting the contents of '/home/runner/_work/backend/backend'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
```

**Comment by nikola-jokic** [comment]
Hey @rarecrumb,

Can you please check if the issue is happening now?

**Comment by rarecrumb** [comment]
> Hey @rarecrumb,
> 
> Can you please check if the issue is happening now?

~~Yes, it's still an issue.~~ Now it _seems_ to be working... What was changed?

Did something change in the last few hours? Should I be trying some kind of canary image tag?

@nikola-jokic why doesn't the runner image have `git` installed? It would be nice: https://github.com/actions/runner/issues/3000#issuecomment-1837135883

Ended up just building my own image:
```Dockerfile
FROM ghcr.io/actions/actions-runner:latest

RUN sudo apt update && sudo apt install git -y
```

**Comment by nikola-jokic** [comment]
Hey @rarecrumb,

The intention of the runner image is to provide a good starting point, or to use an image as is. We wanted an image that is very slim, and is able to execute jobs. The tooling requirements are different from one use-case to another, and we did not want to create a catch-all image. That can only increase image size, which would slow down image pulls. Also, the way you started building your own image is just the way we intended :relaxed: 

The reason I asked if it is working now is that around the time you submitted the issue, I was also encountering some intermittent failures, which were quickly resolved.

Can you also provide a full spec for the gha-runner-scale-set? I am not seeing runner container spec here, only the init container.

**Comment by rarecrumb** [comment]
> Hey @rarecrumb,
> 
> The intention of the runner image is to provide a good starting point, or to use an image as is. We wanted an image that is very slim, and is able to execute jobs. The tooling requirements are different from one use-case to another, and we did not want to create a catch-all image. That can only increase image size, which would slow down image pulls. Also, the way you started building your own image is just the way we intended ☺️
> 
> The reason I asked if it is working now is that around the time you submitted the issue, I was also encountering some intermittent failures, which were quickly resolved.
> 
> Can you also provide a full spec for the gha-runner-scale-set? I am not seeing runner container spec here, only the init container.

Understood, but I am still getting this error on the buildx step.

Step definition in my workflow yml file:
```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          endpoint: builders
          version: latest
          platforms: linux/arm64
```

Error:
```
Download buildx from GitHub Releases
  Use 0.12.0 version spec cache key for v0.12.0
  Cache Size: ~15 MB (15242171 B)
  /usr/bin/tar -xf /home/runner/_work/_temp/5e19ba38-6bcd-4064-8513-7261331db6c0/cache.tgz -P -C /home/runner/_work/frontend/frontend -z
  /usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
  /usr/bin/tar: ../../../../home/runner/.docker/buildx/.bin/0.12.0/linux-arm64: Cannot mkdir: No such file or directory
  /usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
  /usr/bin/tar: ../../../../home/runner/.docker/buildx/.bin/0.12.0/linux-arm64/docker-buildx: Cannot open: No such file or directory
  /usr/bin/tar: Exiting with failure status due to previous errors
  Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
  Downloading https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-arm64
  Received 15242171 of 15242171 (100.0%), 14.5 MBs/sec
  /usr/bin/tar --posix -cf cache.tgz --exclude cache.tgz -P -C /home/runner/_work/frontend/frontend --files-from manifest.txt -z
  Failed to save: Unable to reserve cache with key buildx-dl-bin-0.12.0-linux-arm64, another job may be creating this cache. More details: Cache already exists. Scope: refs/pull/3475/merge, Key: buildx-dl-bin-0.12.0-linux-arm64, Version: 72895c89f46916ebf6753c6c76e20443af733b6516726cbc8801f1aa4838abbb
  Cached to /home/runner/.docker/buildx/.bin/0.12.0/linux-arm64/docker-buildx
```

I have commented out "containerMode" in order to override the entire template.spec.

Manifest from my helm values file:
```yaml

  # containerMode:
  #   type: dind

  template:
    metadata:
      annotations:
        karpenter.sh/do-not-evict: 'true'
    spec:
      containers:
      - name: runner
        image: 'x.dkr.ecr.us-east-1.amazonaws.com/runner:latest'
        command:
        - /home/runner/run.sh
        env:
        - name: DOCKER_HOST
          value: 'unix:///run/docker/docker.sock'
        - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
          value: '120'
        resources:
          requests:
            cpu: 4
            memory: 4Gi
          limits:
            cpu: 4
            memory: 4Gi
        volumeMounts:
          - mountPath: /home/runner/_work
            name: work
          - mountPath: /run/docker
            name: dind-sock
            readOnly: true
          - mountPath: /tmp
            name: tmp
      - name: dind
        image: 'docker:dind'
        args:
        - dockerd
        - '--host=unix:///run/docker/docker.sock'
        - '--group=$(DOCKER_GROUP_GID)'
        env:
        - name: DOCKER_GROUP_GID
          value: '123'
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        securityContext:
          privileged: true
          seLinuxOptions:
            level: "s0"
            role: "system_r"
            type: "super_t"
            user: "system_u"
        volumeMounts:
          - mountPath: /home/runner/_work
            name: work
          - mountPath: /run/docker
            name: dind-sock
          - mountPath: /home/runner/externals
            name: dind-externals
          - mountPath: /tmp
            name: tmp
      initContainers:
      - args:
        - '-r'
        - '-v'
        - /home/runner/externals/.
        - /home/runner/tmpDir/
        command:
        - cp
        image: 'ghcr.io/actions/actions-runner:latest'
        name: init-dind-externals
        volumeMounts:
        - mountPath: /home/runner/tmpDir
          name: dind-externals
        - mountPath: /tmp
          name: tmp
      nodeSelector:
        karpenter.k8s.aws/instance-family: c7g
        kubernetes.io/arch: arm64
      restartPolicy: Never
      securityContext:
        fsGroup: 123
        seLinuxOptions:
          level: "s0"
          role: "system_r"
          type: "super_t"
          user: "system_u"
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: arm64
      volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: dind-sock
        - emptyDir: {}
          name: dind-externals
        - emptyDir: {}
          name: work
```
