### ISSUE TITLE
/home/runner/_work/_tool/maven/3.8.8/x64/bin/mvn: Permission denied

### ISSUE THREAD

**Issue by namhyuck-kim-otsk** [actions/actions-runner-controller#3180]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Kustomize

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Deploy ARC Runner Scale Set 0.7.0 with Persistant Volume for caching.
2. Run github actions
    - Setup Maven Action (s4u/setup-maven-action@v1.11.0)
    - Run mvn clean package -q
3. Error: /home/runner/_work/_tool/maven/3.8.8/x64/bin/mvn: Permission denied
```

### Describe the bug

I encounter  `/home/runner/_work/_tool/maven/3.8.8/x64/bin/mvn: Permission denied` error when using arc runners with Persistant Volumes. 

If I run the same workflow without PV configuration, it works perfectly fine.

Workflow.yaml

```
name: Build Application Flow

on:
  workflow_call:
  push:
    branches: [main]

jobs:
  setup:
    name: Workflow
    runs-on: [ arc-runner ]

    permissions:
      contents: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          checkout-fetch-depth: 0
          java-version: 8
          java-distribution: temurin
          maven-version: 3.8.8         

      - name: Build with Maven
        run: |
          mvn clean package -q 
```

Error Message:
`/home/runner/_work/_tool/maven/3.8.8/x64/bin/mvn: Permission denied`

### Describe the expected behavior

The maven package command should work fine.

### Additional Context

```yaml
https://gist.github.com/namhyuck-kim-otsk/e3f7479a330f8881bc4fa97c360ff0fc
```

### Controller Logs

```shell
-
```

### Runner Pod Logs

```shell
https://gist.github.com/namhyuck-kim-otsk/b441cb3c792c0ace69a6c3be9983dc8c
```
