### ISSUE TITLE
listener metrics unavailable with 0.8.1

### ISSUE THREAD

**Issue by julien-michaud** [actions/actions-runner-controller#3190]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Use chart 0.8.1
```

### Describe the bug

With the 0.8.1 version, the listener pod dont expose all the available metrics

Here are the metrics available on `/metrics`

```
# HELP gha_max_runners Maximum number of runners.
# TYPE gha_max_runners gauge
gha_max_runners{enterprise="",name="test-hosted-beta-2n8tv",namespace="actions-runner-system",organization="test",repository=""} 100
# HELP gha_min_runners Minimum number of runners.
# TYPE gha_min_runners gauge
gha_min_runners{enterprise="",name="test-hosted-beta-2n8tv",namespace="actions-runner-system",organization="test",repository=""} 3
# HELP promhttp_metric_handler_errors_total Total number of internal errors encountered by the promhttp metric handler.
# TYPE promhttp_metric_handler_errors_total counter
promhttp_metric_handler_errors_total{cause="encoding"} 0
promhttp_metric_handler_errors_total{cause="gathering"} 0
```

I had no issues with the 0.7.0 version

### Describe the expected behavior

being able to list all the metrics from the listener, see https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#available-metrics-for-arc

### Additional Context

```yaml
gha-runner-scale-set-controller:
  podLabels:
    finops.test.net/cloud_provider: gcp
    finops.test.net/cost_center: compute
    finops.test.net/product: tools
    finops.test.net/service: actions-runner-controller
    finops.test.net/region: europe-west1
  replicaCount: 3
  podAnnotations:
    ad.datadoghq.com/manager.checks: |
      {
        "openmetrics": {
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8080/metrics",
              "histogram_buckets_as_distributions": true,
              "namespace": "actions-runner-system",
              "metrics": [".*"]
            }
          ]
        }
      }
  metrics:
    controllerManagerAddr: ":8080"
    listenerAddr: ":8080"
    listenerEndpoint: "/metrics"


gha-runner-scale-set:
  githubConfigUrl: https://github.com/test
  githubConfigSecret:
    github_token: <path:secret/github_token/actions_runner_controller#token>

  maxRunners: 100
  minRunners: 3

  containerMode:
    type: "dind"  ## type can be set to dind or kubernetes

  listenerTemplate:
    metadata:
      labels:
        finops.test.net/cloud_provider: gcp
        finops.test.net/cost_center: compute
        finops.test.net/product: tools
        finops.test.net/service: actions-runner-controller
        finops.test.net/region: europe-west1
      annotations:
        ad.datadoghq.com/listener.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:8080/metrics",
                  "histogram_buckets_as_distributions": true,
                  "namespace": "actions-runner-system",
                  "metrics": [".*"]
                }
              ]
            }
          }
    spec:
      containers:
      - name: listener
        securityContext:
          runAsUser: 1000
  template:
    metadata:
      labels:
        finops.test.net/cloud_provider: gcp
        finops.test.net/cost_center: compute
        finops.test.net/product: tools
        finops.test.net/service: actions-runner-controller
        finops.test.net/region: europe-west1
    spec:
      imagePullSecrets:
        - name: test-prod-registry
      containers:
        - name: runner
          image: eu.gcr.io/test-production/devex/gha-runners:v1.0.0-snapshot5
          command: ["/home/runner/run.sh"]

  controllerServiceAccount:
    namespace: actions-runner-system
    name: actions-runner-controller-gha-rs-controller
```

### Controller Logs

```shell
https://gist.github.com/julien-michaud/3b25f14e678a365362a5270c4101acab
```

### Runner Pod Logs

```shell
https://gist.github.com/julien-michaud/812ec630f1b63867a3be2bc23888ad38
```
