### ISSUE TITLE
Listener gets into crash loop with createSession 409 error

### ISSUE THREAD

**Issue by int128** [actions/actions-runner-controller#3209]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
We have 2 Kubernetes clusters.

1. Install the controller into `arc-systems` namespace of cluster A
2. Install the controller into `arc-systems` namespace of cluster B
3. Add a gha-runner-scale-set into `arc-runners` namespace of cluster A. The runner belongs to a repository
4. Add a gha-runner-scale-set into `arc-runners` namespace of cluster B. The runner belongs to the same repository, but has the different runner name
```

### Describe the bug

A listener pod suddenly exits with the following error:

```
example-754b578d-listener listener 2024-01-09T06:12:25Z	INFO	listener-app.worker.kubernetesworker	Updating job info for the runner	{"runnerName": "example-6hcw5-runner-fb29k", REDACTED, "requestId": 6421142}
example-754b578d-listener listener 2024-01-09T06:12:25Z	INFO	listener-app.worker.kubernetesworker	Updating ephemeral runner with merge patch	{"json": "{\"status\":{\"jobDisplayName\":\"REDACTED\",\"workflowRunId\":7457087460}}"}
example-754b578d-listener listener 2024/01/09 06:12:25 Application returned an error: failed to handle job started: could not patch ephemeral runner status, patch JSON: {"status":{"jobDisplayName":"REDACTED","workflowRunId":7457087460}}, error: ephemeralrunners.actions.github.com "example-6hcw5-runner-fb29k" not found
``` 

After that, the listener pod gets into a crash loop with the following error:

```
example-754b578d-listener listener 2024-01-09T06:12:27Z	INFO	listener-app	app initialized
example-754b578d-listener listener 2024-01-09T06:12:27Z	INFO	listener-app	Starting metrics server
example-754b578d-listener listener 2024-01-09T06:12:27Z	INFO	listener-app	Starting listener
example-754b578d-listener listener 2024-01-09T06:12:27Z	INFO	listener-app	refreshing token	{"githubConfigUrl": "https://github.com/REDACTED"}
example-754b578d-listener listener 2024-01-09T06:12:27Z	INFO	listener-app	getting access token for GitHub App auth	{"accessTokenURL": "https://api.github.com/app/installations/REDACTED/access_tokens"}
example-754b578d-listener listener 2024-01-09T06:12:27Z	INFO	listener-app	getting runner registration token	{"registrationTokenURL": "https://api.github.com/repos/REDACTED/actions/runners/registration-token"}
example-754b578d-listener listener 2024-01-09T06:12:27Z	INFO	listener-app	getting Actions tenant URL and JWT	{"registrationURL": "https://api.github.com/actions/runner-registration"}
example-754b578d-listener listener 2024/01/09 06:12:28 Application returned an error: createSession failed: failed to create session: 409 - had issue communicating with Actions backend: The runner scale set example already has an active session for owner example-754b578d-listener.
```

It seems the listener exits at:

https://github.com/actions/actions-runner-controller/blob/f7eb88ce9c6b3cf013ae825bef197773e2bc9d0b/cmd/ghalistener/worker/worker.go#L144

https://github.com/actions/actions-runner-controller/blob/b78cadd90105030e122f78758ba7c3c283a931ab/cmd/ghalistener/listener/listener.go#L181-L185

### Describe the expected behavior

It would be nice to keep a listener running even if a merge patch is failed.

### Additional Context

```yaml
-
```

### Controller Logs

```
2024-01-09T06:04:04Z INFO EphemeralRunner Checking if runner exists in GitHub service {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}, "runnerId": 6247604}
2024-01-09T06:04:04Z INFO EphemeralRunner Runner does not exist in GitHub service {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}, "runnerId": 6247604}
2024-01-09T06:04:04Z INFO EphemeralRunner Ephemeral runner has finished since it does not exist in the service anymore {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner Updating ephemeral runner status to Finished {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner EphemeralRunner status is marked as Finished {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner EphemeralRunner has already finished. Stopping reconciliation and waiting for EphemeralRunnerSet to clean it up {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}, "phase": "Succeeded"}
2024-01-09T06:04:04Z INFO EphemeralRunnerSet Deleting finished ephemeral runner {"ephemeralrunnerset": {"name":"example-6hcw5","namespace":"arc-runners"}, "name": "example-6hcw5-runner-fb29k"}
2024-01-09T06:04:04Z INFO EphemeralRunner Successfully removed runner registration finalizer {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner Finalizing ephemeral runner {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner Cleaning up the runner pod {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner Deleting the runner pod {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner Waiting for ephemeral runner owned resources to be deleted {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner Finalizing ephemeral runner {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner Cleaning up the runner pod {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
2024-01-09T06:04:04Z INFO EphemeralRunner Waiting for ephemeral runner owned resources to be deleted {"ephemeralrunner": {"name":"example-6hcw5-runner-fb29k","namespace":"arc-runners"}}
```

```shell
2024-01-09T06:12:26Z	INFO	AutoscalingListener	Listener pod failed, deleting it and re-creating it	{"autoscalinglistener": {"name":"example-754b578d-listener","namespace":"arc-systems"}, "namespace": "arc-systems", "name": "example-754b578d-listener", "reason": "", "message": ""}"
2024-01-09T06:12:26Z	INFO	AutoscalingListener	Creating a listener pod	{"autoscalinglistener": {"name":"example-754b578d-listener","namespace":"arc-systems"}}"
2024-01-09T06:12:26Z	INFO	AutoscalingListener	Creating listener pod	{"autoscalinglistener": {"name":"example-754b578d-listener","namespace":"arc-systems"}, "namespace": "arc-systems", "name": "example-754b578d-listener"}"
2024-01-09T06:12:26Z	INFO	AutoscalingListener	Created listener pod	{"autoscalinglistener": {"name":"example-754b578d-listener","namespace":"arc-systems"}, "namespace": "arc-systems", "name": "example-754b578d-listener"}"
2024-01-09T06:12:30Z	INFO	AutoscalingListener	Listener pod failed, deleting it and re-creating it	{"autoscalinglistener": {"name":"example-754b578d-listener","namespace":"arc-systems"}, "namespace": "arc-systems", "name": "example-754b578d-listener", "reason": "", "message": ""}"
2024-01-09T06:12:30Z	INFO	AutoscalingListener	Creating a listener pod	{"autoscalinglistener": {"name":"example-754b578d-listener","namespace":"arc-systems"}}"
2024-01-09T06:12:30Z	INFO	AutoscalingListener	Creating listener pod	{"autoscalinglistener": {"name":"example-754b578d-listener","namespace":"arc-systems"}, "namespace": "arc-systems", "name": "example-754b578d-listener"}"
2024-01-09T06:12:30Z	INFO	AutoscalingListener	Created listener pod	{"autoscalinglistener": {"name":"example-754b578d-listener","namespace":"arc-systems"}, "namespace": "arc-systems", "name": "example-754b578d-listener"}"
```

### Runner Pod Logs

```shell
-
```

**Comment by int128** [comment]
I have reverted the Helm chart to v0.7.0 and then the self-hosted runners seems stable.

I noticed the below differences between v0.7.0 (githubrunnerscalesetlistener) and v0.8.0 (ghalistener). Could you check them?

### Error handling on updating an EphemeralRunner
For v0.7.0 (githubrunnerscalesetlistener), it just writes an error log.

https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/cmd/githubrunnerscalesetlistener/autoScalerService.go#L242-L245

For v0.8.0 (ghalistener), it returns the error and the listener process accidentally exits.

https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/cmd/ghalistener/listener/listener.go#L182-L184

I think it should handle the error to avoid crash loop.

### Graceful shutdown of Actions service session
For v0.7.0 (githubrunnerscalesetlistener), it deletes the current session.

https://github.com/actions/actions-runner-controller/blob/202a97ab12833b4916ad7312b1cf235e4b802f0c/cmd/githubrunnerscalesetlistener/main.go#L191
https://github.com/actions/actions-runner-controller/blob/336e11a4e92d3086e756d344713f34aaac339512/cmd/githubrunnerscalesetlistener/autoScalerMessageListener.go#L127-L130
https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/cmd/githubrunnerscalesetlistener/sessionrefreshingclient.go#L116

For v0.8.0 (ghalistener), it does not delete the session. I think it causes 409 errors.

**Comment by mumoshu** [comment]
@nikola-jokic @Link- Hey! I think we found some regression in 0.8.0.

I discussed offline with @int128, and I believe this is caused by the eventual consistency of data returned by GHA, which was handled gracefully in 0.7.0 but not in 0.8.0.

Our theory:

1. ephemeralrunnerset controller creates ephemeralrunner
2. ephemeralrunner controller creates a runner pod
3. Runner pod starts the agent, which starts the job and notifies the GHA API about the job start
4. ephemeralrunner controller calls GHA service API to check existence of the runner in the service.
5. GHA API says the runner is inexistent(**although we did register it beforehand. Perhaps due to eventual consistency in your service**), resulting in the controller to mark the ephemeralrunner as finished
6. ephemeralrunnerset controller removes the ephemeralrunner as finished
7. The listener gets the job started notification from the GHA service.
8. The listener could not find the ephemeralrunner noted in the notification, **existing with status 1.**
9. The listener is restated by k8s, failing instantly due to the duplicate GHA session as it has not been cleaned up in step 8

We think the new ghalistener introduced in 0.8.0 has two regressions(would you mind confirming?) related to step 8, where:

- It doesn't close the session on listener exit anymore in 0.8.0, leaving an unclosed session, which triggers duplicate session errors after the listener restarts.
  - In 0.7.0 runnerscalesetlistener we did use `defer` like https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/cmd/githubrunnerscalesetlistener/main.go#L186-L191
  - In 0.8.0, no session clean up in neither main or app: https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/cmd/ghalistener/app/app.go#L107-L133
- It fails immediately on the missing ephemeralrunner error in 0.8.0.
   - In 0.7.0, we just logged the error without failing https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/cmd/githubrunnerscalesetlistener/autoScalerService.go#L244
   - In 0.8.0, we return the error here which results in the main existing: https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/cmd/ghalistener/listener/listener.go#L182-L184

@nikola-jokic @Link- If the above theory stands, can we at least fix the second bullet point so that the listener doesn't start failing immediately when the GHA service returns stale data?

From @int128 and his colleagues' observation, the `runner scale set example already has an active session for owner example-754b578d-listener` error seems to persist for approx 10 minutes which delays the job runs for the runnerscaleset for that long, and this seems to happen quite often 🤔

**Comment by Link-** [comment]
@mumoshu @int128 thank you for your great work troubleshooting and reporting this issue. We will address it in a patch release, in the meantime, you don't have to revert to previous versions. We expected some problems to arise with the new listener so we included a fallback:

Update the `LISTENER_ENTRYPOINT` to `/github-runnerscaleset-listener` in order to use older listener app.

https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/controllers/actions.github.com/resourcebuilder.go#L237

You can do it by updating the listener template:
https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/charts/gha-runner-scale-set-controller/values.yaml#L21

**Comment by mumoshu** [comment]
@Link- Awesome! I missed that. Thank you for sharing and all your effort!

**Comment by br4mm** [comment]
Not sure if valuable to anyone, but I just had the exact same issue and changed revision back to 0.7.0 - which is working fine now.

**Comment by TiagoJMartins** [comment]
> Update the LISTENER_ENTRYPOINT to github-runnerscaleset-listener in order to use older listener app.

This definitely fixed it for me on 0.8.1, [mentioned here](https://github.com/actions/actions-runner-controller/issues/3209#issuecomment-1893477033). Hoping the next release will include the permanent fix 🤞🏻

I was also having issues with high-usage runner sets getting into this crashing state, and that has also been resolved by changing the entrypoint.

**Comment by ahatzz11** [comment]
@Link- Can you elaborate on how we should insert the `LISTENER_ENTRYPOINT` value? I saw another issue that used the value of `/github-runnerscaleset-listener` instead of `github-runnerscaleset-listener`, so I tried both as an environment variable, and it didn't seem to resolve our issue. Here is `describe`:

```yaml
Containers:
  listener:
    Container ID:
    Image:         ghcr.io/actions/gha-runner-scale-set-controller:0.8.1
    Image ID:
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /ghalistener
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      LISTENER_CONFIG_PATH:  /etc/gha-listener/config.json
      LISTENER_ENTRYPOINT:   github-runnerscaleset-listener
```

I did seem to have luck by setting:

```yaml
listenerTemplate:
 spec:
    containers:
      - name: listener
         command: ["/github-runnerscaleset-listener"]
```

With this command change my listener started and didn't run into this patch bug. However, with the nature of an eventual consistency bug, I don't actually know if that resolved the issue or not because I decided to test just getting rid of all my fixes and now I'm not hitting the bug, but it seems inevitable it'll happen again. Some clarification on how we should define this fix in the `listenerTemplate` would be awesome, and if you could confirm any changes we might see in the pod spec (like the `command` changing) when this fix is properly applied.

**Comment by ahatzz11** [comment]
I hit this issue in our organization today and had a very hard time fixing it with the above suggestions, so I'm putting some information here to help others that might run into this until a proper fix is in place. We are running ~50 runners at max right now and have hundreds to thousands of individual jobs a day. If anything here below is wrong please let me know.

---

Above @Link- mentioned that you should insert `LISTENER_ENTRYPOINT` with a value of `github-runnerscaleset-listener` in the listener template. I think there might be some confusion here because it seems this is the incorrect value to use and the incorrect location to put this env var. After attempting the proposed fix above I still encountered this patch issue and I noticed that the `command` didn't update for the listener pod. Here was a section of my values file for the `gha-runner-scale-set` helm chart:

```yaml
listenerTemplate:
  spec:
    containers:
      - name: listener
        securityContext:
          runAsUser: 1000
        env:
          - name: LISTENER_ENTRYPOINT
            value: github-runnerscaleset-listener
```

Here is the `kubectl pod describe`:

```yaml
Containers:
  listener:
    Container ID:
    Image:         ghcr.io/actions/gha-runner-scale-set-controller:0.8.1
    Image ID:
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /ghalistener
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      LISTENER_CONFIG_PATH:  /etc/gha-listener/config.json
      LISTENER_ENTRYPOINT:   github-runnerscaleset-listener
```

Notice here that the `Command: /ghalistener` is still pointing at the new listener. This solution from above does not seem to work. 

---

The solution I found to work here is to add an env var of `LISTENER_ENTRYPOINT` with the value of `/github-runnerscaleset-listener` to the values file for the **gha-runner-scale-set-controller** helm chart. Here is an example:

```yaml
replicaCount: 1
labels: {}

env: 
  - name: LISTENER_ENTRYPOINT
    value: /github-runnerscaleset-listener
```

This changes the environment variable on the controller which then creates a listener that has the proper entrypoint. This can be seen with another `kubectl describe pod` on the listener:

```yaml
Containers:
  listener:
    Container ID:  containerd://c0baad31de660705d8abf992aaf3aae2357531e247a0e679dbe268b666136bc8
    Image:         ghcr.io/actions/gha-runner-scale-set-controller:0.8.1
    Image ID:      ghcr.io/actions/gha-runner-scale-set-controller@sha256:14f6df6f6300f34c4377b05e72378b05d813160556e3fd3415e56049d7b30ac2
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /github-runnerscaleset-listener
    State:          Running
      Started:      Wed, 24 Jan 2024 18:46:21 -0600
    Ready:          True
    Restart Count:  0
    Environment:
      LISTENER_CONFIG_PATH:  /etc/gha-listener/config.json
```

Here's the code path I followed to get to this solution:
- `main.go` for the controller is what reads the `LISTENER_ENTRYPOINT` env var: https://github.com/actions/actions-runner-controller/blob/5f23afaad311be44be1781b09541d0a01d7912a3/main.go#L206
- The function that is used for that is defined here: https://github.com/actions/actions-runner-controller/blob/5f23afaad311be44be1781b09541d0a01d7912a3/controllers/actions.github.com/resourcebuilder.go#L65
- And the default value for the field that is overriden by that function is the new `/ghalistener`: https://github.com/actions/actions-runner-controller/blob/5f23afaad311be44be1781b09541d0a01d7912a3/controllers/actions.github.com/resourcebuilder.go#L44
