### ISSUE TITLE
volume binding not working for scaleset

### ISSUE THREAD

**Issue by shyam-ks** [actions/actions-runner-controller#3215]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl

helm template oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

.Values.template.spec.volumes doesnt exist. 
Additional volume attachment is not working because of this
```

### Describe the bug

.Values.template.spec.volumes doesnt exist. 
Additional volume attachment is not working because of this

### Describe the expected behavior

addional volume should come up when added to template.template.spec.volumes

```
template:
  ## template.spec will be modified if you change the container mode
  ## with containerMode.type=dind, we will populate the template.spec with following pod spec
  template:
      spec:
        initContainers:
        - name: init-dind-externals
          image: ghcr.io/actions/actions-runner:latest
          command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
          volumeMounts:
            - name: dind-externals
              mountPath: /home/runner/tmpDir
            - name: aaa
              mountPath: /home/runner/externals
        containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: DOCKER_HOST
              value: unix:///run/docker/docker.sock
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /run/docker
              readOnly: true
            - name: aaa
              mountPath: /home/runner/externals
        - name: dind
          image: docker:dind
          args:
            - dockerd
            - --host=unix:///run/docker/docker.sock
            - --group=$(DOCKER_GROUP_GID)
          env:
            - name: DOCKER_GROUP_GID
              value: "123"
          securityContext:
            privileged: true
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /run/docker
            - name: dind-externals
              mountPath: /home/runner/externals
            - name: aaa
              mountPath: /home/runner/externals
        volumes:
        - name: work
          emptyDir: {}
        - name: dind-sock
          emptyDir: {}
        - name: dind-externals
          emptyDir: {}
        - name: aaaa
          emptyDir: {}
```

### Additional Context

```yaml
NA
```

### Controller Logs

```shell
NA
```

### Runner Pod Logs

```shell
NA
```
