### ISSUE TITLE
Controller does not create runner resources

### ISSUE THREAD

**Issue by imishchuk-carbon** [actions/actions-runner-controller#3233]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Both gha-runner-scale-set-controller and gha-runner-scale-set are running `0.8.0`

1. Upgrade gha-runner-scale-set from `0.8.0` to `0.8.1`;
2. Controller logs a message about version mismatch. `autoscalinglistener` , `autoscalingrunnerset` , `ephemeral-runner-controller` and `ephemeralrunnerset` are deleted;
3. Upgrade controller from `0.8.0` to `0.8.1`
```

### Describe the bug

Hey team.

Mistakenly upgraded scale set before upgrading controller and now listed resources are not created:
* `autoscalinglistener`
* `autoscalingrunnerset`
* `ephemeral-runner-controller`
* `ephemeralrunnerset`

Not sure what is the reason for this and would appreciate assistance in troubleshooting

### Describe the expected behavior

After helm charts for both controller and scale set are of the same version all resources are created

### Additional Context

```yaml
gha-runner-scale-set `values.yaml`


    githubConfigSecret: arc-secret
    githubConfigUrl: https://github.com/{{ some_org }}
    maxRunners: 100 #revise
    runnerGroup: "EKS-runners"
    controllerServiceAccount:
      namespace: arc-systems
      name: arc-systems-actions-runner-controller-gha-rs-controller
    template:
      metadata:
        annotations:
          karpenter.sh/do-not-disrupt: "true"
      spec:
        containers:
          - name: runner
            image: custom_image
            imagePullPolicy: IfNotPresent
            command: ["/home/runner/run.sh"]
        serviceAccountName: eks-runners-default
        tolerations:
          - key: node-restriction.kubernetes.io/reserved-for
            operator: Equal
            value: runners
        nodeSelector:
          kubernetes.io/os: linux
          node-restriction.kubernetes.io/reserved-for: runners
```

gha-runner-scale-set-controller `values.yaml`

```
    flags:
      updateStrategy: "eventual"
    nodeSelector:
      kubernetes.io/os: linux
      node-restriction.kubernetes.io/reserved-for: platform
    tolerations:
      - key: node-restriction.kubernetes.io/reserved-for
        operator: Equal
        value: platform
```
```


### Controller Logs

```shell
https://gist.github.com/imishchuk-carbon/5b9698aed21ee8524c94e25bf0e5d0a7
```

### Runner Pod Logs

```shell
N\A
```
