### ISSUE TITLE
Node affinities/nodeselector for action listeners

### ISSUE THREAD

**Issue by timsanwald** [actions/actions-runner-controller#3265]
### What would you like added?

*Add a possibility to define node affinities/nodeselector for action listeners*

### Why is this needed?

Scheduling can be required in situation where you dont want to run pods on special nodes (e.g. nodes with gpu attached, better cpu/memory ratio usage, spot instances, ...). Currently a limited set of options are provided to influence the listener pod. Node selector or affinities would be required to influence the scheduling.

We would like to move the listener to non spot instances with low load on it as we see issues when the listener runs on highly loaded nodes.

**Comment by ahatzz11** [comment]
This is already possible - I haven't specifically used affinity but I have a node selector and a toleration on our listener. This is part of the values file for `gha-runner-scale-set` helm chart. [Docs](https://github.com/actions/actions-runner-controller/blob/c03fac8fdd487e8934b3a45c89326f7615947c85/charts/gha-runner-scale-set/values.yaml#L93)

Example:

```yaml
listenerTemplate:
  spec:
    containers:
      - name: listener
        securityContext:
          runAsUser: 1000
    nodeSelector: {
      "node_pool": "gha-runner"
    }
    tolerations: [
      {
        "key": "node_pool",
        "operator": "Equal",
        "value": "gha-runner",
        "effect": "NoSchedule"
      }
    ]
```
