### ISSUE TITLE
Arguments to `docker` step double quoted in kubernetes containerMode

### ISSUE THREAD

**Issue by kwohlfahrt** [actions/actions-runner-controller#3272]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Deploy `gha-runner-scale-set` chart with `containerMode.type: kubernetes`
2. Run a workflow containing a `docker` action as a step. In our case, it was https://github.com/irongut/CodeCoverageSummary
3. `kubectl get --watch -o yaml` the worker containers, until you see the container spawned for this step
```

### Describe the bug

The arguments of the container for the docker step are quoted incorrectly:

```yaml
  - args:
    - '"--files"'
    - '"././coverage.xml"'
    ... # Other args similar
    - '"80'
    - 100"
```

Note both that the `--files` option is double-quoted, and the final option `"80 100"` seems to be incorrectly split. The original argument definition is [here](https://github.com/irongut/CodeCoverageSummary/blob/f13848964841ca2f7a63343b287493e17dc645de/action.yml#L43-L64) in the action.

This causes the container to error with `Required option 'files' is missing.` (see logs below), because the argument is passed as `"--files"`, not `--files`.

### Describe the expected behavior

I expect the args to be passed correctly as strings, specifically all arguments apart from the last two should have one less level of quoting, and the last two arguments should either be two arguments, or be a single string `80 100`.

This action worked correctly on the summerwind runner.

### Additional Context

```yaml
For the actions runner system:


serviceAccount:
  create: false
  name: actions-runner-system-9ed664d1


For the actions runner itself:

```yaml
containerMode:
  kubernetesModeWorkVolumeClaim:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: exclusive
  type: kubernetes
controllerServiceAccount:
  name: actions-runner-system-9ed664d1
  namespace: actions-runner-system-d70d5c4f
githubConfigSecret: actions-runner-4ec61cf4
githubConfigUrl: https://github.com/CHARM-Tx
maxRunners: 5
minRunners: 1
template:
  spec:
    containers:
    - command:
      - /home/runner/run.sh
      env:
      - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
        value: "false"
      # Image was from a private registry, but largely the public image plus a very small number of extra `apt` packages installed.
      image: <snip>
      name: runner
      resources:
        limits:
          cpu: "1"
    securityContext:
      fsGroup: 1001
```
```


### Controller Logs

```shell
https://gist.github.com/kwohlfahrt/e529299aae54fd4a176d41ec2cc3255c#file-controller-log
```

### Runner Pod Logs

```shell
runner pod: https://gist.github.com/kwohlfahrt/e529299aae54fd4a176d41ec2cc3255c#file-runner-log
step pod: https://gist.github.com/kwohlfahrt/e529299aae54fd4a176d41ec2cc3255c#file-step-log
step pod definition: https://gist.github.com/kwohlfahrt/e529299aae54fd4a176d41ec2cc3255c#file-step-yaml
```
