### ISSUE TITLE
dind can not be used when using runner image in private registry

### ISSUE THREAD

**Issue by pigeonhands** [actions/actions-runner-controller#3275]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

Other

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```yaml
# runner-scale-set values (via helm)

namespace: gh-runners

labels:
  app: arc-runner-set

helm:
  chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  version: 0.8.1
  releaseName: arc-runner-set
  values:
    githubConfigUrl: "https://github.com/<org>"

    githubConfigSecret: gh-arc-runners-app

    maxRunners: 10
    minRunners: 2

    runnerGroup: container-runners
    runnerScaleSetName: "tahi-linux"

    containerMode:
      type: "dind"

    template:
      spec:
        imagePullSecrets:
          - name: <private-registry-secret>
        containers:
          - name: runner
            image: <private-registry>/actions-runner:v1.0.0
            command: ["/home/runner/run.sh"]
    
    controllerServiceAccount:
      namespace: gh-runners
      name: arc-gha-rs-controller
```

### Describe the bug

The ` init-dind-externals` init container is trying to pull the custom image used in a private repository, but the helm does not specify a way to pass in the `imagePullSecrets`, resulting in a `ImagePullBackOff` error.

This deployment works fine when `dind` is not specified.

https://github.com/actions/actions-runner-controller/blob/5347e2c2c80fbc45be7390eab117e861d30776d1/charts/gha-runner-scale-set/templates/_helpers.tpl#L85-L96

### Describe the expected behavior

The init container should either use a publicly avalible image or take into account the `imagePullSecrets`.

### Additional Context
The [example values yaml for actions-runner-controller](https://github.com/actions/actions-runner-controller/blob/9b053102ed5bbc924118fa68d34115787c037c20/charts/gha-runner-scale-set/values.yaml#L111-L113) is not accurate, it claims the image used for the init container will be `ghcr.io/actions/actions-runner:latest`.

https://github.com/actions/actions-runner-controller/blob/9b053102ed5bbc924118fa68d34115787c037c20/charts/gha-runner-scale-set/values.yaml#L117
```yaml
n/a
```

### Controller Logs

```shell
n/a
```

### Runner Pod Logs

```shell
n/a
```
