### ISSUE TITLE
Runner cancelled while job is still running

### ISSUE THREAD

**Issue by jwilkicki** [actions/actions-runner-controller#3298]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.2

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

1.  Setup ARC system per quickstart:
```
NAMESPACE="arc-systems"
helm install arc \
    --namespace "${NAMESPACE}" \
    --create-namespace \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller

kubectl create configmap -n "${NAMESPACE}" self-signed-cert --from-file=self.crt=/usr/local/share/ca-certificates/self.crt
kubectl rollout restart -n "${NAMESPACE}" deployment arc-gha-rs-controller
```
2. Then installed a runner set with this configuration:

```yaml
githubConfigUrl: https://github.mycompany.com/development/my_repo

template:
  spec:
    initContainers:
      - name: init-dind-externals
        image: docker.repositories.mycompany.com/my-custom-runner:latest
        command:
          ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
    containers:
      - name: runner
        image: docker.repositories.mycompany.com/my-custom-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///run/docker/docker.sock
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /run/docker
            readOnly: true
      - name: dind
        image: docker.repositories.mycompany.com/docker:dind
        args:
          - dockerd
          - --host=unix:///run/docker/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /run/docker
          - name: dind-externals
            mountPath: /home/runner/externals
    volumes:
      - name: work
        emptyDir: {}
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}

githubServerTLS:
  certificateFrom:
    configMapKeyRef:
      name: self-signed-cert
      key: self.crt
  runnerMountPath: /usr/local/share/ca-certificates/
```
And this command:

```shell
INSTALLATION_NAME="myrepo-runner-set"
NAMESPACE="arc-runners"
GITHUB_PAT="XXXXXX"

helm upgrade "${INSTALLATION_NAME}" \
    --install \
    --namespace "${NAMESPACE}" \
    --create-namespace \
    --set githubConfigSecret.github_token="${GITHUB_PAT}" \
    -f runners_values.yaml \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

kubectl create configmap -n "${NAMESPACE}" selfcert --from-file=self.crt=/usr/local/share/ca-certificates/self.crt
```

I created a custom docker image to add my self-signed cert and a bunch tools:

```Dockerfile
FROM ghcr.io/actions/actions-runner:latest

USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y \
  && apt-get install -y software-properties-common \
  && add-apt-repository -y ppa:git-core/ppa \
  && apt-get update -y \
  && apt-get install -y --no-install-recommends \
  curl \
  ca-certificates \
  git \
  iproute2 \
  iptables \
  jq \
  sudo \
  uidmap \
  unzip \
  zip \
  fuse-overlayfs \
  gpg \
  lsb-release \
  apt-transport-https \
  openssh-client

# Download latest git-lfs version
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
  apt-get install -y --no-install-recommends git-lfs

COPY self.crt /usr/local/share/ca-certificates
RUN update-ca-certificates


# Install Terraform
ENV TERRAFORM_VERSION="1.3.7"
ENV VAULT_VERSION="1.15.4"
RUN curl -Lo hashicorp.gpg https://apt.releases.hashicorp.com/gpg && \
  apt-key add hashicorp.gpg && \
  rm hashicorp.gpg && \
  echo "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list && \
  apt-get -y update && \
  apt-get -y install terraform${TERRAFORM_VERSION:+=}${TERRAFORM_VERSION}  && \
  rm -v /etc/apt/sources.list.d/hashicorp.list && \
  terraform version 
  
RUN curl -Lo vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip && \
  unzip vault.zip && \
  chmod +x vault && \
  mv vault /usr/local/bin/ && \
  vault version    


# Clean APT cache - put all apt installs before here
RUN rm -rf /var/lib/apt/lists/*

# Install kubectl
ENV KUBECTL_VERSION="v1.26.0"
RUN curl -L -o /usr/local/bin/kubectl "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" &&\
  chmod 755 /usr/local/bin/kubectl && \
  kubectl version --client=true --short

# Install helm
ENV HELM_VERSION="3.13.3"
RUN curl -L -o helm.tar.gz "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" &&\
  tar zxvf helm.tar.gz linux-amd64/helm &&\
  mv linux-amd64/helm /usr/local/bin &&\
  rmdir linux-amd64 &&\
  chmod 755 /usr/local/bin/helm &&\
  rm helm.tar.gz && \
  helm version

# Install awscli v2
# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
  unzip awscliv2.zip && \
  ./aws/install && \
  rm -rfv aws awscliv2.zip && \
  aws --version

ENV TERRAGRUNT_VERSION="v0.55.4"
ADD https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 /tmp
RUN mv /tmp/terragrunt_linux_amd64 /usr/local/bin/terragrunt && \
  chmod +x /usr/local/bin/terragrunt && \
  terragrunt --version

USER runner
```

### Describe the bug

The runner starts running the job and while running a `go test` command shows:  `Error: Process completed with exit code 130.`

Annotations on the job are:

test / test
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
test / test
The operation was canceled.
test / test
Process completed with exit code 130.

The job should run to completion.  Output from the `go test` command seemed to indicate that tests were passing and there weren't any error messages.

### Describe the expected behavior

The job should run to completion, even if `go test` fails

### Additional Context

```yaml
See steps to reproduce
```

### Controller Logs

```shell
https://gist.github.com/jwilkicki/b1b3ec5ae2cad23285f4c40d18070daf
```

### Runner Pod Logs

```shell
https://gist.github.com/jwilkicki/5a63aa79d2347605e1caa54e1b2e7fc6
```
