### ISSUE TITLE
Add more packages to base arc runners

### ISSUE THREAD

**Issue by gfrid** [actions/actions-runner-controller#3342]
### What would you like added?
Add the following packages as default in arc runners
- curl 
- unzip 
- jq 
- wget 
- python3-pip 
- git-all

### Why is this needed?
The Arc runner is too shallow to be able to use it with almost any action in Marketplace also the lack of GIT installation 
renders the ARC unusable when first deployed.

### Additional context
Current workaround until added to runner image:
```
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/bin/bash","-c","sudo apt-get update && sudo apt-get install curl unzip jq wget python3-pip git-all -y && /home/runner/run.sh"]
```
