### ISSUE TITLE
Add resource mgmt to ARC runner set

### ISSUE THREAD

**Issue by gfrid** [actions/actions-runner-controller#3343]
### What would you like added?
Add resource management to container  

### Why is this needed?
Missing clear documentation how to set it, the default should be at least ~1-2Gib Mem and 0.5-1.0 CPU
if less is configured the ARC will fail to compile Docker image and even NPM install fails due to insufficient resources.
This is also not stated in docs.

### Additional context
Workaround: configure manually by adding manually.
```
        resources:
          requests:
            memory: 2Gi
            cpu: 1.0
          limits:
            cpu: 4.0
            memory: 8Gi
```
