### ISSUE TITLE
Runner Scale Set gets stuck, crash loops every 3 seconds: failed to create session: 409 had issue communicating with Actions backend: The runner scale set gha-rs already has an active session for owner gha-rs-7db9c9f7-listener

### ISSUE THREAD

**Issue by jeffmccune** [actions/actions-runner-controller#3351]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Install on west coast cluster
2. Install on east coast cluster
3. Create one `AutoscalingRunnerSet` named `gha-rs` in each of the two clusters.
4. Observe one of the listener pods becomes deadlocked with error `Application returned an error: createSession failed: failed to create session: 409 - had issue communicating with Actions backend: The runner scale set gha-rs already has an active session for owner gha-rs-deadbeef-listener.`
```

### Describe the bug

The listener fails to start.

### Describe the expected behavior

The listener should start in both clusters.

### Additional Context

```yaml
The values.yaml used is as close to the upstream documentation as possible.  The only customization is:


values: {
	controllerServiceAccount: name:      "gha-rs-controller"
	controllerServiceAccount: namespace: "arc-system"
	githubConfigSecret: "controller-manager"
	githubConfigUrl:    "https://github.com/myorg"
}


Where the `controller-manager` secret contains GitHub App credentials.
```

### Controller Logs

```shell
https://gist.github.com/jeffmccune/e893d4af28727d55979f75fcfddc6536#file-controller-logs-txt
```

### Runner Pod Logs

```shell
https://gist.github.com/jeffmccune/e893d4af28727d55979f75fcfddc6536#file-listener-pod-logs-txt
```
