### ISSUE TITLE
When starting gha-runner-scale-set in "dind" mode, I would like to be able to change the Dockerd settings in the Pod using the values.yaml.

### ISSUE THREAD

**Issue by t-matsu200** [actions/actions-runner-controller#3403]
### What would you like added?

When gha-runner-scale-set is started in "dind" mode, I would like to be able to change the proxy settings and insecure-registry settings for Dockerd on the Pod from values.yaml.

### Why is this needed?

When starting gha-runner-scale-set in "dind" mode behind a proxy server, it was not possible to retrieve container images from the internet when running GitHub Actions workflows.
Additionally, it was not possible to retrieve images from container registries with self-certificates applied.
If I modify the settings of "gha-runner-scale-set.dind-container" appropriately, it will behave as expected.
I would like to be able to change proxy settings and insecure-registry settings without having to perform these workarounds.

Actually, I modified the following parts and started gha-runner-scale-set.

◆Added "HTTP_PROXY", "HTTPS_PROXY" and "NO_PROXY"
https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl#L104-L106

◆Mount ConfigMap to "/etc/docker/daemon.json"
https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl#L109-L115

### Additional context

*Add any other context or screenshots about the feature request here.*

**Comment by Hazmi35** [comment]
I need to modify dockerd args on dind container, turns out it is not templated and is hardcoded directly at https://github.com/actions/actions-runner-controller/blob/1987d9eb2ed60b8164bde872ea61b159582ceb40/charts/gha-runner-scale-set/templates/_helpers.tpl#L98-L116

**Comment by Hazmi35** [comment]
> I need to modify dockerd args on dind container, turns out it is not templated and is hardcoded directly at
> 
> https://github.com/actions/actions-runner-controller/blob/1987d9eb2ed60b8164bde872ea61b159582ceb40/charts/gha-runner-scale-set/templates/_helpers.tpl#L98-L116

cc @nikola-jokic. 
I apologize for the mention, but as you are one of the maintainers who frequently commits here.

This issue is labeled `community` but the author clearly states this is for `gha-runner-scale-set`. It is kinda confusing where to report bug and or feature request regarding helm charts for `gha-runner-scale-set`. 

I am not even sure if this is a feature request or a bug because is this intended or something that need to be addressed? I see that there's also PR related to this issue: https://github.com/actions/actions-runner-controller/pull/3394

**Comment by nikola-jokic** [comment]
Hey everyone,

@Hazmi35 you are right, this one is for the gha-runner-scale-set. 
Feature requests related to the `gha-runner-scale-set` should be submitted to the GitHub Community Support Forum:
![image](https://github.com/actions/actions-runner-controller/assets/97525037/a72652cc-d9e7-4606-b71a-22e404629dfb)

That being said, we [documented](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#customizing-container-modes) that:
> To customize the spec, comment out or remove containerMode, and append the configuration you want in the template section.

It should be easy since we documented the exact setup in values.yaml file that would be used for that container mode. I will close this issue here. :relaxed:

**Comment by ui-kane-lin** [comment]
@Hazmi35 Hi, I edited `dind` in `./charts/gha-runner-scale-set/values.yaml `, then I upgrade and restart pods, but settings not working.

Could you share how to modify dind? Thanks

```yml
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --host=unix:///var/run/docker.sock
          - --group=$(DOCKER_GROUP_GID)
          - --insecure-registry=xxxxx.com:5050
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
          - name: DOCKER_OPTS
            value: "--insecure-registry=xxxxx.com:5050 --config-file /etc/docker/daemon.json"
```

**Comment by Hazmi35** [comment]
> @Hazmi35 Hi, I edited `dind` in `./charts/gha-runner-scale-set/values.yaml `, then I upgrade and restart pods, but settings not working.
> 
> Could you share how to modify dind? Thanks
> 
> ```yaml
>       - name: dind
>         image: docker:dind
>         args:
>           - dockerd
>           - --host=unix:///var/run/docker.sock
>           - --group=$(DOCKER_GROUP_GID)
>           - --insecure-registry=xxxxx.com:5050
>         env:
>           - name: DOCKER_GROUP_GID
>             value: "123"
>           - name: DOCKER_OPTS
>             value: "--insecure-registry=xxxxx.com:5050 --config-file /etc/docker/daemon.json"
> ```

Hi, yeah. It seems that it still is hardcoded in the template file on the latest version. I haven't yet created feature request for gha-runner-scale-set.

Because there's no way to configure only the arguments for dind, so I override the whole template instead.

```yaml
## template is the PodSpec for each runner Pod
## For reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
template:
  spec:
    initContainers:
      - name: init-dind-externals
        image: ghcr.io/actions/actions-runner:latest
        imagePullPolicy: Always
        command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - mountPath: /home/runner/tmpDir
            name: dind-externals
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        imagePullPolicy: Always
        command: ["/home/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
          - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
            value: '120'
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 128Mi
      - name: dind
        image: mirror.gcr.io/library/docker:dind
        imagePullPolicy: Always
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
          - name: dind-externals
            mountPath: /home/runner/externals
          - name: dind-config
            mountPath: /etc/docker/daemon.json
            readOnly: true
            subPath: daemon.json
        args:
          - dockerd
          - '--host=unix:///var/run/docker.sock'
          - '--group=$(DOCKER_GROUP_GID)'
        resources:
          limits:
            cpu: 8000m
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 128Mi
    volumes:
      - name: work
        emptyDir: {}
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
      - name: dind-config
        configMap:
          name: actions-runner-dind-config
```

And, I don't modify the dockerd args anymore but added a configuration file to `/etc/docker/daemon.json`

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: actions-runner-dind-config
  namespace: devops
data:
  # ! Please change the mtu value to match your network configuration
  daemon.json: |
    {
      "mtu": 1350,
      "default-network-opts": {
        "bridge": {
         "com.docker.network.driver.mtu": "1350"
        }
      },
      "registry-mirrors": ["https://mirror.gcr.io"]
    }
  ```
