### ISSUE TITLE
Actions runner deployed in kubernetes mode on aks has /runner/_work/externals volume empty causing this error - env: ‘/__e/node20/bin/node’: No such file or directory

### ISSUE THREAD

**Issue by jjayapandian** [actions/actions-runner-controller#3425]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

 0.20.2

### Deployment Method

Helm

### cert-manager installation

using 1.11.4 cert manager

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [x] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: 
  namespace: 
spec:
  replicas: 1
  template:
    metadata: {}
    spec:
      dockerEnabled: false
      dockerdContainerResources: {}
      enterprise: 
      env:
      - name: GITHUB_ACTIONS_RUNNER_TRACE
        value: "true"
      - name: RUNNER_CONTAINER_IN_SAME_NODE
        value: "true"
      group: 
      image: 
      labels:
      - azure
      resources: {}

helm chart values.yaml
actions-runner-controller:
  actionsRunner:
    containerProvider: kubernetes
    persistentVolumeEnabled: true
    persistentVolumeStorageClass: azure-storage
    persistentVolumeStorageSize: 100Mi
```

### To Reproduce

```markdown
1. Use azure storage 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-storage
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
2.Deploy action runner controller on AKS with kubernetes values.yaml
3.Run workflow file
```
---
```
name: test
on:
  workflow_dispatch:
jobs:
  job2:
    runs-on: azure
    container:
      image: alpine
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: dir1
```

### Describe the bug

Getting env: ‘/__e/node20/bin/node’ : No such file or directory when running runners in kubernetes mode

### Describe the expected behavior

/runner/_work/externals  is empty whereas /runner/externals has the data somehow its not mapping properly in kubernetes mode

### Whole Controller Logs

```shell
NA
```

### Whole Runner Pod Logs

```shell
NA
```

### Additional Context

NA

**Comment by procinger** [comment]
Hello search engine user,

I also ran into this problem today. My setup is a Kubernetes cluster with DinD. We use Docker containers in some Github jobs. So that the external tools are also available in Dind, I have created an initContainer which copies externals directory into an emptyDir volume.

```
initContainers:
- name: init-runner
  image: ghcr.io/actions/actions-runner:latest
  imagePullPolicy: IfNotPresent
  command: ["sh", "-c", "cp -ar /home/runner/externals/* /externals/"]
  volumeMounts:
    - name: externals
      mountPath: /externals
containers:
- name: runner
  image: ghcr.io/actions/actions-runner:latest
...snip...
  volumeMounts:
    - name: work
      mountPath: /home/runner/_work
    - name: externals
      mountPath: /home/runner/externals
...snip...
- name: dind
  imagePullPolicy: IfNotPresent
  image: docker:dind
...snip...
  volumeMounts:
    - name: work
      mountPath: /home/runner/_work
    - name: externals
      mountPath: /home/runner/externals
```
hope it helps
