### ISSUE TITLE
Change dind default image

### ISSUE THREAD

**Issue by romankydybets** [actions/actions-runner-controller#3439]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Intall with values file below helm chart
```

### Describe the bug

according to this part configuration
https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml#L134-L135
i could change it for example to any dind image through the values,
but unfortunately it defined inside the helper so no options to override
https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl#L98-L99
do anyone have ideas how to handle such situation?

### Describe the expected behavior

i would like to provide my custom image through the values.

### Additional Context

```yaml
minRunners: 0
maxRunners: 50
containerMode:
  type: "dind"
template:
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/lifecycle
                  operator: In
                  values:
                    - arc-arm64
    containers:
    - name: runner
      image: <runner-image>:2.314.1
      imagePullPolicy: IfNotPresent
      command: ["/home/runner/run.sh"]
      env:
        - name: DOCKER_HOST
          value: unix:///run/docker/docker.sock
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /run/docker
          readOnly: true
      resources:
        requests:
          cpu: 4
          memory: 8Gi
    - name: dind
      image: <dind-repo>:dind
      args:
        - dockerd
        - --host=unix:///run/docker/docker.sock
        - --group=$(DOCKER_GROUP_GID)
      env:
        - name: DOCKER_GROUP_GID
          value: "123"
      resources:
        requests:
          cpu: 4
          memory: 8Gi
      securityContext:
        privileged: true
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /run/docker
        - name: dind-externals
          mountPath: /home/runner/externals
    volumes:
    - name: work
      emptyDir: {}
flags:
  logLevel: "debug"
  logFormat: "text"
```

### Controller Logs

```shell
The are not additional logs, we just heat the limit of pull images
```

### Runner Pod Logs

```shell
The are not additional logs, we just heat the limit of pull images
```
