### ISSUE TITLE
ARC Finalizers Cause a deadlock when uninstalling AutoscalingRunnerSet in ArgoCD

### ISSUE THREAD

**Issue by rteeling-evernorth** [actions/actions-runner-controller#3440]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.0

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Install the ARC AutoscalingRunnerSet as an ArgoCD app
2. Uninstall ArgoCD app
```

### Describe the bug

The argocd app cannot be deleted because Argo tries to delete resources that are normally deleted by the ARC controller and normal deletion is blocked by the `actions.github.com/cleanup-protection` finalizer
including:

- AutoscalingRunnerSet
- kube mode service account
- kube mode role
- rs manager role
- kube mode role binding
- rs manager role binding

### Describe the expected behavior

The chart should cleanly uninstall when i delete the argocd app

### Additional Context

```yaml
I suspect this may be resolvable by helm/argo annotations for the affected resources, I will test with a fork of the helm chart
```

### Controller Logs

```shell
My employer's open source contribution policy forbids me from creating public Gists. I will provide redacted logs upon request via zip/tarball.
```

### Runner Pod Logs

```shell
My employer's open source contribution policy forbids me from creating public Gists. I will provide redacted logs upon request via zip/tarball.
```

**Comment by rteeling-evernorth** [comment]
I was successfully able to fix the issue using argocd annotations  `argocd.argoproj.io/sync-options: Delete=false` and `argocd.argoproj.io/sync-wave: "1"`, I'll open a PR

**Comment by rteeling-evernorth** [comment]
@nikola-jokic could I trouble you for your two cents on this?

**Comment by ahatzz11** [comment]
@rteeling-evernorth Thanks for making an issue for this - I've run into this issue on nearly every upgrade and end up having to turn off syncing, manually delete the finalizers, and then turn syncing back on and it ends up sorting itself out. I do use `sync-waves` on the top level resources to ensure the `gha-runner-scale-set-controller` syncs first and the `gha-runner-scale-set-figure-linux-standard` syncs second:

```
metadata:
  name: gha-runner-scale-set-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # before scale-set

---

metadata:
  name: gha-runner-scale-set-figure-linux-standard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # after controller
```

Looking at your PR you set `argocd.argoproj.io/sync-wave: "1"` - would that conflict in my case with my controller having the same sync wave? Would it makes sense to go negative on the sync-wave for the autoscalingrunnerset to always ensure that runs first?

**Comment by ahatzz11** [comment]
@rteeling-evernorth Thanks for making an issue for this - I've run into this issue on nearly every upgrade and end up having to turn off syncing, manually delete the finalizers, and then turn syncing back on and it ends up sorting itself out. I also have noticed that even if a new controller comes up (say `0.9.1` when upgrading from `0.9.0`) it doesn't seem like that new controller properly handles the finalizers on the scale-set resources that are on the old version.


I do use `sync-waves` on the top level resources to ensure the `gha-runner-scale-set-controller` syncs first and the `gha-runner-scale-set-figure-linux-standard` syncs second:

```
metadata:
  name: gha-runner-scale-set-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # before scale-set

---

metadata:
  name: gha-runner-scale-set-figure-linux-standard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # after controller
```

Looking at your PR you set `argocd.argoproj.io/sync-wave: "1"` - would that conflict in my case with my controller having the same sync wave? Would it makes sense to go negative on the sync-wave for the autoscalingrunnerset to always ensure that runs first?
