### ISSUE TITLE
Failed to get new registration token while installing ARC org wide for enterprise GITHUB

### ISSUE THREAD

**Issue by itsmekarthikreddy** [actions/actions-runner-controller#3484]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.6

### Helm Chart Version

0.23.7

### CertManager Version

1.8.0

### Deployment Method

Helm

### cert-manager installation

Yes Installed as per ARC Doc

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: k8s-runners-autoscaler
  namespace: XXXX-actions-runners
spec:
  scaleTargetRef:
    name: k8s-runners
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - XXX/XXX
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: k8s-single-runner
  namespace: XXXX-actions-runners
spec:
  repository: XXXX/XXXX
  env: []
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners
  namespace: XXXX-actions-runners
spec:
  template:
    spec:
      repository: XXXX/XXXX
      labels:
        - XXX-core-stack
      env: []
```

### To Reproduce

```markdown
Create GIT HUB app as per https://github.com/actions/actions-runner-controller/blob/master/docs/authenticating-to-the-github-api.md
Create secret controller-manager in actions-runners-system with above details and pem key
```

### Describe the bug

Failed to get new registration token

### Describe the expected behavior

Runner should be created successfully.

### Whole Controller Logs

```shell
https://gist.github.com/itsmekarthikreddy/18c5112333acaee2c54f0945b0f87222
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/itsmekarthikreddy/18c5112333acaee2c54f0945b0f87222
```
