### ISSUE TITLE
Lost communication with the server due to the GitHub API returning a BadRequest or Forbidden error

### ISSUE THREAD

**Issue by Thiry1** [actions/actions-runner-controller#3519]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
The issue occurs randomly, so a specific reproduction method has not been identified.
```

### Describe the bug

The following error is displayed in the GitHub Actions execution log:
```
The self-hosted runner: runner-bgkcw-runner-rh47x lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

When checking the runner's pod logs, I found the following two errors:
```
[RUNNER 2024-05-15 07:40:21Z ERR  GitHubActionsService] GET request to https://pipelinesghubeus10.actions.githubusercontent.com/XXX/_apis/distributedtask/pools/1/messages?sessionId=34d4403f-0a18-48ad-a541-f773c0e60b88&status=Online&runnerVersion=2.316.1&os=Linux&architecture=X64&disableUpdate=true failed. HTTP Status: Forbidden
```
```
[RUNNER 2024-05-15 07:40:29Z ERR  GitHubActionsService] POST request to https://pipelinesghubeus10.actions.githubusercontent.com/XXX/_apis/oauth2/token failed. HTTP Status: BadRequest
```

These errors occur simultaneously in jobs running on different nodes at the same time.

### Describe the expected behavior

The job completes without errors.

### Additional Context

```yaml
ghaRunnerScaleSetValues:
  runnerScaleSetName: "XXX"
  githubConfigUrl: "https://github.com/XXX"
  githubConfigSecret: "github-apps-secret"
  maxRunners: 8
  minRunners: 1
  containerMode:
    type: "kubernetes"
    kubernetesModeWorkVolumeClaim:
      accessModes:
        - "ReadWriteOnce"
      storageClassName: "gp3"
      resources:
        requests:
          storage: "10Gi"
    kubernetesModeServiceAccount:
      annotations: null
  template:
    spec:
      initContainers:
        - name: "kube-init"
          image: "XXX"
          command: ["sudo", "chown", "-R", "1001:1001", "/home/runner/_work"]
          volumeMounts:
            - name: "work"
              mountPath: "/home/runner/_work"
      containers:
        - name: "runner"
          image: "XXX"
          command: ["/bin/bash", "-c"]
          args: ["sudo nohup containerd & sudo nohup buildkitd & /home/runner/run.sh"]
          resources:
            requests:
              cpu: 5
              memory: "16Gi"
            limits:
              cpu: 8
              memory: "32Gi"
          env:
            - name: "ACTIONS_RUNNER_CONTAINER_HOOKS"
              value: "/home/runner/k8s/index.js"
            - name: "ACTIONS_RUNNER_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: "ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER"
              value: "false"
          volumeMounts:
            - name: "work"
              mountPath: "/home/runner/_work"
          securityContext:
            privileged: true
      volumes:
        - name: "work"
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - "ReadWriteOnce"
                storageClassName: "gp3"
                resources:
                  requests:
                    storage: "10Gi"
```

### Controller Logs

```shell
https://gist.github.com/Thiry1/ab048d389e8801946dd85ff4b221bffd
```

### Runner Pod Logs

```shell
https://gist.github.com/Thiry1/6ab73735da6d1202dd0000243b04c953
```
