### ISSUE TITLE
Failed to reserve container name

### ISSUE THREAD

**Issue by ohookins** [actions/actions-runner-controller#3580]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.2

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Run ARC as intended
2. Run jobs from Github Actions
3. Wait long enough to see this problem
```

### Describe the bug

```
  Warning  Failed     31m (x3 over 32m)  kubelet            Error: failed to reserve container name "init-dind-externals_arc-runner-set-amd
64-q7zq7-runner-2jzmk_arc-runners_9c48686b-7390-4ca2-a2c3-fd8f987006fd_0": name "init-dind-externals_arc-runner-set-amd64-q7zq7-runner-2jzm
k_arc-runners_9c48686b-7390-4ca2-a2c3-fd8f987006fd_0" is reserved for "b911cb53c12aaaf27a723838474f67aa987e24662ac79cbaa5a696fccb917e72"
```

Occasionally we are seeing this error in pods, which get stuck in the state `init:CreateContainerError`. It's not clear how they get there. The error above is in the events of the failed pods. It appears that there may be some race condition or resource checking which is not happening correctly in the controller since a pod seemingly exists already (at least, with the picked identifiers) when another is created.

### Describe the expected behavior

We don't get this error on any runner pods being created.

### Additional Context

```yaml
runnerGroup: self-hosted-amd64
githubConfigUrl: xxxx
githubConfigSecret: xxxx

# From: https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml#L108
template:
  spec:
    serviceAccountName: default
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/arch: amd64
    initContainers:
    - name: init-dind-externals
      image: xxxx/actions-runner:latest
      command: ["cp", "-r", "/home/runner/externals/.", "/home/runner/tmpDir/"]
      volumeMounts:
        - name: dind-externals
          mountPath: /home/runner/tmpDir
    - name: dind
      image: xxxx/docker:dind
      restartPolicy: Always
      args:
        - dockerd
        - --host=unix:///run/docker/docker.sock
        - --group=$(DOCKER_GROUP_GID)
      startupProbe:
        exec:
          command:
            - docker
            - --host=unix:///run/docker/docker.sock
            - version
      env:
        - name: DOCKER_GROUP_GID
          value: "123"
      resources:
        requests:
          cpu: 1
          memory: 4G
      securityContext:
        privileged: true
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /run/docker
        - name: dind-externals
          mountPath: /home/runner/externals
    containers:
    - name: runner
      image: xxxx/actions-runner:latest
      imagePullPolicy: Always
      command: ["/home/runner/run.sh"]
      env:
        - name: DOCKER_HOST
          value: unix:///run/docker/docker.sock
      resources:
        requests:
          cpu: 2
          memory: 8G
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /run/docker
          readOnly: true
    volumes:
    - name: work
      emptyDir: {}
    - name: dind-sock
      emptyDir: {}
    - name: dind-externals
      emptyDir: {}
```

### Controller Logs

```shell
I haven't managed to catch the controller logs for this in the act yet.
```

### Runner Pod Logs

```shell
N/A the runner can't init.
```
