### ISSUE TITLE
Scale Set Contoller stuck: thinks runner pods are failed, but they have been deleted

### ISSUE THREAD

**Issue by garymm** [actions/actions-runner-controller#3592]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.2

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Not sure but a guess:
1. Deploy a scale set controller
1. Deploy a scale set
1. Trigger some jobs
1. The jobs fail
1. ??? Not sure ???
```

### Describe the bug

The controller thinks that the runners are in state `failed` forever and thus won't scale the scale set up anymore.
In reality the runners have been deleted and no longer exist.
In the controller log we see:
`"name":"berkeley-gpu-runners-pltxc-runner-s4b7j","namespace":"gh-actions-runner-scale-sets"`

But:
```sh
❯ kubectl get pod berkeley-gpu-runners-pltxc-runner-s4b7j -n gh-actions-runner-scale-sets
Error from server (NotFound): pods "berkeley-gpu-runners-pltxc-runner-s4b7j" not found
```

### Describe the expected behavior

The controller pod notices that the runner pods no longer exist and reacts appropriately.

### Additional Context

```yaml
controller values are all defaults.


scale set values:

githubConfigSecret: pre-defined-secret
githubConfigUrl: https://github.com/Astera-org
controllerServiceAccount:
  namespace: gha-runner-scale-set-controller
  name: gha-runner-scale-set-controller-gha-rs-controller
minRunners: 1
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        resources:
          limits:
            nvidia.com/gpu: 1
```

### Controller Logs

```shell
https://gist.github.com/garymm/22ad6e8e9f6a38576e138a72793dc67a
```

### Runner Pod Logs

```shell
There are no pods running.
```
