### ISSUE TITLE
Github App Authentication not working: Not found 404

### ISSUE THREAD

**Issue by Smana** [actions/actions-runner-controller#3615]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.2

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Install the controller
2. Define an AutoscalingRunnerSet
3. Checking the controller's log. In the gist below


Actually everything is defined [here](https://github.com/Smana/demo-cloud-native-ref/tree/feat_github_arc/tooling/base/arc)
```

### Describe the bug

Hey everyone,

Even though I folowed the [documentation](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api#authenticating-arc-with-a-github-app) related to the authentication, I'm not able to get the controller working properly.
It seems to be permissions issues but I'm not sure.

Could you please give me a hand?

Thank you.

### Describe the expected behavior

A runner should be created, I should not have these authentication error logs.

### Additional Context

[here](https://github.com/Smana/demo-cloud-native-ref/tree/feat_github_arc/tooling/base/arc)

Controller values:
```yaml
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    flags:
      logLevel: "debug"
      logFormat: "json"
```

Scaler-set values:
```yaml
    runnerGroup: "default"
    githubConfigUrl: "https://github.com/Smana"
    githubConfigSecret: default-gha-runner-scale-set
    maxRunners: 5

    containerMode:
      type: "kubernetes"
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp3"
        resources:
          requests:
            storage: 10Gi
```

### Controller Logs

```shell
https://gist.github.com/Smana/70257128cf9892df7537f787b679c445
```

### Runner Pod Logs

```shell
No runners
```

**Comment by Smana** [comment]
I'm wondering if I misunderstood what to put under the githubConfigUrl :thinking:

**Comment by Smana** [comment]
oh it seems that specifying a repo did the trick, but would that mean that I should have a scaler-set per repo??

**Comment by Smana** [comment]
Ok the action was scheduled in my cluster even though I got the error
```console
System.UnauthorizedAccessException: Access to the path '/home/runner/_work/_tool' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

But that's another issue, I'm digging into.
Anyway can somebody answer to my question above? Then I'll close this issue.

**Comment by Smana** [comment]
Regarding the permissions issue I'm gonna try [this method](https://github.com/actions/actions-runner-controller/issues/2890). But that's strange if this is required to change the permissions ...

**Comment by Smana** [comment]
I fixed my filesystem issue using
```yaml
    template:
      spec:
        securityContext:
          runAsUser: 1001
          runAsGroup: 123
          fsGroup: 1000
```

I'm gonna close this issue and I'll ask my question regarding a scaler set per repo in the discussions.
