### ISSUE TITLE
Helm warning when using gha-runner-scale-set as app dependency

### ISSUE THREAD

**Issue by rfinnie-epic** [actions/actions-runner-controller#3620]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.2

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

`Chart.yaml`:

```yaml
---
apiVersion: 'v2'
name: 'arc-runners'
description: 'GitHub arc runners'
type: 'application'
version: '0.1.0'

dependencies:
  - name: 'gha-runner-scale-set'
    version: '0.9.2'
    repository: 'oci://ghcr.io/actions/actions-runner-controller-charts'
```

`values.yaml`:

```yaml
---
gha-runner-scale-set:
  githubConfigUrl: 'https://github.com/enterprises/example'
  githubConfigSecret: 'runner-pat'
  # ...
```

Run:
```shell
helm install my-label --namespace arc-runners --values ./values.yaml .
```

### Describe the bug

When the above chart is installed or upgraded while pulling in gha-runner-scale-set as a dependency, it produces the following Helm warning:

```
Release "my-label" does not exist. Installing it now.
coalesce.go:286: warning: cannot overwrite table with non table for arc-runners.gha-runner-scale-set.githubConfigSecret (map[github_token:])
NAME: my-label
LAST DEPLOYED: Sun Jun 23 15:30:22 2024
NAMESPACE: arc-runners
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

This warning appears to be harmless as it does successfully use the `runner-pat` k8s secret, but I'm not sure if it's a error on the upstream chart, or with Helm itself.

### Describe the expected behavior

No warning

### Additional Context

```yaml
See above
```

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```
