### ISSUE TITLE
ARC in k8s mode not working with ResourceQuotas. Jobs fail instead of queuing.

### ISSUE THREAD

**Issue by ropelli** [actions/actions-runner-controller#3630]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
In k8s mode using the  container hook template, you need to request more cpu,memory,storage etc. than the resource quota. For example:

1. Define resource quota with hard limit for cpus/memory e.g. 8 cpus

apiVersion: v1
kind: ResourceQuota
metadata:
  name: arc-runners-quota
  namespace: arc-runners
spec:
  hard:
    requests.cpu: "8"

2. Set up ARC with autoscalingrunnerset k8s mode with a container hook template
```yaml
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: self-hosted-k8s
  namespace: arc-runners
spec:
...
  template:
    spec:
      containers:
      - name: runner
        resources:
          requests:
            cpu: "0"
        env:
        ...
        - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
          value: /home/runner/workflow-pod-config/workflow-pod-config.yaml
        ...
        volumeMounts:
        ...
        - mountPath: /home/runner/workflow-pod-config
          name: workflow-pod-config
      volumes:
      ...
      - name: workflow-pod-config
        configMap:
          name: workflow-pod-config
          items:
            - key: workflow-pod-config.yaml
              path: workflow-pod-config.yaml
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-pod-config
  namespace: arc-runners
data:
  workflow-pod-config.yaml: |
    apiVersion: v1
    kind: PodTemplate
    metadata:
      labels:
        app: runner-pod-template
    spec:
      serviceAccountName: kube-mode-workflow
      containers:
      - name: $job
        resources:
          requests:
            cpu: "5"
```
3. Run a workflow with two jobs matching the autoscalingunnerset name
```yaml
push:
  branches: [ main ]
jobs:
  job1:
    runs-on: self-hosted-k8s
    container:
      image: ubuntu:22.04
    steps:
    - run: sleep 60
  job2:
    runs-on: self-hosted-k8s
    container:
      image: ubuntu:22.04
  - run: sleep 60
```
You can also do this with a single job that goes over the resource quota. But above is more likely scenario.
```


### Describe the bug

In the example provided, one job will run successfully, the other will fail when trying to create the workflow pod as the resource quota is temporarily being exceeded.

In general, jobs fail due to quota being temporarily being exceeded.
![image](https://github.com/actions/actions-runner-controller/assets/5762764/9e10bb04-efbb-4c2f-93eb-d580e60b9022)


### Describe the expected behavior

In the example provided, one job should run at a time and queue properly and complete one after the other. Leading to a successful build.

In general, when quota is temporarily exceeded, we should try again after a while preferably through a queue implementation. Though it is also bit stupid that the runner starts even when there is no room for the workflow pod but I am not sure what could be done without changing the architecture of ARC a lot.

### Additional Context

```yaml
This can be considered separate issue than https://github.com/actions/actions-runner-controller/issues/3629 as I believe the code needs to change in a different spot and it behaves a little bit differently. This is why I created two issues.
```

### Controller Logs

```shell
https://gist.github.com/ropelli/2260d7303e4a09c75170105ee1afdaac
```

### Runner Pod Logs

```shell
https://gist.github.com/ropelli/8d8ea405ad54128c24e42292a3aaeb09
```

**Comment by jonathan-fileread** [comment]
Thanks @ropelli for mentioning this. Very curious on a fix!

**Comment by jonathan-fileread** [comment]
bump updates?

**Comment by alexgaganashvili** [comment]
@ropelli , this appears to be related to https://github.com/actions/runner-container-hooks/issues/112
You should set ACTIONS_RUNNER_USE_KUBE_SCHEDULER to true; but your storage class needs to support the ReadWriteMany access mode.

**Comment by ropelli** [comment]
@alexgaganashvili, that doesn't seem to help. I still get the same error. I believe when the node runs out out of resources, the pod gets still created but just won't schedule and may timeout. In the ResourceQuota case, the whole pod never appears in the cluster and errors out at the creation immediately and won't even get that far.

I prepared scripts for trying this out faster. These should work in a standard `kind` cluster. Please put all these in the same directory and override your enterprise github instance url and PAT token:

## deploy.sh
```bash
#!/bin/bash

NAMESPACE=arc-systems
helm upgrade --install arc \
    --namespace $NAMESPACE \
    --create-namespace \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller

INSTALLATION_NAME="arc-runner-set"
NAMESPACE="arc-runners"
GITHUB_CONFIG_URL="https://github.com/<enterprise/org/repo>"
GITHUB_PAT="<your-pat-token>"
helm upgrade --install "${INSTALLATION_NAME}" \
    --namespace "${NAMESPACE}" \
    --create-namespace \
    --set githubConfigUrl="${GITHUB_CONFIG_URL}" \
    --set githubConfigSecret.github_token="${GITHUB_PAT}" \
    --values values.yaml \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

kubectl apply -f others.yaml
```
# values.yaml
```yaml
containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard"
    resources:
      requests:
        storage: 1Gi
template:
  spec:
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      resources:
        requests:
          cpu: "0"
      env:
        - name: ACTIONS_RUNNER_USE_KUBE_SCHEDULER
          value: "true"
        - name: ACTIONS_RUNNER_CONTAINER_HOOKS
          value: /home/runner/k8s/index.js
        - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
          value: /home/runner/workflow-pod-config/workflow-pod-config.yaml
        - name: ACTIONS_RUNNER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "true"
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - mountPath: /home/runner/workflow-pod-config
          name: workflow-pod-config
    volumes:
      - name: workflow-pod-config
        configMap:
          name: workflow-pod-config
          items:
            - key: workflow-pod-config.yaml
              path: workflow-pod-config.yaml
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "standard"
              resources:
                requests:
                  storage: 1Gi
```

# others.yaml
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-pod-config
  namespace: arc-runners
data:
  workflow-pod-config.yaml: |
    apiVersion: v1
    kind: PodTemplate
    metadata:
      labels:
        app: runner-pod-template
    spec:
      containers:
      - name: $job
        resources:
          requests:
            cpu: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: arc-runners-quota
  namespace: arc-runners
spec:
  hard:
    requests.cpu: "8"

```
