### ISSUE TITLE
DIND gha-runner-scale-set: cp: cannot stat '/home/runner/externals/.': No such file or directory

### ISSUE THREAD

**Issue by rdvansloten** [actions/actions-runner-controller#3634]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
- Install latest oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
- Watch as "init-dind-externals" errors out with cp: cannot stat '/home/runner/externals/.': No such file or directory
```

### Describe the bug

Expected my init-dind-externals to work.

### Describe the expected behavior

init-dind-externals should start, so that my runner can.

### Additional Context

```yaml
Using this Dockerfile build from the main branch of the repo:
actions-runner-dind.ubuntu-22.04.dockerfile

Passing this values file, straight from the docs, with edits where needed. The images are from my private registry, since our firewall doesn't allow remote pull. I imported/built official Dockerfiles from the repo, or pulled straight from ghcr. I built/imported everything for 0.9.3 today.


githubConfigUrl: "https://github.com/my-company"
githubConfigSecret:
  github_token: "redacted"

runnerGroup: "redacted"

template:
  spec:
    initContainers:
      - name: init-dind-externals
        image: redacted.azurecr.io/actions/actions-runner:latest
        command:
          ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
    containers:
      - name: runner
        image: redacted.azurecr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
      - name: dind
        image: redacted.azurecr.io/library/docker:26.1.4-dind
        args:
          - dockerd
          - --host=unix:///var/run/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
          - name: dind-externals
            mountPath: /home/runner/externals
    volumes:
      - name: work
        emptyDir: {}
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
```
```


### Controller Logs

```shell
Controller has no opinion about a crashing init container.
```

### Runner Pod Logs

```shell
`cp: cannot stat '/home/runner/externals/.': No such file or directory`
```

**Comment by umaasik** [comment]
I'm running into the same issue using rootless images.

**Comment by aaronmassicotte** [comment]
Same boat here, on 0.9.2. It's odd because this is only occurring on one of 3 runnersets, all using the same helm chart and cluster

**Comment by claytonchew** [comment]
Submitted a fix (#3740) for this.

**Comment by AurimasNav** [comment]
I'm encountering this when trying to use values.yaml to specify my runner image:

```yaml
template:
  spec:
    containers:
    - name: runner
      image: private-repo.com/actions-runner:latest
      command: ["/home/runner/run.sh"]
```

which is built using Dockerfile:

```Dockerfile
FROM summerwind/actions-runner:latest

USER root

RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

RUN <<EOF
. /etc/os-release
wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y -qq powershell
EOF

USER runner
```
