### ISSUE TITLE
Rootless DIND runner set does not work following official documentation

### ISSUE THREAD

**Issue by shodanwashere** [actions/actions-runner-controller#3646]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Go to https://docs.github.com/en/enterprise-cloud@latest/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#example-running-dind-rootless
2. Use the supplied snippet and use the runner set chart to create a runner set using rootless DIND.
3. Set the `minRunners` to 1 so you can have one runner pod be spawned and tested on.
4. The Pod should initialize but the DIND container will fail with an Error.
```

### Describe the bug

The runner pods don't become Ready. When analyzing the logs of the DIND container, I get errors reporting "Permissions denied".

### Describe the expected behavior

I expected the runner pod to get Ready and just work with pipelines.

### Additional Context

```yaml
githubConfigUrl: "https://github.com/enterprises/REDACTED"

githubConfigSecret:
  github_token: "ghp_REDACTED"

maxRunners: 8

minRunners: 2

template:
  spec:
    initContainers:
    - name: init-dind-externals
      image: ghcr.io/actions/actions-runner:latest
      command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
      volumeMounts:
      - name: dind-externals
        mountPath: /home/runner/tmpDir
      securityContext:
        runAsUser: 0
    - name: init-dind-rootless
      image: docker:dind-rootless
      command:
        - sh
        - -c
        - |
          set -x
          cp -a /etc/. /dind-etc/
          echo 'runner:x:1001:1001:runner:/home/runner:/bin/ash' >> /dind-etc/passwd
          echo 'runner:x:1001:' >> /dind-etc/group
          echo 'runner:100000:65536' >> /dind-etc/subgid
          echo 'runner:100000:65536' >>  /dind-etc/subuid
          chmod 755 /dind-etc;
          chmod u=rwx,g=rx+s,o=rx /dind-home
          chown 1001:1001 /dind-home
      securityContext:
        runAsUser: 0
        privileged: true
      volumeMounts:
        - mountPath: /dind-etc
          name: dind-etc
        - mountPath: /dind-home
          name: dind-home
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      securityContext:
        privileged: true
        runAsUser: 1001
        runAsGroup: 1001
      env:
      - name: DOCKER_HOST
        value: unix:///var/run/docker.sock
      volumeMounts:
      - name: work
        mountPath: /home/runner/_work
      - name: dind-sock
        mountPath: /var/run
    - name: dind
      image: docker:dind-rootless
      args:
      - dockerd
      - --host=unix:///var/run/docker.sock
      securityContext:
        privileged: true
        runAsUser: 1001
        runAsGroup: 1001
      volumeMounts:
      - name: work
        mountPath: /home/runner/_work
      - name: dind-sock
        mountPath: /var/run
      - name: dind-externals
        mountPath: /home/runner/externals
      - name: dind-etc
        mountPath: /etc
      - name: dind-home
        mountPath: /home/runner
    volumes:
    - name: work
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "gp2"
            resources:
              requests:
                storage: 50Gi
    - name: dind-sock
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "gp2"
            resources:
              requests:
                storage: 5Gi
    - name: dind-externals
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "gp2"
            resources:
              requests:
                storage: 15Gi
    - name: dind-etc
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "gp2"
            resources:
              requests:
                storage: 5Gi
    - name: dind-home
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "gp2"
            resources:
              requests:
                storage: 20Gi
    fsGroup: 1001
```

### Controller Logs

```shell
https://gist.github.com/shodanwashere/72412fbeb9cae702847bf00c5e5037db
```

### Runner Pod Logs

```shell
Describe: https://gist.github.com/shodanwashere/bac9e93a65084b4bb6e9efc5325cff99
Logs (dind): https://gist.github.com/shodanwashere/ab60c36e8166d35ed5847ba81e45ca62
```
