### ISSUE TITLE
ReadWriteMany volumes do not work on kubernetes mode

### ISSUE THREAD

**Issue by flbb** [actions/actions-runner-controller#3673]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Run any action with a ReadWriteMany work volume on a Azure kubernetes Cluster
2. Action ends in error in container initialization
```

### Describe the bug

When using ReadWriteMany volume as the work volume on kubernetes mode on a Azure kubernetes cluster the action results in an error:

```
Run '/home/runner/k8s/index.js'
  shell: /home/runner/externals/node16/bin/node {0}
Error: Error: EPERM: operation not permitted, chmod '/home/runner/_work/externals/node16/bin'
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
``` 

When the Volumes Storage Class is set to use `uid=1001 gid=1001` on the `mountOptions`, the action will not start and ends in idling endlessly.

### Describe the expected behavior

Expected behavior would be having the job write hello with the following configuration:

```
name: Testing
run-name: Testing
on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  testing:
    name: 'testing'
    runs-on: aks-runners-testing
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Test
        run: |
          echo 'hello'
        shell: bash
``` 

### Additional Context

```yaml
Values for the runner-scale-set:

gha-runner-scale-set:
  githubConfigUrl: "---"
  githubConfigSecret: secret
  maxRunners: 30
  minRunners: 0
  containerMode:
    type: kubernetes
  runnerGroup: "aks-runners-group"
  runnerScaleSetName: "aks-runners-testing"
  listenerTemplate:
    spec:
      containers:
      - name: listener
        securityContext:
          runAsUser: 1000
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          imagePullPolicy: Always
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOKS
              value: /home/runner/k8s/index.js
            - name: ACTIONS_RUNNER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
            - name: ACTIONS_RUNNER_USE_KUBE_SCHEDULER
              value: "true"
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
      volumes:
        - name: work
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteMany" ]
                storageClassName: aks-runner-sc
                resources:
                  requests:
                    storage: 1Gi


Storage Class used:

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aks-runner-sc
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Delete
mountOptions:
  - mfsymlinks
  - actimeo=30
  - dir_mode=0777
  - file_mode=0777
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

### Controller Logs

```shell
-
```

### Runner Pod Logs

```shell
-
```

**Comment by gabrik** [comment]
I'm experiencing the a similar issue on self-hosted cluster with NFS persistent for container storage.

Actually the build proceds fine but then stops on the last step with the same error, so I'm following to see if there is anything that can also help my use-case.

**Comment by jonathan-fileread** [comment]
+1 - this is an issue occuring on our end

**Comment by jonathan-fileread** [comment]
securityContext:
      runAsUser: <>
      runAsGroup: <>
      
      


Adjusting this looks to be the fix

**Comment by flbb** [comment]
> ```
> securityContext:
>   runAsUser: <>
>   runAsGroup: <>
> ```
> 
> Adjusting this looks to be the fix

@jonathan-fileread  What kind of a Storage Class are you using? What user/group have you configured to the `securityContext` configuration?

**Comment by flbb** [comment]
You can make this work with the following configurations:
```

gha-runner-scale-set:
  githubConfigUrl: "---"
  githubConfigSecret: secret
  maxRunners: 30
  minRunners: 0
  containerMode:
    type: kubernetes
  runnerGroup: "aks-runners-group"
  runnerScaleSetName: "aks-runners"
  listenerTemplate:
    spec:
      containers:
      - name: listener
        securityContext:
          runAsUser: 1000
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
              value: /home/runner/pod-templates/default.yaml
            - name: ACTIONS_RUNNER_USE_KUBE_SCHEDULER
              value: "true"
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: pod-templates
              mountPath: /home/runner/pod-templates
              readOnly: true
      volumes:
        - name: work
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteMany" ]
                storageClassName: aks-runner-sc
                resources:
                  requests:
                    storage: 10Gi
        - name: pod-templates
          configMap:
            name: runner-pod-template
            
            
Configmap used:

apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-pod-template
  namespace: aks-runners
data:
  default.yaml: |
    ---
    apiVersion: v1
    kind: PodTemplate
    metadata:
      name: runner-pod-template
      namespace: aks-runners
      labels:
        app: runner-pod-template
        azure.workload.identity/use: "true"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: $job
        resources:
          requests:
            cpu: 100m
            memory: 0.5Gi

Storage Class used:

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aks-runner-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
provisioner: file.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Delete
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - actimeo=30
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
