### ISSUE TITLE
Not possible to deploy gha-runner-scale-set-controller helm chart via Fluxcd

### ISSUE THREAD

**Issue by Mikey032** [actions/actions-runner-controller#3728]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Deploy the gha-runner-scale-set-controller helm chart via Fluxcd. Flux yaml files are added in additional context.
2. Deployment fails with error:

NAME	REVISION          	SUSPENDED	READY	MESSAGE                                                                                                                                                                           
arc 	0.9.3+4fda46fd8c4e	False    	False	Helm install failed for release arc systems/arc with chart gha-runner-scale-set-controller@0.9.3+4fda46fd8c4e: 1 error occurred:                                                                                                                                                                                                                                                              * Deployment.apps "arc-gha-rs-controller" is invalid: spec.template.labels: Invalid value: "0.9.3+4fda46fd8c4e": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```


### Describe the bug

The chart revision is used in the arc-gha-rs-controller Deployment which contains a + sign which is not allowed.

### Describe the expected behavior

Succesfull deployment of arc-gha-rs-controller

### Additional Context

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: arc
  namespace: arc-systems
spec:
  interval: 10m
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
  ref:
    tag: 0.9.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-systems
spec:
  interval: 5m
  install:
    remediation:
      retries: 10
  releaseName: arc
  targetNamespace: arc-systems
  chartRef:
    kind: OCIRepository
    name: arc
```


### Controller Logs

```shell
None, not yet running
```


### Runner Pod Logs

```shell
None, not yet running
```

**Comment by t4eman** [comment]
I had a similar issue. I would suggest pulling from GitHub directly.
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: arc
  namespace: arc-systems
spec:
  interval: 10m
  url: https://github.com/actions/actions-runner-controller
  ref:
    tag: gha-runner-scale-set-0.9.3
```

**Comment by Fareroo7** [comment]
@mumoshu @rentziass same issue here...
Would love to see this PR merged soon!

**Comment by arnauvp-factorial** [comment]
Hi! we use flux to deploy ARC to our CI clusters.

This is the yaml for the repository:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gha-runner-scale-set
  namespace: flux-system
spec:
  interval: 30m
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
```

**Comment by jhaumont** [comment]
Hello @arnauvp-factorial 

**EDIT: I finally have a working solution (issue with egress filtering on the cluster...)**

Can you share your helmRelease manifest ? 🙏 
I currently try to setup it. I have the same HelmRepository but I have the following error:

`source-controller  chart pull error: failed to download chart for remote reference: failed to get 'oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller:0.9.3': failed to do request: Head "https://ghcr.io/v2/actions/actions-runner-controller-charts/gha-runner-scale-set-controller/manifests/0.9.3": read tcp 10.64.9.170:48980->140.82.121.33:443: read: connection reset by peer`

And the chart declaration in the HR:
```yaml
chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
```

**Comment by lexdevelop** [comment]
This works for me
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: actions-runner-controller
  namespace: arc-systems
spec:
  interval: 10m
  url: https://github.com/actions/actions-runner-controller
  ref:
    tag: gha-runner-scale-set-0.9.3
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
  namespace: arc-systems
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/gha-runner-scale-set-controller
      version: 0.9.3
      sourceRef:
        kind: GitRepository
        name: actions-runner-controller
```
