### ISSUE TITLE
"Chart version" does not contain the appropriate version

### ISSUE THREAD

**Issue by kizuna-cloud** [actions/actions-runner-controller#3744]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. get an image of "gha-runner-scale-set controller" from the following site and manage it in my cloud

https://hub.docker.com/r/summerwind/actions-runner-controller/tags

2. confirm boot with ArgoCD, pod is stable of "gha-runner-scale-set controller"

3. then build manifest file for B as follows, but error log is detected


    - path: .
      repoURL: ghcr.io/actions
      targetRevision: 0.9.3
      chart: actions-runner-controller-charts/gha-runner-scale-set
      helm:
        values: |
          githubConfigUrl: https://github.com/XXXXXXXXX/YYYYYYYYYYYYYYYYYYYY
          githubConfigSecret: SECRETS
          maxRunners: 2
          minRunners: 1
          controllerServiceAccount:
            namespace: NAMESPACE
            name: "gha-runner-scale-set-controller"
          containerMode:
            type: "kubernetes"
            kubernetesModeWorkVolumeClaim:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "dynamic-blob-storage"
              resources:
                requests:
                  storage: 1Gi
          template:
            spec:
              serviceAccountName: XXXXXXXXXXXXXXXXXXXXX-runner
              containers:
                - name: runner
                  image: "XXXXXXXXXXXXXXXXXXXXXXXXX"
                  command: ["/home/runner/run.sh"]


Apart from the above question, I would like to get the latest image of "gha-runner-scale set". 
Where should I get it from? if you have image that are officially provided, please share url
```

### Describe the bug

```
YYYY-MM-DDTHH:MM:SSZ	INFO	AutoscalingRunnerSet	Autoscaling runner set version doesn't match the build version. Deleting the resource.	{"version": "gha-runner-scale-set-0.9.3", "autoscalingrunnerset": {"name":"gha-runner-scale-set","namespace":"NAMESPACE"}, "targetVersion": "gha-runner-scale-set-0.9.3", "actualVersion": "0.9.3"}
```
Checked Controller Logs and found the above log, so determined that the label in AutoscalingRunnerSet is incorrectly set.

### Describe the expected behavior

 I cloned the officially provided chart to my local environment and modified the Chart version as follows

charts/gha-runner-scale-set/Chart.yaml

```
appVersion: "0.9.3"
↓
appVersion: "gha-ruuner-scale-set-0.9.3"
```

The helm template command was executed and the following label was corrected

```
app.kubernetes.io/version=0.9.3
↓
app.kubernetes.io/version=gha-ruuner-scale-set-0.9.3
```

I don't plan to install Helm Chart locally, so I need to know what to do about it.

### Additional Context

```yaml
values: |
          githubConfigUrl: https://github.com/XXXXXXXXX/YYYYYYYYYYYYYYYYYYYY
          githubConfigSecret: SECRETS
          maxRunners: 2
          minRunners: 1
          controllerServiceAccount:
            namespace: NAMESPACE
            name: "gha-runner-scale-set-controller"
          containerMode:
            type: "kubernetes"
            kubernetesModeWorkVolumeClaim:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "dynamic-blob-storage"
              resources:
                requests:
                  storage: 1Gi
          template:
            spec:
              serviceAccountName: XXXXXXXXXXXXXXXXXXXXX-runner
              containers:
                - name: runner
                  image: "XXXXXXXXXXXXXXXXXXXXXXXXX"
                  command: ["/home/runner/run.sh"]
```

### Controller Logs

```shell
YYYY-MM-DDTHH:MM:SSZ	INFO	AutoscalingRunnerSet	Autoscaling runner set version doesn't match the build version. Deleting the resource.	{"version": "gha-runner-scale-set-0.9.3", "autoscalingrunnerset": {"name":"gha-runner-scale-set","namespace":"NAMESPACE"}, "targetVersion": "gha-runner-scale-set-0.9.3", "actualVersion": "0.9.3"}
```
```


### Runner Pod Logs
no runner pod is created - no events
