### ISSUE TITLE
Idle count metric reports always 0

### ISSUE THREAD

**Issue by velkovb** [actions/actions-runner-controller#3787]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Set minRunners for a specific scale set to 4.
2. Go to the metrics endpoint of a listener pod.
3. Check `gha_idle_runners` metrics and it is 0.
4. Go to your runners settings in Github. Find the specific runner.
5. Search for the runner name and you will see 4 idle runners.
```

### Describe the bug

`gha_idle_runners` is always returned as 0 despite there being idle runners.

### Describe the expected behavior

`gha_idle_runners` is properly returned as the number of idle runners.

### Additional Context

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - spot
fullnameOverride: gha-runner-scale-set-controller
metrics:
  controllerManagerAddr: :8080
  listenerAddr: :8081
  listenerEndpoint: /metrics
priorityClassName: system-cluster-critical
replicaCount: 1
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
tolerations:
- effect: NoSchedule
  key: pot
  operator: Equal
  value: "true"
```

### Controller Logs

```shell
https://gist.github.com/velkovb/61706771a1b7a9d6f27af4d50c63ca35
```

### Runner Pod Logs

```shell
There are no runner pods here.
```
