### ISSUE TITLE
[FEAT] Enable to add annotations to the listeners

### ISSUE THREAD

**Issue by laserpedro** [actions/actions-runner-controller#3815]
### What would you like added?

``` 
listenerTemplate:
    metadata:
      annotations:
      prometheus.io/scrape: true
      prometheus.io/path: /metrics
      prometheus.io/port: 8080
```
### Why is this needed?

We need this to be able to scrap the listener metrics that are very useful for jobs, steps monitoring

### Additional context

Let me know if you want more.

**Comment by jef** [comment]
You can add metrics to the listener, but you're missing the `spec.containers`:

```yaml
listenerTemplate:
  metadata:
    annotations:
      prometheus.io/scrape: true
      prometheus.io/path: /metrics
      prometheus.io/port: 8080
  spec:
    containers:
      - name: listener
```
