### ISSUE TITLE
Actions runner controller gets stuck when pods get evicted

### ISSUE THREAD

**Issue by PythonCoderAS** [actions/actions-runner-controller#3840]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Trigger a lot of jobs that require runners (maybe a matrix with a large number of combinations)
2. Trigger a disk pressure taint on the node (an example is to run out of PVC space on the storage allocator)
3. Remove any other node from the cluster
```

### Describe the bug

My cluster hit a disk pressure taint and 15 pods got evicted. However, when the taint was removed, the evicted pods were stuck and no new pods were launched, meaning that no new self-hosted actions ran until I manually deleted the evicted pods.

### Describe the expected behavior

Either it should auto-delete the evicted pods, or just create new pods on top.

### Additional Context

```yaml
githubConfigUrl: "https://github.com/HARP-research-Inc"
githubConfigSecret:
  github_token: "<redacted>"
containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "local-path"
    resources:
      requests:
        storage: 2Gi
minRunners: 3
```

### Controller Logs

```shell
https://gist.github.com/PythonCoderAS/19d8fc2f3e6a0623ca8311bede0b027e
```

### Runner Pod Logs

```shell
https://gist.github.com/PythonCoderAS/1f39f9769e9ce8e3060f1e4791d7508d
```
