### ISSUE TITLE
Using invalid container causes action run to hang unless force cancelled

### ISSUE THREAD

**Issue by PythonCoderAS** [actions/actions-runner-controller#3845]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Make a workflow where one of the jobs uses an image that does not exist (such as `ghcr.io/actions/totally-fake-container:1`)
```

### Describe the bug

The workflow gets stuck at "Initializing containers" and does not exit, and the cancel button on the UI does not work. I have to use the REST API's "secret" force-cancel endpoint to stop the workflow.

### Describe the expected behavior

The action would fail as soon as it couldn't pull the image

### Additional Context

```yaml
githubConfigUrl: "https://github.com/HARP-research-Inc"
githubConfigSecret:
  github_token: "<redacted>"
containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "local-path"
    resources:
      requests:
        storage: 2Gi
minRunners: 3
```

### Controller Logs

```shell
https://gist.github.com/PythonCoderAS/3d9dada9b51173822750c42641716d19
```

### Runner Pod Logs

```shell
https://gist.github.com/PythonCoderAS/e9f519a1b8a1dfa6f30418527708c398
https://gist.github.com/PythonCoderAS/ebf144381398630d2d3832feb265a132
```
