### ISSUE TITLE
runner pod try to use service account from same namespace where was deployed

### ISSUE THREAD

**Issue by IUAD1K3E** [actions/actions-runner-controller#3928]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.10.1

### Deployment Method

ArgoCD

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
gha-runner-scale-set:
  githubConfigSecret: actions-runner-scaleset
  runnerScaleSetName: "test-runners-dev"
  runnerGroup: my-test-runners-dev
  githubConfigUrl: https://myorg
  maxRunners: 5
  minRunners: 1
  template:
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: runner
          image: https://github-action-runners:v1.0.0
          command: ["/home/runner/run.sh"]
```

### Describe the bug

i deployed via argocd scale-set-controller and scale-set 
play with permissions and in the end get stuck, my scale-set runner tru to use service account in the same namespace as was deployed. 
status:
  message: >-
    Failed to create the pod: pods "actions-runner-scaleset-dev-t4w4z-runner-4xl7t"
    is forbidden: error looking up service account
    actions-runner-scaleset-dev/actions-runner-controller-gha-rs-controller:
    serviceaccount "actions-runner-controller-gha-rs-controller" not found
controller with modified service account ( I just added permission) created in actions-runner-controller namespace. 

### Describe the expected behavior

how to achieve multi scaleset deployments with single controller?  

### Additional Context

```yaml
gha-runner-scale-set:
  githubConfigSecret: actions-runner-scaleset
  runnerScaleSetName: "test-runners-dev"
  runnerGroup: my-test-runners-dev
  githubConfigUrl: https://myorg
  maxRunners: 5
  minRunners: 1
  template:
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: runner
          image: https://github-action-runners:v1.0.0
          command: ["/home/runner/run.sh"]
```

### Controller Logs

```shell
ERROR	Reconciler error	{"controller": "ephemeralrunner", "controllerGroup": "actions.github.com", "controllerKind": "EphemeralRunner", "EphemeralRunner": {"name":"github-actions-scaleset-dev-2cp4r-runner-dr8jp","namespace":"github-actions-scaleset-dev"}, "namespace": "github-actions-scaleset-dev", "name": "github-actions-scaleset-dev-2cp4r-runner-dr8jp", "reconcileID": "1f6c9e65-664f-472e-a444-aab02067ee90", "error": "failed to get actions client for runner: failed to get secret: secrets \"github-actions-scaleset-dev\" not found"}
```

### Runner Pod Logs

```shell
message: >-
    Failed to create the pod: pods "actions-runner-scaleset-dev-t4w4z-runner-4xl7t"
    is forbidden: error looking up service account
    actions-runner-scaleset-dev/actions-runner-controller-gha-rs-controller:
    serviceaccount "actions-runner-controller-gha-rs-controller" not found
```
