### ISSUE TITLE
Installing gha-runner-scale-set-controller produces needless warning

### ISSUE THREAD

**Issue by Time0o** [actions/actions-runner-controller#3936]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.10.1

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
$ k3s --version
k3s version v1.31.5+k3s1 (56ec5dd4)
go version go1.22.10
$ helm version
version.BuildInfo{Version:"v3.17.1", GitCommit:"980d8ac1939e39138101364400756af2bdee1da5", GitTreeState:"clean", GoVersion:"go1.23.5"}
$ helm install arc --kubeconfig /etc/rancher/k3s/k3s.yaml --namespace "arc" --create-namespace oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
```

### Describe the bug

`helm install` produces the following warning:

```
WARNING: Older version of the listener (githubrunnerscalesetlistener) is deprecated and will be removed in the future gha-runner-scale-set-0.10.0 release. If you are using environment variable override to force the old listener, please remove the environment variable and use the new listener (ghalistener) instead.
```

This should be a bug since no such environment variable is and the new listener is installed. This should be trivial to check for instead of outputting this unconditionally.

### Describe the expected behavior

No warning is displayed.

### Additional Context

```yaml
$ cat /etc/rancher/k3s/k3s.yaml 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: ...
    client-key-data: ...
```

### Controller Logs

```shell
https://gist.github.com/Time0o/275331c0c5628903235b86bad7553e9f
```

### Runner Pod Logs

```shell
Not applicable
```
