### ISSUE TITLE
Runner Template does not support pod resources (k8s 1.32+)

### ISSUE THREAD

**Issue by AngellusMortis** [actions/actions-runner-controller#3943]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.10.1

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Add values for `template.spec.resources` in the gha-runner-scale-set Helm chart values
```

### Describe the bug

Kubernetes 1.32 adds the ability to set [resource limits on the pod level](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#pod-level-resource-specification), the [CRD definition for AutoscalingRunnerSet](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/crds/actions.github.com_autoscalingrunnersets.yaml) does not allow this. Doing so results in 

```
failed to create typed patch object (arc-runners/cicd-pipelines-dev; actions.github.com/v1alpha1, Kind=AutoscalingRunnerSet): .spec.template.spec.resources: field not declared in schema
```

### Describe the expected behavior

`AutoscalingRunnerSet` should support pod level resource limits

### Additional Context

```yaml
template:
  spec:
    resources:
      requests:
        cpu: "2000m"
        memory: "1000Mi"
      limits:
        cpu: "2000m"
        memory: "8000Mi"
```

### Controller Logs

```shell
failed to create typed patch object (arc-runners/cicd-pipelines-dev; actions.github.com/v1alpha1, Kind=AutoscalingRunnerSet): .spec.template.spec.resources: field not declared in schema
```

### Runner Pod Logs

```shell
failed to create typed patch object (arc-runners/cicd-pipelines-dev; actions.github.com/v1alpha1, Kind=AutoscalingRunnerSet): .spec.template.spec.resources: field not declared in schema
```

**Comment by FearlessHyena** [comment]
Just wanted to check if this has been released and if anyone has gotten this to work?

I'm using the latest v0.11.0 and tried setting the requests for CPU/Memory explicitly but it doesn't seem to be working and GKE still reports the CPU/Memory requested as `0`  

```yaml
template:
  spec:
    resources:
      requests:
        cpu: "700m"
        memory: "2.3G"
```

(I'm using k8s 1.32 btw)

**Comment by FearlessHyena** [comment]
@nikola-jokic 
I've tested this multiple times but this doesn't seem to work. Can we reopen this or can someone else verify how to get this 
 to work?

**Comment by AngellusMortis** [comment]
Yeah, it seems like the values file is accepting the `resources` on the spec object, but it is not being passed onto the actual pods.

```yml
        template:
          spec:
            resources:
              requests:
                cpu: "1000m"
                memory: "1000Mi"
              limits:
                cpu: "2000m"
                memory: "8000Mi"
```

```bash
$ kubectl -n arc-runners get pod cicd-pipelines-x2bqb-runner-48pn2 -o yaml | yq .spec.resources
null
```

**Comment by FearlessHyena** [comment]
Thanks for checking! I'm seeing the same behavior so we need to reopen this issue

**Comment by AngellusMortis** [comment]
Made https://github.com/actions/actions-runner-controller/issues/4034 since this ticket has not been reopened yet.

**Comment by mcdermg** [comment]
@nikola-jokic could we get this re-openend as https://github.com/actions/actions-runner-controller/pull/3949 does not seem to have resolved the issue and resources for the runner scale sets are not processed and it leads to pods never actually coming up and into serice in a scale set that is passing in resources via `values.yaml` in the container spec

**Comment by mcdermg** [comment]
As an example 

values.yaml  for arc-runner-set-02

```
githubConfigSecret: arc-secret

githubConfigUrl: "https://github.com/insidepetroleum/main-combocurve"

runnerScaleSetName: "arc-runner-set-02"

minRunners: 0
maxRunners: 30

template:
  spec:
    nodeSelector:
      nodepool-type: arc-runner-nodepool-02
      deployment-type: deploy
    topologySpreadConstraints:
      - maxSkew: 4
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: arc-runner-set-02
    containers:
    - name: runner
      resources:
        requests:
          cpu: "1"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "7Gi"
```

CRD Autoscalingrunnersets for the runner pool showing the resources
```
Name:         arc-runner-set-02
Namespace:    gha-arc-runners
Labels:       actions.github.com/organization=insidepetroleum
              actions.github.com/repository=main-combocurve
              actions.github.com/scale-set-name=arc-runner-set-02
              actions.github.com/scale-set-namespace=gha-arc-runners
              app.kubernetes.io/component=autoscaling-runner-set
              app.kubernetes.io/instance=arc-runner-set-02
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=arc-runner-set-02
              app.kubernetes.io/part-of=gha-rs
              app.kubernetes.io/version=0.10.1
              helm.sh/chart=gha-rs-0.10.1
Annotations:  actions.github.com/cleanup-manager-role-binding: arc-runner-set-02-gha-rs-manager
              actions.github.com/cleanup-manager-role-name: arc-runner-set-02-gha-rs-manager
              actions.github.com/cleanup-no-permission-service-account-name: arc-runner-set-02-gha-rs-no-permission
              actions.github.com/runner-group-name: Default
              actions.github.com/runner-scale-set-name: arc-runner-set-02
              actions.github.com/values-hash: 677b0af7181e9bc6815704c747f9c6e81480489d4bde37abcaf4f559e6c0fc0
              meta.helm.sh/release-name: gha-arc-runner-set-02
              meta.helm.sh/release-namespace: gha-arc-runners
              runner-scale-set-id: 6
API Version:  actions.github.com/v1alpha1
Kind:         AutoscalingRunnerSet
Metadata:
  Creation Timestamp:  2025-03-18T02:52:01Z
  Finalizers:
    autoscalingrunnerset.actions.github.com/finalizer
  Generation:        25
  Resource Version:  735002233
  UID:               c9bc5761-5d84-445b-a113-ea05664f4632
Spec:
  Github Config Secret:   arc-secret
  Github Config URL:      https://github.com/insidepetroleum/main-combocurve
  Max Runners:            40
  Min Runners:            0
  Runner Scale Set Name:  arc-runner-set-02
  Template:
    Spec:
      Containers:
        Name:  runner
        Resources:
          Limits:
            Cpu:     2
            Memory:  7Gi
          Requests:
            Cpu:     1
            Memory:  4Gi
      Node Selector:
        Deployment - Type:   deploy
        Nodepool - Type:     arc-runner-nodepool-02
      Restart Policy:        Never
      Service Account Name:  arc-runner-set-02-gha-rs-no-permission
      Topology Spread Constraints:
        Label Selector:
          Match Labels:
            app.kubernetes.io/name:  arc-runner-set-02
        Max Skew:                    4
        Topology Key:                kubernetes.io/hostname
        When Unsatisfiable:          ScheduleAnyway
Status:
  Current Runners:            13
  Failed Ephemeral Runners:   10
  Pending Ephemeral Runners:  3
  Running Ephemeral Runners:  0
Events:                       <none>
```

However pods do not come into service when the resources are in place, there is no issue with pods running when the resources are omitted

![Image](https://github.com/user-attachments/assets/37065e81-ef0c-49db-9f31-3c08319d8386)


Runners appear to stay in a pending state as per arc-runner-set-02  below
```
NAME                MINIMUM RUNNERS   MAXIMUM RUNNERS   CURRENT RUNNERS   STATE   PENDING RUNNERS   RUNNING RUNNERS   FINISHED RUNNERS   DELETING RUNNERS
arc-runner-set-01   0                 30                0                         0                 0                                    
arc-runner-set-02   0                 40                13                        3                 0                                    
```


The behavior is a little strange as  the Autoscalingrunnersets status block is showing changing values for current runners, failed runners etc but no pods in the namespace. 

```
Status:
  Current Runners:            35
  Failed Ephemeral Runners:   30
  Pending Ephemeral Runners:  5
  Running Ephemeral Runners:  0
Events:                       <none>
❯ k get po -n gha-arc-runners
No resources found in gha-arc-runners namespace.
```
So seems that pods just will not schedule when the resources are passed in via the values yaml with in the container pod spec, once that is removed the pods work run again as normal.  For instance the job in the screenshot above was immediately picked once did a redeploy of scale runner set via helm without and resource definition in values yaml.

The larger issue that I am facing as a result of the above is that without resources specified the cluster autoscaler is not scaling GKE node pool/s properly and we are getting runners clumping on single nodes and encountering bottleneck issues & workflow failures as a result of CPU & memeory pressure.

**Comment by AngellusMortis** [comment]
Whatever your issue is, it is not related to this one. You are defining resources on the _container_ level, not the pod level. This is specifically about resources on a _pod_ level.

```yaml
template:
  spec:
    nodeSelector:
      nodepool-type: arc-runner-nodepool-02
      deployment-type: deploy
    topologySpreadConstraints:
      - maxSkew: 4
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: arc-runner-set-02
    containers:
    - name: runner
      resources:  # resources on the container
        requests:
          cpu: "1"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "7Gi"
```

Pod level resources instead would be: 

```yaml
template:
  spec:
    nodeSelector:
      nodepool-type: arc-runner-nodepool-02
      deployment-type: deploy
    topologySpreadConstraints:
      - maxSkew: 4
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: arc-runner-set-02
    resources:  # resources on the pod
      requests:
        cpu: "1"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "7Gi"
    containers:
    - name: runner
```
