### ISSUE TITLE
Sometimes, a job need to wait 30/60 minutes before getting a runner

### ISSUE THREAD

**Issue by julien-michaud** [actions/actions-runner-controller#3953]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.10.1

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Start workflows
2. The first two jobs will get a runner very quickly
3. The third one will sometimes stay pending for 30/40 minutes before getting a runner
```

### Describe the bug

Let's say that I have a workflow with 3 jobs running in parallel. 

Sometimes, the jobs 1 and 2 will get a runner right away but the third one will have to wait 30 minutes to an hour before getting a runner. 

### Describe the expected behavior

All the jobs should start right away. 

Note that I have two runner-scale-sets with the same `runnerScaleSetName` name, I don't know if its a bad practice or not but its working fine 🤷‍♂ 

I did that to ease teh upgrade process when a new chart is available, I update the gha-runner-scale-sets one by one to avoid service interruptions.

Thanks 

### Additional Context

```yaml
gha-runner-scale-set-controller:
  enabled: true
  flags:
    logLevel: "warn"
  podLabels:
    finops.company.net/cloud_provider: gcp
    finops.company.net/cost_center: compute
    finops.company.net/product: tools
    finops.company.net/service: actions-runner-controller
    finops.company.net/region: europe-west1
  replicaCount: 3
  podAnnotations:
    ad.datadoghq.com/manager.checks: |
      {
        "openmetrics": {
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8080/metrics",
              "histogram_buckets_as_distributions": true,
              "namespace": "actions-runner-system",
              "metrics": [".*"]
            }
          ]
        }
      }
  metrics:
    controllerManagerAddr: ":8080"
    listenerAddr: ":8080"
    listenerEndpoint: "/metrics"

gha-runner-scale-set:
  enabled: true
  githubConfigUrl: https://github.com/company
  githubConfigSecret:
    github_token: <path:secret/github_token/actions_runner_controller#token>

  maxRunners: 100
  minRunners: 1

  containerMode:
    type: "dind"  ## type can be set to dind or kubernetes

  listenerTemplate:
    metadata:
      labels:
        finops.company.net/cloud_provider: gcp
        finops.company.net/cost_center: compute
        finops.company.net/product: tools
        finops.company.net/service: actions-runner-controller
        finops.company.net/region: europe-west1
      annotations:
        ad.datadoghq.com/listener.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:8080/metrics",
                  "histogram_buckets_as_distributions": true,
                  "namespace": "actions-runner-system",
                  "max_returned_metrics": 6000,
                  "metrics": [".*"],
                  "exclude_metrics": [
                    "gha_job_startup_duration_seconds",
                    "gha_job_execution_duration_seconds"
                  ],
                  "exclude_labels": [
                    "enterprise",
                    "event_name",
                    "job_name",
                    "job_result",
                    "job_workflow_ref",
                    "organization",
                    "repository",
                    "runner_name"
                  ]
                }
              ]
            }
          }
    spec:
      containers:
      - name: listener
        securityContext:
          runAsUser: 1000
  template:
    metadata:
      labels:
        finops.company.net/cloud_provider: gcp
        finops.company.net/cost_center: compute
        finops.company.net/product: tools
        finops.company.net/service: actions-runner-controller
        finops.company.net/region: europe-west1
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: company-prod-registry
      containers:
        - name: runner
          image: eu.gcr.io/company-production/devex/gha-runners:v1.0.0-snapshot5
          command: ["/home/runner/run.sh"]

  controllerServiceAccount:
    namespace: actions-runner-system
    name: actions-runner-controller-gha-rs-controller
```

### Controller Logs

```shell
https://gist.github.com/julien-michaud/dce55b9320fb236b622cbb00919277ce
```

### Runner Pod Logs

```shell
/
```

**Comment by avadhanij** [comment]
We are seeing the same issue and we have a similar setup. We are unsure if the two runnerscalesets (for upgrade ease) is actually causing problems.

**Comment by emmahsax** [comment]
We are on 0.8.2, and seem to be encountering a similar issue. We recently upgraded Karpenter to 1.3.3, and that's when we began seeing this issue. But it may have been existing before that.

**Comment by marcusisnard** [comment]
I’m observing similar behavior, even when not running in a high availability setup (single cluster on Azure). Unfortunately, the logs offer no insight, and the latency is unpredictable.

**Comment by marcusisnard** [comment]
Our organization is experiencing job queue delays exceeding 12 hours, severely impacting production workloads. No error logs are observed on our side. What steps can we take to troubleshoot this issue? @nikola-jokic

**Comment by nikola-jokic** [comment]
Hey everyone,

Could you please submit these logs without obfuscation through the support? We cannot investigate it without understanding which workflow runs are stuck. If you have failed runners, they count as the number of runners, so we can avoid creating an indefinite number of runners if something goes wrong with the cluster.
But if the delay is caused on the back-end side, please submit the workflow run that is stuck, and the unobfuscated log, so we can troubleshoot it. Thanks!

**Comment by nikola-jokic** [comment]
Hey everyone,

We found the root cause of the issue, and it should be fixed now. Please let us know if you are still experiencing this issue. I will leave this issue open for now for visibility. Thank you all for reporting it!

**Comment by marcusisnard** [comment]
> Hey everyone,
> 
> We found the root cause of the issue, and it should be fixed now. Please let us know if you are still experiencing this issue. I will leave this issue open for now for visibility. Thank you all for reporting it!

Do we need to uninstall and re-deploy ARC?

**Comment by nikola-jokic** [comment]
No, the issue was on the back-end side, so it should start working properly without touching the ARC installation.

**Comment by marcusisnard** [comment]
<img width="470" alt="Image" src="https://github.com/user-attachments/assets/ca8f35f4-80a2-4b0a-96d8-ec4d3f265349" />
<img width="1170" alt="Image" src="https://github.com/user-attachments/assets/0697e8f9-35c1-4e62-aa63-5a5a0161d95f" />

We are still seeing this issue, lots of jobs still pending, we do not have a cap on the maximum number of runners. Please let me know how I can send the appropriate logs and helm chart values used for our deployment.

**Comment by nikola-jokic** [comment]
Do you have failed ephemeral runners? If you don't have failed ones, please send the listener log, the controller log and workflow URLs of the pending jobs. You can submit them in the support issue if you don't want to share them publicly. 
If you do have failed runners, please remove all failed ephemeral runner instances, which would free up the slots to scale up.

**Comment by niodice** [comment]
@marcusisnard unfortunately I offer no help, but I wanted to ask how you view that particular UI. It looks like a GitHub view showing the scale sets directly in the UI. I have no such view, but it would be nice to see it.

**Comment by nikola-jokic** [comment]
Hey @niodice, the UI doesn't show that. The failed runners are scoped to the cluster, and is a mechanism we use to guard against the bad state. So you would have to inspect these runners inside the cluster, and not in the UI (if I understood you correctly)

**Comment by niodice** [comment]
@nikola-jokic we just saw this again. Where can I open a support case to share logs in a private venue?

**Comment by nikola-jokic** [comment]
Hey @niodice,

Very sorry, I'm responding slowly. Can you please reach out to our support? Please share the workflow run, controller and the listener log.

**Comment by niodice** [comment]
Thanks @nikola-jokic , submitted under https://support.github.com/ticket/personal/0/3381328

**Comment by hlascelles** [comment]
We are still seeing this. Self-hosted k8s ARC. Runner version 2.323.0. 

Everything runs fine, until we see the number of "Failed ephemeral runners" in the `AutoscalingRunnerSet` climb to match the total number of allowed runners. Then everything stops. No runners are in the web console. All Listeners stop at `"listener-app.listener","message":"Getting next message","lastMessageID":0`

![Image](https://github.com/user-attachments/assets/9fc2803a-a900-47da-a679-67df5898fc63)

We are automating a cron that checks the number of  "Failed ephemeral runners" and if it goes up we delete and recreate the `AutoscalingRunnerSet`. It appears to reregister, runners appear in the web console, and builds all start again.

**Comment by nikola-jokic** [comment]
Just a small hint @hlascelles, you can delete these ephemeral runner resources, and the ephemeral runner set will re-create them with the fresh config. Might be easier to manage than updating the autoscaling runner set

**Comment by uladzislauhramovich** [comment]
@nikola-jokic  how does one do that? Just reinstall the chart?

**Comment by uladzislauhramovich** [comment]
@nikola-jokic how does one do that? Just reinstall the chart? Because there are no failed pods or related errors visible.

**Comment by forgondolin** [comment]
That's also happening in our cluster, periodically I have to delete the ephemeralrunerset, also it's not scaling as it should.
@hlascelles your cron is restarting only the runnerset or also the controller?

**Comment by hlascelles** [comment]
@nikola-jokic  Same question as @uladzislauhramovich ... How do you delete the ephemeral runners? Are they k8s resources? There is nothing in the GitHub web console, no runners there.

@forgondolin We are deleting the `autoscalingrunnersets` (which are then autorecreated by flux).

**Comment by forgondolin** [comment]
Idk if it helps but:
kubectl delete ephemeralrunnersets -n namespace --all or runnerscaleset for checking the runner admin

**Comment by OneideLuizSchneider** [comment]
For us, I had to reinstall it to make it work, I had to do this a couple of times lately!

**Comment by Tombar** [comment]
We are running into the exact same issue as described in this issue.


One thing we notice is that, while github UI reports the correct number of active runners, the ephemeralrunnerset k8s resource doesn't

We are running the lastest version of the chart, crds and docker agent

**Comment by forgondolin** [comment]
@hlascelles suggestion current works for us, is not the ideal, but the cronjob made it better, still not ideal but I'm experimenting with different timesets

**Comment by OneideLuizSchneider** [comment]
Since I upgraded it to `0.11.0`, I'm not facing this issue anymore!

**Comment by forgondolin** [comment]
@OneideLuizSchneider I've tried 0.11.0 but it keeps spinning and killing the autoscaller like crazy in a loop, any tips on that?
ty!

**Comment by OneideLuizSchneider** [comment]
> [@OneideLuizSchneider](https://github.com/OneideLuizSchneider) I've tried 0.11.0 but it keeps spinning and killing the autoscaller like crazy in a loop, any tips on that? ty!

@forgondolin 
Well, I did upgrade the k8s autoscaler as well, and another point, we have many runners, for example(dev, staging, prod, etc), not sure if it has something to do with it, maybe create some runners for testing, like `testing-build` and see if it still happens, it seems that if you use one a lot it starts to happen(again, not sure).

**Comment by forgondolin** [comment]
@OneideLuizSchneider gonna give that a try in the next sprint. Thanks a lot

**Comment by uladzislauhramovich** [comment]
> Well, I did upgrade the k8s autoscaler as well, and another point, we have many runners, for example(dev, staging, prod, etc), not sure if it has something to do with it, maybe create some runners for testing, like `testing-build` and see if it still happens, it seems that if you use one a lot it starts to happen(again, not sure).

Same, it only happens with the most used label of our runners. The others are fine.

**Comment by mmack** [comment]
We face the same problem. Version: 0.11.0

**Comment by uladzislauhramovich** [comment]
Ok, I'm not sure how I missed that initially but you can find your failed runners by running `kubectl get ephemeralrunners -A` and then delete them. Not sure yet if this helps with scheduling times the same way redeployment does.

@hlascelles

**Comment by patrickvinograd** [comment]
So it's not inherently a bug that there are ephemeralrunner resources in failed state - I see the value of persisting those for diagnosis purposes - since the pod goes away, having a handle to a persistent resource to track down an error is useful.

And, as several people have landed on in this and other issues, one could write a cron job to periodically clean up failed ephemeralrunners. But, why are we having to do that vs. the system self-healing? 

It seems like there is potentially a bug in the autoscaling logic in either the listener or in the ephemeralrunnerset controller, i.e. that it is not discounting failed ephemeralrunners when it makes its scaling decision. this morning I had an instance of a job waiting for a runner, and the listener was logging `Calculated target runner count ... "decision": 1 ... "currentRunnerCount": 1 ...` but that 1 existing runner was `Failed`, i.e. never going to execute a job.

I haven't dug into the listener code to confirm, but it seems like the listener should not count failed runners. There's a tradeoff that in the long term failed listeners might pile up, and might even do so quickly if there's a non-sporadic failure mode. So maybe a configurable "max failed runners" threshold would be in order?

**Comment by schmidlidev** [comment]
In our case, setting `minRunners: 1` resolved the issue. (Previously we had the default of 0)

Adding some additional context to maybe help debugging the core issue: In our setup, we have several runner groups that each use different machine types, to more efficiently support light/medium/heavy workflows. We noticed this issue would only regularly occur on just one of our runner groups, the one for the smallest workloads, running on n1-standard-1 machines in GKE. As these runners are only used for very light workflows, their average job duration is under 11 seconds, the P95 is under 9 seconds.

Is it possible that very short job durations are tripping up the autoscaler's count of active/available runners?

**Comment by adamcharnock** [comment]
We're seeing either this issue, or an issue similar to it. From the logs it seems the following happens:

**1. An ephemeral runner is spun up**

```
EphemeralRunner	Created ephemeral runner pod	
EphemeralRunner	Waiting for runner container status to be available (x3)
EphemeralRunner	Ephemeral runner container is still running
```

**2. The job runs**

**3. The runner fails to de-register itself from GitHub**

It seems the pod gets killed during de-registration maybe (although `terminationGracePeriodSeconds=30`)?

```
[RUNNER 2025-06-04 14:38:19Z WARN GitHubActionsService] GET request to https://broker.actions.githubusercontent.com/message?sessionId=ccfba96a-xxxx-xxxx-xxxx-f848ce3aec47&status=Busy&runnerVersion=2.325.0&os=Linux&architecture=X64&disableUpdate=true has been cancelled.
[RUNNER 2025-06-04 14:38:19Z ERR  BrokerServer] Catch exception during request
[RUNNER 2025-06-04 14:38:19Z ERR  BrokerServer] System.Threading.Tasks.TaskCanceledException: The operation was canceled.

... snip a whole lot of system stack tracing ...

at GitHub.Runner.Common.RunnerService.RetryRequest[T](Func`1 func, CancellationToken cancellationToken, Int32 maxRetryAttemptsCount, Func`2 shouldRetry)
at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
```

**4. The controller fails the job**

The controller fails the job because it can see the runner still exists in GitHub:

```
EphemeralRunner	Runner exists in GitHub service	{"version": "canary-cae7efa", "ephemeralrunner": {"name":"lithus-container-runner-fzpjf-runner-6mt6n","namespace":"arc-runners"}, "runnerId": 25702}
EphemeralRunner	Ephemeral runner pod has finished, but the runner still exists in the service. Deleting the pod to restart it.	{"version": "canary-cae7efa", "ephemeralrunner": {"name":"lithus-container-runner-fzpjf-runner-6mt6n","namespace":"arc-runners"}}
EphemeralRunner	Deleting the ephemeral runner pod	{"version": "canary-cae7efa", "ephemeralrunner": {"name":"lithus-container-runner-fzpjf-runner-6mt6n","namespace":"arc-runners"}, "podId": "fb4cb454-fa6c-4dc9-b71e-9e0fc2f55da0"}
EphemeralRunner	Updating ephemeral runner status to track the failure count	{"version": "canary-cae7efa", "ephemeralrunner": {"name":"lithus-container-runner-fzpjf-runner-6mt6n","namespace":"arc-runners"}}
```

The result is that the EphemeralRunner gets stuck in a failed state

---

Note we are running a fairly new version, `canary-cae7efa`

Also of note is that we run a [custom build of kubevirt-actions-runner](https://github.com/golithus/kubevirt-actions-runner/), and the VM-based runners also seem to suffer from the same series of events, resulting in a failed EphemeralRunner state.

**Comment by OneideLuizSchneider** [comment]
Today it is happening again, I had to reinstall one runner again, to make it work.

So, are you (GitHub guys) doing anything or testing to fix it?? 
This is getting so annoying....

The `currentRunnerCount` increases, but nothing happens. Even on GitHub nothing changes, it stays waiting...
Version:  `0.11.0`
Some Logs: 
```
2025-06-05T10:48:39Z	INFO	listener-app.worker.kubernetesworker	Calculated target runner count	{"assigned job": 0, "decision": 1, "min": 0, "max": 30, "currentRunnerCount": 1, "jobsCompleted": 0}
2025-06-05T10:48:39Z	INFO	listener-app.worker.kubernetesworker	Compare	{"original": "{\"metadata\":{\"creationTimestamp\":null},\"spec\":{\"replicas\":-1,\"patchID\":-1,\"ephemeralRunnerSpec\":{\"metadata\":{\"creationTimestamp\":null},\"spec\":{\"containers\":null}}},\"status\":{\"currentReplicas\":0,\"pendingEphemeralRunners\":0,\"runningEphemeralRunners\":0,\"failedEphemeralRunners\":0}}", "patch": "{\"metadata\":{\"creationTimestamp\":null},\"spec\":{\"replicas\":1,\"patchID\":1977,\"ephemeralRunnerSpec\":{\"metadata\":{\"creationTimestamp\":null},\"spec\":{\"containers\":null}}},\"status\":{\"currentReplicas\":0,\"pendingEphemeralRunners\":0,\"runningEphemeralRunners\":0,\"failedEphemeralRunners\":0}}"}
2025-06-05T10:48:39Z	INFO	listener-app.worker.kubernetesworker	Preparing EphemeralRunnerSet update	{"json": "{\"spec\":{\"patchID\":1977,\"replicas\":1}}"}
2025-06-05T10:48:39Z	INFO	listener-app.worker.kubernetesworker	Ephemeral runner set scaled.	{"namespace": "arc-runners", "name": "hiddenrunnername-p94n8", "replicas": 1}
2025-06-05T10:48:39Z	INFO	listener-app.listener	Getting next message	{"lastMessageID": 100006518}
```

**Comment by nikola-jokic** [comment]
Hey @adamcharnock,

Do you know the reason why runners are being cancelled? In the next 0.12.0 release, we removed the failed state by implementing backoffs, but that will only treat the symptom, not the issue of them being killed. Please keep us updated if you find anything on that end.

@OneideLuizSchneider is your runner in the failed state, or is it just the listener not picking up the message?

**Comment by adam-lithus** [comment]
I can confirm that @schmidlidev's suggestion of `minRunners: 1` has helped. No more stuck runners, but less ideal as we don't have runners waiting around to pickup new jobs.

@nikola-jokic I'm actually not sure they are being 'cancelled' as such. I don't really know what normal shutdown procedure looks like. From my point of view either of these could be true:

1. The runners get killed/deleted because they successfully finish. But they cannot de-register themselves for some reason
2. The runners get killed because the controller things they need to be cancelled. And again they cannot de-register themselves for some reason

I haven't quite been able to squeeze enough understanding of ARC + log-data into my brain at the same time to figure out exactly what is happening. I didn't get any more time today, but I'll try tomorrow if I can.

**Comment by niodice** [comment]
`minRunners: 1` would probably work, but in our case, we are able to spin our infra down when there are no runners across the org -- which is a considerable cost savings!

**Comment by OneideLuizSchneider** [comment]
> Hey [@adamcharnock](https://github.com/adamcharnock),
> 
> Do you know the reason why runners are being cancelled? In the next 0.12.0 release, we removed the failed state by implementing backoffs, but that will only treat the symptom, not the issue of them being killed. Please keep us updated if you find anything on that end.
> 
> [@OneideLuizSchneider](https://github.com/OneideLuizSchneider) is your runner in the failed state, or is it just the listener not picking up the message?

@nikola-jokic 
It stays forever in a waiting state, and the listener generates the logs on my message above, and that's it, nothing happens(I waited for like 15min and it didn't start), once I reinstall it, it works every time.

...and about that `minRunners: 1` suggested above, no way, we are downscaling to `0`, once there is no activity anymore, our Workers/Instances are big, it would be a waste of money doing this.

**Comment by nikola-jokic** [comment]
No one is suggesting that everyone uses `minRunners: 1`. It is not the intended solution. It has been said that it would be a temporary workaround. Please inspect the runner pod and post the runner log, the controller log, and the listener log so we can take actionable steps. Make sure to include as much context as you can. I'm failing to reproduce the issue.

When you say it stays in a waiting state forever, does that mean it has 0 pods while jobs are waiting in the queue? Did you list ephemeral runners? Each ephemeral runner can have 0 to 1 runner pods. 

Please understand that I need to get enough context so I can help.

**Comment by OneideLuizSchneider** [comment]
I didn't say you suggested it. I guess it is clear now.

logs?? The only ones we see are the ones I sent above, there is no POD yet, only these logs.

Step 1: The Action starts
Step 2: We get the logs on the Listener the logs I sent above
Step 3: that's it, 
              even if I cancel it and try again 3-4-5 times, the same behavior 

So, and seems to be an issue on your side, as many here have the same or close to the same issue, there should some weird metrics on your side, maybe broken pipe connections, etc

and its been months since this issue here started, for us it is like a month only... but it is getting annoying, because it is totally random, it starts when it starts..

**Comment by niodice** [comment]
@nikola-jokic I cannot speak for the exact issue that @OneideLuizSchneider is experiencing, but I've personally seen this nearly exclusively in cases where a job is scheduled, then quickly cancelled (due to a concurrency setting in the workflow itself) because a new job is queued.

I've reported the behavior here - https://github.com/actions/actions-runner-controller/issues/4091 - and also included a ton of logs in a support ticket here - https://support.github.com/ticket/personal/0/3381328. Hope this helps.

**Comment by OneideLuizSchneider** [comment]
@niodice 
Let us know here when you get a return or when you solve it
My first comment is a little more above here, and I fixed it by updating it, but this week, basically the same behavior again.

**Comment by zanehala-wk** [comment]
I'll throw my hat in the ring here as well. This issue has been impacting us a fair amount recently. We had very low numbers of failed runners (between 0-1 in a day, we run ~100k jobs a day fwiw), with a notable uptick starting around June 1st. We run a mixture of runners on both spot and on-demand instances, we essentially see no difference in rate of occurrence between them. 

We observe the following:
- The controller starts a new runner.
- The runner comes online and registers successfully.
- Nearly immediately after registration we get a `An error occurred: Runner not found` error from the runner.
- This repeats 4 more times until the controller kills the pod for good and updates the failure count.

A brief segment of runner logs,
```
timestamp: 2025-06-05T20:35:44.929756Z message: √ Connected to GitHub
timestamp: 2025-06-05T20:35:45.147263Z message: Current runner version: '2.324.0'
timestamp: 2025-06-05T20:35:45.147487Z message: 2025-06-05 20:35:45Z: Listening for Jobs
timestamp: 2025-06-05T20:35:46.913704Z message: An error occurred: Runner not found
timestamp: 2025-06-05T20:35:46.936999Z message: Runner listener exit with terminated error, stop the service, no retry needed.
timestamp: 2025-06-05T20:35:46.937177Z message: Exiting runner...
```

This becomes problematic for our runners that are low traffic because the failed runner count seems to prevent new runners from coming online and meeting demand. This causes jobs to wait a long time before they are able to get picked up by a runner. We run with `minRunners: 1` but that still does not totally mitigate this when the failed count is > 1. 

I submitted a GH support ticket for this as well if any GH employees happen to read this. Happy to supply more info to help debug this.

**Comment by adamcharnock** [comment]
It seems that `minRunners: 1` only helped for so long. The EphmeralRunners got stuck again last night. We could see that all the `EphermalRunners` had workflows assigned to them, but there were no running runner pods. We therefore deleted/restarted the listener & controller pods and that resolved the immediate issue.

For now we have implemented [the cron job workaround](https://github.com/actions/actions-runner-controller/issues/3649#issuecomment-2294372351). This simply periodically deletes the listener pods. We have also increased `minRunners` up from `1`.

---

I have a strong suspicion that @niodice is onto something here. This particular client sees a fair number of cancelled workflows.

**Comment by int128** [comment]
For our environment, the failed EphemeralRunners was appeared from 2025-05-09 to 2025-06-06. Now, I can see no failed EphemeralRunner.

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/98ef6985-330f-4292-97f5-a24b2cc5846f" />

Instead, the max age of queue jobs metric has been increased since around 2025-05-26. We calculate this metric from ListRepositoryWorkflowRuns API.

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/1bc7b285-119d-4515-b18b-e7dc4f0ce19a" />

I noticed that some EphemeralRunners are running but not assigned to any jobs. Here is a log:

```console
% kubectl get -n arc-runners ephemeralrunners.actions.github.com --no-headers | egrep 'Running +[0-9h]+m$' 
example-7qjnc-runner-4vqbm            https://github.com/example   12462048   Running                                                                                                                                     71m
example-7qjnc-runner-ftgvt            https://github.com/example   12461690   Running                                                                                                                                     98m
example-7qjnc-runner-gfhht            https://github.com/example   12459397   Running                                                                                                                                     3h13m
example-7qjnc-runner-hqcdp            https://github.com/example   12458515   Running                                                                                                                                     3h33m
```

I checked the pod logs but could see only "listening" log.

```
√ Connected to GitHub

Current runner version: '2.325.0'
2025-06-12 00:45:54Z: Listening for Jobs
```

At this moment, we run a CronJob to clean up failed or stuck EphemeralRunners.

```sh
# Failed
kubectl get -n arc-runners ephemeralrunners.actions.github.com --no-headers |
  (grep Failed || true) |
  cut -f1 -d' ' |
  xargs -t --no-run-if-empty kubectl delete -n arc-runners ephemeralrunners.actions.github.com

# Stuck over 1m
kubectl get -n arc-runners ephemeralrunners.actions.github.com --no-headers |
  (egrep 'Running +[0-9h]+m$' || true) |
  cut -f1 -d' ' |
  xargs -t --no-run-if-empty kubectl delete -n arc-runners ephemeralrunners.actions.github.com
```

I think this issue affects the job queued time and pod running cost in our environment. I hope GitHub improves the stability of Actions.

**Comment by avadhanij** [comment]
Haha, the timing of your reply is too coincidental. We have also noticed a sudden spike in these "zombie" runners. We had already implemented a cronjob that would clean up these failed runners. I just enhanced that cronjob to also clean up these zombie runners.

These are the characteristics I chose 
1. In running state
2. Not assigned to any repo (status.jobRepositoryName is null)
3. Alive/in this state for more than 10 minutes.

**Comment by forgondolin** [comment]
FYI, We've updated to 0.11.0 and unfortunately didn't solve our problem, the cronjob seems to be the best solution so far for us. Actually, the 0.11.0 with the autoscaling solution kinda made it worse than having 0.10.0 with the cronjob running

**Comment by hlascelles** [comment]
We have been using a command line cron. Can someone post a canonical `CronJob` k8s resource that does the trick please?

**Comment by OneideLuizSchneider** [comment]
@hlascelles 
I built this one here, I just built my own kubectl image as well, its been  running for almost 2 weeks now..

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-gh-listeners
  namespace: tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-gh-listeners
rules:
  # Allow managing pods (list, get, delete)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-gh-listeners
subjects:
  - kind: ServiceAccount
    name: delete-gh-listeners
    namespace: tools
roleRef:
  kind: ClusterRole
  name: delete-gh-listeners
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-gh-listeners
  namespace: tools
spec:
  schedule: "0 7 * * *"        # Every day at 07:00 UTC  
  concurrencyPolicy: Forbid    # Prevents concurrent runs of the CronJob to avoid resource conflicts
  suspend: false               # Ensures the CronJob is active and not paused
  startingDeadlineSeconds: 60  # Maximum time in seconds to start the job if it misses its scheduled time
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:        
        spec:        
          serviceAccountName: delete-gh-listeners
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 2000
          containers:
          - name: delete-gh-listeners
            image: oneidels/kubectl:latest
            imagePullPolicy: Always
            command:
              - /bin/bash
              - -c
              - |
                echo "Deleting arc-systems listeners..."
                kubectl get pod -n arc-systems -l app.kubernetes.io/component=runner-scale-set-listener
                kubectl delete pod -n arc-systems -l app.kubernetes.io/component=runner-scale-set-listener
                kubectl get pod -n arc-systems -l app.kubernetes.io/component=runner-scale-set-listener
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000  
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
            resources:
              limits:
                memory: "128Mi"
                cpu: "100m"
              requests:
                memory: "64Mi"
                cpu: "50m"
          
```
Dockerhub: https://hub.docker.com/r/oneidels/kubectl
My Dockerfile: https://github.com/OneideLuizSchneider/k8s-manifests/blob/main/cronjobs/restart-gh-listeners/Dockerfile

**Comment by adam-lithus** [comment]
This is what we are using. Search and replace for `YOUR-NAMESPACE`, otherwise should be good to go. Using an off-the-shelf docker image:


```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-listener-restart-sa
  namespace: "YOUR-NAMESPACE"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: actions-listener-restart-role
  namespace: "YOUR-NAMESPACE"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: actions-listener-restart-rolebinding
  namespace: "YOUR-NAMESPACE"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: actions-listener-restart-role
subjects:
- kind: ServiceAccount
  name: actions-listener-restart-sa
  namespace: "YOUR-NAMESPACE"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: actions-listener-restart-cron
  namespace: "YOUR-NAMESPACE"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: actions-listener-restart-sa
          containers:
          - name: actions-listener-restart-pod
            image: bitnami/kubectl:1.33.1
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              runAsUser: 999
            command:
            - /bin/sh
            - -c
            - kubectl delete pod -n YOUR-NAMESPACE -l app.kubernetes.io/component=runner-scale-set-listener --wait=false
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-listener-restart-sa
  namespace: "YOUR-NAMESPACE"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: actions-listener-restart-role
  namespace: "YOUR-NAMESPACE"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: actions-listener-restart-rolebinding
  namespace: "YOUR-NAMESPACE"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: actions-listener-restart-role
subjects:
- kind: ServiceAccount
  name: actions-listener-restart-sa
  namespace: "YOUR-NAMESPACE"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: actions-listener-restart-cron
  namespace: "YOUR-NAMESPACE"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: actions-listener-restart-sa
          containers:
          - name: actions-listener-restart-pod
            image: bitnami/kubectl:1.33.1
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              runAsUser: 999
            command:
            - /bin/sh
            - -c
            - kubectl delete pod -n YOUR-NAMESPACE -l app.kubernetes.io/component=runner-scale-set-listener --wait=false
          restartPolicy: Never
```

**Comment by adamcharnock** [comment]
This is what we are using. Search and replace for `YOUR-NAMESPACE`, otherwise should be good to go. Using an off-the-shelf docker image:


```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-listener-restart-sa
  namespace: "YOUR-NAMESPACE"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: actions-listener-restart-role
  namespace: "YOUR-NAMESPACE"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: actions-listener-restart-rolebinding
  namespace: "YOUR-NAMESPACE"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: actions-listener-restart-role
subjects:
- kind: ServiceAccount
  name: actions-listener-restart-sa
  namespace: "YOUR-NAMESPACE"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: actions-listener-restart-cron
  namespace: "YOUR-NAMESPACE"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: actions-listener-restart-sa
          containers:
          - name: actions-listener-restart-pod
            image: bitnami/kubectl:1.33.1
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              runAsUser: 999
            command:
            - /bin/sh
            - -c
            - kubectl delete pod -n YOUR-NAMESPACE -l app.kubernetes.io/component=runner-scale-set-listener --wait=false
          restartPolicy: Never
```

(Apologies for the double post. I originally posted under a different GitHub account)
