### ISSUE TITLE
PVC From Snapshot

### ISSUE THREAD

**Issue by stobias123** [actions/actions-runner-controller#3966]
### What would you like added?

I'd love to be able to create a PVC on demand from a snapshot for each runner that I build. We have a significant amount of data we cache in PVCs (100s of GB) and I'd love to be able to create PVC for each runner based on a snapshot with this data.

PVC can be created like so

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
    dataSource:
      name: dagger-2025-02-20
      kind: VolumeSnapshot
      apiGroup: snapshot.storage.k8s.io
```

so I'd hope for some CRD interface like 
Note: Feature requests to integrate vendor specific cloud tools (e.g. `awscli`, `gcloud-sdk`, `azure-cli`) will likely be rejected as the Runner image aims to be vendor agnostic.
```
      volumes:
      - ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
                dataSource:
                  name: dagger-2025-02-20
                  kind: VolumeSnapshot
                  apiGroup: snapshot.storage.k8s.io
```

### Why is this needed?

Moving 100s of GB on every build is cumbersome and takes lots of time. just restoring from a snapshot would be great.
