### ISSUE TITLE
volumeMounts ignored on dind container spec

### ISSUE THREAD

**Issue by alismanis-lv** [actions/actions-runner-controller#3968]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.10.1

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Override helm values for dind container.

template:
  spec:
    containers:
      - name: dind
        volumeMounts:
          - name: s3-vol
            mountPath: /s3
    volumes:
      - name: s3-vol
        persistentVolumeClaim:
          claimName: s3-pvc
```

### Describe the bug

It appears that _helpers.tpl ignores override values for dind container but same is not ignored for runner. 

### Describe the expected behavior

I should be able to add extra volumes to dind container just like I can do the same for runner.

### Additional Context

```yaml
Override helm values for dind container.

template:
  spec:
    containers:
      - name: dind
        volumeMounts:
          - name: s3-vol
            mountPath: /s3
    volumes:
      - name: s3-vol
        persistentVolumeClaim:
          claimName: s3-pvc
```

### Controller Logs

```shell
.
```

### Runner Pod Logs

```shell
.
```
