### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "xxx" namespace: "xxx" from "": no matches for kind "AutoscalingRunnerSet" in version "actions.github.com/v1alpha1" ensure CRDs are installed first

### ISSUE THREAD

**Issue by esaporski** [actions/actions-runner-controller#3980]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.10.1

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Create `values.yml` file.
2. Run `helm upgrade --install` command the first time.
```

### Describe the bug

I'm getting this error when installing this Helm chart for the first time:
```
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "my-release-name" namespace: "my-namespace" from "": no matches for kind "AutoscalingRunnerSet" in version "actions.github.com/v1alpha1" ensure CRDs are installed first
```

It looks like the CRDs are not installed. I found this in the documentation but it never tells you how to install or manage the CRDs: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#about-custom-resources

>Because custom resources are extensions of the Kubernetes API, they won't be available in a default Kubernetes installation.
>You will need to install these custom resources to use ARC.
>For more information on installing custom resources, see [Quickstart for Actions Runner Controller](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller).

CRDs are only mentioned here in the  **Quickstart for Actions Runner Controller** documentation: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller#installing-actions-runner-controller
> 1. To install the operator and the custom resource definitions (CRDs) in your cluster, do the following.
>   a. In your Helm chart, update the NAMESPACE value to the location you want your operator pods to be created. This namespace must allow access to the Kubernetes API server.
>  b. Install the Helm chart.

---
Helm install command:
```
helm upgrade my-release-name \
    --install \
    --create-namespace \
    --namespace my-namespace \
    --values values.yml \
    --wait \
    --timeout 1h \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
```

### Describe the expected behavior

I should be able to run the same command from the docs and install the Helm chart.

### Additional Context

```yaml
## githubConfigUrl is the GitHub url for where you want to configure runners
## ex: https://github.com/myorg/myrepo or https://github.com/myorg
githubConfigUrl: "https://github.com/my-org"

## githubConfigSecret is the k8s secret information to use when authenticating via the GitHub API.
githubConfigSecret: github-app-secret

## maxRunners is the max number of runners the autoscaling runner set will scale up to.
maxRunners: 10

## minRunners is the min number of idle runners. The target number of runners created will be
## calculated as a sum of minRunners and the number of jobs assigned to the scale set.
minRunners: 1

runnerGroup: "self-hosted"

## name of the runner scale set to create.  Defaults to the helm release name
# runnerScaleSetName: ""

## template is the PodSpec for each runner Pod
## For reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]

# Fix: 
# Error: execution error at (gha-runner-scale-set/templates/manager_role_binding.yaml:17:11):
#   No gha-rs-controller deployment found using label (app.kubernetes.io/part-of=gha-rs-controller).
#   Consider setting controllerServiceAccount.name in values.yaml to be explicit if you think the discovery is wrong.
controllerServiceAccount:
  namespace: serverless
  # <.Release.name>-gha-runner-scale-set-controller
  name: my-release-name-gha-runner-scale-set-controller
```

### Controller Logs

```shell
There are no logs
```

### Runner Pod Logs

```shell
There are no logs
```
