### ISSUE TITLE
Unable to download composite actions

### ISSUE THREAD

**Issue by vvanouytsel** [actions/actions-runner-controller#4009]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.10.1

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Create a composite action
2. Implement that composite action in a workflow.

name: Dummy
on:
  workflow_dispatch:
jobs:
  validate:
    runs-on: my-runner
    steps:
      - uses: company/my-composite-action@main
```

### Describe the bug

I am using ARC in Kubernetes mode. When running a workflow that implements a composite action the runner attempts to download the tarball using the API. However, sometimes this seems to work and sometimes it does not.

In the case of failure the following error is returned during the `Set up jobs` step.
```bash
[WORKER 2025-04-01 12:04:33Z INFO ExecutionContext]     "'/home/runner/_work/_actions/_temp_224a2dae-8980-416e-8717-a82a0cbbabd9/617782da-a246-44e0-a927-544a114d8232.tar.gz' contains '0' directories"
```

### Describe the expected behavior

I would expect the composite action to be downloaded as a tarball via the GitHub API. What confuses me is that it sometimes works and sometimes it does not.

### Additional Context

```yaml
The values.yaml used for the runner scale set:


template:
  spec:
    serviceAccountName: my-serviceaccount
    containers:
    - name: runner
      image: company.example.com/arc-linux-runner:123
      command: ["/home/runner/run.sh"]
      resources:
        limits:
          ephemeral-storage: 20G
          memory: 10Gi
        requests:
          cpu: "1"
          ephemeral-storage: 5G
          memory: 10Gi
      env:
        - name: ACTIONS_RUNNER_CONTAINER_HOOKS
          value: /home/runner/k8s/index.js
        - name: ACTIONS_RUNNER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
    nodeSelector:
      kubernetes.io/arch: amd64
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "azureblob-fuse-standard"
              resources:
                requests:
                  storage: 1Gi

controllerServiceAccount:
  namespace: gha-runner-scale-set-controller
  name: gha-runner-scale-set-controller-gha-rs-controller
githubConfigUrl: REDACTED
githubConfigSecret:
  github_app_id: REDACTED
  github_app_installation_id: REDACTED
  github_app_private_key: REDACTED

minRunners: 1
maxRunners: 25
```

### Controller Logs

```shell
https://gist.github.com/vvanouytsel/55bed8f836b25a3c6df533994d050e40
```

### Runner Pod Logs

```shell
Runner pod logs:
https://gist.github.com/vvanouytsel/7e02c209b4560e14ae5f42d7435fbeeb

Output of the workflow:
https://gist.github.com/vvanouytsel/922d44f6f1b518416cbda74c70226cb8
```

**Comment by vvanouytsel** [comment]
After some more troubleshooting I think I can conclude that it is somehow related to using a StorageClass backed by `blob.csi.azure.com`.

When adding an init container that sleeps for 1 second, the issue never pops up.

```yaml
    initContainers:
    - name: init
      image: busybox
      command:
        - sleep
        - "1"
```

This leads me to believe it is somehow related to a race condition in the underlying storage that is provisioned by the `blob.csi.azure.com` CSI provider.

After changing to a different storage provider (disk.csi.azure.com) the issue was not reproducible anymore.
