### ISSUE TITLE
Runner Template does not support pod resources (k8s 1.32+)

### ISSUE THREAD

**Issue by AngellusMortis** [actions/actions-runner-controller#4034]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.11.0

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Add values for `template.spec.resources` in the gha-runner-scale-set Helm chart values
```

### Describe the bug

Reopen https://github.com/actions/actions-runner-controller/issues/3943 as it is not actually fixed.

0.11.0 now allows `resources` on the spec object, but it is not being passed onto the actual pods.

```yml
        template:
          spec:
            resources:
              requests:
                cpu: "1000m"
                memory: "1000Mi"
              limits:
                cpu: "2000m"
                memory: "8000Mi"
```

```bash
$ kubectl -n arc-runners get pod cicd-pipelines-x2bqb-runner-48pn2 -o yaml | yq .spec.resources
null
```

### Describe the expected behavior

The final runner pods should have a resource limit on the pods.

### Additional Context

```yaml
template:
          spec:
            resources:
              requests:
                cpu: "1000m"
                memory: "1000Mi"
              limits:
                cpu: "2000m"
                memory: "8000Mi"
```

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```

**Comment by nikola-jokic** [comment]
Hey @AngellusMortis,

It is supported, I think you just didn't enable the feature gate in order for it to be applied.

For example, I started the kind cluster with the following config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "PodLevelResources": true
```
Then I applied the spec with the following template:

```yaml
template:
  spec:
    resources:
      requests:
        cpu: "1000m"
        memory: "1000Mi"
      limits:
        cpu: "2000m"
        memory: "3000Mi"
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
```

Running the command you pasted (i.e. `kubectl get -n arc-runners pod [your_pod]`) showed proper resources applied.

Since the CRD contains the spec as well, I don't think this issue is related to ARC, you should just turn on the featureGate and you should have it.
