### ISSUE TITLE
Bumping version from 0.10.1 -> 0.11.0 gha-runner-scale-set chart failed

### ISSUE THREAD

**Issue by andycwk** [actions/actions-runner-controller#4045]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.10.0

### Deployment Method

Other

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Have a good install of 0.10.1 via Flux and then attempt to upgrade the scale set to 0.11.0
```

### Describe the bug

Flux reports the helm release fails with the following error..

Helm upgrade failed: template: gha-runner-scale-set/templates/no_permission_serviceaccount.yaml:1:63: executing "gha-runner-scale-set/templates/no_permission_servicea
ccount.yaml" at <.Values.resourceMeta.noPermissionServiceAccount>: nil pointer evaluating interface {}.noPermissionServiceAccount

### Describe the expected behavior

I expected the new version to install wtihout issue!

### Additional Context

```yaml
release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-tad-scale-set
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gha-runner-scale-set
      version: "0.11.0"
      sourceRef:
        kind: HelmRepository
        name: arc

  interval: 10m0s
  targetNamespace: arc-xx-apps-deploy-runners
  
  valuesFrom:
    - kind: ConfigMap
      name: xx-apps-deploy-scale-set-values


config map for values..
apiVersion: v1
kind: ConfigMap
metadata:
  name: xx-apps-deploy-scale-set-values
  namespace: flux-system

data:
  values.yaml: |
    githubConfigUrl: https://gh.xx.com/xx-Apps
    githubConfigSecret: arc-xx-apps-gh-app-secret

    namespace: arc-xx-apps-deploy-runners
    runnerScaleSetName: xx-apps-deploy-only-scale-set

    minRunners: 1

    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            command: ["/home/runner/run.sh"]
            securityContext:
              privileged: true
              capabilities:
                add:
                  - SYS_ADMIN
                  - DAC_OVERRIDE
            volumeMounts:
              - name: dev-fuse
                mountPath: /dev/fuse
              - name: fuse-config
                mountPath: /etc/fuse.conf
                readOnly: true
        volumes:
          - name: dev-fuse
            hostPath:
              path: /dev/fuse
              type: CharDevice
          - name: fuse-config
            hostPath:
              path: /etc/fuse.conf
              type: File
```

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```
