### ISSUE TITLE
Disk space is not released after the runner completes

### ISSUE THREAD

**Issue by XuehaoSun** [actions/actions-runner-controller#4056]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [ ] I am using charts that are officially provided

### Controller Version

0.11.0

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Run docker compose in dind mode
```

### Describe the bug

We use the `dind` mode, which allows us to run `docker compose` in CI
It is obvious that the outputs of the `df -h` and `sudo du -sh /*` are significantly different, `df -h` shows that 700GB of storage is being used, but `sudo du - sh /*` only has a total of around 200GB. I know this cannot be used as direct evidence, so I used four k8s nodes, two of which are running ARC, the result is that only the two nodes running ARC will encounter this issue. 
But after restarting the machine, the disk usage will return to normal
We also analyzed the data of `lsof | grep delete` and did not find anything.
- `df -h`
![Image](https://github.com/user-attachments/assets/70455de0-8aac-42e7-a417-57350db28b34)
- `sudo du -sh /*`
![Image](https://github.com/user-attachments/assets/a36442c9-fb21-429f-8aef-8426469a44ae)

### Describe the expected behavior

Disk resources can be restored normally

### Additional Context

```yaml
K8s Rev: v1.29.15

githubConfigUrl: ""
githubConfigSecret:
  github_token: ""
maxRunners: 16
minRunners: 1
containerMode:
  type: "dind"
template:
  spec:
    volumes:
      - name: model-path
        hostPath:
          path: /data2
    containers:
      - name: runner
        image: runner-name:latest
        command: ["/home/runner/run.sh"]
        volumeMounts:
          - name: model-path
            mountPath: /data2
        resources:
          requests:
            cpu: "40"
            memory: "200Gi"
          limits:
            cpu: "40"
            memory: "200Gi"
```

### Controller Logs

```shell
No exceptions or errors were found
```

### Runner Pod Logs

```shell
No exceptions or errors were found
```
