### ISSUE TITLE
workflow pod don't populate service account

### ISSUE THREAD

**Issue by naveenpg11** [actions/actions-runner-controller#4115]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.11.0

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Sharing my HELM Values
2. Apply the helm (adding privilate:True in security context)
3. Have a dummy job trigger using the runner
4. You will see a runner pod being created, then a workflow pod.
5. The newly created ServiceAccount is visible in the runner pod, but, not in the workflow pod, it has "default" service account, which is resulting in not able to write to a ecr in my case.
```

### Describe the bug

The workflow pod is not having the newly created ServiceAccount, but it had "default" - (unable to pull ecr ) - why workflow pod is having default serviceAccount, when thought it is created one, but not using it.

### Describe the expected behavior

I'd expect the workflow pod to have new serviceAccount( which had access to pull ecr image.)

### Additional Context

```yaml
gha-runner-scale-set:
  githubConfigUrl: "https://github.com/example-org"

  githubConfigSecret: github-arc-creds

  maxRunners: 5
  minRunners: 0

  runnerGroup: "example-group"

  containerMode:
    type: "kubernetes"
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi

  listenerTemplate:
    spec:
      nodeSelector:
        group: system
      containers:
      - name: listener

  template:
    spec:
      securityContext:
        fsGroup: 1000
        seLinuxOptions:
          level: "s0"
          role: "system_r"
          type: "super_t"
          user: "system_u"
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
        - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
          value: /podtemplates/build.yaml
        volumeMounts:
        - name: podtemplates
          mountPath: /podtemplates
      volumes:
      - name: podtemplates
        configMap:
          name: podtemplates

  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller

  resourceMeta:
    kubernetesModeServiceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::<your-account-id>:role/<your-service-role-name>

  namespaceOverride: ""
```

### Controller Logs

```shell
https://gist.github.com/naveenpg11/0edfab58e6311d04e13336740efa1e98
```

### Runner Pod Logs

```shell
https://gist.github.com/naveenpg11/d72908ff5012fa997e4534d7dc83e640
```
