### ISSUE TITLE
EphemeralRunners are stuck in failed state after the job succeeds

### ISSUE THREAD

**Issue by Dawnflash** [actions/actions-runner-controller#4136]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.12.0

### Deployment Method

ArgoCD

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Not consistently reproducible, there's a small chance for it to happen whenever a job succeeds.
Just run some workload, then check that no EphemeralRunners are stuck in a failed state.
```

### Describe the bug

After the workload succeeds the controller marks the EphemeralRunner as failed and it doesn't create a new pod, just hangs in a failed state until manually removed. There is always exactly 1 failure with a timestamp: `"status": { "failures": {"<uuid>": "<timestamp>"}}`.

It probably lingers in the Github API a bit longer after the pod dies and the controller treats it as a failure. It calls [deletePodAsFailed](https://github.com/actions/actions-runner-controller/blob/0b2534ebc906c8e14d0affbdccafb922e2a5c2db/controllers/actions.github.com/ephemeralrunner_controller.go#L316) which is what's visible in the log excerpt.

After that it goes into backoff but it is never processed again. After the backoff period elapses there are no further logs available referencing the EphemeralRunner and it remains stuck and unmanaged.

For now we are removing these orphans periodically but the orphans seem to negatively impact CI job startup times.

The runners are eventually removed from Github API because I manually checked them and they were no longer present in Github. Yet the EphemeralRunners remain stuck.

### Describe the expected behavior

The EphemeralRunner is cleanly removed once Github releases it. It should keep reconciling after the backoff period elapses instead of giving up on it silently.

### Additional Context

```yaml
Using a simple runnerset with DinD mode, cloud Github organization installation (via Github app).
```

### Controller Logs

```shell
https://gist.github.com/Dawnflash/0a3fc1da0f99dfe67fc17b6987821a53
```

### Runner Pod Logs

```shell
Don't have those but the jobs normally succeed. All green in Github.
```

**Comment by kaplan-shaked** [comment]
We are suffering from the same issue

**Comment by kyrylomiro** [comment]
@nikola-jokic I think this is something connected to the change from this pr https://github.com/actions/actions-runner-controller/pull/4059 ,w e are seeing the same, the pod is get deleted, but the `EphemeralRunner` object is keep in the state running like this 
```
Status:
  Failures:
    9b0c5e46-bf2c-41cc-90f2-6fcc4f57f599:  2025-06-19T11:29:42Z
  Job Repository Name:                     xxxxshared-workflows-github-actions
  Job Workflow Ref:                        xxxxx.yaml@refs/heads/main
  Phase:                                   Running
  Ready:                                   false
  Runner Id:                               15718317
```

**Comment by nikola-jokic** [comment]
Hey, this might not be related to the actual controller change. Looking at the log, we see that the ephemeral runner finishes, but it exists. That shouldn't happen. After the ephemeral runner is done executing the job, it should self-delete. Therefore, the issue might be on the back-end side. Can you please share the workflow run URL?

**Comment by nikola-jokic** [comment]
Hey, is anyone running ARC with a version older than 0.12.0 and experiencing this?

**Comment by kyrylomiro** [comment]
@nikola-jokic yes, I can share the workflow URL, but just before I want to show you how bad is the situation, this is all our runners right now. https://gist.github.com/kyrylomiro/64c559e7d3608fd459443f4a25328c12 so all of them that has errors, actually doesn't have pods, but the state keeps saying it's running, and actually our scheduling time now is reaching to n minutes. Workflow URL, trying to find it now.

**Comment by kyrylomiro** [comment]
@nikola-jokic this is the [url](https://github.com/miroapp-dev/server/actions/runs/15760961496/job/44427818581?pr=45380) and exact job the cause the runner to end up in  `m-runner-hvlmr-runner-4x2cs              Running   map[53171800-7476-4af6-8a7b-00f286b15671:2025-06-19T15:13:22Z]`

**Comment by kyrylomiro** [comment]
@nikola-jokic the [run](https://github.com/miroapp-dev/azure-cards-app/actions/runs/15760566564/job/44426901910)  is this one where github is showing that workflow is still running but runner is already gone

**Comment by nimjor** [comment]
I can corroborate this issue, was going to open it myself but didn't get a chance to yet.  The EphemeralRunners exist indefinitely with a `.status.phase: Running`.  I'll share the cronjob setup I added to buy me time to continue investigating without blocking our users' job startups:

<details><summary>zombie-runner-cleanup.yaml</summary>

(obviously change the namespace as needed for your env)

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zombie-runner-cleanup
  namespace: gha-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zombie-runner-cleanup
  namespace: gha-runners
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - actions.github.com
    resources:
      - ephemeralrunners
    verbs:
      - get
      - list
      - delete
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zombie-runner-cleanup
  namespace: gha-runners
subjects:
  - kind: ServiceAccount
    name: zombie-runner-cleanup
    namespace: gha-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zombie-runner-cleanup
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: zombie-runner-cleanup
  namespace: gha-runners
spec:
  schedule: "*/10 * * * *" # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: zombie-runner-cleanup
          containers:
            - name: zombie-runner-cleanup
              image: alpine:3
              command:
                - /bin/sh
                - -c
                - |
                  apk add kubectl yq
                  #!/bin/sh
                  set -e

                  echo ""
                  echo "Starting cleanup task..."

                  PODS_FILE="/tmp/pods.txt"
                  RUNNERS_FILE="/tmp/runners.txt"
                  DIFF_FILE="/tmp/runners_diff.txt"
                  NS="gha-runners"
                  SELECTOR="app.kubernetes.io/part-of=gha-runner-scale-set"

                  kubectl -n $NS get pods -l $SELECTOR -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' > $PODS_FILE
                  kubectl -n $NS get ephemeralrunners -o yaml | yq '.items[] | select(.status.phase == "Running") | .metadata.name' > $RUNNERS_FILE

                  ## Subtract Pods from running EphemeralRunners to find runners that no longer have a pod
                  comm -13 <(sort $PODS_FILE) <(sort $RUNNERS_FILE) > $DIFF_FILE

                  echo "Runner pods: $(wc -l $PODS_FILE | awk -F' ' '{print $1}')"
                  echo "Ephemeral runners: $(wc -l $RUNNERS_FILE | awk -F' ' '{print $1}')"
                  echo "Found $(wc -l $DIFF_FILE | awk -F' ' '{print $1}') ephemeral runners without pods"

                  for runner in $(cat $DIFF_FILE); do 
                      kubectl -n $NS delete ephemeralrunner $runner
                  done
                  rm $PODS_FILE $RUNNERS_FILE $DIFF_FILE

                  echo "Done."

          restartPolicy: OnFailure
```

</details>

This issue was not happening to our runners in 0.11.0.  And it is not intermittent, in the sense that the overall issue doesn't come and go by the day, it is always affecting some percentage of our runners, but it IS intermittent in the sense that it seems to happen randomly to our jobs, with no discernible difference.  It seems to affect roughly 2-20 jobs an hour for us.  If we don't clean them up, the controller seems to be counting those as part of the current scale metric so it doesn't think it needs more runners added to meet demand, thus the increasing length of job queue.
