### ISSUE TITLE
OutOfSync when deploying controller with ArgoCD: preserveUnknownFields diff on CRDs

### ISSUE THREAD

**Issue by LiatSchulz** [actions/actions-runner-controller#4137]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.12.0

### Deployment Method

ArgoCD

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Deploy the 2 ARC helm charts (v0.12.0) with ArgoCD (I'm doing so through Terraform)
2. Go to the controller appset in Argocd
3. ephemeralrunnersets, ephemeralrunners, autoscalingrunnersets, autoscalinglisteners are OutOfSync with the same diff showing: The desired manifest has `preserveUnknownFields: false` which the live manifest is missing.

from live manifest:

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  creationTimestamp: '2025-06-15T12:33:55Z'
  generation: 3
  managedFields:
    - apiVersion: apiextensions.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:controller-gen.kubebuilder.io/version: {}
        f:spec:
          f:group: {}
          f:names:
            f:kind: {}
            f:listKind: {}
            f:plural: {}
            f:singular: {}
          f:preserveUnknownFields: {}
          f:scope: {}
          f:versions: {}
...
```

### Describe the bug

I'm currently setting up an EKS cluster with ARC installed using Terraform, Helm and ArgoCD.
I had this issue: https://github.com/actions/actions-runner-controller/issues/3533#issuecomment-2625371437 Then upgraded the argocd chart to 7.8.5 and it solved it.
Now when installing the controller and runner, ArgoCD shows OutOfSync on the `github-runners-controller` AppSet.
I made sure to delete both arc-systems and arc-runners namespaces and re-deployed them but the issue persists.
I am able to use the runners in Github regardless.

<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/3e205826-ce7a-45b3-80d6-680a72da38bd" />
<img width="1442" alt="Image" src="https://github.com/user-attachments/assets/7ac0ec33-ef62-4ff6-9b6c-d6a7bfe2aad0" />

### Describe the expected behavior

ArgoCD AppSets are in Synced status

### Additional Context

```yaml
controller values.yml:

replicaCount: 1

image:
  repository: "ghcr.io/actions/gha-runner-scale-set-controller"
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:


serviceAccount:
  create: true

  annotations: {}

  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

volumes: []
volumeMounts: []

priorityClassName: ""

flags:
  logLevel: "debug"
  logFormat: "text"
  runnerMaxConcurrentReconciles: 2

  updateStrategy: "immediate"
namespaceOverride: ""


runners values.yml:

## githubConfigUrl is the GitHub url for where you want to configure runners
githubConfigUrl: "<org-url>"

## githubConfigSecret is the k8s secret information to use when authenticating via the GitHub API.
githubConfigSecret: "<secret-name>"

maxRunners: 10

minRunners: 0

runnerGroup: "arc-runners"


## template is the PodSpec for each runner Pod
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "4"
            memory: "16Gi" 

controllerServiceAccount:
  namespace: arc-systems
  name: github-runners-controller-gha-rs-controller
```

### Controller Logs

```shell
https://gist.github.com/LiatSchulz/4d0f12553b92b33588da86e98011f946
```

### Runner Pod Logs

```shell
No runner pods needed at the moment
```

**Comment by ProPlayerNA** [comment]
Hey,

This is due to a deprecation of a field in the CRD when using argoCD 3.0:
https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.14-3.0/#removing-default-ignores-of-preserveunknownfields-for-crd

Some already did a PR for it: https://github.com/actions/actions-runner-controller/pull/4135

**Comment by peimanja** [comment]
Seeing the same issue

**Comment by LiatSchulz** [comment]
Thank you! will wait for the PR 👍

**Comment by ddesborough** [comment]
We have also run into this. Hopefully the PR gets incorporated soon.

**Comment by sbarasii-go7** [comment]
Hi! 
The same issue
please look at it

**Comment by CreMindES** [comment]
Just bumped into this, thanks @ProPlayerNA.

**Comment by peimanja** [comment]
got around this for now by adding this in my ArgoCD helm configuration:
```yaml
configs:
  cm:
    resource.customizations: |
      apiextensions.k8s.io/CustomResourceDefinition:
        ignoreDifferences: |
          jsonPointers:
          - /spec/preserveUnknownFields
```
