### ISSUE TITLE
The job_name label for the metrics is blank

### ISSUE THREAD

**Issue by rskmm0chang** [actions/actions-runner-controller#4149]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.12.0

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
To execute the job, specify a runner provisioned by ARC in runs-on
```

### Describe the bug

Previously, `job_name` was included in `gha_completed_jobs_total` and `gha_started_jobs_total`. However, the `job_name` value has been empty since approximately 19:00 (UTC) on 2025/6/9.

When checking the metrics with curl, they appear as follows:
```
gha_job_startup_duration_seconds_sum{event_name="",job_name="",job_result="",job_workflow_ref="XXXX",organization="XXXX",repository="XXXX"} 120
```

### Describe the expected behavior

As stated in https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml#L157, the job_name value is expected to be present, but currently it's empty.

The absence of `job_name` in metrics, preventing us from performing job-specific analysis, such as identifying which jobs are taking a long time to start up.

### Additional Context

```yaml
values.yaml for runner-scale-set

githubConfigUrl: XXXX
listenerMetrics:
  counters:
    gha_completed_jobs_total:
      labels:
      - repository
      - organization
      - job_name
      - event_name
      - job_result
      - job_workflow_ref
    gha_started_jobs_total:
      labels:
      - repository
      - organization
      - job_name
      - event_name
      - job_workflow_ref
  gauges:
    gha_assigned_jobs:
      labels:
      - name
      - namespace
      - repository
      - organization
    gha_busy_runners:
      labels:
      - name
      - namespace
      - repository
      - organization
    gha_desired_runners:
      labels:
      - name
      - namespace
      - repository
      - organization
    gha_idle_runners:
      labels:
      - name
      - namespace
      - repository
      - organization
    gha_max_runners:
      labels:
      - name
      - namespace
      - repository
      - organization
    gha_min_runners:
      labels:
      - name
      - namespace
      - repository
      - organization
    gha_registered_runners:
      labels:
      - name
      - namespace
      - repository
      - organization
    gha_running_jobs:
      labels:
      - name
      - namespace
      - repository
      - organization
  histograms:
    gha_job_execution_duration_seconds:
      buckets:
      - 0.01
      - 0.05
      - 0.1
      - 0.5
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 12
      - 15
      - 18
      - 20
      - 25
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100
      - 110
      - 120
      - 150
      - 180
      - 210
      - 240
      - 300
      - 360
      - 420
      - 480
      - 540
      - 600
      - 900
      - 1200
      - 1800
      - 2400
      - 3000
      - 3600
      labels:
      - repository
      - organization
      - job_name
      - job_result
      - event_name
      - job_workflow_ref
    gha_job_startup_duration_seconds:
      buckets:
      - 0.01
      - 0.05
      - 0.1
      - 0.5
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 12
      - 15
      - 18
      - 20
      - 25
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100
      - 110
      - 120
      - 150
      - 180
      - 210
      - 240
      - 300
      - 360
      - 420
      - 480
      - 540
      - 600
      - 900
      - 1200
      - 1800
      - 2400
      - 3000
      - 3600
      labels:
      - repository
      - organization
      - job_name
      - job_result
      - event_name
      - job_workflow_ref
minRunners: 0
```

### Controller Logs

```shell
I'll omit this as it's unrelated.
```

### Runner Pod Logs

```shell
I'll omit this as it's unrelated.
```
