### ISSUE TITLE
[Helm] Specifying a service account and namespace causes helm deployment to fail

### ISSUE THREAD

**Issue by madchap** [actions/actions-runner-controller#4162]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [x] I am using charts that are officially provided

### Controller Version

0.12.1

### Deployment Method

Helm

### Checks

- [x] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [x] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

This was done to attempt to ease ops burden. I may be missing an option, but I think I've tried all possibilities.
The odd part is that, while the helm release fails to deploy, the runners actually work. I realized that as one of my coworker pushed and runners started to show up.

1. Create your own chart such as 

```
name: shift-arc
description: Helm chart for deploying ARC controllers and runners
version: 1.0.0
apiVersion: v2

dependencies:
  - name: gha-runner-scale-set-controller
    version: 0.12.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts

  - name: gha-runner-scale-set
    version: 0.12.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
```

2. Pass some values.yaml (see below)

3. build and deploy

```
helm repo add arc https://actions-runner-controller.github.io/actions-runner-controller
helm repo update
helm dependency build

echo "Installing/upgrading $ARC_CONTROLLER_NS for controllers and listeners"
helm upgrade --install --wait \
  --create-namespace --namespace arc-systems \
  gha-runner-scale-set-controller .

echo
echo "Installing/upgrading $ARC_RUNNERS_NS for self-hosted runners"
helm upgrade --install --wait \
  --create-namespace --namespace arc-runners \
  --set githubConfigUrl=https://github.com/LightFrameTech/Shift \
  gha-runner-scale-set .
```

### Describe the bug

The `arc-runners` chart fail to deploy:

```
Installing/upgrading arc-systems for controllers and listeners
Release "gha-runner-scale-set-controller" does not exist. Installing it now.
NAME: gha-runner-scale-set-controller
LAST DEPLOYED: Mon Jun 30 16:55:12 2025
NAMESPACE: arc-systems
STATUS: deployed
REVISION: 1
TEST SUITE: None

Installing/upgrading arc-runners for self-hosted runners
Release "gha-runner-scale-set" does not exist. Installing it now.
Error: Unable to continue with install: ServiceAccount "arc-gha-rs-controller" in namespace "arc-systems" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "gha-runner-scale-set": current value is "gha-runner-scale-set-controller"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "arc-runners": current value is "arc-systems"
```

### Describe the expected behavior

The runners scaleset helm chart deploys without error.

### Additional Context

```yaml
values.yaml


## https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/values.yaml
gha-runner-scale-set-controller:
  metrics:
    controllerManagerAddr: ":8080"
    listenerAddr: ":8080"
    listenerEndpoint: "/metrics"

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

  serviceAccount:
    create: true
    name: "arc-gha-rs-controller"
  
  namespaceOverride: "arc-systems"

  securityContext: {} # TODO harden


## https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
gha-runner-scale-set:
  ## We currently do per repo
  githubConfigUrl: "https://github.com/MyCompany/Shift"

  # We use a GH App, and not a token. Created manually, see 1Password for details
  githubConfigSecret: shift-arc-runners-secret

  maxRunners: 15
  minRunners: 0

  ## name of the runner scale set to create.  Defaults to the helm release name
  runnerScaleSetName: "shift-dev-arc-runner-set"

  # Explicitly configure the controller service account to avoid discovery issues
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller

  ## We require dind as we are invoking docker commands in our workflows.
  containerMode:
    type: "dind"  ## type can be set to dind or kubernetes

  # Configure Prometheus annotations for the listener. Controller's metrics need to be configured separately.
  listenerTemplate:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: listener

  template:
    spec:
      containers:
        - name: runner
          # Use our custom image from public ECR
          image: public.ecr.aws/xxxxxxx/arc-runner-images:1.7-2.325.0
          command: ["/home/runner/run.sh"]
          resources:
            requests:
              # front will silently OOM, hang, timeout and fail to build memory resources is specified
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "3"
              memory: "3Gi"

  namespaceOverride: "arc-runners"
```

### Controller Logs
No errors on the controller end.

https://gist.github.com/madchap/33e682d98585fb8d6e9a2ee14ac2194d

### Runner Pod Logs
No errors on the runners end. The runners actually work....

But the helm never deploys successfully!
