### ISSUE TITLE
Ability to use secrets in helm chart for GH token

### ISSUE THREAD

**Issue by lexfrei** [actions/actions-runner-controller#771]
**Is your feature request related to a problem? Please describe.**
Looks like there is no option to use secrets for GH tokens. This situation pushes users to make mistakes like [this one](https://github.com/lexfrei/k8s/commit/a3e83003a37b04dea9435dd948f25d372888cafa#diff-adfd879ef451f814845283792225fa47132c905a854b5553d0e3091c49100d8bR13).

**Describe the solution you'd like**
Ability to use secrets for GH tokens. Example from traefik's chart:
```yaml
        env:
          - name: CF_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cf-token
                key: token
```
