### ISSUE TITLE
 controllers.Runner      Scale target not found.

### ISSUE THREAD

**Issue by roshvin** [actions/actions-runner-controller#885]
could you pls suggest what might be the problem .  i am not able to scan with webhook 

2021-10-12T17:14:51.772Z        INFO    controllers.Runner      Scale target not found. If this is unexpected, ensure that there is exactly one repository-wide or organizational runner deployment that matches this webhook event{"event": "check_run", "hookID": "44", "delivery": "e94a62d0-2b7f-11ec-8800-7e9296c6943d", "checkRun.status": "queued", "action": "created"}

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: repo-runner
spec:
  template:
    spec:
      labels:
      - xxx
      repository: ROK-ACTION-TEST/repo
      env: []
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      image: xxxxxxx/gha-caas-runner-generic
      dockerEnabled: false
      securityContext:
        runAsUser: 1000
      volumeMounts:
       - mountPath: /runner
         name: runner
      volumes:
      - name: runner
        emptyDir: {}
---
kind: HorizontalRunnerAutoscaler
metadata:
   name: repo-scaller
spec:
  scaleTargetRef:
    name: repo-runner
  minReplicas: 1
  maxReplicas: 3
  scaleUpTrigggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
    amount: 1
    duration: "5m"


```
